// app/components/primary-sources/activities/complete-sentences/complete-sentences-by-rephrasing-with-choices.tsx
import { motion } from "motion/react";
import { Check, X } from "lucide-react";
import { useState, useEffect } from "react";

// local imports
import { cn, shuffle } from "@/lib/utils";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/inputs/input";
import { FeedbackType } from "@/lib/types/activity-types";
import { AnswerChecker } from "@/lib/utils/answer-checker";
import ActivityTitle from "@/components/templates/activity-title";
import { useSoundEffects } from "@/shared/hooks/use-sound-effects";
import ActivityResults, {
  ActivityResultsAlertDialog,
} from "@/components/templates/results";

type TCompleteSentencesByRephrasingWithChoices = {
  feedback: FeedbackType;
  questions: {
    title: string;
    fontSize?: number;
    options: string[];
    questions: {
      question: string;
      answer: string;
    }[];
  };
};

const answerChecker = new AnswerChecker();

/**
 * @deprecated This component is deprecated and will be removed in the next major release.
 *
 * **Deprecation Details:**
 * - **Reason:** Component architecture has been redesigned for better performance and maintainability
 *
 * **Migration Guide:**
 * Please use the `CompleteSentencesByRephrasingActivity` component instead:
 * ```tsx
 * import { CompleteSentencesActivity } from '@/components/activities/complete-sentences-activity';
 * ```
 *
 * **Breaking Changes:**
 * - Props structure has been simplified
 * - Event handlers have been renamed for consistency
 * - CSS classes follow the new design system
 *
 * @see {@link CompleteSentencesActivity} - Replacement component
 * @see {@link https://docs.example.com/migration/v3} - Full migration guide
 */
const CompleteSentencesByRephrasingWithChoices = ({
  feedback,
  questions,
}: TCompleteSentencesByRephrasingWithChoices) => {
  // Add state for shuffled questions
  const [shuffledQuestions, setShuffledQuestions] = useState(
    questions.questions,
  );
  const [score, setScore] = useState(0);
  const [allAnswered, setAllAnswered] = useState(false);
  const [checkedItems, setCheckedItems] = useState<number[]>([]);
  const [answers, setAnswers] = useState<{ [key: number]: string }>({});
  const [feedbacks, setFeedbacks] = useState<{ [key: number]: boolean }>({});
  const [showResults, setShowResults] = useState(false);

  const { playSound } = useSoundEffects();

  // Custom reset handler that will shuffle questions
  const handleReset = () => {
    setShuffledQuestions(shuffle(questions.questions));
    setScore(0);
    setAllAnswered(false);
    setCheckedItems([]);
    setAnswers({});
    setFeedbacks({});
    setShowResults(false);
  };

  // Initialize with shuffled questions
  useEffect(() => {
    setShuffledQuestions(shuffle(questions.questions));
  }, [questions.questions]);

  // Check if all questions have been answered
  const allQuestionsAnswered = shuffledQuestions.every((_, index) => {
    const answer = answers[index];
    return answer && answer.trim() !== "";
  });

  // Custom check function for all questions
  const handleCheckAllAnswers = () => {
    let newScore = 0;
    const newFeedbacks: { [key: number]: boolean } = {};
    const newCheckedItems: number[] = [];

    shuffledQuestions.forEach((_, index) => {
      const userAnswer = answers[index] || "";
      const result = checkAnswer(userAnswer, index);
      const isCorrect = typeof result === "boolean" ? result : result.isCorrect;

      newFeedbacks[index] = isCorrect;
      newCheckedItems.push(index);

      if (isCorrect) {
        newScore++;
      }
    });

    setScore(newScore);
    setFeedbacks(newFeedbacks);
    setCheckedItems(newCheckedItems);
    setAllAnswered(true);

    // Play sound based on overall performance
    playSound(newScore === shuffledQuestions.length ? "success" : "failure");
  };

  const handleInputChange = (index: number, value: string) => {
    setAnswers((prev) => ({
      ...prev,
      [index]: value,
    }));
  };

  const visibleQuestions = shuffledQuestions;

  const checkAnswer = (userAnswer: string, questionIndex: number) => {
    const correctAnswer = shuffledQuestions[questionIndex].answer.toLowerCase();
    return answerChecker.checkAnswer(userAnswer.toLowerCase(), {
      acceptedAnswers: [correctAnswer],
    });
  };

  const renderQuestion = (q: string, questionIndex: number) => {
    const words = q.split(" ");
    const actualIndex = questionIndex; // Use direct index since we're showing all questions

    return words.map((w, i) => {
      if (w.startsWith("___")) {
        // Calculate width based on number of underscores (multiples of 3)
        const underscoreCount = w.length;
        const widthMultiplier = underscoreCount / 3;
        const baseWidth = 200;
        const calculatedWidth = baseWidth * widthMultiplier;

        return (
          <span
            key={i}
            className="inline-flex flex-col mx-1"
            style={{ minWidth: `${calculatedWidth}px` }}
          >
            <Input
              type="text"
              value={answers[actualIndex] || ""}
              onChange={(e) => handleInputChange(questionIndex, e.target.value)}
              disabled={checkedItems.includes(actualIndex)}
              className="min-w-0 px-2 border-none bg-transparent text-center focus:outline-none"
              style={{ maxWidth: `${calculatedWidth * 1.6}px` }}
            />
            <div
              className={cn("border-b border-dashed border-picton-blue-700", {
                "border-lemon-700": checkedItems.includes(actualIndex),
              })}
            />
          </span>
        );
      }
      return (
        <span
          key={i}
          className={cn("inline-flex items-center mx-1", {
            "bg-lemon-100 text-lemon-700 px-2 py-1 rounded":
              w.includes("_") && w.split("_").length === 2,
          })}
        >
          {w.replace(/_/g, "")}
        </span>
      );
    });
  };

  return (
    <div className="h-full flex flex-col">
      <ActivityTitle title={questions.title} />

      {!showResults ? (
        <div
          className="flex flex-col h-full bg-picton-blue-100"
          style={{
            fontSize: questions.fontSize ? `${questions.fontSize}px` : "20px",
          }}
        >
          <div className="grid gap-4 py-4 h-full grow overflow-y-auto">
            {visibleQuestions.map((q, i) => {
              const uniqueKey = `question-${i}`;
              const actualIndex = i;

              return (
                <motion.div
                  key={uniqueKey}
                  initial={{ opacity: 0, scale: 0 }}
                  animate={{ opacity: 1, scale: 1 }}
                  transition={{ duration: 0.5, delay: i * 0.1 }}
                  className={cn("h-full rounded-lg", {
                    "bg-picton-blue-50": !checkedItems.includes(actualIndex),
                    "bg-lemon-50 text-lemon-700":
                      checkedItems.includes(actualIndex),
                    "bg-green-100 text-green-700": feedbacks[actualIndex],
                    "bg-red-100 text-red-700": feedbacks[actualIndex] === false,
                  })}
                >
                  <div className="p-4 flex flex-col justify-between h-full">
                    <div className="flex flex-wrap items-center">
                      {renderQuestion(q.question, i)}
                    </div>
                    <div className="flex items-center gap-2 mt-4 ml-auto">
                      {checkedItems.includes(actualIndex) && (
                        <motion.div
                          initial={{ scale: 0 }}
                          animate={{ scale: 1 }}
                          className={cn(
                            "flex items-center justify-center rounded-full p-1",
                            feedbacks[actualIndex]
                              ? "bg-green-100 text-green-600"
                              : "bg-red-100 text-red-600",
                          )}
                        >
                          {feedbacks[actualIndex] ? (
                            <Check className="h-5 w-5" />
                          ) : (
                            <X className="h-5 w-5" />
                          )}
                        </motion.div>
                      )}
                    </div>
                  </div>
                </motion.div>
              );
            })}
          </div>

          {questions.options.filter((o) => o.trim() !== "").length > 0 && (
            <div className="py-4">
              <h2 className="text-xl mb-2">Answers</h2>
              <div className="flex flex-wrap gap-4 bg-picton-blue-200 w-fit p-2 rounded">
                {questions.options.map((o, i) => (
                  <div
                    key={i}
                    className="text-picton-blue-700  px-5 py-1 rounded"
                  >
                    {o}
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Single Check Answers Button */}
          <Button
            disabled={!allQuestionsAnswered || allAnswered}
            onClick={handleCheckAllAnswers}
            variant="brand-lemon"
            className="w-fit ml-auto"
            size="lg"
          >
            {allAnswered ? "Answers Checked" : "Check All Answers"}
          </Button>
        </div>
      ) : (
        <div
          className="flex flex-col h-full bg-picton-blue-100 p-6 overflow-y-auto"
          style={{
            fontSize: questions.fontSize ? `${questions.fontSize}px` : "20px",
          }}
        >
          <div className="bg-picton-blue-50 rounded-lg p-6">
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-8">
              {shuffledQuestions.map((question, idx) => {
                const userAnswer = answers[idx] || "";
                const result = checkAnswer(userAnswer, idx);
                const isCorrect =
                  typeof result === "boolean" ? result : result.isCorrect;

                return (
                  <div
                    key={idx}
                    className={cn(
                      "p-4 rounded-lg border",
                      isCorrect
                        ? "bg-green-50 border-green-200"
                        : "bg-red-50 border-red-200",
                    )}
                  >
                    <div className="flex justify-between items-center mb-2">
                      <div>
                        <p className="font-medium">{question.question}</p>
                      </div>
                      <div
                        className={cn(
                          "flex items-center justify-center rounded-full p-1",
                          isCorrect
                            ? "bg-green-100 text-green-600"
                            : "bg-red-100 text-red-600",
                        )}
                      >
                        {isCorrect ? (
                          <Check className="h-5 w-5" />
                        ) : (
                          <X className="h-5 w-5" />
                        )}
                      </div>
                    </div>

                    <div className="grid grid-cols-2 gap-4 mt-2">
                      <div>
                        <p className="text-sm text-gray-500">Your answer:</p>
                        <p className={!isCorrect ? "text-red-600" : ""}>
                          {userAnswer || "(no answer)"}
                        </p>
                      </div>
                      {feedback === "wrong-correct-answers" && (
                        <div>
                          <p className="text-sm text-gray-500">
                            Correct answer:
                          </p>
                          <p className="text-green-600">{question.answer}</p>
                        </div>
                      )}
                    </div>
                  </div>
                );
              })}
            </div>

            <ActivityResults
              score={score}
              total={shuffledQuestions.length}
              onRestart={handleReset}
            />
          </div>
        </div>
      )}

      <ActivityResultsAlertDialog
        score={score}
        total={shuffledQuestions.length}
        open={allAnswered && !showResults}
        onOpenChange={(open) => {
          if (!open) {
            setShowResults(true);
          }
        }}
      />
    </div>
  );
};

export default CompleteSentencesByRephrasingWithChoices;

// app/components/primary-sources/activities/complete-sentences/complete-sentences-by-rephrasing-with-choices.vue
<script setup lang="ts">
import { computed, ref, watch } from "vue";
import { Icon } from "@iconify/vue";
import ActivityTitle from "@/components/templates/activity-title";
import ActivityResults, { ActivityResultsAlertDialog } from "@/components/templates/results";
import Input from "@/components/ui/inputs/input.vue";
import { Button } from "~/components/ui/button";
import { AnswerChecker } from "~/lib/utils/answer-checker";
import { shuffle } from "~/utilities/utils";
import { cn } from "~/lib/utils";
import {
  calculateBlankWidth,
  parseQuestionSegments,
  type QuestionSegment,
} from "~/components/primary-sources/activity-helpers/question-renderer-utils";

interface QuestionItem {
  id?: number | string;
  question: string;
  answer: string | string[];
}

interface QuestionsProps {
  title: string;
  fontSize?: number;
  options?: string[];
  questions: QuestionItem[];
}

interface Props {
  feedback: "none" | "wrong-correct" | "wrong-correct-answers";
  questions: QuestionsProps;
}

const props = defineProps<Props>();
const ui = useActivityUiText();
const answerChecker = new AnswerChecker();

const shuffledQuestions = ref<QuestionItem[]>([]);
const answers = ref<Record<number, string[]>>({});
const feedbacks = ref<Record<number, boolean>>({});
const checkedItems = ref<number[]>([]);
const allAnswered = ref(false);
const showResults = ref(false);
const score = ref(0);

const availableOptions = computed(() =>
  (props.questions.options || []).map((option) => option.trim()).filter(Boolean),
);

const resetState = () => {
  shuffledQuestions.value = shuffle([...props.questions.questions]);
  answers.value = {};
  feedbacks.value = {};
  checkedItems.value = [];
  allAnswered.value = false;
  showResults.value = false;
  score.value = 0;
};

watch(
  () => props.questions,
  () => {
    resetState();
  },
  { immediate: true, deep: true },
);

const splitAnswerValue = (value: string) =>
  value
    .split(/[/,;|\n]+/)
    .map((answer) => String(answer ?? "").trim())
    .filter(Boolean);

const getCorrectAnswers = (questionIndex: number) => {
  const rawAnswer = shuffledQuestions.value[questionIndex]?.answer;
  if (Array.isArray(rawAnswer)) {
    return rawAnswer
      .map((answer) => String(answer ?? "").trim())
      .filter(Boolean);
  }

  const normalizedAnswer = String(rawAnswer ?? "").trim();
  const blankCount = getBlankCount(shuffledQuestions.value[questionIndex]?.question || "");
  const splitAnswers = splitAnswerValue(normalizedAnswer);

  if (splitAnswers.length > 1) {
    return splitAnswers;
  }

  if (blankCount > 1 && normalizedAnswer.includes(" ")) {
    return normalizedAnswer
      .split(/\s+/)
      .map((answer) => answer.trim())
      .filter(Boolean);
  }

  return normalizedAnswer ? [normalizedAnswer] : [];
};

const getUserAnswers = (questionIndex: number) => answers.value[questionIndex] || [];

const getAnswerValue = (questionIndex: number, blankIndex: number) =>
  getUserAnswers(questionIndex)[blankIndex] || "";

const handleInputChange = (questionIndex: number, blankIndex: number, value: string | number) => {
  const nextAnswers = [...getUserAnswers(questionIndex)];
  nextAnswers[blankIndex] = String(value ?? "");

  answers.value = {
    ...answers.value,
    [questionIndex]: nextAnswers,
  };
};

const checkAnswer = (questionIndex: number) => {
  const userAnswers = getUserAnswers(questionIndex).map((answer) => answer.trim());
  const correctAnswers = getCorrectAnswers(questionIndex).map((answer) => answer.trim());

  if (userAnswers.length !== correctAnswers.length) {
    return false;
  }

  return correctAnswers.every((answer, index) =>
    answerChecker.checkAnswer(userAnswers[index] || "", {
      acceptedAnswers: [answer],
      strictMode: true,
    }).isCorrect,
  );
};

const handleCheckAllAnswers = () => {
  let nextScore = 0;
  const nextFeedbacks: Record<number, boolean> = {};
  const nextCheckedItems: number[] = [];

  shuffledQuestions.value.forEach((_, index) => {
    const isCorrect = checkAnswer(index);
    nextFeedbacks[index] = isCorrect;
    nextCheckedItems.push(index);
    if (isCorrect) {
      nextScore += 1;
    }
  });

  feedbacks.value = nextFeedbacks;
  checkedItems.value = nextCheckedItems;
  score.value = nextScore;
  allAnswered.value = true;
};

type QuestionRenderSegment = QuestionSegment & {
  calculatedWidth?: number;
  blankIndex?: number;
};

const getQuestionSegments = (question: string): QuestionRenderSegment[] => {
  let blankIndex = 0;

  return parseQuestionSegments(question).map((segment) => {
    if (segment.type !== "blank") {
      return segment;
    }

    const { calculatedWidth } = calculateBlankWidth(segment.content.length, 1024);

    return {
      ...segment,
      blankIndex: blankIndex++,
      calculatedWidth: Math.max(calculatedWidth, 120),
    };
  });
};

const getBlankCount = (question: string) =>
  getQuestionSegments(question).filter((segment) => segment.type === "blank").length;

const allQuestionsAnswered = computed(() =>
  shuffledQuestions.value.every((question, index) => {
    const blankCount = getBlankCount(question.question);
    return Array.from({ length: blankCount }).every(
      (_, blankIndex) => getAnswerValue(index, blankIndex).trim() !== "",
    );
  }),
);

const formatUserAnswer = (questionIndex: number) => {
  const userAnswers = getUserAnswers(questionIndex).filter((answer) => answer.trim() !== "");
  return userAnswers.length ? userAnswers.join(", ") : "(no answer)";
};

const formatCorrectAnswer = (questionIndex: number) => getCorrectAnswers(questionIndex).join(", ");
</script>

<template>
  <div class="flex h-full flex-col">
    <ActivityTitle :title="props.questions.title" />

    <div
      v-if="availableOptions.length"
      class="mb-4 rounded-xl border border-picton-blue-200 bg-white/95 p-4 shadow-sm"
    >
      <div class="flex w-fit flex-wrap gap-4 rounded bg-picton-blue-200 p-3">
        <div
          v-for="(option, optionIndex) in availableOptions"
          :key="`${option}-${optionIndex}`"
          class="rounded px-5 py-1 text-picton-blue-700"
        >
          {{ option }}
        </div>
      </div>
    </div>

    <div
      v-if="!showResults"
      class="flex h-full flex-col bg-picton-blue-100"
      :style="{ fontSize: props.questions.fontSize ? `${props.questions.fontSize}px` : '20px' }"
    >
      <div class="grid h-full grow gap-4 overflow-y-auto py-4">
        <div
          v-for="(q, i) in shuffledQuestions"
          :key="q.id ?? i"
          :class="[
            'h-full rounded-lg p-4 flex flex-col justify-between',
            !checkedItems.includes(i)
              ? 'bg-picton-blue-50'
              : feedbacks[i]
                ? 'bg-green-100 text-green-700'
                : 'bg-red-100 text-red-700'
          ]"
        >
          <div class="flex flex-wrap items-center leading-loose">
            <span class="mr-2 font-medium text-gray-600">{{ i + 1 }}.</span>

            <template
              v-for="segment in getQuestionSegments(q.question)"
              :key="`${q.id ?? i}-${segment.index}`"
            >
              <span
                v-if="segment.type === 'text'"
                class="mx-1 whitespace-pre-line"
              >
                {{ segment.content }}
              </span>

              <span
                v-else-if="segment.type === 'highlighted'"
                class="inline-flex items-center mx-1 rounded bg-lemon-100 px-2 py-1 text-lemon-700"
              >
                {{ segment.content }}
              </span>

              <span
                v-else
                class="inline-flex flex-col mx-1"
                :style="{ minWidth: `${segment.calculatedWidth}px` }"
              >
                <Input
                  type="text"
                  :model-value="getAnswerValue(i, segment.blankIndex || 0)"
                  :disabled="checkedItems.includes(i)"
                  class="min-w-0 px-2 border-none bg-transparent text-center focus:outline-none"
                  :style="{ maxWidth: `${(segment.calculatedWidth || 120) * 1.6}px` }"
                  @update:model-value="(value) => handleInputChange(i, segment.blankIndex || 0, value)"
                />
                <div
                  :class="
                    cn('border-b border-dashed border-picton-blue-700', {
                      'border-lemon-700': checkedItems.includes(i),
                    })
                  "
                />
              </span>
            </template>
          </div>

          <div class="flex items-center gap-2 mt-4 ml-auto">
            <div
              v-if="checkedItems.includes(i)"
              :class="[
                'flex items-center justify-center rounded-full p-1',
                feedbacks[i] ? 'bg-green-100 text-green-600' : 'bg-red-100 text-red-600',
              ]"
            >
              <Icon :icon="feedbacks[i] ? 'mdi:check' : 'mdi:close'" width="20" height="20" />
            </div>
          </div>
        </div>
      </div>

      <Button :disabled="!allQuestionsAnswered || allAnswered" @click="handleCheckAllAnswers" variant="brand-lemon" class="w-fit ml-auto" size="lg">
        {{ allAnswered ? ui.answersChecked : ui.checkAllAnswers }}
      </Button>
    </div>

    <div v-else class="flex h-full flex-col overflow-y-auto bg-picton-blue-100 p-6">
      <div class="rounded-lg bg-picton-blue-50 p-6">
        <div class="mb-8 grid grid-cols-1 gap-4 md:grid-cols-2">
          <div
            v-for="(question, idx) in shuffledQuestions"
            :key="question.id ?? idx"
            :class="[
              'rounded-lg border p-4',
              checkAnswer(idx) ? 'border-green-200 bg-green-50' : 'border-red-200 bg-red-50',
            ]"
          >
            <div class="mb-2 flex items-center justify-between gap-3">
              <p class="font-medium">{{ question.question }}</p>
              <div
                :class="[
                  'flex items-center justify-center rounded-full p-1',
                  checkAnswer(idx) ? 'bg-green-100 text-green-600' : 'bg-red-100 text-red-600',
                ]"
              >
                <Icon :icon="checkAnswer(idx) ? 'mdi:check' : 'mdi:close'" width="20" height="20" />
              </div>
            </div>

            <div class="mt-2 grid grid-cols-2 gap-4">
              <div>
                <p class="text-sm text-gray-500">{{ ui.yourAnswer }}</p>
                <p :class="{ 'text-red-600': !checkAnswer(idx) }">{{ formatUserAnswer(idx) }}</p>
              </div>
              <div v-if="props.feedback === 'wrong-correct-answers'">
                <p class="text-sm text-gray-500">{{ ui.correctAnswer }}</p>
                <p class="text-green-600">{{ formatCorrectAnswer(idx) }}</p>
              </div>
            </div>
          </div>
        </div>

        <ActivityResults :score="score" :total="shuffledQuestions.length" :onRestart="resetState" />
      </div>
    </div>

    <ActivityResultsAlertDialog
      :score="score"
      :total="shuffledQuestions.length"
      :open="allAnswered && !showResults"
      :onRestart="resetState"
      :onOpenChange="
        (open: boolean) => {
          if (!open) {
            showResults = true;
          }
        }
      "
    />
  </div>
</template>
