// app/components/primary-sources/activities/complete-sentences/complete-sentences-by-selecting-clues.vue
<script setup lang="ts">
import { computed, ref, watch } from "vue";
import { Button } from "~/components/ui/button";
import Input from "~/components/ui/inputs/input";
import ActivityTitle from "~/components/templates/activity-title";
import type { FeedbackType } from "~/types/activity-types";
import { useSoundEffects } from "~/composables/use-sound-effects";
import ActivityResults, {
  ActivityResultsAlertDialog,
} from "~/components/templates/results";
import { shuffle } from "~/utilities/utils";

type Props = {
  questions: {
    title: string;
    options: string[];
    questions: {
      id: number | string;
      question: string;
      correctAnswer: string;
    }[];
  };
  feedback?: FeedbackType;
};

type QuestionState = {
  id: number | string;
  question: string;
  correctAnswer: string;
  displayText: string;
  highlightedWord: string;
  userAnswer: string;
  isCorrect?: boolean;
};

const props = defineProps<Props>();
const { playSound } = useSoundEffects();

const buildProcessedQuestions = (): QuestionState[] =>
  props.questions.questions.map((q) => {
    const underscoreIndex = q.question.indexOf("_");
    if (underscoreIndex !== -1) {
      const highlightedWord = q.question.substring(underscoreIndex + 1).split(" ")[0] || "";
      const displayText = q.question
        .replace(`_${highlightedWord}`, highlightedWord)
        .replace(/_/g, "");
      return { ...q, displayText, highlightedWord, userAnswer: "" };
    }
    return { ...q, displayText: q.question, highlightedWord: "", userAnswer: "" };
  });

const questionsState = ref<QuestionState[]>([]);
const showResults = ref(false);
const score = ref(0);
const allAnswered = ref(false);
const isDialogOpen = ref(false);

const resetActivity = () => {
  questionsState.value = shuffle(
    buildProcessedQuestions().map((q) => ({
      ...q,
      userAnswer: "",
      isCorrect: undefined,
    })),
  );
  showResults.value = false;
  score.value = 0;
  allAnswered.value = false;
  isDialogOpen.value = false;
};

watch(
  () => props.questions,
  () => {
    resetActivity();
  },
  { immediate: true, deep: true },
);

watch(
  questionsState,
  () => {
    allAnswered.value = questionsState.value.every((q) => q.userAnswer.trim() !== "");
  },
  { deep: true },
);

const handleInputChange = (questionId: number | string, value: string) => {
  questionsState.value = questionsState.value.map((q) =>
    q.id === questionId ? { ...q, userAnswer: value } : q,
  );
};

const checkAnswers = () => {
  let correctCount = 0;
  questionsState.value = questionsState.value.map((q) => {
    const isCorrect = q.userAnswer.trim().toLowerCase() === q.correctAnswer.toLowerCase();
    if (isCorrect) correctCount++;
    return { ...q, isCorrect };
  });
  score.value = correctCount;
  playSound("success");
  isDialogOpen.value = true;
};

const selectableWords = computed(() => (props.questions.options || []).filter((w) => w.trim() !== ""));
</script>

<template>
  <div class="h-full flex flex-col">
    <ActivityTitle :title="props.questions.title" />

    <div class="space-y-4 overflow-y-auto flex-1 p-2">
      <div
        v-for="(q, index) in questionsState"
        :key="q.id"
        class="p-4 bg-white rounded-md shadow-sm"
      >
        <div class="flex flex-wrap items-center gap-2">
          <span class="font-bold text-red-500 min-w-8">{{ index + 1 }}.</span>
          <div class="font-medium">
            {{ q.displayText.split(q.highlightedWord)[0] }}
            <span class="bg-picton-blue-200 px-2 py-1 rounded">{{ q.highlightedWord }}</span>
            {{ q.displayText.split(q.highlightedWord).slice(1).join(q.highlightedWord) }}
          </div>

          <Input
            :model-value="q.userAnswer"
            :disabled="showResults"
            class="flex-1 min-w-32 ml-4"
            placeholder="Type answer here"
            @update:modelValue="(v: string | number) => handleInputChange(q.id, String(v ?? ''))"
          />

          <div
            v-if="showResults"
            class="text-sm"
            :class="q.isCorrect ? 'text-green-600' : 'text-red-600'"
          >
            {{ q.isCorrect ? "Correct" : "Wrong" }}
          </div>
        </div>
        <div
          v-if="showResults && props.feedback === 'wrong-correct-answers' && q.isCorrect === false"
          class="mt-2 text-sm text-green-600"
        >
          Correct answer: {{ q.correctAnswer }}
        </div>
      </div>
    </div>

    <div v-if="!showResults" class="flex flex-wrap mt-4 gap-4">
      <span
        v-for="(word, i) in selectableWords"
        :key="i"
        class="px-2 py-1 rounded bg-picton-blue-100 text-picton-blue-700"
      >
        {{ word }}
      </span>
    </div>

    <ActivityResults
      v-if="showResults"
      :score="score"
      :total="questionsState.length"
      :onRestart="resetActivity"
    />
    <div v-else class="flex mt-4 justify-end">
      <Button :onClick="checkAnswers" :disabled="!allAnswered">Check Answers</Button>
    </div>

    <ActivityResultsAlertDialog
      :open="isDialogOpen"
      :score="score"
      :total="questionsState.length"
      :onOpenChange="(open: boolean) => {
        if (!open) {
          if (props.feedback === 'none') resetActivity();
          else showResults = true;
          isDialogOpen = false;
        }
      }"
    />
  </div>
</template>

// app/components/primary-sources/activities/complete-sentences/complete-sentences-by-selecting-clues.tsx
import { useEffect, useState } from "react";

// Local imports
import { Button } from "@/components/ui/button";
import CustomInput from "@/components/ui/inputs/custom-input";
import ActivityTitle from "@/components/templates/activity-title";
import { FeedbackType } from "@/lib/types/activity-types";
import { useSoundEffects } from "@/shared/hooks/use-sound-effects";
import ActivityResults, {
  ActivityResultsAlertDialog,
} from "@/components/templates/results";
import { shuffle } from "@/lib/utils";

type TCompleteSentencesBySelectingCluesProps = {
  questions: {
    title: string;
    options: string[];
    questions: {
      id: number | string;
      question: string;
      correctAnswer: string;
    }[];
  };
  feedback?: FeedbackType;
};

type TQuestionState = {
  id: number | string;
  question: string;
  correctAnswer: string;
  displayText: string;
  highlightedWord: string;
  userAnswer: string;
  isCorrect?: boolean;
};

const CompleteSentencesBySelectingCluesActivity = ({
  questions,
  feedback,
}: TCompleteSentencesBySelectingCluesProps) => {
  const { title, options, questions: questionItems } = questions;
  const { playSound } = useSoundEffects();

  // Process questions to extract highlighted words and format display text
  const processedQuestions: TQuestionState[] = questionItems.map((q) => {
    const questionText = q.question;
    // Find the word marked with underscore
    const underscoreIndex = questionText.indexOf("_");

    if (underscoreIndex !== -1) {
      // Extract the highlighted word (without the underscore)
      const highlightedWord = questionText
        .substring(underscoreIndex + 1)
        .split(" ")[0];

      // Create the display text with the word highlighted (but without underscore)
      const displayText = questionText
        .replace("_" + highlightedWord, highlightedWord)
        .replace(/_/g, ""); // Remove any remaining underscores

      return {
        ...q,
        displayText,
        highlightedWord,
        userAnswer: "",
      };
    }

    // Fallback if no underscore found
    return {
      ...q,
      displayText: questionText,
      highlightedWord: "",
      userAnswer: "",
    };
  });

  const [questionsState, setQuestionsState] =
    useState<TQuestionState[]>(processedQuestions);
  const [showResults, setShowResults] = useState(false);
  const [score, setScore] = useState(0);
  const [allAnswered, setAllAnswered] = useState(false);
  const [isDialogOpen, setIsDialogOpen] = useState(false);

  // Check if all questions have been answered
  useEffect(() => {
    const answered = questionsState.every((q) => q.userAnswer.trim() !== "");
    setAllAnswered(answered);
  }, [questionsState]);

  // Handle input change
  const handleInputChange = (questionId: number | string, value: string) => {
    setQuestionsState((prevState) =>
      prevState.map((q) =>
        q.id === questionId ? { ...q, userAnswer: value } : q
      )
    );
  };

  // Check answers and calculate score
  const checkAnswers = () => {
    let correctCount = 0;

    const updatedQuestions = questionsState.map((q) => {
      const isCorrect =
        q.userAnswer.trim().toLowerCase() === q.correctAnswer.toLowerCase();
      if (isCorrect) correctCount++;
      return { ...q, isCorrect };
    });

    setQuestionsState(updatedQuestions);
    setScore(correctCount);
    playSound("success");
    setAllAnswered(true);
    setIsDialogOpen(true);
  };

  // Reset the activity
  const resetActivity = () => {
    setQuestionsState(
      shuffle(
        processedQuestions.map((q) => ({
          ...q,
          userAnswer: "",
          isCorrect: undefined,
        }))
      )
    );
    setShowResults(false);
    setScore(0);
  };

  // Handle word selection from word bank
  const handleWordSelection = (word: string, questionId: number | string) => {
    if (showResults) return;

    setQuestionsState((prevState) =>
      prevState.map((q) =>
        q.id === questionId ? { ...q, userAnswer: word } : q
      )
    );
  };

  return (
    <div className="h-full flex flex-col">
      <ActivityTitle title={title} />

      <div className="space-y-4">
        {questionsState.map((q, index) => {
          // Generate the display text with highlighted word
          const parts = q.displayText.split(q.highlightedWord);
          const before = parts[0];
          const after = parts.slice(1).join(q.highlightedWord);

          return (
            <div key={q.id} className="p-4 bg-white rounded-md shadow-sm">
              <div className="flex flex-wrap items-center gap-2">
                <span className="font-bold text-red-500 min-w-8">
                  {index + 1}.
                </span>
                <div className="font-medium">
                  {before}
                  <span className="bg-picton-blue-200 px-2 py-1 rounded">
                    {q.highlightedWord}
                  </span>
                  {after}
                </div>

                <CustomInput
                  value={q.userAnswer}
                  onChange={(value) => handleInputChange(q.id, value)}
                  placeholder="Type answer here"
                  disabled={showResults}
                  className="flex-1 min-w-32 ml-4"
                  isCorrect={showResults ? q.isCorrect : undefined}
                  correctAnswer={
                    feedback === "wrong-correct-answers"
                      ? q.correctAnswer
                      : undefined
                  }
                />
              </div>
            </div>
          );
        })}
      </div>

      {showResults ? (
        <ActivityResults
          score={score}
          total={questionsState.length}
          onRestart={resetActivity}
        />
      ) : (
        <>
          {/* Word Bank */}
          <div className="flex flex-wrap mt-8 gap-6">
            {options.map((word, i) => (
              <div key={i}>{word}</div>
            ))}
          </div>
          <div className="flex mt-4 justify-end">
            <Button onClick={checkAnswers} disabled={!allAnswered}>
              Check Answers
            </Button>
          </div>
        </>
      )}

      <ActivityResultsAlertDialog
        open={isDialogOpen}
        onOpenChange={(open) => {
          if (!open) {
            if (feedback === "none") {
              resetActivity();
            } else {
              setShowResults(true);
            }
            setIsDialogOpen(false);
          }
        }}
        score={score}
        total={questionsState.length}
      />
    </div>
  );
};

export default CompleteSentencesBySelectingCluesActivity;
