// app/components/primary-sources/activities/complete-sentences/complete-sentences-with-two-clauses.vue
<script setup lang="ts">
import { ref, watch, computed } from "vue";
import { Icon } from "@iconify/vue";
import { cn, shuffle } from "~/utilities/utils";
import { Button } from "~/components/ui/button";
import Input from "~/components/ui/inputs/input";
import type { FeedbackType } from "~/types/activity-types";
import ActivityTitle from "~/components/templates/activity-title";
import { useSoundEffects } from "~/composables/use-sound-effects";
import ActivityResults, {
  ActivityResultsAlertDialog,
} from "~/components/templates/results";

type Props = {
  feedback: FeedbackType;
  questions: {
    title: string;
    fontSize?: string;
    questions: {
      word: string;
      answer: string | string[];
    }[];
  };
};

const props = defineProps<Props>();
const { playSound } = useSoundEffects();

const shuffledQuestions = ref([...props.questions.questions]);
const score = ref(0);
const allAnswered = ref(false);
const allChecked = ref(false);
const answers = ref<Record<number, string>>({});
const feedbacks = ref<Record<number, boolean>>({});
const showResults = ref(false);

const normalize = (value: string) => value.trim().toLowerCase();
const compareAnswersLocal = (userAnswer: string, expected: string | string[]) => {
  const user = normalize(userAnswer);
  if (Array.isArray(expected)) {
    return expected.some((item) => normalize(item) === user);
  }
  return normalize(expected) === user;
};

const shuffleQuestions = () => {
  shuffledQuestions.value = shuffle([...props.questions.questions]);
};

watch(
  () => props.questions.questions,
  () => {
    shuffleQuestions();
    allAnswered.value = false;
    allChecked.value = false;
    score.value = 0;
    answers.value = {};
    feedbacks.value = {};
    showResults.value = false;
  },
  { immediate: true, deep: true },
);

watch(
  [answers, shuffledQuestions],
  () => {
    allAnswered.value = shuffledQuestions.value.every(
      (_, index) => (answers.value[index] || "").trim().length > 0,
    );
  },
  { deep: true },
);

const handleCheckAll = () => {
  let correctCount = 0;
  const newFeedbacks: Record<number, boolean> = {};
  shuffledQuestions.value.forEach((question, index) => {
    const userAnswer = answers.value[index] || "";
    const isCorrect = compareAnswersLocal(userAnswer, question.answer);
    newFeedbacks[index] = isCorrect;
    if (isCorrect) correctCount++;
  });
  feedbacks.value = newFeedbacks;
  score.value = correctCount;
  allChecked.value = true;

  const percentage = shuffledQuestions.value.length
    ? (correctCount / shuffledQuestions.value.length) * 100
    : 0;
  if (percentage === 100) playSound("success");
  else if (percentage >= 70) playSound("correct");
  else playSound("failure");
};

const handleInputChange = (index: number, value: string) => {
  answers.value = {
    ...answers.value,
    [index]: value,
  };
};

const resetGame = () => {
  shuffleQuestions();
  allAnswered.value = false;
  allChecked.value = false;
  score.value = 0;
  answers.value = {};
  feedbacks.value = {};
  showResults.value = false;
};

const contentStyle = computed(() => ({
  fontSize: props.questions.fontSize ? `${props.questions.fontSize}px` : "20px",
}));
</script>

<template>
  <div class="h-full flex flex-col">
    <ActivityTitle :title="props.questions.title" />

    <div v-if="!showResults" class="flex flex-col h-full bg-picton-blue-100" :style="contentStyle">
      <div class="grid grid-cols-2 gap-4 py-4 flex-1 overflow-y-auto">
        <div
          v-for="(question, index) in shuffledQuestions"
          :key="index"
          class="bg-picton-blue-50 h-fit flex flex-col rounded-lg p-6"
          :class="
            cn({
              'bg-green-100 text-green-700': allChecked && feedbacks[index],
              'bg-red-100 text-red-700': allChecked && feedbacks[index] === false,
            })
          "
        >
          <div class="flex flex-col justify-between h-full">
            <p class="mb-4">{{ question.word }}</p>
            <div>
              <Input
                :model-value="answers[index] || ''"
                :disabled="allChecked"
                class="px-2 border-none bg-transparent text-center"
                @update:modelValue="(v: string | number) => handleInputChange(index, String(v ?? ''))"
              />
              <div
                class="w-full border-b border-dashed border-picton-blue-700 mt-2"
                :class="
                  cn({
                    'border-green-700': allChecked && feedbacks[index],
                    'border-red-700': allChecked && feedbacks[index] === false,
                  })
                "
              />
            </div>
          </div>
          <div v-if="allChecked" class="flex justify-center mt-4">
            <div
              class="flex items-center justify-center rounded-full p-1"
              :class="feedbacks[index] ? 'bg-green-100 text-green-600' : 'bg-red-100 text-red-600'"
            >
              <Icon :icon="feedbacks[index] ? 'mdi:check' : 'mdi:close'" class="h-6 w-6" />
            </div>
          </div>
        </div>
      </div>

      <Button
        v-if="!allChecked"
        :onClick="handleCheckAll"
        :disabled="!allAnswered"
        variant="brand-lemon"
        class="ml-auto text-lg py-3"
      >
        Check Answers
      </Button>

      <div v-if="allChecked" class="p-4 bg-picton-blue-100 border-t">
        <Button
          :onClick="() => { showResults = true; }"
          variant="brand-lemon"
          class="w-full text-lg py-3"
        >
          View Results
        </Button>
      </div>
    </div>

    <div v-else class="flex flex-col h-full bg-picton-blue-100 p-6 overflow-y-auto" :style="contentStyle">
      <div class="bg-picton-blue-50 rounded-lg p-6">
        <div class="grid grid-cols-2 gap-4 mb-8">
          <div
            v-for="(question, idx) in shuffledQuestions"
            :key="idx"
            class="p-4 rounded-lg border"
            :class="compareAnswersLocal(answers[idx] || '', question.answer) ? 'bg-green-50 border-green-200' : 'bg-red-50 border-red-200'"
          >
            <div class="flex justify-between items-center mb-2">
              <p class="font-medium">{{ question.word }}</p>
              <div
                class="flex items-center justify-center rounded-full p-1"
                :class="compareAnswersLocal(answers[idx] || '', question.answer) ? 'bg-green-100 text-green-600' : 'bg-red-100 text-red-600'"
              >
                <Icon
                  :icon="compareAnswersLocal(answers[idx] || '', question.answer) ? 'mdi:check' : 'mdi:close'"
                  class="h-5 w-5"
                />
              </div>
            </div>

            <div class="space-y-2">
              <div>
                <p class="text-sm text-gray-500">Your answer:</p>
                <p :class="compareAnswersLocal(answers[idx] || '', question.answer) ? 'text-green-600' : 'text-red-600'">
                  {{ answers[idx] || "(no answer)" }}
                </p>
              </div>
              <div
                v-if="props.feedback === 'wrong-correct-answers' && !compareAnswersLocal(answers[idx] || '', question.answer)"
              >
                <p class="text-sm text-gray-500">Correct answer:</p>
                <p class="text-green-600">
                  {{ Array.isArray(question.answer) ? question.answer.join(" / ") : question.answer }}
                </p>
              </div>
            </div>
          </div>
        </div>

        <ActivityResults :score="score" :total="shuffledQuestions.length" :onRestart="resetGame" />
      </div>
    </div>

    <ActivityResultsAlertDialog
      :score="score"
      :total="shuffledQuestions.length"
      :open="allChecked && !showResults"
      :onOpenChange="(open: boolean) => {
        if (!open) showResults = true;
      }"
    />
  </div>
</template>

// app/components/primary-sources/activities/complete-sentences/complete-sentences-with-two-clauses.tsx
import { useState, useEffect } from "react";
import { Check, X } from "lucide-react";

// Local imports
import { cn, shuffle } from "@/lib/utils";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/inputs/input";
import { FeedbackType } from "@/lib/types/activity-types";
import { compareAnswers } from "@/lib/utils/answer-processing";
import ActivityTitle from "@/components/templates/activity-title";
import { useSoundEffects } from "@/shared/hooks/use-sound-effects";
import ActivityResults, {
  ActivityResultsAlertDialog,
} from "@/components/templates/results";

type TCompleteSentencesWithTwoClauses = {
  feedback: FeedbackType;
  questions: {
    title: string;
    fontSize?: string;
    questions: {
      word: string;
      answer: string | string[];
    }[];
  };
};

const CompleteSentencesWithTwoClausesActivity = ({
  feedback,
  questions,
}: TCompleteSentencesWithTwoClauses) => {
  const [shuffledQuestions, setShuffledQuestions] = useState([
    ...questions.questions,
  ]);
  const [score, setScore] = useState(0);
  const [allAnswered, setAllAnswered] = useState(false);
  const [allChecked, setAllChecked] = useState(false);
  const [answers, setAnswers] = useState<{ [key: number]: string }>({});
  const [feedbacks, setFeedbacks] = useState<{ [key: number]: boolean }>({});
  const [showResults, setShowResults] = useState(false);

  const { playSound } = useSoundEffects();

  // Function to shuffle questions
  const shuffleQuestions = () => {
    const shuffled = shuffle([...questions.questions]);
    setShuffledQuestions(shuffled);
  };

  // Initialize with shuffled questions
  useEffect(() => {
    shuffleQuestions();
  }, [questions.questions]);

  // Check if all questions have answers
  useEffect(() => {
    const hasAllAnswers = shuffledQuestions.every(
      (_, index) => answers[index]?.trim().length > 0,
    );
    setAllAnswered(hasAllAnswers);
  }, [answers, shuffledQuestions]);

  const handleCheckAll = () => {
    let correctCount = 0;
    const newFeedbacks: { [key: number]: boolean } = {};

    shuffledQuestions.forEach((question, index) => {
      const userAnswer = answers[index]?.trim().toLowerCase();
      const correctAnswer = question.answer;

      const isCorrect = compareAnswers(userAnswer, correctAnswer, {
        preserveSpaces: true,
      });

      newFeedbacks[index] = isCorrect;
      if (isCorrect) {
        correctCount++;
      }
    });

    setFeedbacks(newFeedbacks);
    setScore(correctCount);
    setAllChecked(true);

    // Play sound based on overall performance
    const percentage = (correctCount / shuffledQuestions.length) * 100;
    if (percentage === 100) {
      playSound("success");
    } else if (percentage >= 70) {
      playSound("correct");
    } else {
      playSound("failure");
    }
  };

  const handleInputChange = (index: number, value: string) => {
    setAnswers((prev) => ({
      ...prev,
      [index]: value,
    }));
  };

  const resetGame = () => {
    shuffleQuestions();
    setAllAnswered(false);
    setAllChecked(false);
    setScore(0);
    setAnswers({});
    setFeedbacks({});
    setShowResults(false);
  };

  return (
    <div className="h-full flex flex-col">
      <ActivityTitle title={questions.title} />

      {!showResults ? (
        <div
          className="flex flex-col h-full bg-picton-blue-100"
          style={{
            fontSize: questions.fontSize ? `${questions.fontSize}px` : "20px",
          }}
        >
          <div className="grid grid-cols-2 gap-4 py-4 flex-1 overflow-y-auto">
            {shuffledQuestions.map((question, index) => (
              <div
                key={index}
                className={cn(
                  "bg-picton-blue-50 h-fit flex flex-col rounded-lg p-6",
                  {
                    "bg-green-100 text-green-700":
                      allChecked && feedbacks[index],
                    "bg-red-100 text-red-700":
                      allChecked && feedbacks[index] === false,
                  },
                )}
              >
                <div className="flex flex-col justify-between h-full">
                  <p className="mb-4">{question.word}</p>
                  <div>
                    <Input
                      value={answers[index] || ""}
                      onChange={(e) => handleInputChange(index, e.target.value)}
                      disabled={allChecked}
                      className="px-2 border-none bg-transparent text-center"
                      // placeholder="Complete the sentence..."
                    />
                    <div
                      className={cn(
                        "w-full border-b border-dashed border-picton-blue-700 mt-2",
                        {
                          "border-green-700": allChecked && feedbacks[index],
                          "border-red-700":
                            allChecked && feedbacks[index] === false,
                        },
                      )}
                    />
                  </div>
                </div>
                {allChecked && (
                  <div className="flex justify-center mt-4">
                    <div
                      className={cn(
                        "flex items-center justify-center rounded-full p-1",
                        feedbacks[index]
                          ? "bg-green-100 text-green-600"
                          : "bg-red-100 text-red-600",
                      )}
                    >
                      {feedbacks[index] ? (
                        <Check className="h-6 w-6" />
                      ) : (
                        <X className="h-6 w-6" />
                      )}
                    </div>
                  </div>
                )}
              </div>
            ))}
          </div>

          {/* Check Answers Button */}
          {!allChecked && (
            <Button
              onClick={handleCheckAll}
              disabled={!allAnswered}
              variant="brand-lemon"
              className="ml-auto text-lg py-3"
            >
              Check Answers
            </Button>
          )}

          {/* View Results Button */}
          {allChecked && (
            <div className="p-4 bg-picton-blue-100 border-t">
              <Button
                onClick={() => setShowResults(true)}
                variant="brand-lemon"
                className="w-full text-lg py-3"
              >
                View Results
              </Button>
            </div>
          )}
        </div>
      ) : (
        <div
          className="flex flex-col h-full bg-picton-blue-100 p-6 overflow-y-auto"
          style={{
            fontSize: questions.fontSize ? `${questions.fontSize}px` : "20px",
          }}
        >
          <div className="bg-picton-blue-50 rounded-lg p-6">
            <div className="grid grid-cols-2 gap-4 mb-8">
              {shuffledQuestions.map((question, idx) => {
                const userAnswer = answers[idx] || "";
                const isCorrect = compareAnswers(userAnswer, question.answer, {
                  preserveSpaces: true,
                });

                return (
                  <div
                    key={idx}
                    className={cn(
                      "p-4 rounded-lg border",
                      isCorrect
                        ? "bg-green-50 border-green-200"
                        : "bg-red-50 border-red-200",
                    )}
                  >
                    <div className="flex justify-between items-center mb-2">
                      <p className="font-medium">{question.word}</p>
                      <div
                        className={cn(
                          "flex items-center justify-center rounded-full p-1",
                          isCorrect
                            ? "bg-green-100 text-green-600"
                            : "bg-red-100 text-red-600",
                        )}
                      >
                        {isCorrect ? (
                          <Check className="h-5 w-5" />
                        ) : (
                          <X className="h-5 w-5" />
                        )}
                      </div>
                    </div>

                    <div className="space-y-2">
                      <div>
                        <p className="text-sm text-gray-500">Your answer:</p>
                        <p
                          className={
                            !isCorrect ? "text-red-600" : "text-green-600"
                          }
                        >
                          {userAnswer || "(no answer)"}
                        </p>
                      </div>
                      {feedback === "wrong-correct-answers" && !isCorrect && (
                        <div>
                          <p className="text-sm text-gray-500">
                            Correct answer:
                          </p>
                          <p className="text-green-600">{question.answer}</p>
                        </div>
                      )}
                    </div>
                  </div>
                );
              })}
            </div>

            <ActivityResults
              score={score}
              total={shuffledQuestions.length}
              onRestart={resetGame}
            />
          </div>
        </div>
      )}

      <ActivityResultsAlertDialog
        score={score}
        total={shuffledQuestions.length}
        open={allChecked && !showResults}
        onOpenChange={(open) => {
          if (!open) setShowResults(true);
        }}
      />
    </div>
  );
};

export default CompleteSentencesWithTwoClausesActivity;
