// app/components/primary-sources/activities/exam-activities/exam-complete-sentences-by-rephrasing.tsx
"use client";

import { motion } from "motion/react";
import { useEffect, useState } from "react";

// Local imports
import { cn, toRoman } from "@/lib/utils";
import { useExamContext } from "@/shared/context/exam-context";
import { AnswerChecker } from "@/lib/utils/answer-checker";
import { QuestionAnswer } from "@/shared/context/exam-context";
import { useWindowSize } from "@/shared/hooks/use-window-size";
import { ActivityType } from "@/lib/types/activity-types";
import { QuestionRenderer } from "@/components/activity-helpers";

export type ExamCompleteSentencesByRephrasingProps = {
  questions: {
    title: string;
    fontSize?: number;
    algorithm: ActivityType;
    questions: {
      id: string;
      question: string;
      answer: string[];
      image?: string | null;
    }[];
    options?: string[];
  };
  activityIndex: number;
  activityId: string;
  onStateUpdate?: (totalQuestions: number, answeredCount: number) => void;
};

const answerChecker = new AnswerChecker();

const ExamCompleteSentencesByRephrasing = ({
  questions,
  activityIndex,
  activityId,
  onStateUpdate,
}: ExamCompleteSentencesByRephrasingProps) => {
  const { width } = useWindowSize();
  const [answers, setAnswers] = useState<Record<string, string>>({});

  const { collectAnswers, updateActivityScore } = useExamContext();

  const totalQuestions = questions.questions.length;

  // Check answer based on algorithm type
  const checkAnswer = (userAnswer: string, question: { answer: string[] }) => {
    // Split user answers by comma and trim each answer
    const userAnswers = userAnswer
      .split("|")
      .map((ans: string) => ans.trim().toLowerCase());
    const correctAnswers = question.answer.map((ans: string) =>
      ans.toLowerCase(),
    );

    // Check if all answers match their corresponding correct answers
    return (
      (questions.algorithm === ActivityType.CompleteSentencesByRephrasing ||
        questions.algorithm ===
          ActivityType.CompleteSentenceByRephrasingWithChoices ||
        userAnswers.length === correctAnswers.length) &&
      userAnswers.every(
        (ans: string, i: number) =>
          answerChecker.checkAnswer(ans, {
            acceptedAnswers:
              questions.algorithm ===
                ActivityType.CompleteSentencesByRephrasing ||
              questions.algorithm ===
                ActivityType.CompleteSentenceByRephrasingWithChoices
                ? correctAnswers
                : [correctAnswers[i]],
            strictMode: true,
          }).isCorrect,
      )
    );
  };

  // Calculate score for this activity using AI answer checking
  const calculateScore = async () => {
    let score = 0;
    const detailedAnswers: QuestionAnswer[] = [];

    questions.questions.forEach((question) => {
      const userAnswerString = answers[question.id] || "";
      const isCorrect = checkAnswer(userAnswerString, question);

      if (isCorrect) {
        score++;
      }

      // Store detailed answer information
      detailedAnswers.push({
        questionId: question.id,
        userAnswer: userAnswerString,
        correctAnswer: question.answer.join("| "),
        isCorrect,
        question: question.question,
        options: questions.options || [],
      });
    });

    return { score, answers: detailedAnswers };
  };

  // Update exam context whenever answers change (with debouncing for AI calls)
  useEffect(() => {
    if (!collectAnswers) return;

    const updateScore = async () => {
      const { score, answers } = await calculateScore();

      updateActivityScore(activityIndex, {
        activityId,
        activityIndex,
        score,
        totalQuestions,
        answers,
      });
    };

    updateScore();
  }, [collectAnswers, answers]);

  // Update parent component state immediately for visual feedback
  useEffect(() => {
    const answeredCount = Object.keys(answers).filter(
      (key) => answers[key]?.trim() !== "",
    ).length;

    onStateUpdate?.(totalQuestions, answeredCount);
  }, [answers, totalQuestions]);

  // Handle input change for multiple blanks in a question
  const handleInputChange = (
    questionId: string,
    blankIndex: number,
    value: string,
  ) => {
    setAnswers((prev) => {
      const currentAnswerString = prev[questionId] || "";
      const currentAnswers = currentAnswerString.split("|");

      // Ensure array has enough elements
      while (currentAnswers.length <= blankIndex) {
        currentAnswers.push("");
      }

      currentAnswers[blankIndex] = value;

      return {
        ...prev,
        [questionId]: currentAnswers.join("|"),
      };
    });
  };

  // Handle input change for single blank (with choices algorithm)
  const handleSingleInputChange = (questionId: string, value: string) => {
    setAnswers((prev) => ({
      ...prev,
      [questionId]: value,
    }));
  };

  // Render question with input fields for blanks
  const renderQuestion = (
    questionText: string,
    questionId: string,
    questionAnswers: string[],
  ) => {
    // Get current answers for this question
    const currentAnswerString = answers[questionId] || "";
    const currentAnswers = currentAnswerString.split("|");

    const handleBlankChange = (blankIndex: number, value: string) => {
      // For with choices algorithm, use single input handling
      if (
        questions.algorithm ===
        ActivityType.CompleteSentenceByRephrasingWithChoices
      ) {
        handleSingleInputChange(questionId, value);
      } else {
        handleInputChange(questionId, blankIndex, value);
      }
    };

    return (
      <QuestionRenderer
        question={questionText}
        answers={questionAnswers}
        userAnswers={currentAnswers}
        mode="exam"
        screenWidth={width}
        onBlankChange={handleBlankChange}
        highlightClassName="bg-lemon-100 text-lemon-700"
      />
    );
  };

  return (
    <div
      className="h-full flex flex-col bg-white rounded-b-xl shadow-sm"
      style={{
        fontSize: questions.fontSize ? `${questions.fontSize}px` : "20px",
      }}
    >
      {/* Options section - show at top for with choices algorithm */}
      {questions.options &&
        questions.options.length > 0 &&
        questions.algorithm ===
          ActivityType.CompleteSentenceByRephrasingWithChoices && (
          <div className="p-4 pb-2">
            <div className="flex flex-wrap gap-2 border-2 border-picton-blue-300 bg-picton-blue-100 w-fit py-4 rounded">
              {questions.options.map((option, index) => (
                <div
                  key={index}
                  className="text-picton-blue-700 leading-4 px-3"
                >
                  {option}
                </div>
              ))}
            </div>
          </div>
        )}

      {/* Questions container - scrollable */}
      <div className="flex-1 overflow-y-auto p-2 md:p-4">
        <div className="space-y-8">
          {questions.questions.map((question, questionIndex) => {
            const userAnswer = answers[question.id] || "";
            const hasAnswer = userAnswer.trim() !== "";

            return (
              <motion.div
                key={questionIndex}
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: questionIndex * 0.1 }}
                className="border rounded-lg p-2 md:flex-1 bg-neutral-50"
              >
                <div className="flex flex-col md:flex-row items-center justify-between md:gap-2">
                  <div>
                    <p
                      className={cn(
                        "w-6 md:w-8 h-6 md:h-8 rounded-full mr-1 inline-flex items-center justify-center font-bold text-sm flex-shrink-0",
                        hasAnswer
                          ? "bg-picton-blue-500 text-white"
                          : "bg-gray-200 text-gray-600",
                      )}
                    >
                      {toRoman(questionIndex + 1)}{" "}
                    </p>
                    <div className="inline">
                      {renderQuestion(
                        question.question,
                        question.id,
                        question.answer,
                      )}
                    </div>
                  </div>
                  {question.image && (
                    <div className="min-w-[150px] h-32 md:h-28">
                      <img
                        src={question.image}
                        alt={question.question}
                        className="w-full h-full rounded-lg object-cover"
                      />
                    </div>
                  )}
                </div>
              </motion.div>
            );
          })}
        </div>
      </div>

      {/* Options section - show at bottom for other algorithms */}
      {questions.options &&
        questions.options.length > 0 &&
        questions.algorithm !==
          ActivityType.CompleteSentenceByRephrasingWithChoices && (
          <div className="p-4 py-2 border-t bg-white space-y-1">
            <h3 className="font-semibold text-picton-blue-700">
              Available options:
            </h3>
            <div className="flex flex-wrap gap-2 bg-picton-blue-100 w-fit py-4 rounded">
              {questions.options.map((option, index) => (
                <div
                  key={index}
                  className="text-picton-blue-700 leading-4 px-3"
                >
                  {option}
                </div>
              ))}
            </div>
          </div>
        )}
    </div>
  );
};

export default ExamCompleteSentencesByRephrasing;

// app/components/primary-sources/activities/exam-activities/exam-complete-sentences-by-rephrasing.vue
<script setup lang="ts">
import { computed, ref, watch } from "vue";
import { useWindowSize } from "@vueuse/core";
import { Input } from "~/components/ui/input";
import { calculateBlankWidth, parseQuestionSegments, type QuestionSegment } from "~/components/primary-sources/activity-helpers/question-renderer-utils";
import { AnswerChecker } from "~/lib/utils/answer-checker";
import { ActivityType } from "~/types/activity-types";
import { cn, toRoman } from "~/utilities/utils";
import { useExamContext, type QuestionAnswer } from "~/shared/context/exam-context";

type ExamCompleteSentencesByRephrasingProps = {
  questions: {
    title: string;
    fontSize?: number;
    algorithm: ActivityType;
    questions: {
      id: string;
      question: string;
      answer: string[];
      image?: string | null;
    }[];
    options?: string[];
  };
  activityIndex: number;
  activityId: string;
  onStateUpdate?: (totalQuestions: number, answeredCount: number) => void;
};

type RenderSegment = QuestionSegment & {
  blankIndex?: number;
  calculatedWidth?: number;
  isTwoUnderscores?: boolean;
};

const props = defineProps<ExamCompleteSentencesByRephrasingProps>();

const answerChecker = new AnswerChecker();
const { width } = useWindowSize();
const { collectAnswers, updateActivityScore } = useExamContext();

const answers = ref<Record<string, string>>({});
const totalQuestions = computed(() => props.questions.questions.length);
const fontSizeStyle = computed(() => ({
  fontSize: props.questions.fontSize ? `${props.questions.fontSize}px` : "20px",
}));

const checkAnswer = (userAnswer: string, question: { answer: string[] }) => {
  const userAnswers = userAnswer
    .split("|")
    .map((answer) => answer.trim().toLowerCase())
    .filter((answer, index, allAnswers) => answer !== "" || index < allAnswers.length);

  const correctAnswers = question.answer.map((answer) => answer.toLowerCase());

  return (
    (props.questions.algorithm === ActivityType.CompleteSentencesByRephrasing ||
      props.questions.algorithm === ActivityType.CompleteSentenceByRephrasingWithChoices ||
      userAnswers.length === correctAnswers.length) &&
    userAnswers.every((answer, index) =>
      answerChecker.checkAnswer(answer, {
        acceptedAnswers :
          props.questions.algorithm === ActivityType.CompleteSentencesByRephrasing ||
          props.questions.algorithm === ActivityType.CompleteSentenceByRephrasingWithChoices
            ? correctAnswers
            : [correctAnswers[index]] as string[],
        strictMode: true,
      }).isCorrect,
    )
  );
};

const calculateScore = () => {
  let score = 0;
  const detailedAnswers: QuestionAnswer[] = [];

  props.questions.questions.forEach((question) => {
    const userAnswer = answers.value[question.id] || "";
    const isCorrect = checkAnswer(userAnswer, question);

    if (isCorrect) {
      score++;
    }

    detailedAnswers.push({
      questionId: question.id,
      userAnswer,
      correctAnswer: question.answer.join("| "),
      isCorrect,
      question: question.question,
      options: props.questions.options || [],
    });
  });

  return { score, answers: detailedAnswers };
};

const getCurrentAnswers = (questionId: string) =>
  (answers.value[questionId] || "").split("|");

const buildSegments = (questionText: string): RenderSegment[] => {
  let blankIndex = 0;

  return parseQuestionSegments(questionText).map((segment) => {
    if (segment.type !== "blank") {
      return segment;
    }

    const { calculatedWidth, isTwoUnderscores } = calculateBlankWidth(
      segment.content.length,
      width.value || 1024,
    );

    const enrichedSegment: RenderSegment = {
      ...segment,
      blankIndex,
      calculatedWidth,
      isTwoUnderscores,
    };

    blankIndex++;
    return enrichedSegment;
  });
};

const handleInputChange = (questionId: string, blankIndex: number, value: string | number) => {
  if (props.questions.algorithm === ActivityType.CompleteSentenceByRephrasingWithChoices) {
    answers.value = {
      ...answers.value,
      [questionId]: String(value ?? ""),
    };
    return;
  }

  const currentAnswers = getCurrentAnswers(questionId);
  while (currentAnswers.length <= blankIndex) {
    currentAnswers.push("");
  }

  currentAnswers[blankIndex] = String(value ?? "");

  answers.value = {
    ...answers.value,
    [questionId]: currentAnswers.join("|"),
  };
};

watch(
  answers,
  () => {
    const answeredCount = Object.values(answers.value).filter((answer) => answer.trim() !== "").length;
    props.onStateUpdate?.(totalQuestions.value, answeredCount);
  },
  { deep: true },
);

watch(
  [answers, collectAnswers],
  () => {
    if (!collectAnswers.value) return;

    const { score, answers: detailedAnswers } = calculateScore();
    updateActivityScore(props.activityIndex, {
      activityId: props.activityId,
      activityIndex: props.activityIndex,
      score,
      totalQuestions: totalQuestions.value,
      answers: detailedAnswers,
    });
  },
  { deep: true },
);
</script>

<template>
  <div class="flex h-full flex-col rounded-b-xl bg-white shadow-sm" :style="fontSizeStyle">
    <div
      v-if="
        props.questions.options?.length &&
        props.questions.algorithm === ActivityType.CompleteSentenceByRephrasingWithChoices
      "
      class="p-4 pb-2"
    >
      <div class="flex w-fit flex-wrap gap-2 rounded border-2 border-picton-blue-300 bg-picton-blue-100 py-4">
        <div
          v-for="option in props.questions.options"
          :key="option"
          class="px-3 leading-4 text-picton-blue-700"
        >
          {{ option }}
        </div>
      </div>
    </div>

    <div class="flex-1 overflow-y-auto p-2 md:p-4">
      <div class="space-y-8">
        <div
          v-for="(question, questionIndex) in props.questions.questions"
          :key="question.id"
          class="rounded-lg border bg-neutral-50 p-2 md:flex-1"
        >
          <div class="flex flex-col items-center justify-between md:flex-row md:gap-2">
            <div>
              <p
                :class="
                  cn(
                    'mr-1 inline-flex h-6 w-6 flex-shrink-0 items-center justify-center rounded-full text-sm font-bold md:h-8 md:w-8',
                    (answers[question.id] || '').trim() !== ''
                      ? 'bg-picton-blue-500 text-white'
                      : 'bg-gray-200 text-gray-600',
                  )
                "
              >
                {{ toRoman(questionIndex + 1) }}
              </p>
              <div class="inline leading-loose">
                <template
                  v-for="segment in buildSegments(question.question)"
                  :key="`${question.id}-${segment.index}`"
                >
                  <span
                    v-if="segment.type === 'text'"
                    class="mx-1 items-center leading-loose"
                  >
                    {{ segment.content }}
                  </span>

                  <span
                    v-else-if="segment.type === 'highlighted'"
                    class="mx-1 items-center rounded bg-lemon-100 px-2 leading-loose text-lemon-700"
                  >
                    {{ segment.content }}
                  </span>

                  <span
                    v-else
                    :class="cn('mx-1 inline-flex', { 'flex-col': !segment.isTwoUnderscores })"
                    :style="{ width: `${segment.calculatedWidth}px` }"
                  >
                    <Input
                      type="text"
                      :model-value="getCurrentAnswers(question.id)[segment.blankIndex || 0] || ''"
                      class="min-w-0 border-none bg-transparent px-2 text-center"
                      :style="{ maxWidth: `${(segment.calculatedWidth || 0) * 1.6}px` }"
                      @update:model-value="
                        (value) => handleInputChange(question.id, segment.blankIndex || 0, value)
                      "
                    />
                    <div
                      v-if="!segment.isTwoUnderscores"
                      class="border-b border-dashed border-picton-blue-700"
                    />
                  </span>
                </template>
              </div>
            </div>

            <div v-if="question.image" class="h-32 min-w-[150px] md:h-28">
              <img
                :src="question.image"
                :alt="question.question"
                class="h-full w-full rounded-lg object-cover"
              >
            </div>
          </div>
        </div>
      </div>
    </div>

    <div
      v-if="
        props.questions.options?.length &&
        props.questions.algorithm !== ActivityType.CompleteSentenceByRephrasingWithChoices
      "
      class="space-y-1 border-t bg-white p-4 py-2"
    >
      <h3 class="font-semibold text-picton-blue-700">Available options:</h3>
      <div class="flex w-fit flex-wrap gap-2 rounded bg-picton-blue-100 py-4">
        <div
          v-for="option in props.questions.options"
          :key="option"
          class="px-3 leading-4 text-picton-blue-700"
        >
          {{ option }}
        </div>
      </div>
    </div>
  </div>
</template>
