// app/components/primary-sources/activities/exam-activities/exam-comprehension-junior-one.tsx
"use client";

import { useState, useEffect, useCallback, useMemo } from "react";
import { motion } from "motion/react";

// local imports
import { cn, toRoman } from "@/lib/utils";
import { Textarea } from "@/components/ui/textarea";
import { AnswerChecker } from "@/lib/utils/answer-checker";
import { useExamContext } from "@/shared/context/exam-context";

export type ExamComprehensionJuniorOneProps = {
  questions: {
    title: string;
    algorithm: "Comprehension junior one" | "Comprehension junior two";
    notes: string;
    image?: string;
    optionsTitle?: string;
    useAI?: boolean;
    questions: {
      question: string;
      image?: string;
      answers: string[];
      options: {
        id: string;
        text: string;
      }[];
    }[];
  };
  activityIndex: number;
  activityId: string;
  onStateUpdate?: (totalQuestions: number, answeredCount: number) => void;
};

const answerChecker = new AnswerChecker();

const ExamComprehensionJuniorOne = ({
  questions,
  activityIndex,
  activityId,
  onStateUpdate,
}: ExamComprehensionJuniorOneProps) => {
  const [allUserAnswers, setAllUserAnswers] = useState<
    Record<number, string[]>
  >({});
  const [isCheckingAnswers, setIsCheckingAnswers] = useState(false);

  const { collectAnswers, updateActivityScore } = useExamContext();

  // Memoize total questions calculation
  const totalQuestions = useMemo(
    () => questions.questions.length,
    [questions.questions],
  );

  // Memoized answered count for parent updates
  const answeredCount = useMemo(() => {
    return Object.values(allUserAnswers).reduce((total, questionAnswers) => {
      return (
        total + questionAnswers.filter((answer) => answer.trim() !== "").length
      );
    }, 0);
  }, [allUserAnswers]);

  // Calculate score for this activity using AI
  const calculateScoreWithAI = useCallback(async () => {
    try {
      setIsCheckingAnswers(true);

      const allSubmissions: { questionId: string; answer: string }[] = [];
      const allAIQuestions: any[] = [];

      // Create comprehensive context with reading material
      const comprehensionContext = {
        readingMaterial: questions.notes,
        activityTitle: questions.title,
        activityType: "reading-comprehension",
        instructions:
          "Answer based on the provided reading material. Demonstrate understanding of the text content.",
      };

      questions.questions.forEach((question, questionIndex) => {
        const userAnswers = allUserAnswers[questionIndex] || [];

        userAnswers.forEach((answer, answerIndex) => {
          if (!answer.trim()) return; // Skip empty answers

          const submissionId = `q${questionIndex}-a${answerIndex}`;

          allSubmissions.push({
            questionId: submissionId,
            answer: answer.trim(),
          });

          allAIQuestions.push({
            id: submissionId,
            question: question.question,
            context: comprehensionContext,
            acceptedAnswers: question.answers[answerIndex]
              ? [question.answers[answerIndex]]
              : [],
            strictMode: false,
            maxMarks: 1,
            questionType: "reasoning" as const, // Required for AI evaluation
            evaluationCriteria: `Evaluate this comprehension answer based on the provided reading material. The student should demonstrate understanding of the text content. Accept answers that are semantically equivalent to the expected answer or show clear comprehension of the relevant concepts from the reading. Award full marks for correct understanding, partial marks for partially correct responses that show some comprehension.`,
          });
        });
      });

      const results = await answerChecker.checkAnswersWithAI(
        allSubmissions,
        allAIQuestions,
      );

      // Calculate total score from AI results
      const score = results.reduce((total, result) => {
        return total + result.result.marksAwarded;
      }, 0);

      return { score };
    } catch (error) {
      console.error("AI checking failed:", error);

      // Fallback to traditional checking
      let score = 0;
      questions.questions.forEach((question, questionIndex) => {
        const userAnswers = allUserAnswers[questionIndex] || [];
        userAnswers.forEach((answer, answerIndex) => {
          const result = answerChecker.checkAnswer(answer.trim(), {
            acceptedAnswers: [question.answers[answerIndex]],
          });
          if (result.isCorrect) {
            score++;
          }
        });
      });

      return { score };
    } finally {
      setIsCheckingAnswers(false);
    }
  }, [allUserAnswers, questions, answerChecker]);

  // Update exam context when answers are collected
  useEffect(() => {
    if (!collectAnswers) return;

    const processScoring = async () => {
      const { score } = await calculateScoreWithAI();
      updateActivityScore(activityIndex, {
        activityId,
        activityIndex,
        score,
        totalQuestions,
      });
    };

    processScoring();
  }, [collectAnswers]);

  // Update progress state
  useEffect(() => {
    onStateUpdate?.(totalQuestions, answeredCount);
  }, [totalQuestions, answeredCount]);

  // Optimized input change handler
  const handleInputChange = useCallback(
    (questionIndex: number, answerIndex: number, value: string) => {
      setAllUserAnswers((prev) => {
        const questionAnswers =
          prev[questionIndex] ||
          Array(questions.questions[questionIndex].answers.length).fill("");
        const newQuestionAnswers = [...questionAnswers];
        newQuestionAnswers[answerIndex] = value;

        return {
          ...prev,
          [questionIndex]: newQuestionAnswers,
        };
      });
    },
    [questions.questions],
  );

  // Memoized textarea component to prevent unnecessary re-renders
  const MemoizedTextarea = useCallback(
    ({
      questionIndex,
      answerIndex,
      userAnswer,
      hasAnswer,
      placeholder = "Type your answer here...",
      className = "",
    }: {
      questionIndex: number;
      answerIndex: number;
      userAnswer: string;
      hasAnswer: boolean;
      placeholder?: string;
      className?: string;
    }) => (
      <div className="relative">
        <Textarea
          value={userAnswer}
          onChange={(e) =>
            handleInputChange(questionIndex, answerIndex, e.target.value)
          }
          placeholder={placeholder}
          className={cn(
            "text-base min-h-[40px] focus:border-picton-blue-500",
            hasAnswer && "border-picton-blue-400 bg-picton-blue-50/30",
            className,
          )}
          rows={1}
          disabled={isCheckingAnswers}
        />
        <div className="absolute top-2 right-2">
          <div
            className={cn(
              "w-3 h-3 rounded-full",
              hasAnswer ? "bg-green-500" : "bg-neutral-300",
            )}
          />
        </div>
        {/* <div className="border-b border-dashed border-picton-blue-700 mt-1" /> */}
      </div>
    ),
    [handleInputChange, isCheckingAnswers],
  );

  const renderQuestionWithInputs = (question: any, questionIndex: number) => {
    const userAnswers =
      allUserAnswers[questionIndex] || Array(question.answers.length).fill("");

    if (question.question.includes("___")) {
      // Handle fill-in-the-blank questions
      const parts = question.question.split("___");

      return (
        <div className="text-base leading-relaxed">
          {parts.map((part: string, partIndex: number) => (
            <span key={partIndex}>
              <span>{part}</span>
              {partIndex < parts.length - 1 && (
                <span className="inline-block mx-2 align-middle">
                  <MemoizedTextarea
                    questionIndex={questionIndex}
                    answerIndex={partIndex}
                    userAnswer={userAnswers[partIndex] || ""}
                    hasAnswer={(userAnswers[partIndex] || "").trim() !== ""}
                    className="max-w-40"
                  />
                </span>
              )}
            </span>
          ))}
        </div>
      );
    } else {
      // Handle regular questions with single answer
      return (
        <div className="space-y-3">
          <p className="text-base font-medium">{question.question}</p>
          <div className="w-full">
            <MemoizedTextarea
              questionIndex={questionIndex}
              answerIndex={0}
              userAnswer={userAnswers[0] || ""}
              hasAnswer={(userAnswers[0] || "").trim() !== ""}
              placeholder="Enter your answer here..."
              className="w-full"
            />
          </div>
        </div>
      );
    }
  };

  return (
    <div className="h-full flex flex-col bg-white rounded-xl shadow-sm">
      {/* Content container - scrollable */}
      <div className="flex gap-2 h-full">
        {/* Notes section */}
        <div className="bg-white w-1/2 flex flex-col justify-start rounded-xl p-6">
          <div className="overflow-auto max-h-[calc(100vh-200px)]">
            <div
              className="whitespace-pre-line text-base leading-relaxed text-picton-blue-700"
              dangerouslySetInnerHTML={{
                __html: questions.notes,
              }}
            />
          </div>
        </div>

        {/* Questions section */}
        <div className="w-1/2 flex flex-col rounded-xl p-6">
          <div className="flex-1 overflow-y-auto">
            <div className="space-y-8">
              {questions.questions.map((question, questionIndex) => (
                <motion.div
                  key={questionIndex}
                  initial={{ opacity: 0, y: 20 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ delay: questionIndex * 0.1 }}
                  className="border rounded-lg p-6 bg-neutral-50 text-neutral-700"
                >
                  <div className="flex items-start gap-4">
                    {/* Question number circle */}
                    <div className="font-semibold flex-shrink-0">
                      {toRoman(questionIndex + 1)}.
                    </div>

                    {/* Question content */}
                    <div className="flex-1">
                      {renderQuestionWithInputs(question, questionIndex)}
                    </div>
                  </div>
                </motion.div>
              ))}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default ExamComprehensionJuniorOne;

// app/components/primary-sources/activities/exam-activities/exam-comprehension-junior-one.vue
<script setup lang="ts">
import { computed, ref, watch } from "vue";
import { Textarea } from "~/components/ui/textarea";
import { AnswerChecker } from "~/lib/utils/answer-checker";
import { toRoman } from "~/utilities/utils";
import { useExamContext } from "~/shared/context/exam-context";

type ExamComprehensionJuniorOneProps = {
  questions: {
    title: string;
    algorithm: "Comprehension junior one" | "Comprehension junior two";
    notes: string;
    image?: string;
    optionsTitle?: string;
    useAI?: boolean;
    questions: {
      question: string;
      image?: string;
      answers: string[];
      options: {
        id: string;
        text: string;
      }[];
    }[];
  };
  activityIndex: number;
  activityId: string;
  onStateUpdate?: (totalQuestions: number, answeredCount: number) => void;
};

const props = defineProps<ExamComprehensionJuniorOneProps>();

const answerChecker = new AnswerChecker();
const { collectAnswers, updateActivityScore } = useExamContext();

const allUserAnswers = ref<Record<number, string[]>>({});
const isCheckingAnswers = ref(false);
const totalQuestions = computed(() => props.questions.questions.length);

const answeredCount = computed(() =>
  Object.values(allUserAnswers.value).reduce(
    (total, questionAnswers) =>
      total + questionAnswers.filter((answer) => answer.trim() !== "").length,
    0,
  ),
);

const calculateScore = async () => {
  try {
    isCheckingAnswers.value = true;

    const submissions: { questionId: string; answer: string }[] = [];
    const aiQuestions: {
      id: string;
      question: string;
      acceptedAnswers: string[];
      strictMode: boolean;
      maxMarks: number;
      questionType: "reasoning";
      context: Record<string, unknown>;
      evaluationCriteria: string;
    }[] = [];

    props.questions.questions.forEach((question, questionIndex) => {
      const userAnswers = allUserAnswers.value[questionIndex] || [];

      userAnswers.forEach((answer, answerIndex) => {
        if (!answer.trim()) return;

        const questionId = `q${questionIndex}-a${answerIndex}`;
        submissions.push({
          questionId,
          answer: answer.trim(),
        });

        aiQuestions.push({
          id: questionId,
          question: question.question,
          acceptedAnswers: question.answers[answerIndex] ? [question.answers[answerIndex]] : [],
          strictMode: false,
          maxMarks: 1,
          questionType: "reasoning",
          context: {
            readingMaterial: props.questions.notes,
            activityTitle: props.questions.title,
          },
          evaluationCriteria:
            "Evaluate this answer based on understanding of the reading material and semantic similarity to the accepted answer.",
        });
      });
    });

    if (!submissions.length) {
      return { score: 0 };
    }

    const results =
      props.questions.useAI
        ? await answerChecker.checkAnswersWithAI(submissions, aiQuestions)
        : submissions.map((submission) => ({
            questionId: submission.questionId,
            result: answerChecker.checkAnswer(submission.answer, {
              acceptedAnswers:
                aiQuestions.find((question) => question.id === submission.questionId)?.acceptedAnswers || [],
            }),
          }));

    const score = results.reduce((total, result) => total + result.result.marksAwarded, 0);
    return { score };
  } finally {
    isCheckingAnswers.value = false;
  }
};

const ensureQuestionAnswers = (questionIndex: number, answerCount: number) =>
  allUserAnswers.value[questionIndex] || Array.from({ length: answerCount }, () => "");

const handleInputChange = (questionIndex: number, answerIndex: number, value: string | number) => {
  const nextQuestionAnswers = [...ensureQuestionAnswers(
    questionIndex,
    (props.questions.questions as any[])[questionIndex].answers.length,
  )];

  nextQuestionAnswers[answerIndex] = String(value ?? "");

  allUserAnswers.value = {
    ...allUserAnswers.value,
    [questionIndex]: nextQuestionAnswers,
  };
};

watch(answeredCount, (value) => {
  props.onStateUpdate?.(totalQuestions.value, value);
});

watch(
  [allUserAnswers, collectAnswers],
  async () => {
    if (!collectAnswers.value) return;

    const { score } = await calculateScore();
    updateActivityScore(props.activityIndex, {
      activityId: props.activityId,
      activityIndex: props.activityIndex,
      score,
      totalQuestions: totalQuestions.value,
    });
  },
  { deep: true },
);
</script>

<template>
  <div class="flex h-full flex-col rounded-xl bg-white shadow-sm">
    <div class="flex h-full gap-2">
      <div class="flex w-1/2 flex-col justify-start rounded-xl bg-white p-6">
        <div class="max-h-[calc(100vh-200px)] overflow-auto">
          <div
            class="whitespace-pre-line text-base leading-relaxed text-picton-blue-700"
            v-html="props.questions.notes"
          />
        </div>
      </div>

      <div class="flex w-1/2 flex-col rounded-xl p-6">
        <div class="flex-1 overflow-y-auto">
          <div class="space-y-8">
            <div
              v-for="(question, questionIndex) in props.questions.questions"
              :key="`${questionIndex}-${question.question}`"
              class="rounded-lg border bg-neutral-50 p-6 text-neutral-700"
            >
              <div class="flex items-start gap-4">
                <div class="flex-shrink-0 font-semibold">
                  {{ toRoman(questionIndex + 1) }}.
                </div>

                <div class="flex-1">
                  <div v-if="question.question.includes('___')" class="text-base leading-relaxed">
                    <template
                      v-for="(part, partIndex) in question.question.split('___')"
                      :key="`${questionIndex}-${partIndex}`"
                    >
                      <span>{{ part }}</span>
                      <span
                        v-if="partIndex < question.question.split('___').length - 1"
                        class="mx-2 inline-block align-middle"
                      >
                        <Textarea
                          :model-value="ensureQuestionAnswers(questionIndex, question.answers.length)[partIndex] || ''"
                          class="min-h-[40px] max-w-40 text-base"
                          rows="1"
                          :disabled="isCheckingAnswers"
                          @update:model-value="
                            (value) => handleInputChange(questionIndex, partIndex, value)
                          "
                        />
                      </span>
                    </template>
                  </div>

                  <div v-else class="space-y-3">
                    <p class="text-base font-medium">{{ question.question }}</p>
                    <Textarea
                      :model-value="ensureQuestionAnswers(questionIndex, question.answers.length)[0] || ''"
                      class="w-full text-base"
                      rows="1"
                      :disabled="isCheckingAnswers"
                      @update:model-value="
                        (value) => handleInputChange(questionIndex, 0, value)
                      "
                    />
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>
