// app/components/primary-sources/activities/exam-activities/exam-complete-paragraph-without-clues.vue
<script setup lang="ts">
import { computed, ref, watch } from "vue";
import { Input } from "~/components/ui/input";
import { cn } from "~/utilities/utils";
import { AnswerChecker } from "~/lib/utils/answer-checker";
import { useExamContext, type QuestionAnswer } from "~/shared/context/exam-context";

type ExamCompleteParagraphWithoutCluesProps = {
  questions: {
    title: string;
    paragraph: string;
    image?: string;
    answers: string[];
    options?: string[];
    withClues: boolean;
  };
  activityIndex: number;
  activityId: string;
  onStateUpdate?: (totalQuestions: number, answeredCount: number) => void;
};

const props = defineProps<ExamCompleteParagraphWithoutCluesProps>();

const answerChecker = new AnswerChecker();
const userAnswers = ref<string[]>(Array.from({ length: props.questions.answers.length }, () => ""));

const { collectAnswers, updateActivityScore } = useExamContext();

const totalQuestions = computed(() => props.questions.answers.length);
const paragraphParts = computed(() => props.questions.paragraph.split("___"));

const calculateScore = () => {
  let score = 0;
  const answers: QuestionAnswer[] = [];

  userAnswers.value.forEach((answer, index) => {
    const isCorrect = answerChecker.checkAnswer(answer, {
      acceptedAnswers: [props.questions.answers[index]] as string[],
    }).isCorrect;

    if (isCorrect) {
      score++;
    }

    answers.push({
      questionId: `blank-${index}`,
      userAnswer: answer,
      correctAnswer: props.questions.answers[index] as string,
      isCorrect,
      question: props.questions.paragraph,
      options: props.questions.options || [],
    });
  });

  return { score, answers };
};

watch(
  userAnswers,
  () => {
    const answeredCount = userAnswers.value.filter((answer) => answer.trim() !== "").length;
    props.onStateUpdate?.(totalQuestions.value, answeredCount);
  },
  { deep: true },
);

watch(
  [userAnswers, collectAnswers],
  () => {
    if (!collectAnswers.value) return;

    const { score, answers } = calculateScore();
    updateActivityScore(props.activityIndex, {
      activityId: props.activityId,
      activityIndex: props.activityIndex,
      score,
      totalQuestions: totalQuestions.value,
      answers,
    });
  },
  { deep: true },
);

const handleInputChange = (index: number, value: string | number) => {
  const nextAnswers = [...userAnswers.value];
  nextAnswers[index] = String(value ?? "");
  userAnswers.value = nextAnswers;
};
</script>

<template>
  <div class="flex h-full flex-col rounded-xl">
    <div class="h-full min-h-[400px] md:grid md:grid-cols-3">
      <div
        :class="
          cn(
            'col-span-2 flex h-full w-full flex-col gap-2 overflow-auto border-r bg-white p-4 md:rounded-bl-xl',
            { 'md:col-span-3': !props.questions.image },
          )
        "
      >
        <div v-if="props.questions.withClues && props.questions.options?.length">
          <div class="flex w-fit flex-wrap gap-2 rounded border-2 border-picton-blue-300 bg-picton-blue-100 py-4">
            <span
              v-for="option in props.questions.options"
              :key="option"
              class="px-3 text-base leading-4 text-picton-blue-700"
            >
              {{ option }}
            </span>
          </div>
        </div>

        <div class="text-lg leading-loose">
          <template v-for="(part, index) in paragraphParts" :key="`${index}-${part}`">
            <span>{{ part }}</span>
            <span
              v-if="index < paragraphParts.length - 1"
              class="mx-2 inline-block align-middle"
            >
              <Input
                type="text"
                :model-value="userAnswers[index]"
                class="max-w-40 rounded-none border-none bg-transparent text-center !text-lg text-picton-blue-700 focus:bg-picton-blue-50"
                @update:model-value="(value) => handleInputChange(index, value)"
              />
              <div class="border-b border-dashed border-picton-blue-700" />
            </span>
          </template>
        </div>
      </div>

      <div
        v-if="props.questions.image"
        class="flex items-center justify-center rounded-bl-xl rounded-br-xl bg-white p-4 md:rounded-bl-none"
      >
        <img
          :src="props.questions.image"
          alt="Activity illustration"
          class="max-h-[400px] w-full rounded-lg object-contain"
        >
      </div>
    </div>
  </div>
</template>

// app/components/primary-sources/activities/exam-activities/exam-complete-paragraph-without-clues.tsx
"use client";

import { Fragment, useState, useEffect } from "react";

// local imports
import { cn } from "@/lib/utils";
import { Input } from "@/components/ui/input";
import { AnswerChecker } from "@/lib/utils/answer-checker";
import { useExamContext } from "@/shared/context/exam-context";
import { QuestionAnswer } from "@/shared/context/exam-context";

export type ExamCompleteParagraphWithoutCluesProps = {
  questions: {
    title: string;
    paragraph: string;
    image?: string;
    answers: string[];
    options?: string[];
    withClues: boolean;
  };
  activityIndex: number;
  activityId: string;
  onStateUpdate?: (totalQuestions: number, answeredCount: number) => void;
};

const answerChecker = new AnswerChecker();

const ExamCompleteParagraphWithoutClues = ({
  questions,
  activityIndex,
  activityId,
  onStateUpdate,
}: ExamCompleteParagraphWithoutCluesProps) => {
  const [userAnswers, setUserAnswers] = useState<string[]>(
    Array.from({ length: questions.answers.length }, () => "")
  );

  const { collectAnswers, updateActivityScore } = useExamContext();

  const totalQuestions = questions.answers.length;

  // Calculate score for this activity
  const calculateScore = () => {
    let score = 0;
    const detailedAnswers: QuestionAnswer[] = [];

    userAnswers.forEach((answer, index) => {
      const isCorrect = answerChecker.checkAnswer(answer, {
        acceptedAnswers: [questions.answers[index]],
      }).isCorrect;

      if (isCorrect) {
        score++;
      }

      // Store detailed answer information
      detailedAnswers.push({
        questionId: `blank-${index}`,
        userAnswer: answer,
        correctAnswer: questions.answers[index],
        isCorrect,
        question: questions.paragraph,
        options: questions.options || [],
      });
    });

    return { score, answers: detailedAnswers };
  };

  // Update exam context whenever answers change
  useEffect(() => {
    if (!collectAnswers) return;

    const { score, answers } = calculateScore();
    updateActivityScore(activityIndex, {
      activityId,
      activityIndex,
      score,
      totalQuestions,
      answers,
    });
  }, [collectAnswers]);

  useEffect(() => {
    const answeredCount = userAnswers.filter(
      (answer) => answer.trim() !== ""
    ).length;
    onStateUpdate?.(totalQuestions, answeredCount);
  }, [userAnswers]);

  const handleInputChange = (index: number, value: string) => {
    const newAnswers = [...userAnswers];
    newAnswers[index] = value;
    setUserAnswers(newAnswers);
  };

  const renderParagraphWithInputs = () => {
    const paragraphParts = questions.paragraph.split("___");

    return (
      <div className="text-lg leading-loose">
        {paragraphParts.map((part, i) => (
          <Fragment key={i}>
            <span>{part}</span>
            {i < paragraphParts.length - 1 && (
              <span className="inline-block mx-2 align-middle">
                <Input
                  type="text"
                  value={userAnswers[i]}
                  onChange={(e) => handleInputChange(i, e.target.value)}
                  className="max-w-40 rounded-none border-none bg-transparent text-picton-blue-700 text-center !text-lg focus:bg-picton-blue-50"
                />
                <div className="border-b border-dashed border-picton-blue-700" />
              </span>
            )}
          </Fragment>
        ))}
      </div>
    );
  };

  return (
    <div className="h-full flex flex-col rounded-xl">
      {/* Content container - scrollable */}
      <div className="md:grid md:grid-cols-3 h-full min-h-[400px]">
        {/* Main paragraph area */}
        <div
          className={cn(
            "bg-white flex col-span-2 flex-col overflow-auto border-r gap-2 h-full w-full md:rounded-bl-xl p-4",
            {
              "md:col-span-3": !questions.image,
            }
          )}
        >
          {/* Options section for activities with clues */}
          {questions.withClues && questions.options && (
            <div>
              {/*<h3 className="font-semibold text-picton-blue-700">Options</h3>*/}
              <div className="flex flex-wrap gap-2 bg-picton-blue-100 border-2 border-picton-blue-300 w-fit py-4 rounded">
                {questions.options.map((option, i) => (
                  <span
                    key={i}
                    className="text-picton-blue-700 text-base leading-4 px-3"
                  >
                    {option}
                  </span>
                ))}
              </div>
            </div>
          )}

          <div className="text-lg leading-loose">
            {renderParagraphWithInputs()}
          </div>
        </div>

        {/* Image section if available */}
        {questions.image && (
          <div className="bg-white flex items-center justify-center rounded-br-xl rounded-bl-xl md:rounded-bl-none p-4">
            <img
              src={questions.image}
              alt="Activity illustration"
              className="object-contain w-full max-h-[400px] rounded-lg"
            />
          </div>
        )}
      </div>
    </div>
  );
};

export default ExamCompleteParagraphWithoutClues;
