// app/components/primary-sources/activities/exam-activities/exam-rearrange-steps-vertically.vue
<script setup lang="ts">
import { computed, ref, watch } from "vue";
import Input from "~/components/ui/inputs/input";
import { cn } from "~/utilities/utils";
import { useExamContext, type QuestionAnswer } from "~/shared/context/exam-context";

type ExamRearrangeStepsVerticallyProps = {
  questions: {
    title: string;
    questions: {
      id: string;
      text: string;
      order: number;
    }[];
  };
  activityIndex: number;
  activityId: string;
  onStateUpdate?: (totalQuestions: number, answeredCount: number) => void;
};

const props = defineProps<ExamRearrangeStepsVerticallyProps>();

const order = ref<Record<string, string>>({});

const { collectAnswers, updateActivityScore } = useExamContext();

const totalQuestions = computed(() => props.questions.questions.length);

const calculateScore = () => {
  let score = 0;
  const answers: QuestionAnswer[] = [];

  props.questions.questions.forEach((question) => {
    const userAnswer = order.value[question.id] || "";
    const isCorrect = userAnswer !== "" && Number(userAnswer) === question.order;

    if (isCorrect) {
      score++;
    }

    answers.push({
      questionId: question.id,
      userAnswer,
      correctAnswer: question.order.toString(),
      isCorrect,
      question: question.text,
      options: [],
    });
  });

  return { score, answers };
};

watch(
  order,
  () => {
    const answeredCount = Object.values(order.value).filter((value) => value.trim() !== "").length;
    props.onStateUpdate?.(totalQuestions.value, answeredCount);
  },
  { deep: true },
);

watch(
  [order, collectAnswers],
  () => {
    if (!collectAnswers.value) return;

    const { score, answers } = calculateScore();
    updateActivityScore(props.activityIndex, {
      activityId: props.activityId,
      activityIndex: props.activityIndex,
      score,
      totalQuestions: totalQuestions.value,
      answers,
    });
  },
  { deep: true },
);

const handleChange = (questionId: string, value: string) => {
  if (value === "") {
    order.value = {
      ...order.value,
      [questionId]: "",
    };
    return;
  }

  if (!Number.isNaN(Number(value)) && Number(value) > 0 && Number(value) <= totalQuestions.value) {
    order.value = {
      ...order.value,
      [questionId]: value,
    };
  }
};
</script>

<template>
  <div class="flex h-full flex-col rounded-xl bg-white shadow-sm">
    <div class="flex-1 overflow-y-auto p-4">
      <div class="space-y-4">
        <div
          v-for="question in props.questions.questions"
          :key="question.id"
          class="rounded-lg border bg-gray-50 p-4"
        >
          <div class="flex items-center gap-4">
            <div class="relative flex-shrink-0">
              <Input
                type="number"
                min="1"
                :max="totalQuestions.toString()"
                remove-arrows
                :model-value="order[question.id] || ''"
                placeholder=""
                :class="
                  cn(
                    'h-16 w-16 text-center text-2xl font-bold border-2',
                    (order[question.id] || '').trim() !== ''
                      ? 'border-picton-blue-500 bg-picton-blue-100 text-picton-blue-700'
                      : 'border-gray-300 bg-gray-100 text-gray-600',
                  )
                "
                @update:model-value="(value) => handleChange(question.id, String(value ?? ''))"
              />
            </div>

            <div class="flex-1">
              <p class="text-lg leading-relaxed text-gray-800">
                {{ question.text }}
              </p>
            </div>

            <div
              :class="
                cn(
                  'h-4 w-4 flex-shrink-0 rounded-full',
                  (order[question.id] || '').trim() !== ''
                    ? 'bg-picton-blue-500'
                    : 'bg-gray-200',
                )
              "
            />
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

// app/components/primary-sources/activities/exam-activities/exam-rearrange-steps-vertically.tsx
"use client";

import { motion } from "motion/react";
import { useEffect, useState } from "react";

// Local imports
import { cn } from "@/lib/utils";
import { Input } from "@/components/ui/inputs/input";
import { useExamContext } from "@/shared/context/exam-context";
import { QuestionAnswer } from "@/shared/context/exam-context";

export type ExamRearrangeStepsVerticallyProps = {
  questions: {
    title: string;
    questions: {
      id: string;
      text: string;
      order: number;
    }[];
  };
  activityIndex: number;
  activityId: string;
  onStateUpdate?: (totalQuestions: number, answeredCount: number) => void;
};

const ExamRearrangeStepsVertically = ({
  questions,
  activityIndex,
  activityId,
  onStateUpdate,
}: ExamRearrangeStepsVerticallyProps) => {
  const [order, setOrder] = useState<Record<string, string>>({});

  const { collectAnswers, updateActivityScore } = useExamContext();

  const totalQuestions = questions.questions.length;

  // Calculate score for this activity
  const calculateScore = () => {
    let score = 0;
    const detailedAnswers: QuestionAnswer[] = [];

    questions.questions.forEach((question) => {
      const userAnswer = order[question.id] || "";
      const correctAnswer = question.order.toString();
      const isCorrect = !!(userAnswer && Number(userAnswer) === question.order);

      if (isCorrect) {
        score++;
      }

      // Store detailed answer information
      detailedAnswers.push({
        questionId: question.id,
        userAnswer: userAnswer,
        correctAnswer: correctAnswer,
        isCorrect,
        question: question.text,
        options: [],
      });
    });

    return { score, answers: detailedAnswers };
  };

  // Update exam context whenever answers change
  useEffect(() => {
    if (!collectAnswers) return;

    const { score, answers } = calculateScore();

    updateActivityScore(activityIndex, {
      activityId,
      activityIndex,
      score,
      totalQuestions,
      answers,
    });
  }, [collectAnswers, order]);

  // Update parent component state immediately for visual feedback
  useEffect(() => {
    const answeredCount = Object.keys(order).filter(
      (key) => order[key]?.trim() !== "",
    ).length;

    onStateUpdate?.(totalQuestions, answeredCount);
  }, [order, totalQuestions]);

  // Handle input change
  const handleChange = (questionId: string, value: string) => {
    if (value === "") {
      setOrder((prev) => ({
        ...prev,
        [questionId]: "",
      }));
    } else if (
      !isNaN(Number(value)) &&
      Number(value) > 0 &&
      Number(value) <= totalQuestions
    ) {
      setOrder((prev) => ({
        ...prev,
        [questionId]: value,
      }));
    }
  };

  return (
    <div className="h-full flex flex-col bg-white rounded-xl shadow-sm">
      {/* Questions container - scrollable */}
      <div className="flex-1 overflow-y-auto p-4">
        <div className="space-y-4">
          {questions.questions.map((question, index) => {
            const userAnswer = order[question.id] || "";
            const hasAnswer = userAnswer.trim() !== "";

            return (
              <motion.div
                key={question.id}
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: index * 0.1 }}
                className="border rounded-lg p-4 bg-gray-50"
              >
                <div className="flex items-center gap-4">
                  {/* Step number input */}
                  <div className="relative flex-shrink-0">
                    <Input
                      type="number"
                      min="1"
                      max={totalQuestions}
                      value={userAnswer}
                      onChange={(e) =>
                        handleChange(question.id, e.target.value)
                      }
                      className={cn(
                        "w-16 h-16 no-number-input-arrows text-center text-2xl font-bold border-2",
                        hasAnswer
                          ? "bg-picton-blue-100 border-picton-blue-500 text-picton-blue-700"
                          : "bg-gray-100 border-gray-300 text-gray-600",
                      )}
                      placeholder=""
                    />
                  </div>

                  {/* Question text */}
                  <div className="flex-1">
                    <p className="text-lg leading-relaxed text-gray-800">
                      {question.text}
                    </p>
                  </div>

                  {/* Visual indicator */}
                  <div
                    className={cn(
                      "w-4 h-4 rounded-full flex items-center justify-center text-sm font-bold flex-shrink-0",
                      hasAnswer
                        ? "bg-picton-blue-500 text-white"
                        : "bg-gray-200 text-gray-600",
                    )}
                  />
                </div>
              </motion.div>
            );
          })}
        </div>
      </div>

      {/* Instructions footer */}
      {/*<div className="p-4 border-t bg-picton-blue-50">
        <p className="text-sm text-picton-blue-700 text-center">
          <strong>Instructions:</strong> Enter numbers from 1 to{" "}
          {totalQuestions} to arrange the steps in the correct order.
        </p>
      </div>*/}
    </div>
  );
};

export default ExamRearrangeStepsVertically;
