// app/components/primary-sources/activities/numbers-activities/comparing-quantities.vue
<script setup lang="ts">
import { computed, onMounted, reactive, ref, watch } from "vue";
import { QuantityRenderer } from "./shared";
import AnswerDropZone from "./shared/answer-drop-zone.vue";
import ActivityTitle from "~/components/templates/activity-title";
import ActivityResults, {
  ActivityResultsAlertDialog,
} from "~/components/templates/results";
import type { FeedbackType } from "~/types/activity-types";
import { useSoundEffects } from "~/composables/use-sound-effects";
import { cn } from "~/utilities/utils";

type ComparingQuantitiesProps = {
  questions: {
    title: string;
    questions: {
      answer: "Second" | "First";
      leftNumber: number;
      leftImage: string;
      rightNumber: number;
    }[];
  };
  feedback: FeedbackType;
};

const props = defineProps<ComparingQuantitiesProps>();

const score = ref(0);
const showResults = ref(false);
const allAnswered = ref(false);
const questionAnswers = reactive<Record<number, "" | "First" | "Second">>({});
const correctAnswers = ref<string[]>([]);

const { playSound } = useSoundEffects();

const totalQuestions = computed(() => props.questions.questions.length);

const initAnswers = () => {
  props.questions.questions.forEach((_, index) => {
    questionAnswers[index] = "";
  });
};

onMounted(initAnswers);
watch(() => props.questions, initAnswers, { deep: true });

watch(
  () => ({ ...questionAnswers }),
  () => {
    const answeredCount = Object.keys(questionAnswers).filter((k) => !!questionAnswers[Number(k)]).length;
    if (answeredCount !== totalQuestions.value || totalQuestions.value === 0) return;

    let totalScore = 0;
    const correct: string[] = [];
    props.questions.questions.forEach((question, index) => {
      const userAnswer = questionAnswers[index];
      if (userAnswer === question.answer) {
        totalScore += 1;
        correct.push(index.toString());
      }
    });

    score.value = totalScore;
    correctAnswers.value = correct;
    allAnswered.value = true;
    playSound("success");
  },
  { deep: true },
);

const handleAnswerClick = (questionIndex: number, side: "First" | "Second") => {
  questionAnswers[questionIndex] = side;
  playSound("click");
};

const resetActivity = () => {
  score.value = 0;
  showResults.value = false;
  allAnswered.value = false;
  correctAnswers.value = [];
  initAnswers();
};

const isCorrect = (questionIndex: number) =>
  correctAnswers.value.includes(questionIndex.toString());

const renderQuantityImages = (count: number, image: string) => ({
  count,
  image,
  maxItemsPerRow: 7,
  className: "sm:max-w-[350px] xl:max-w-full flex-wrap",
});
</script>

<template>
  <div class="h-full flex flex-col">
    <ActivityTitle :title="props.questions.title" />

    <div class="flex-1 flex flex-col gap-6 overflow-y-auto p-4">
      <div class="space-y-6">
        <div
          v-for="(question, index) in props.questions.questions"
          :key="index"
          class="bg-white rounded-lg p-6 mb-6"
        >
          <div class="flex flex-col md:flex-row items-center justify-between gap-8">
            <div class="bg-gray-50 md:flex md:items-center gap-2 p-4 rounded-lg border border-gray-200 w-full">
              <QuantityRenderer v-bind="renderQuantityImages(question.leftNumber, question.leftImage)" />

              <div class="relative w-fit ml-auto">
                <AnswerDropZone
                  :id="`${index}-left`"
                  answerType="click"
                  :currentAnswer="questionAnswers[index]"
                  :correctAnswer="question.answer"
                  :showResults="showResults"
                  placeholder="Select"
                  :onClickChange="() => handleAnswerClick(index, 'First')"
                  :isSelected="questionAnswers[index] === 'First'"
                  :className="
                    `min-w-[120px] ${
                      showResults && questionAnswers[index] === 'First'
                        ? isCorrect(index)
                          ? 'bg-green-200 text-green-700 border-green-300'
                          : 'bg-red-200 text-red-700 border-red-300'
                        : questionAnswers[index] === 'First'
                          ? 'bg-picton-blue-200 border-picton-blue-400'
                          : ''
                    }`
                  "
                >
                  First
                </AnswerDropZone>

                <div v-if="showResults && questionAnswers[index] === 'First'" class="absolute -top-2 -right-2 z-10">
                  <span
                    :class="cn('h-6 w-6 bg-white rounded-full p-1 inline-flex items-center justify-center', isCorrect(index) ? 'text-green-600' : 'text-red-600')"
                  >
                    {{ isCorrect(index) ? "✓" : "✕" }}
                  </span>
                </div>
              </div>
            </div>

            <div class="bg-gray-50 md:flex md:items-center gap-2 p-4 rounded-lg border border-gray-200 w-full">
              <div class="relative w-fit ml-auto">
                <AnswerDropZone
                  :id="`${index}-right`"
                  answerType="click"
                  :currentAnswer="questionAnswers[index]"
                  :correctAnswer="question.answer"
                  :showResults="showResults"
                  placeholder="Select"
                  :onClickChange="() => handleAnswerClick(index, 'Second')"
                  :isSelected="questionAnswers[index] === 'Second'"
                  :className="
                    `min-w-[120px] ${
                      showResults && questionAnswers[index] === 'Second'
                        ? isCorrect(index)
                          ? 'bg-green-200 text-green-700 border-green-300'
                          : 'bg-red-200 text-red-700 border-red-300'
                        : questionAnswers[index] === 'Second'
                          ? 'bg-picton-blue-200 border-picton-blue-400'
                          : ''
                    }`
                  "
                >
                  Second
                </AnswerDropZone>

                <div v-if="showResults && questionAnswers[index] === 'Second'" class="absolute -top-2 -right-2 z-10">
                  <span
                    :class="cn('h-6 w-6 bg-white rounded-full p-1 inline-flex items-center justify-center', isCorrect(index) ? 'text-green-600' : 'text-red-600')"
                  >
                    {{ isCorrect(index) ? "✓" : "✕" }}
                  </span>
                </div>
              </div>

              <QuantityRenderer v-bind="renderQuantityImages(question.rightNumber, question.leftImage)" />
            </div>
          </div>
        </div>
      </div>

      <div v-if="showResults" class="mt-4">
        <ActivityResults :score="score" :total="totalQuestions" :onRestart="resetActivity" />
      </div>

      <ActivityResultsAlertDialog
        :score="score"
        :total="totalQuestions"
        :open="allAnswered"
        :onOpenChange="(open: boolean) => {
          if (!open) {
            if (props.feedback === 'none') resetActivity();
            else showResults = true;
            allAnswered = false;
          }
        }"
      />
    </div>
  </div>
</template>

// app/components/primary-sources/activities/numbers-activities/comparing-quantities.tsx
"use client";

import { motion } from "motion/react";
import { Check, X } from "lucide-react";
import { useState, useEffect } from "react";

// Local imports
import { QuantityRenderer } from "./shared";
import AnswerDropZone from "./shared/answer-drop-zone";
import { FeedbackType } from "@/lib/types/activity-types";
import ActivityTitle from "@/components/templates/activity-title";
import { useSoundEffects } from "@/shared/hooks/use-sound-effects";
import ActivityResults, {
  ActivityResultsAlertDialog,
} from "@/components/templates/results";

type ComparingQuantitiesProps = {
  questions: {
    title: string;
    questions: {
      answer: "Second" | "First";
      leftNumber: number;
      leftImage: string;
      rightNumber: number;
    }[];
  };
  feedback: FeedbackType;
};

const ComparingQuantities = ({
  questions,
  feedback,
}: ComparingQuantitiesProps) => {
  const [score, setScore] = useState(0);
  const [showResults, setShowResults] = useState(false);
  const [allAnswered, setAllAnswered] = useState(false);
  const [questionAnswers, setQuestionAnswers] = useState<
    Record<number, string>
  >({});
  const [correctAnswers, setCorrectAnswers] = useState<string[]>([]);

  const { playSound } = useSoundEffects();

  const totalQuestions = questions.questions.length;

  // Initialize question answers when component mounts
  useEffect(() => {
    const initialAnswers: Record<number, string> = {};
    questions.questions.forEach((_, index) => {
      initialAnswers[index] = "";
    });
    setQuestionAnswers(initialAnswers);
  }, [questions]);

  // Check if all questions are answered and calculate score
  useEffect(() => {
    const answeredQuestions = Object.keys(questionAnswers).filter((key) => {
      return questionAnswers[parseInt(key)];
    });

    if (answeredQuestions.length === totalQuestions) {
      let totalScore = 0;
      const correct: string[] = [];

      questions.questions.forEach((question, index) => {
        const userAnswer = questionAnswers[index];
        if (userAnswer === question.answer) {
          totalScore += 1;
          correct.push(index.toString());
        }
      });

      setScore(totalScore);
      setCorrectAnswers(correct);
      setAllAnswered(true);
      playSound("success");
    }
  }, [questionAnswers, questions, totalQuestions]);

  const handleAnswerClick = (
    questionIndex: number,
    side: "First" | "Second"
  ) => {
    setQuestionAnswers((prev) => ({
      ...prev,
      [questionIndex]: side,
    }));
    playSound("click");
  };

  const resetActivity = () => {
    setScore(0);
    setShowResults(false);
    setAllAnswered(false);
    setCorrectAnswers([]);

    // Reset question answers
    const initialAnswers: Record<number, string> = {};
    questions.questions.forEach((_, index) => {
      initialAnswers[index] = "";
    });
    setQuestionAnswers(initialAnswers);
  };

  const iconVariants = {
    initial: { scale: 0, opacity: 0 },
    animate: {
      scale: 1,
      opacity: 1,
      transition: { type: "spring", damping: 10 },
    },
  };

  const isCorrect = (questionIndex: number) => {
    return correctAnswers.includes(questionIndex.toString());
  };

  const renderResultIcon = (
    questionIndex: number,
    side: "First" | "Second"
  ) => {
    if (!showResults) return null;

    const userAnswer = questionAnswers[questionIndex];
    const correctAnswer = questions.questions[questionIndex].answer;
    const isThisSideCorrect = correctAnswer === side;
    const userSelectedThis = userAnswer === side;

    if (userSelectedThis) {
      return isThisSideCorrect ? (
        <motion.div
          className="absolute -top-2 -right-2 z-10"
          variants={iconVariants}
          initial="initial"
          animate="animate"
        >
          <Check className="text-green-600 h-6 w-6 bg-white rounded-full p-1" />
        </motion.div>
      ) : (
        <motion.div
          className="absolute -top-2 -right-2 z-10"
          variants={iconVariants}
          initial="initial"
          animate="animate"
        >
          <X className="text-red-600 h-6 w-6 bg-white rounded-full p-1" />
        </motion.div>
      );
    }

    return null;
  };

  const renderQuantityImages = (count: number, image: string, alt: string) => {
    return (
      <QuantityRenderer
        count={count}
        image={image}
        maxItemsPerRow={7}
        className="sm:max-w-[350px] xl:max-w-full flex-wrap"
      />
    );
  };

  const renderQuestion = (question: any, index: number) => {
    const currentAnswer = questionAnswers[index];

    return (
      <div key={index} className="bg-white rounded-lg p-6 mb-6">
        <div className="flex flex-col md:flex-row items-center justify-between gap-8">
          {/* Left Side */}
          <div className="bg-gray-50 md:flex md:items-center gap-2 p-4 rounded-lg border border-gray-200 w-full">
            {renderQuantityImages(
              question.leftNumber,
              question.leftImage,
              "Left item"
            )}
            {/* Left Selection Zone */}
            <div className="relative w-fit ml-auto">
              <AnswerDropZone
                id={`${index}-left`}
                answerType="click"
                currentAnswer={currentAnswer}
                correctAnswer={question.answer}
                showResults={showResults}
                placeholder="Select"
                onClickChange={() => handleAnswerClick(index, "First")}
                isSelected={currentAnswer === "First"}
                className={`min-w-[120px] ${
                  showResults && currentAnswer === "First"
                    ? isCorrect(index)
                      ? "bg-green-200 text-green-700 border-green-300"
                      : "bg-red-200 text-red-700 border-red-300"
                    : currentAnswer === "First"
                    ? "bg-picton-blue-200 border-picton-blue-400"
                    : ""
                }`}
              >
                First
              </AnswerDropZone>
              {renderResultIcon(index, "First")}
            </div>
          </div>

          {/* Right Side */}
          <div className="bg-gray-50 md:flex md:items-center gap-2 p-4 rounded-lg border border-gray-200 w-full">
            {/* Right Selection Zone */}
            <div className="relative w-fit ml-auto">
              <AnswerDropZone
                id={`${index}-right`}
                answerType="click"
                currentAnswer={currentAnswer}
                correctAnswer={question.answer}
                showResults={showResults}
                placeholder="Select"
                onClickChange={() => handleAnswerClick(index, "Second")}
                isSelected={currentAnswer === "Second"}
                className={`min-w-[120px] ${
                  showResults && currentAnswer === "Second"
                    ? isCorrect(index)
                      ? "bg-green-200 text-green-700 border-green-300"
                      : "bg-red-200 text-red-700 border-red-300"
                    : currentAnswer === "Second"
                    ? "bg-picton-blue-200 border-picton-blue-400"
                    : ""
                }`}
              >
                Second
              </AnswerDropZone>
              {renderResultIcon(index, "Second")}
            </div>
            {renderQuantityImages(
              question.rightNumber,
              question.leftImage,
              "Right item"
            )}
          </div>
        </div>
      </div>
    );
  };

  return (
    <div className="h-full flex flex-col">
      <ActivityTitle title={questions.title} />

      <div className="flex-1 flex flex-col gap-6 overflow-y-auto p-4">
        {/* All Questions */}
        <div className="space-y-6">
          {questions.questions.map((question, index) =>
            renderQuestion(question, index)
          )}
        </div>

        {showResults && (
          <div className="mt-4">
            <ActivityResults
              score={score}
              total={totalQuestions}
              onRestart={resetActivity}
            />
          </div>
        )}

        <ActivityResultsAlertDialog
          score={score}
          total={totalQuestions}
          open={allAnswered}
          onOpenChange={(open) => {
            if (!open) {
              if (feedback === "none") {
                resetActivity();
              } else {
                setShowResults(true);
              }
              setAllAnswered(false);
            }
          }}
        />
      </div>
    </div>
  );
};

export default ComparingQuantities;
