// app/components/primary-sources/activities/numbers-activities/counting-objects.tsx
import { Check, X, ChevronRight } from "lucide-react";
import { motion } from "motion/react";
import { useState, useEffect } from "react";

// local imports
import { cn, shuffle } from "@/lib/utils";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/inputs/input";
import { FeedbackType } from "@/lib/types/activity-types";
import { AnswerChecker } from "@/lib/utils/answer-checker";
import ActivityTitle from "@/components/templates/activity-title";
import { useSoundEffects } from "@/shared/hooks/use-sound-effects";
import ActivityResults, {
  ActivityResultsAlertDialog,
} from "@/components/templates/results";

type CountingObjectsActivityProps = {
  feedback: FeedbackType;
  questions: {
    title: string;
    questions: {
      id: number;
      number: number;
    }[];
  };
};

const answerChecker = new AnswerChecker();

// Colors for different place values (3D cube colors)
const PLACE_VALUE_COLORS = [
  "#ef4444", // red for ones
  "#3b82f6", // blue for tens
  "#10b981", // green for hundreds
  "#f59e0b", // amber for thousands
  "#8b5cf6", // purple for ten thousands
  "#ec4899", // pink for hundred thousands
  "#6366f1", // indigo for millions
  "#f97316", // orange for ten millions
];

const PLACE_VALUE_LABELS = [
  "Ones",
  "Tens",
  "Hundreds",
  "Thousands",
  "Ten Thousands",
  "Hundred Thousands",
  "Millions",
  "Ten Millions",
];

// 3D cube sizes for different place values (reduced sizes to fit better)
const PLACE_VALUE_SIZES = [
  20, // ones (reduced from 25)
  30, // tens (reduced from 40)
  45, // hundreds (reduced from 60)
  70, // thousands (reduced from 100)
  60, // ten thousands (reduced from 80)
  55, // hundred thousands (reduced from 70)
  50, // millions (reduced from 65)
  65, // ten millions (reduced from 85)
];

const CountingObjectsActivity = ({
  questions,
  feedback,
}: CountingObjectsActivityProps) => {
  const [shuffledQuestions, setShuffledQuestions] = useState([
    ...questions.questions,
  ]);
  const [currentQuestionIndex, setCurrentQuestionIndex] = useState(0);
  const [score, setScore] = useState(0);
  const [allAnswered, setAllAnswered] = useState(false);
  const [userAnswer, setUserAnswer] = useState("");
  const [answers, setAnswers] = useState<{ [key: number]: string }>({});
  const [feedbacks, setFeedbacks] = useState<{ [key: number]: boolean }>({});
  const [showResults, setShowResults] = useState(false);
  const [isAnswerChecked, setIsAnswerChecked] = useState(false);

  const { playSound } = useSoundEffects();

  const shuffleQuestions = () => {
    setShuffledQuestions(shuffle([...questions.questions]));
  };

  // Shuffle questions on initial render
  useEffect(() => {
    shuffleQuestions();
  }, [questions.questions]);

  // Reset answer state when question changes
  useEffect(() => {
    setUserAnswer(answers[currentQuestionIndex] || "");
    setIsAnswerChecked(false);
  }, [currentQuestionIndex, answers]);

  const getPlaceValueBreakdown = (number: number) => {
    const digits = number.toString().split("").reverse();
    return digits
      .map((digit, index) => ({
        digit: parseInt(digit),
        placeValue: Math.pow(10, index),
        label: PLACE_VALUE_LABELS[index],
        color: PLACE_VALUE_COLORS[index % PLACE_VALUE_COLORS.length],
        size: PLACE_VALUE_SIZES[index % PLACE_VALUE_SIZES.length],
        position: index,
      }))
      .reverse();
  };

  const renderSimpleCube = (size: number, color: string, index: number) => {
    return (
      <div
        key={index}
        style={{
          width: `${size}px`,
          height: `${size}px`,
          margin: "2px",
          display: "inline-block",
          position: "relative",
          transformStyle: "preserve-3d",
          transform: "rotateX(-10deg) rotateY(-10deg)",
          flexShrink: 0,
        }}
      >
        {/* Front face */}
        <div
          style={{
            position: "absolute",
            width: `${size}px`,
            height: `${size}px`,
            backgroundColor: color,
            border: "1px solid rgba(0,0,0,0.2)",
            transform: `translateZ(${size / 2}px)`,
          }}
        />

        {/* Back face */}
        <div
          style={{
            position: "absolute",
            width: `${size}px`,
            height: `${size}px`,
            backgroundColor: color,
            border: "1px solid rgba(0,0,0,0.2)",
            transform: `translateZ(-${size / 2}px) rotateY(180deg)`,
          }}
        />

        {/* Right face */}
        <div
          style={{
            position: "absolute",
            width: `${size}px`,
            height: `${size}px`,
            backgroundColor: color,
            filter: "brightness(0.7)",
            border: "1px solid rgba(0,0,0,0.2)",
            transform: `rotateY(90deg) translateZ(${size / 2}px)`,
          }}
        />

        {/* Left face */}
        <div
          style={{
            position: "absolute",
            width: `${size}px`,
            height: `${size}px`,
            backgroundColor: color,
            filter: "brightness(0.7)",
            border: "1px solid rgba(0,0,0,0.2)",
            transform: `rotateY(-90deg) translateZ(${size / 2}px)`,
          }}
        />

        {/* Top face */}
        <div
          style={{
            position: "absolute",
            width: `${size}px`,
            height: `${size}px`,
            backgroundColor: color,
            filter: "brightness(1.2)",
            border: "1px solid rgba(0,0,0,0.2)",
            transform: `rotateX(90deg) translateZ(${size / 2}px)`,
          }}
        />

        {/* Bottom face */}
        <div
          style={{
            position: "absolute",
            width: `${size}px`,
            height: `${size}px`,
            backgroundColor: color,
            filter: "brightness(0.5)",
            border: "1px solid rgba(0,0,0,0.2)",
            transform: `rotateX(-90deg) translateZ(${size / 2}px)`,
          }}
        />
      </div>
    );
  };

  const renderPlaceValueBoxes = (
    digit: number,
    color: string,
    size: number
  ) => {
    if (digit === 0) return null;

    let styles = "";

    if (size <= 25) {
      // ones
      styles = "grid-cols-1 gap-2";
    } else if (size <= 40) {
      // tens
      styles = "grid-cols-2 gap-3";
    } else if (size <= 60) {
      // hundreds
      styles = "grid-cols-3 gap-4";
    } else {
      // thousands and above
      styles = "grid-cols-3 gap-10";
    }

    return (
      <div
        className={cn(
          "grid justify-items-center",
          // `grid-cols-${gridCols}`,
          styles
        )}
      >
        {Array.from({ length: digit }, (_, i) => (
          <motion.div
            key={i}
            initial={{ scale: 0, opacity: 0 }}
            animate={{ scale: 1, opacity: 1 }}
            transition={{
              duration: 0.3,
              delay: i * 0.05,
              type: "spring",
              stiffness: 200,
            }}
          >
            {renderSimpleCube(size, color, i)}
          </motion.div>
        ))}
      </div>
    );
  };

  const checkCurrentAnswer = () => {
    const currentQuestion = shuffledQuestions[currentQuestionIndex];
    const isCorrect = answerChecker.checkAnswer(userAnswer, {
      acceptedAnswers: [currentQuestion.number.toString()],
      strictMode: false,
    }).isCorrect;

    setFeedbacks((prev) => ({
      ...prev,
      [currentQuestionIndex]: isCorrect,
    }));

    setAnswers((prev) => ({
      ...prev,
      [currentQuestionIndex]: userAnswer,
    }));

    setIsAnswerChecked(true);

    if (isCorrect) {
      setScore((prev) => prev + 1);
      playSound("correct");
    } else {
      playSound("failure");
    }

    // Auto proceed to next question after a delay, or finish if last question
    setTimeout(() => {
      if (currentQuestionIndex < shuffledQuestions.length - 1) {
        setCurrentQuestionIndex((prev) => prev + 1);
        setIsAnswerChecked(false);
        setUserAnswer("");
      } else {
        // All questions completed
        setAllAnswered(true);
      }
    }, 1500);
  };

  const handleResetWithShuffle = () => {
    shuffleQuestions();
    setCurrentQuestionIndex(0);
    setScore(0);
    setAllAnswered(false);
    setUserAnswer("");
    setAnswers({});
    setFeedbacks({});
    setShowResults(false);
    setIsAnswerChecked(false);
  };

  const currentQuestion = shuffledQuestions[currentQuestionIndex];
  const placeValueBreakdown = getPlaceValueBreakdown(currentQuestion.number);
  const isCurrentAnswerCorrect = feedbacks[currentQuestionIndex];

  return (
    <div className="h-full flex flex-col">
      <ActivityTitle title={questions.title} />

      {!showResults ? (
        <div className="flex flex-col h-full bg-picton-blue-100">
          <div className="flex-1 overflow-y-auto py-2">
            <div
              key={currentQuestionIndex}
              className="bg-white rounded-lg p-6 shadow-sm"
            >
              {/* Place Value Visualization */}
              <div className="flex gap-6 mb-8 justify-between">
                {placeValueBreakdown.map((place, index) => (
                  <motion.div
                    key={`${currentQuestionIndex}-${index}`}
                    initial={{ opacity: 0 }}
                    animate={{ opacity: 1 }}
                    transition={{ duration: 0.4 }}
                    className="bg-gray-50 rounded-lg p-4 border text-center grow"
                  >
                    <h4 className="font-medium text-neutral-700 text-2xl mb-3">
                      {place.label}
                    </h4>
                    <div className="min-h-[480px] flex items-center justify-center">
                      {place.digit === 0 ? (
                        <div className="text-gray-400 italic">
                          No {place.label.toLowerCase()}
                        </div>
                      ) : (
                        renderPlaceValueBoxes(
                          place.digit,
                          place.color,
                          place.size
                        )
                      )}
                    </div>
                  </motion.div>
                ))}
              </div>

              {/* Action Buttons */}
              <div className="flex flex-col md:flex-row md:justify-end items-center gap-4">
                {/* Answer Input */}
                <div>
                  <div className="flex items-center gap-4">
                    <Input
                      type="text"
                      value={userAnswer}
                      onChange={(e) => setUserAnswer(e.target.value)}
                      disabled={isAnswerChecked}
                      className="max-w-xs !text-2xl text-center"
                      placeholder="Enter the number"
                    />
                    {isAnswerChecked && (
                      <motion.div
                        initial={{ scale: 0 }}
                        animate={{ scale: 1 }}
                        className={cn(
                          "flex items-center justify-center rounded-full p-2",
                          isCurrentAnswerCorrect
                            ? "bg-green-100 text-green-600"
                            : "bg-red-100 text-red-600"
                        )}
                      >
                        {isCurrentAnswerCorrect ? (
                          <Check className="h-6 w-6" />
                        ) : (
                          <X className="h-6 w-6" />
                        )}
                      </motion.div>
                    )}
                  </div>

                  {isAnswerChecked &&
                    !isCurrentAnswerCorrect &&
                    feedback === "wrong-correct-answers" && (
                      <motion.div
                        initial={{ opacity: 0, y: -10 }}
                        animate={{ opacity: 1, y: 0 }}
                        className="mt-2 p-3 bg-red-50 border border-red-200 rounded-lg"
                      >
                        <p className="text-red-700 text-sm">
                          Correct answer:{" "}
                          <strong>
                            {currentQuestion.number.toLocaleString()}
                          </strong>
                        </p>
                      </motion.div>
                    )}
                </div>

                <div className="flex gap-3">
                  {!isAnswerChecked ? (
                    <Button
                      onClick={checkCurrentAnswer}
                      disabled={!userAnswer.trim()}
                      variant="brand-lemon"
                    >
                      {currentQuestionIndex < shuffledQuestions.length - 1
                        ? "Next Question"
                        : "Check Answer"}
                    </Button>
                  ) : (
                    <Button
                      variant="brand-lemon"
                      disabled={true}
                      className="flex items-center gap-2"
                    >
                      {currentQuestionIndex < shuffledQuestions.length - 1 ? (
                        <>
                          Moving to Next...
                          <ChevronRight className="h-4 w-4" />
                        </>
                      ) : (
                        "Finishing Activity..."
                      )}
                    </Button>
                  )}
                </div>
              </div>
            </div>
          </div>

          {/* Progress Indicators */}
          <div className="flex items-center justify-center gap-2 p-4 bg-white">
            {shuffledQuestions.map((_, index) => {
              const isAnswered = answers[index] !== undefined;
              const isCorrect = feedbacks[index];
              const isCurrent = index === currentQuestionIndex;

              return (
                <div
                  key={index}
                  className={cn(
                    "w-10 h-10 rounded-lg flex items-center justify-center transition-all duration-200",
                    {
                      "bg-picton-blue-200": !isAnswered && !isCurrent,
                      "bg-lemon-200": isAnswered,
                      "border-2 border-picton-blue-500":
                        isCurrent && !isAnswered,
                      "border-2 border-lemon-500": isCurrent && isAnswered,
                    }
                  )}
                >
                  {isAnswered && (
                    <div className="absolute">
                      {isCorrect ? (
                        <Check className="text-green-500" size={16} />
                      ) : (
                        <X className="text-red-500" size={16} />
                      )}
                    </div>
                  )}
                </div>
              );
            })}
          </div>
        </div>
      ) : (
        <div className="flex flex-col h-full bg-picton-blue-100 text-lg p-6 overflow-y-auto">
          <div className="bg-picton-blue-50 rounded-lg p-6">
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-8">
              {shuffledQuestions.map((question, idx) => {
                const userAnswerForQuestion = answers[idx] || "";
                const isCorrect = feedbacks[idx];

                return (
                  <div
                    key={idx}
                    className={cn(
                      "p-4 rounded-lg border",
                      isCorrect
                        ? "bg-green-50 border-green-200"
                        : "bg-red-50 border-red-200"
                    )}
                  >
                    <div className="flex justify-between items-center mb-2">
                      <div>
                        <p className="font-medium">Question {idx + 1}</p>
                        <p className="text-sm text-gray-600">
                          Number: {question.number.toLocaleString()}
                        </p>
                      </div>
                      <div
                        className={cn(
                          "flex items-center justify-center rounded-full p-1",
                          isCorrect
                            ? "bg-green-100 text-green-600"
                            : "bg-red-100 text-red-600"
                        )}
                      >
                        {isCorrect ? (
                          <Check className="h-5 w-5" />
                        ) : (
                          <X className="h-5 w-5" />
                        )}
                      </div>
                    </div>

                    <div className="grid grid-cols-2 gap-4 mt-2">
                      <div>
                        <p className="text-sm text-gray-500">Your answer:</p>
                        <p
                          className={cn(
                            "font-medium",
                            isCorrect ? "text-green-600" : "text-red-600"
                          )}
                        >
                          {userAnswerForQuestion || "(no answer)"}
                        </p>
                      </div>
                      {feedback === "wrong-correct-answers" && !isCorrect && (
                        <div>
                          <p className="text-sm text-gray-500">
                            Correct answer:
                          </p>
                          <p className="text-green-600 font-medium">
                            {question.number.toLocaleString()}
                          </p>
                        </div>
                      )}
                    </div>
                  </div>
                );
              })}
            </div>

            <ActivityResults
              score={score}
              total={shuffledQuestions.length}
              onRestart={handleResetWithShuffle}
            />
          </div>
        </div>
      )}

      <ActivityResultsAlertDialog
        score={score}
        total={shuffledQuestions.length}
        open={allAnswered && !showResults}
        onOpenChange={(open) => {
          if (!open) {
            setShowResults(true);
          }
        }}
      />
    </div>
  );
};

export default CountingObjectsActivity;

// app/components/primary-sources/activities/numbers-activities/counting-objects.vue
<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, ref, watch } from "vue";
import { cn, shuffle } from "~/utilities/utils";
import Input from "~/components/ui/inputs/input";
import { Button } from "~/components/ui/button";
import ActivityTitle from "~/components/templates/activity-title";
import ActivityResults, {
  ActivityResultsAlertDialog,
} from "~/components/templates/results";
import type { FeedbackType } from "~/types/activity-types";
import { useSoundEffects } from "~/composables/use-sound-effects";

type CountingObjectsActivityProps = {
  feedback: FeedbackType;
  questions: {
    title: string;
    questions: {
      id: number;
      number: number;
    }[];
  };
};

const props = defineProps<CountingObjectsActivityProps>();

// Colors for different place values (3D cube colors)
const PLACE_VALUE_COLORS = [
  "#ef4444",
  "#3b82f6",
  "#10b981",
  "#f59e0b",
  "#8b5cf6",
  "#ec4899",
  "#6366f1",
  "#f97316",
];

const PLACE_VALUE_LABELS = [
  "Ones",
  "Tens",
  "Hundreds",
  "Thousands",
  "Ten Thousands",
  "Hundred Thousands",
  "Millions",
  "Ten Millions",
];

const PLACE_VALUE_SIZES = [20, 30, 45, 70, 60, 55, 50, 65];

const shuffledQuestions = ref([...props.questions.questions]);
const currentQuestionIndex = ref(0);
const score = ref(0);
const allAnswered = ref(false);
const userAnswer = ref("");
const answers = ref<Record<number, string>>({});
const feedbacks = ref<Record<number, boolean>>({});
const showResults = ref(false);
const isAnswerChecked = ref(false);

const { playSound } = useSoundEffects();

let advanceTimer: number | null = null;
onBeforeUnmount(() => {
  if (advanceTimer) window.clearTimeout(advanceTimer);
});

const shuffleQuestions = () => {
  shuffledQuestions.value = shuffle([...props.questions.questions]);
};

onMounted(() => {
  shuffleQuestions();
});

watch(
  () => props.questions.questions,
  () => {
    shuffleQuestions();
    currentQuestionIndex.value = 0;
    score.value = 0;
    allAnswered.value = false;
    userAnswer.value = "";
    answers.value = {};
    feedbacks.value = {};
    showResults.value = false;
    isAnswerChecked.value = false;
  },
);

watch(
  [currentQuestionIndex, answers],
  () => {
    userAnswer.value = answers.value[currentQuestionIndex.value] || "";
    isAnswerChecked.value = false;
  },
  { deep: true },
);

const currentQuestion = computed(() => shuffledQuestions.value[currentQuestionIndex.value]);
const placeValueBreakdown = computed(() => {
  const digits = (currentQuestion.value?.number ?? 0).toString().split("").reverse();
  return digits
    .map((digit, index) => ({
      digit: Number.parseInt(digit, 10),
      placeValue: Math.pow(10, index),
      label: PLACE_VALUE_LABELS[index] ?? `10^${index}`,
      color: PLACE_VALUE_COLORS[index % PLACE_VALUE_COLORS.length] ?? "#3b82f6",
      size: PLACE_VALUE_SIZES[index % PLACE_VALUE_SIZES.length] ?? 20,
      position: index,
    }))
    .reverse();
});

const isCurrentAnswerCorrect = computed(
  () => feedbacks.value[currentQuestionIndex.value],
);

const total = computed(() => shuffledQuestions.value.length);

const normalizeNumberString = (value: string) => value.replace(/[,\s]/g, "");
const isCorrectAnswer = (value: string, expected: number) => {
  const normalized = normalizeNumberString(value);
  const parsed = Number.parseInt(normalized, 10);
  return Number.isFinite(parsed) && parsed === expected;
};

const renderSimpleCubeStyle = (size: number, color: string) => ({
  width: `${size}px`,
  height: `${size}px`,
  margin: "2px",
  display: "inline-block",
  position: "relative",
  transformStyle: "preserve-3d",
  transform: "rotateX(-10deg) rotateY(-10deg)",
  flexShrink: 0,
} as const);

const faceStyle = (size: number, color: string, transform: string, filter?: string) =>
  ({
    position: "absolute",
    width: `${size}px`,
    height: `${size}px`,
    backgroundColor: color,
    border: "1px solid rgba(0,0,0,0.2)",
    transform,
    ...(filter ? { filter } : {}),
  }) as const;

const placeGridClass = (size: number) => {
  if (size <= 25) return "grid-cols-1 gap-2";
  if (size <= 40) return "grid-cols-2 gap-3";
  if (size <= 60) return "grid-cols-3 gap-4";
  return "grid-cols-3 gap-10";
};

const checkCurrentAnswer = () => {
  const q = currentQuestion.value;
  if (!q) return;

  const ok = isCorrectAnswer(userAnswer.value, q.number);

  feedbacks.value = { ...feedbacks.value, [currentQuestionIndex.value]: ok };
  answers.value = { ...answers.value, [currentQuestionIndex.value]: userAnswer.value };
  isAnswerChecked.value = true;

  if (ok) {
    score.value += 1;
    playSound("correct");
  } else {
    playSound("failure");
  }

  if (advanceTimer) window.clearTimeout(advanceTimer);
  advanceTimer = window.setTimeout(() => {
    if (currentQuestionIndex.value < shuffledQuestions.value.length - 1) {
      currentQuestionIndex.value += 1;
      isAnswerChecked.value = false;
      userAnswer.value = "";
    } else {
      allAnswered.value = true;
    }
  }, 1500);
};

const handleResetWithShuffle = () => {
  shuffleQuestions();
  currentQuestionIndex.value = 0;
  score.value = 0;
  allAnswered.value = false;
  userAnswer.value = "";
  answers.value = {};
  feedbacks.value = {};
  showResults.value = false;
  isAnswerChecked.value = false;
};
</script>

<template>
  <div class="h-full flex flex-col">
    <ActivityTitle :title="props.questions.title" />

    <div v-if="!showResults" class="flex flex-col h-full bg-picton-blue-100">
      <div class="flex-1 overflow-y-auto py-2">
        <div :key="currentQuestionIndex" class="bg-white rounded-lg p-6 shadow-sm">
          <div class="flex gap-6 mb-8 justify-between">
            <div
              v-for="(place, idx) in placeValueBreakdown"
              :key="`${currentQuestionIndex}-${idx}`"
              class="bg-gray-50 rounded-lg p-4 border text-center grow"
            >
              <h4 class="font-medium text-neutral-700 text-2xl mb-3">
                {{ place.label }}
              </h4>
              <div class="min-h-[480px] flex items-center justify-center">
                <div v-if="place.digit === 0" class="text-gray-400 italic">
                  No {{ place.label.toLowerCase() }}
                </div>
                <div v-else :class="cn('grid justify-items-center', placeGridClass(place.size))">
                  <div v-for="i in place.digit" :key="i">
                    <div :style="renderSimpleCubeStyle(place.size, place.color)">
                      <div
                        :style="faceStyle(place.size, place.color, `translateZ(${place.size / 2}px)`)"
                      />
                      <div
                        :style="
                          faceStyle(
                            place.size,
                            place.color,
                            `translateZ(-${place.size / 2}px) rotateY(180deg)`,
                          )
                        "
                      />
                      <div
                        :style="
                          faceStyle(
                            place.size,
                            place.color,
                            `rotateY(90deg) translateZ(${place.size / 2}px)`,
                            'brightness(0.7)',
                          )
                        "
                      />
                      <div
                        :style="
                          faceStyle(
                            place.size,
                            place.color,
                            `rotateY(-90deg) translateZ(${place.size / 2}px)`,
                            'brightness(0.7)',
                          )
                        "
                      />
                      <div
                        :style="
                          faceStyle(
                            place.size,
                            place.color,
                            `rotateX(90deg) translateZ(${place.size / 2}px)`,
                            'brightness(1.2)',
                          )
                        "
                      />
                      <div
                        :style="
                          faceStyle(
                            place.size,
                            place.color,
                            `rotateX(-90deg) translateZ(${place.size / 2}px)`,
                            'brightness(0.5)',
                          )
                        "
                      />
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <div class="flex flex-col md:flex-row md:justify-end items-center gap-4">
            <div>
              <div class="flex items-center gap-4">
                <Input
                  type="text"
                  :model-value="userAnswer"
                  :disabled="isAnswerChecked"
                  class="max-w-xs !text-2xl text-center"
                  placeholder="Enter the number"
                  @update:modelValue="(v: string) => (userAnswer = v)"
                />
                <div
                  v-if="isAnswerChecked"
                  :class="
                    cn(
                      'flex items-center justify-center rounded-full p-2',
                      isCurrentAnswerCorrect
                        ? 'bg-green-100 text-green-600'
                        : 'bg-red-100 text-red-600',
                    )
                  "
                >
                  <span class="text-lg leading-none">
                    {{ isCurrentAnswerCorrect ? "✓" : "✕" }}
                  </span>
                </div>
              </div>

              <div
                v-if="
                  isAnswerChecked &&
                  !isCurrentAnswerCorrect &&
                  props.feedback === 'wrong-correct-answers'
                "
                class="mt-2 p-3 bg-red-50 border border-red-200 rounded-lg"
              >
                <p class="text-red-700 text-sm">
                  Correct answer:
                  <strong>{{ currentQuestion?.number?.toLocaleString?.() }}</strong>
                </p>
              </div>
            </div>

            <div class="flex gap-3">
              <Button
                v-if="!isAnswerChecked"
                variant="brand-lemon"
                :disabled="!userAnswer.trim()"
                :onClick="checkCurrentAnswer"
              >
                {{
                  currentQuestionIndex < total - 1 ? "Next Question" : "Check Answer"
                }}
              </Button>
              <Button
                v-else
                variant="brand-lemon"
                :disabled="true"
                class="flex items-center gap-2"
              >
                {{
                  currentQuestionIndex < total - 1
                    ? "Moving to Next..."
                    : "Finishing Activity..."
                }}
              </Button>
            </div>
          </div>
        </div>
      </div>

      <div class="flex items-center justify-center gap-2 p-4 bg-white">
        <div
          v-for="(_, idx) in shuffledQuestions"
          :key="idx"
          :class="
            cn(
              'w-10 h-10 rounded-lg flex items-center justify-center transition-all duration-200 relative',
              {
                'bg-picton-blue-200': answers[idx] === undefined && idx !== currentQuestionIndex,
                'bg-lemon-200': answers[idx] !== undefined,
                'border-2 border-picton-blue-500':
                  idx === currentQuestionIndex && answers[idx] === undefined,
                'border-2 border-lemon-500':
                  idx === currentQuestionIndex && answers[idx] !== undefined,
              },
            )
          "
        >
          <span v-if="answers[idx] !== undefined" class="absolute text-sm">
            {{ feedbacks[idx] ? "✓" : "✕" }}
          </span>
        </div>
      </div>
    </div>

    <div
      v-else
      class="flex flex-col h-full bg-picton-blue-100 text-lg p-6 overflow-y-auto"
    >
      <div class="bg-picton-blue-50 rounded-lg p-6">
        <div class="grid grid-cols-1 md:grid-cols-2 gap-4 mb-8">
          <div
            v-for="(question, idx) in shuffledQuestions"
            :key="idx"
            :class="
              cn(
                'p-4 rounded-lg border',
                feedbacks[idx] ? 'bg-green-50 border-green-200' : 'bg-red-50 border-red-200',
              )
            "
          >
            <div class="flex justify-between items-center mb-2">
              <div>
                <p class="font-medium">Question {{ idx + 1 }}</p>
                <p class="text-sm text-gray-600">
                  Number: {{ question.number.toLocaleString() }}
                </p>
              </div>
              <div
                :class="
                  cn(
                    'flex items-center justify-center rounded-full p-1',
                    feedbacks[idx] ? 'bg-green-100 text-green-600' : 'bg-red-100 text-red-600',
                  )
                "
              >
                <span class="text-base leading-none">{{ feedbacks[idx] ? "✓" : "✕" }}</span>
              </div>
            </div>

            <div class="grid grid-cols-2 gap-4 mt-2">
              <div>
                <p class="text-sm text-gray-500">Your answer:</p>
                <p
                  :class="
                    cn('font-medium', feedbacks[idx] ? 'text-green-600' : 'text-red-600')
                  "
                >
                  {{ answers[idx] || "(no answer)" }}
                </p>
              </div>
              <div
                v-if="props.feedback === 'wrong-correct-answers' && !feedbacks[idx]"
              >
                <p class="text-sm text-gray-500">Correct answer:</p>
                <p class="text-green-600 font-medium">
                  {{ question.number.toLocaleString() }}
                </p>
              </div>
            </div>
          </div>
        </div>

        <ActivityResults :score="score" :total="total" :onRestart="handleResetWithShuffle" />
      </div>
    </div>

    <ActivityResultsAlertDialog
      :score="score"
      :total="total"
      :open="allAnswered && !showResults"
      :onOpenChange="(open: boolean) => { if (!open) showResults = true }"
    />
  </div>
</template>
