// app/components/primary-sources/activities/game-activities/arrange-alphabet.vue
<script setup lang="ts">
import { computed, ref, watch } from "vue";
import { Icon } from "@iconify/vue";
import { useWindowSize } from "@vueuse/core";
import { cn, getImageUrl } from "@/lib/utils";
import ActivityTitle from "@/components/templates/activity-title";
import { ActivityResultsAlertDialog } from "@/components/templates/results";
import GameModeWrapper from "@/components/ui/game-mode/game-mode-wrapper";
import type { GameStats } from "@/components/ui/game-mode";
import type { FeedbackType } from "@/lib/types/activity-types";
import { useObjects } from "~/composables/useObjects";
import { useSoundEffects } from "~/composables/use-sound-effects";

type Props = {
  questions: {
    title: string;
    type?: string;
    fontSize?: number;
    isGameMode?: boolean;
    gameTimeLimit?: number;
  };
  feedback?: FeedbackType;
};

const props = defineProps<Props>();

const { objects, loading, error, refetch } = useObjects({
  type: props.questions.type || null,
  limit: 10,
  autoFetch: true,
});

const currentWordIndex = ref(0);
const placedLetters = ref<string[]>([]);
const isCorrect = ref(false);
const isIncorrect = ref(false);
const showDialog = ref(false);
const isTransitioning = ref(false);
const gameComplete = ref(false);
const score = ref(0);
const totalWords = ref(0);
const completedObjectIds = ref<number[]>([]);
const wrongAttempts = ref(0);
const showHint = ref(false);
const completedQuestions = ref(new Set<number>());
const incorrectQuestions = ref(new Set<number>());

const { playSound } = useSoundEffects();
const { width } = useWindowSize();

const currentObject = computed(() => objects.value[currentWordIndex.value]);
const currentWord = computed(() => currentObject.value?.name?.toLowerCase() || "");
const currentImage = computed(() => getImageUrl(currentObject.value?.imagePath || "", true));

watch(
  objects,
  (value) => {
    totalWords.value = value.length;
    if (value[0]?.name) {
      placedLetters.value = Array(value[0].name.length).fill("");
    }
  },
  { immediate: true },
);

watch(
  currentWord,
  (value) => {
    if (!value) return;

    placedLetters.value = Array(value.length).fill("");
    wrongAttempts.value = 0;
    showHint.value = false;
  },
  { immediate: true },
);

watch(isIncorrect, (value, _, onCleanup) => {
  if (!value) return;

  const timer = setTimeout(() => {
    placedLetters.value = Array(currentWord.value.length).fill("");
    isCorrect.value = false;
    isIncorrect.value = false;

    if (wrongAttempts.value >= 2) {
      showHint.value = true;
    }
  }, 1500);

  onCleanup(() => {
    clearTimeout(timer);
  });
});

watch(isCorrect, (value, _, onCleanup) => {
  if (!value || isTransitioning.value) return;

  const timer = setTimeout(() => {
    score.value += 1;
    const nextCompletedQuestions = new Set(completedQuestions.value);
    nextCompletedQuestions.add(currentWordIndex.value);
    completedQuestions.value = nextCompletedQuestions;
    moveToNextWord();
  }, 1000);

  onCleanup(() => {
    clearTimeout(timer);
  });
});

const alphabet = "abcdefghijklmnopqrstuvwxyz".split("");
const alphabetColors: Record<string, string> = {
  a: "text-purple-600",
  b: "text-pink-500",
  c: "text-amber-400",
  d: "text-amber-800",
  e: "text-gray-500",
  f: "text-blue-500",
  g: "text-red-600",
  h: "text-green-500",
  i: "text-yellow-400",
  j: "text-pink-500",
  k: "text-amber-400",
  l: "text-amber-800",
  m: "text-gray-500",
  n: "text-blue-500",
  o: "text-red-600",
  p: "text-green-500",
  q: "text-yellow-400",
  r: "text-purple-600",
  s: "text-pink-500",
  t: "text-amber-400",
  u: "text-amber-800",
  v: "text-gray-500",
  w: "text-blue-500",
  x: "text-red-600",
  y: "text-green-500",
  z: "text-yellow-400",
};

const resetActivity = async () => {
  currentWordIndex.value = 0;
  isTransitioning.value = false;
  score.value = 0;
  gameComplete.value = false;
  wrongAttempts.value = 0;
  showHint.value = false;
  completedQuestions.value = new Set();
  incorrectQuestions.value = new Set();
  isCorrect.value = false;
  isIncorrect.value = false;
  showDialog.value = false;

  if (objects.value[0]?.name) {
    placedLetters.value = Array(objects.value[0].name.length).fill("");
  }

  await refetch(completedObjectIds.value);
};

const handleDialogChange = (open: boolean) => {
  showDialog.value = open;
  if (!open) {
    void resetActivity();
  }
};

const handleTimeUp = () => {
  if (!gameComplete.value) {
    gameComplete.value = true;
    showDialog.value = true;
  }
};

const handleGameComplete = (_stats: GameStats) => {
  gameComplete.value = true;
  showDialog.value = true;
};

const moveToNextWord = () => {
  isTransitioning.value = true;

  if (currentObject.value) {
    completedObjectIds.value = [...completedObjectIds.value, currentObject.value.id];
  }

  setTimeout(() => {
    if (currentWordIndex.value < objects.value.length - 1) {
      currentWordIndex.value += 1;
      isCorrect.value = false;
      isTransitioning.value = false;
      wrongAttempts.value = 0;
      showHint.value = false;
      return;
    }

    gameComplete.value = true;
    showDialog.value = true;
  }, 500);
};

const handleLetterClick = (letter: string) => {
  if (isTransitioning.value || !currentWord.value || isCorrect.value || isIncorrect.value) return;

  const emptyIndex = placedLetters.value.findIndex((value) => value === "");
  if (emptyIndex === -1) return;

  const nextPlacedLetters = [...placedLetters.value];
  nextPlacedLetters[emptyIndex] = letter;
  placedLetters.value = nextPlacedLetters;

  if (nextPlacedLetters.includes("")) {
    playSound("correct");
    return;
  }

  const wordIsCorrect = nextPlacedLetters.join("").toLowerCase() === currentWord.value.toLowerCase();

  if (wordIsCorrect) {
    isCorrect.value = true;
    playSound("success");
    return;
  }

  isIncorrect.value = true;
  wrongAttempts.value += 1;
  const nextIncorrectQuestions = new Set(incorrectQuestions.value);
  nextIncorrectQuestions.add(currentWordIndex.value);
  incorrectQuestions.value = nextIncorrectQuestions;
  playSound("failure");
};

const handleRemoveLetter = (index: number) => {
  if (isTransitioning.value || !currentWord.value || isCorrect.value) return;

  const nextPlacedLetters = [...placedLetters.value];
  nextPlacedLetters[index] = "";
  placedLetters.value = nextPlacedLetters;
  isCorrect.value = false;
  isIncorrect.value = false;
};
</script>

<template>
  <div
    v-if="loading"
    class="flex h-full flex-1 flex-col items-center justify-center"
  >
    <div class="mb-4 h-12 w-12 animate-spin rounded-full border-b-2 border-t-2 border-picton-blue-600" />
    <p class="text-lg text-gray-600">Loading words...</p>
  </div>

  <div
    v-else-if="error || objects.length === 0"
    class="flex h-full flex-1 flex-col items-center justify-center"
  >
    <p class="mb-4 text-lg text-red-600">
      {{ error || "No words available for this activity" }}
    </p>
    <button
      type="button"
      class="rounded-lg bg-picton-blue-600 px-4 py-2 text-white hover:bg-picton-blue-700"
      @click="refetch()"
    >
      Try Again
    </button>
  </div>

  <GameModeWrapper
    v-else
    class="flex h-full flex-1 flex-col"
    :is-game-mode="props.questions.isGameMode || false"
    :total-questions="totalWords"
    :completed-questions="completedQuestions"
    :incorrect-questions="incorrectQuestions"
    :total-time-limit="props.questions.gameTimeLimit || 300"
    :on-time-up="handleTimeUp"
    :on-game-complete="handleGameComplete"
    :show-timer="props.questions.isGameMode || false"
    :show-progress="props.questions.isGameMode || false"
  >
    <div class="flex h-full flex-1 flex-col">
      <ActivityTitle :title="props.questions.title" />

      <div class="flex h-full flex-1 flex-col items-center justify-between gap-10">
        <div
          class="grid gap-2 text-center font-bold"
          :style="{
            gridTemplateColumns: `repeat(${width > 768 ? 13 : 7}, minmax(0, 1fr))`,
          }"
        >
          <p
            v-for="letter in alphabet"
            :key="letter"
            :class="`cursor-pointer select-none text-4xl transition-transform hover:scale-110 md:text-6xl ${alphabetColors[letter]}`"
            @click="handleLetterClick(letter)"
          >
            {{ letter }}
          </p>
        </div>

        <div class="relative h-[300px] rounded-lg bg-white p-2 md:shadow-md">
          <div
            v-if="showHint"
            class="absolute left-1/2 top-[-2rem] -translate-x-1/2 transform rounded border border-yellow-300 bg-yellow-100 px-2 py-1 text-sm text-yellow-800"
          >
            Hint: First letter is "{{ currentWord[0]?.toUpperCase() }}"
          </div>

          <img
            v-if="currentImage"
            :src="currentImage"
            :alt="`Clue for word: ${currentWord}`"
            class="h-full w-full rounded object-contain"
          />
          <div
            v-else
            class="flex h-full w-full items-center justify-center text-gray-500"
          >
            No image available
          </div>
        </div>

        <div
          :class="
            cn(
              'flex flex-wrap items-center justify-center gap-2 rounded-lg p-4 transition-colors duration-300 md:gap-3',
              {
                'bg-picton-blue-200': !isCorrect && !isIncorrect,
                'bg-green-200': isCorrect,
                'bg-red-200': isIncorrect,
              },
            )
          "
        >
          <div
            v-for="(_, index) in currentWord.split('')"
            :key="`${currentWordIndex}-${index}`"
            class="relative"
          >
            <div
              :class="
                cn(
                  'flex h-10 w-10 items-center justify-center rounded-md text-xl font-bold md:h-16 md:w-16 md:text-3xl',
                  {
                    'border-2 border-picton-blue-300': !placedLetters[index],
                    'text-lemon-700': placedLetters[index] && !isIncorrect,
                    'text-red-600': placedLetters[index] && isIncorrect,
                    'border-yellow-400 bg-yellow-100':
                      showHint && index === 0 && !placedLetters[index],
                  },
                )
              "
            >
              <button
                v-if="placedLetters[index]"
                type="button"
                class="flex h-full w-full items-center justify-center rounded hover:bg-red-100"
                @click="handleRemoveLetter(index)"
              >
                {{ placedLetters[index] }}
              </button>
              <span v-else-if="showHint && index === 0" class="text-gray-400">
                {{ currentWord[0]?.toUpperCase() }}
              </span>
            </div>
          </div>

          <div v-if="isCorrect" class="ml-2 text-3xl text-green-600">
            <Icon icon="mdi:check" width="32" height="32" />
          </div>
        </div>

        <ActivityResultsAlertDialog
          :score="score"
          :total="totalWords"
          :open="showDialog"
          :on-open-change="handleDialogChange"
        />
      </div>
    </div>
  </GameModeWrapper>
</template>

// app/components/primary-sources/activities/game-activities/arrange-alphabet.tsx
import { CheckIcon } from "lucide-react";
import { useState, useEffect, useCallback } from "react";
import * as motion from "motion/react-client";
import { AnimatePresence } from "motion/react";

// Local imports
import { cn, getImageUrl } from "@/lib/utils";
import ActivityTitle from "@/components/templates/activity-title";
import { useSoundEffects } from "@/shared/hooks/use-sound-effects";
import { ActivityResultsAlertDialog } from "@/components/templates/results";
import { useObjects } from "@/hooks/useObjects";
import { FeedbackType } from "@/lib/types/activity-types";
import { GameModeWrapper, GameStats } from "@/components/ui/game-mode";
import { useWindowSize } from "@/shared/hooks/use-window-size";

interface ArrangeAlphabetProps {
  questions: {
    title: string;
    type?: string;
    fontSize?: number;
    isGameMode?: boolean;
    gameTimeLimit?: number;
  };
  feedback?: FeedbackType;
}

const ArrangeAlphabet = ({
  questions: {
    title,
    type,
    fontSize,
    isGameMode = false,
    gameTimeLimit = 300, // 5 minutes default
  },
  feedback,
}: ArrangeAlphabetProps) => {
  // Fetch objects for the activity
  const { objects, loading, error, refetch } = useObjects({
    type: type || null,
    limit: 10,
    autoFetch: true,
  });

  const [currentWordIndex, setCurrentWordIndex] = useState<number>(0);
  const [placedLetters, setPlacedLetters] = useState<string[]>([]);
  const [isCorrect, setIsCorrect] = useState<boolean>(false);
  const [isIncorrect, setIsIncorrect] = useState<boolean>(false);
  const [showDialog, setShowDialog] = useState<boolean>(false);
  const [isTransitioning, setIsTransitioning] = useState<boolean>(false);
  const [gameComplete, setGameComplete] = useState<boolean>(false);
  const [score, setScore] = useState<number>(0);
  const [totalWords, setTotalWords] = useState<number>(0);
  const [completedObjectIds, setCompletedObjectIds] = useState<number[]>([]);
  const [wrongAttempts, setWrongAttempts] = useState<number>(0);
  const [showHint, setShowHint] = useState<boolean>(false);
  const [completedQuestions, setCompletedQuestions] = useState<Set<number>>(
    new Set(),
  );
  const [incorrectQuestions, setIncorrectQuestions] = useState<Set<number>>(
    new Set(),
  );

  const { playSound } = useSoundEffects();
  const { width } = useWindowSize();

  // Get current target word and image from objects
  const currentObject = objects[currentWordIndex];
  const currentWord = currentObject?.name.toLowerCase() || "";
  const currentImage = getImageUrl(currentObject?.imagePath || "", true);

  // Initialize game when objects are loaded
  useEffect(() => {
    if (
      !loading &&
      objects.length > 0 &&
      placedLetters.length === 0 &&
      currentWord
    ) {
      setPlacedLetters(Array(currentWord.length).fill(""));
      setTotalWords(objects.length);
    }
  }, [loading, objects, currentWord, placedLetters.length]);

  // Reset current word
  const resetCurrentWord = () => {
    setPlacedLetters(Array(currentWord.length).fill(""));
    setIsCorrect(false);
    setIsIncorrect(false);
    setWrongAttempts(0);
    setShowHint(false);
  };

  // Reset the entire activity
  const resetActivity = () => {
    setCurrentWordIndex(0);
    setIsTransitioning(false);
    setScore(0);
    setGameComplete(false);
    setCompletedObjectIds([]);
    setWrongAttempts(0);
    setShowHint(false);
    setCompletedQuestions(new Set());
    setIncorrectQuestions(new Set());
    if (objects.length > 0) {
      setPlacedLetters(Array(objects[0]?.name.length || 0).fill(""));
    }
    setIsCorrect(false);
    setIsIncorrect(false);
    // Refetch new objects
    refetch(completedObjectIds);
  };

  // Handle dialog close
  const handleDialogChange = (open: boolean) => {
    setShowDialog(open);
    if (!open) {
      resetActivity();
    }
  };

  // Handle time up
  const handleTimeUp = useCallback(() => {
    if (!gameComplete) {
      setGameComplete(true);
      setShowDialog(true);
    }
  }, [gameComplete]);

  // Handle game complete
  const handleGameComplete = useCallback((stats: GameStats) => {
    setGameComplete(true);
    setShowDialog(true);
  }, []);

  // Move to next word
  const moveToNextWord = useCallback(() => {
    setIsTransitioning(true);

    // Add current object to completed list
    if (currentObject) {
      setCompletedObjectIds((prev) => [...prev, currentObject.id]);
    }

    // Delay to allow exit animation to complete
    setTimeout(() => {
      if (currentWordIndex < objects.length - 1) {
        setCurrentWordIndex((prev) => prev + 1);
        setIsCorrect(false);
        setIsTransitioning(false);
        // Reset wrong attempts and hint for new word
        setWrongAttempts(0);
        setShowHint(false);
      } else {
        setGameComplete(true);
        setShowDialog(true);
      }
    }, 500);
  }, [currentWordIndex, objects.length, currentObject]);

  // Effect to initialize placedLetters when word changes
  useEffect(() => {
    if (currentWord) {
      setPlacedLetters(Array(currentWord.length).fill(""));
      setWrongAttempts(0);
      setShowHint(false);
    }
  }, [currentWord]);

  // Effect to clear incorrect state after animation
  useEffect(() => {
    if (isIncorrect) {
      const timer = setTimeout(() => {
        setIsIncorrect(false);
        resetCurrentWord();
        // Show hint after 2 wrong attempts
        if (wrongAttempts >= 2) {
          setShowHint(true);
        }
      }, 1500);
      return () => clearTimeout(timer);
    }
  }, [isIncorrect, wrongAttempts]);

  // Effect to handle word completion and transition
  useEffect(() => {
    if (isCorrect && !isTransitioning) {
      const timer = setTimeout(() => {
        setScore((prev) => prev + 1);
        // Add to completed questions
        setCompletedQuestions((prev) => new Set([...prev, currentWordIndex]));
        moveToNextWord();
      }, 1000);
      return () => clearTimeout(timer);
    }
  }, [isCorrect, isTransitioning, moveToNextWord, currentWordIndex]);

  // Alphabet array with colors
  const alphabet = "abcdefghijklmnopqrstuvwxyz".split("");
  const alphabetColors: Record<string, string> = {
    a: "text-purple-600",
    b: "text-pink-500",
    c: "text-amber-400",
    d: "text-amber-800",
    e: "text-gray-500",
    f: "text-blue-500",
    g: "text-red-600",
    h: "text-green-500",
    i: "text-yellow-400",
    j: "text-pink-500",
    k: "text-amber-400",
    l: "text-amber-800",
    m: "text-gray-500",
    n: "text-blue-500",
    o: "text-red-600",
    p: "text-green-500",
    q: "text-yellow-400",
    r: "text-purple-600",
    s: "text-pink-500",
    t: "text-amber-400",
    u: "text-amber-800",
    v: "text-gray-500",
    w: "text-blue-500",
    x: "text-red-600",
    y: "text-green-500",
    z: "text-yellow-400",
  };

  // Handle letter click
  const handleLetterClick = (letter: string) => {
    if (isTransitioning || !currentWord || isCorrect || isIncorrect) return;

    const emptyIndex = placedLetters.findIndex((l) => l === "");
    if (emptyIndex !== -1) {
      const newPlacedLetters = [...placedLetters];
      newPlacedLetters[emptyIndex] = letter;
      setPlacedLetters(newPlacedLetters);

      // Check if word is complete
      if (!newPlacedLetters.includes("")) {
        const wordIsCorrect =
          newPlacedLetters.join("").toLowerCase() === currentWord.toLowerCase();

        if (wordIsCorrect) {
          setIsCorrect(true);
          playSound("success");
        } else {
          setIsIncorrect(true);
          setWrongAttempts((prev) => prev + 1);
          // Add to incorrect questions
          setIncorrectQuestions((prev) => new Set([...prev, currentWordIndex]));
          playSound("failure");
        }
      } else {
        playSound("correct");
      }
    }
  };

  // Handle removing a letter
  const handleRemoveLetter = (index: number) => {
    if (isTransitioning || !currentWord || isCorrect) return;

    const newPlacedLetters = [...placedLetters];
    newPlacedLetters[index] = "";
    setPlacedLetters(newPlacedLetters);
    setIsCorrect(false);
    setIsIncorrect(false);
  };

  // Loading state
  if (loading) {
    return (
      <div className="flex flex-col h-full flex-1 items-center justify-center">
        <div className="animate-spin rounded-full h-12 w-12 border-t-2 border-b-2 border-picton-blue-600 mb-4" />
        <p className="text-lg text-gray-600">Loading words...</p>
      </div>
    );
  }

  // Error state
  if (error || objects.length === 0) {
    return (
      <div className="flex flex-col h-full flex-1 items-center justify-center">
        <p className="text-lg text-red-600 mb-4">
          {error || "No words available for this activity"}
        </p>
        <button
          onClick={() => refetch()}
          className="px-4 py-2 bg-picton-blue-600 text-white rounded-lg hover:bg-picton-blue-700"
        >
          Try Again
        </button>
      </div>
    );
  }

  return (
    <GameModeWrapper
      isGameMode={isGameMode}
      totalQuestions={totalWords}
      completedQuestions={completedQuestions}
      incorrectQuestions={incorrectQuestions}
      totalTimeLimit={gameTimeLimit}
      onTimeUp={handleTimeUp}
      onGameComplete={handleGameComplete}
      showTimer={isGameMode}
      showProgress={isGameMode}
      className="flex flex-col h-full flex-1"
    >
      <div className="flex flex-col h-full flex-1">
        <ActivityTitle title={title} />

        {/* Alphabet display */}
        <div className="flex flex-col items-center justify-between h-full flex-1 gap-10">
          <div
            className="grid grid-cols-12 md:gap-2 font-bold text-center"
            style={{
              gridTemplateColumns: `repeat(${width > 768 ? 13 : 7}, minmax(0, 1fr))`,
            }}
          >
            {alphabet.map((letter) => (
              <p
                key={letter}
                className={`cursor-pointer select-none text-4xl md:text-6xl ${alphabetColors[letter]} hover:scale-110 transition-transform`}
                onClick={() => handleLetterClick(letter)}
              >
                {letter}
              </p>
            ))}
          </div>

          {/* Image clue */}
          <div className="h-[300px] bg-white rounded-lg md:shadow-md p-2 relative">
            {showHint && (
              <div className="absolute -top-8 left-1/2 transform -translate-x-1/2 bg-yellow-100 border border-yellow-300 rounded px-2 py-1 text-sm text-yellow-800">
                Hint: First letter is "{currentWord[0]?.toUpperCase()}"
              </div>
            )}
            {currentImage ? (
              <img
                src={currentImage}
                alt={`Clue for word: ${currentWord}`}
                className="w-full h-full object-contain rounded"
                onError={(e) => {
                  // Fallback if image fails to load
                  const target = e.currentTarget as HTMLImageElement;
                  target.style.display = "none";
                  const parent = target.parentElement;
                  if (parent) {
                    parent.innerHTML =
                      '<div class="w-full h-full flex items-center justify-center text-gray-500">Image failed to load</div>';
                  }
                }}
              />
            ) : (
              <div className="w-full h-full flex items-center justify-center text-gray-500">
                No image available
              </div>
            )}
          </div>

          {/* Word challenge container */}
          <AnimatePresence mode="wait">
            <motion.div
              key={`word-container-${currentWordIndex}`}
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -20 }}
              transition={{ duration: 0.3 }}
              className={cn(
                "flex justify-center items-center flex-wrap gap-2 md:gap-3 p-4 rounded-lg transition-colors duration-300",
                {
                  "bg-picton-blue-200": !isCorrect && !isIncorrect,
                  "bg-green-200": isCorrect,
                  "bg-red-200": isIncorrect,
                },
              )}
            >
              {/* Input boxes */}
              {currentWord.split("").map((letter, index) => (
                <div key={index} className="relative">
                  <motion.div
                    className={cn(
                      `w-10 md:w-16 h-10 md:h-16 rounded-md flex items-center justify-center text-xl md:text-3xl font-bold`,
                      {
                        "text-lemon-700": placedLetters[index] && !isIncorrect,
                        "text-red-600": placedLetters[index] && isIncorrect,
                        "border-2 border-picton-blue-300":
                          !placedLetters[index],
                        "bg-yellow-100 border-yellow-400":
                          showHint && index === 0 && !placedLetters[index],
                      },
                    )}
                    animate={{
                      backgroundColor: placedLetters[index]
                        ? isIncorrect
                          ? "#ffcccc"
                          : "#fcfec3"
                        : "transparent",
                      scale: placedLetters[index] ? [1, 1.07, 1] : 1,
                    }}
                    transition={{ duration: 0.5 }}
                  >
                    <AnimatePresence mode="wait">
                      {showHint && index === 0 && !placedLetters[index] && (
                        <motion.div
                          key="hint-letter"
                          initial={{ opacity: 0, scale: 0.8 }}
                          animate={{ opacity: 0.5, scale: 1 }}
                          exit={{ opacity: 0, scale: 0.8 }}
                          className="text-gray-400"
                        >
                          {currentWord[0]?.toUpperCase()}
                        </motion.div>
                      )}
                      {placedLetters[index] && (
                        <motion.div
                          key={`letter-${placedLetters[index]}-${index}`}
                          initial={{ y: -100, opacity: 0 }}
                          animate={{ y: 0, opacity: 1 }}
                          exit={{ y: 50, opacity: 0 }}
                          transition={{
                            type: "spring",
                            stiffness: 300,
                            damping: 20,
                          }}
                          onClick={() => handleRemoveLetter(index)}
                          className="cursor-pointer w-full h-full flex items-center justify-center hover:bg-red-100 rounded"
                        >
                          {placedLetters[index]}
                        </motion.div>
                      )}
                    </AnimatePresence>
                  </motion.div>
                </div>
              ))}

              {/* Checkmark for correct answer */}
              {isCorrect && (
                <motion.div
                  initial={{ scale: 0, opacity: 0 }}
                  animate={{ scale: 1, opacity: 1 }}
                  exit={{ scale: 0, opacity: 0 }}
                  transition={{ type: "spring", stiffness: 300, damping: 15 }}
                  className="ml-2 text-green-600 text-3xl"
                >
                  <CheckIcon />
                </motion.div>
              )}
            </motion.div>
          </AnimatePresence>
        </div>

        {/* Results dialog */}
        <ActivityResultsAlertDialog
          score={score}
          total={totalWords}
          open={showDialog}
          onOpenChange={handleDialogChange}
          completionMessage={`Great job! You've completed ${score} out of ${totalWords} words correctly!`}
        />
      </div>
    </GameModeWrapper>
  );
};

export default ArrangeAlphabet;
