// app/components/primary-sources/activities/game-activities/short-answer-questions.tsx
"use client";

import { motion } from "motion/react";
import debounce from "lodash.debounce";
import { Check, X } from "lucide-react";
import { useState, useCallback, useEffect } from "react";

// local imports
import { cn, getImageUrl, shuffle } from "@/lib/utils";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/inputs/input";
import { useObjects } from "@/hooks/useObjects";
import ActivityTitle from "@/components/templates/activity-title";
import { FeedbackType } from "@/lib/types/activity-types";
import { useSoundEffects } from "@/shared/hooks/use-sound-effects";
import { GameModeWrapper, GameStats } from "@/components/ui/game-mode";
import ActivityResults, {
  ActivityResultsAlertDialog,
} from "@/components/templates/results";

type ShortAnswerQuestionsProps = {
  questions: {
    title: string;
    type?: string;
    fontSize?: number;
    isGameMode?: boolean;
    gameTimeLimit?: number;
  };
  feedback?: FeedbackType;
  activityId?: number;
  studentProfileId?: number;
  parentAccountId?: number;
  sessionId?: number;
  autoSaveAnswers?: boolean;
};

type Question = {
  id: number;
  question: string;
  answer: string;
  image?: string | null;
};

const ShortAnswerQuestions = ({
  questions: {
    title,
    fontSize,
    type,
    isGameMode = false,
    gameTimeLimit = 300, // 5 minutes default
  },
  feedback,
}: ShortAnswerQuestionsProps) => {
  // Fetch objects for the activity
  const { objects, loading, error, refetch } = useObjects({
    type: type || null,
    limit: 10,
    autoFetch: true,
  });

  const [gameQuestions, setGameQuestions] = useState<Question[]>([]);
  const [score, setScore] = useState(0);
  const [allAnswered, setAllAnswered] = useState(false);
  const [checkedItems, setCheckedItems] = useState<number[]>([]);
  const [answers, setAnswers] = useState<{ [key: number]: string }>({});
  const [feedbacks, setFeedbacks] = useState<{ [key: number]: boolean }>({});
  const [showResults, setShowResults] = useState(false);
  const [gameComplete, setGameComplete] = useState(false);
  const [completedQuestions, setCompletedQuestions] = useState<Set<number>>(
    new Set(),
  );
  const [incorrectQuestions, setIncorrectQuestions] = useState<Set<number>>(
    new Set(),
  );
  const [completedObjectIds, setCompletedObjectIds] = useState<number[]>([]);

  const { playSound } = useSoundEffects();

  // Generate questions from objects
  const generateQuestions = useCallback(() => {
    if (!objects || objects.length < 1) return;

    // Filter out invalid objects and create questions
    const validQuestions: Question[] = objects
      .filter((obj) => {
        // Only include objects that have both a name and either syllables or a valid name
        return (
          obj.name &&
          obj.name.trim() !== "" &&
          ((obj.syllables && obj.syllables.trim() !== "") ||
            obj.name.trim() !== "")
        );
      })
      .map((obj) => ({
        id: obj.id,
        question: (obj.syllables && obj.syllables.trim()) || obj.name, // Use syllables if available and not empty, otherwise use name
        answer: obj.name,
        image: getImageUrl(
          obj.imagePath && obj.imagePath.trim() !== ""
            ? obj.imagePath
            : undefined,
          true,
        ),
      })); // Already limited by fetch limit
    setGameQuestions(shuffle(validQuestions));
  }, [objects]);

  // Generate questions when objects are loaded
  useEffect(() => {
    if (!loading && objects.length > 0) {
      generateQuestions();
    }
  }, [loading, objects, generateQuestions]);

  const handleTimeUp = useCallback(() => {
    if (!gameComplete) {
      handleCheckAllAnswers();
    }
  }, [gameComplete]);

  const handleGameComplete = useCallback((stats: GameStats) => {
    setGameComplete(true);
    // setShowResults(true);
  }, []);

  // Check if all questions have been answered
  const allQuestionsAnswered = gameQuestions.every((_, index) => {
    const answer = answers[index];
    return answer && answer.trim() !== "";
  });

  // Custom reset function that also shuffles questions
  const handleResetWithShuffle = () => {
    setScore(0);
    setAllAnswered(false);
    setCheckedItems([]);
    setAnswers({});
    setFeedbacks({});
    setShowResults(false);
    setGameComplete(false);
    setCompletedQuestions(new Set());
    setIncorrectQuestions(new Set());

    if (isGameMode) {
      // Track completed objects and refetch new ones
      const currentObjectIds = objects.map((obj) => obj.id);
      setCompletedObjectIds((prev) => [...prev, ...currentObjectIds]);
      refetch([...completedObjectIds, ...currentObjectIds]);
    } else {
      // Regenerate questions from existing objects
      generateQuestions();
    }
  };

  const checkAnswer = (userAnswer: string, correctAnswer: string): boolean => {
    return (
      userAnswer.toLowerCase().trim() === correctAnswer.toLowerCase().trim()
    );
  };

  // Custom check function for all questions
  const handleCheckAllAnswers = async () => {
    let newScore = 0;
    const newFeedbacks: { [key: number]: boolean } = {};
    const newCheckedItems: number[] = [];
    // const timeSpent = Date.now() - startTime;

    gameQuestions.forEach((question, index) => {
      const userAnswer = answers[index] || "";
      const isCorrect = checkAnswer(userAnswer, question.answer);

      newFeedbacks[index] = isCorrect;
      newCheckedItems.push(index);

      // Add to completed questions
      setCompletedQuestions((prev) => new Set([...prev, index]));

      if (!isCorrect) {
        setIncorrectQuestions((prev) => new Set([...prev, index]));
      }

      if (isCorrect) {
        newScore++;
      }
    });

    setScore(newScore);
    setFeedbacks(newFeedbacks);
    setCheckedItems(newCheckedItems);
    setAllAnswered(true);
    setGameComplete(true);

    // Play sound based on overall performance
    playSound(newScore === gameQuestions.length ? "success" : "failure");
  };

  // Create debounced version of the answer checking logic (for future auto-save if needed)
  const debouncedCheckAndSave = useCallback(
    debounce((index: number, value: string) => {
      // Future implementation for auto-save
    }, 1000),
    [],
  );

  const handleInputChange = (index: number, value: string) => {
    setAnswers((prev) => ({
      ...prev,
      [index]: value,
    }));

    debouncedCheckAndSave(index, value);
  };

  if (loading) {
    return (
      <div className="flex items-center justify-center min-h-[400px]">
        <div className="text-lg">Loading questions...</div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="flex items-center justify-center min-h-[400px]">
        <div className="text-lg text-red-500">
          Error loading questions: {error}
        </div>
      </div>
    );
  }

  if (gameQuestions.length === 0) {
    return (
      <div className="flex items-center justify-center min-h-[400px]">
        <div className="text-lg">No questions available</div>
      </div>
    );
  }

  return (
    <GameModeWrapper
      isGameMode={isGameMode}
      totalQuestions={gameQuestions.length}
      completedQuestions={completedQuestions}
      incorrectQuestions={incorrectQuestions}
      totalTimeLimit={gameTimeLimit}
      onTimeUp={handleTimeUp}
      onGameComplete={handleGameComplete}
      showTimer={isGameMode}
      showProgress={isGameMode}
    >
      <div className="h-full flex flex-col">
        <ActivityTitle title={title} />

        <div className="flex flex-col h-full bg-picton-blue-100 gap-2">
          <div
            className="flex-1 overflow-y-auto space-y-4 py-4"
            style={{
              fontSize: fontSize ? `${fontSize}px` : "20px",
            }}
          >
            {gameQuestions.map((q, i) => {
              const actualIndex = i;

              return (
                <motion.div
                  key={q.id}
                  initial={{ opacity: 0, y: 20 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ duration: 0.5, delay: i * 0.1 }}
                  className={cn("rounded-lg min-h-[80px] flex items-center", {
                    "bg-picton-blue-50": !checkedItems.includes(actualIndex),
                    "bg-lemon-50 text-lemon-700":
                      checkedItems.includes(actualIndex),
                    "bg-green-100 text-green-700": feedbacks[actualIndex],
                    "bg-red-100 text-red-700": feedbacks[actualIndex] === false,
                  })}
                >
                  <div className="px-4 py-2 flex items-center justify-between w-full">
                    <div>
                      <span className="mr-2 md:mr-4 font-medium text-gray-600">
                        {i + 1}.
                      </span>
                      {q.image && (
                        <div className="h-28 mr-4">
                          <img
                            src={q.image}
                            alt={q.question}
                            className="w-full h-full rounded-lg object-cover"
                          />
                        </div>
                      )}
                      <div className="inline-flex items-center flex-1 gap-4">
                        <span className="font-medium">{q.question}</span>
                        <span
                          className="inline-flex flex-col mx-1"
                          style={{ width: "150px" }}
                        >
                          <Input
                            type="text"
                            value={answers[actualIndex] || ""}
                            onChange={(e) =>
                              handleInputChange(actualIndex, e.target.value)
                            }
                            disabled={checkedItems.includes(actualIndex)}
                            placeholder=""
                            className="min-w-0 px-2 border-none bg-transparent text-center focus:outline-none"
                            style={{ maxWidth: "320px" }}
                          />
                          <div
                            className={cn(
                              "border-b border-dashed border-picton-blue-700",
                              {
                                "border-lemon-700":
                                  checkedItems.includes(actualIndex),
                              },
                            )}
                          />
                        </span>
                      </div>
                    </div>
                    <div className="flex items-center gap-2">
                      {checkedItems.includes(actualIndex) && (
                        <>
                          <motion.div
                            initial={{ scale: 0 }}
                            animate={{ scale: 1 }}
                            className={cn(
                              "flex items-center justify-center rounded-full p-1",
                              feedbacks[actualIndex]
                                ? "bg-green-100 text-green-600"
                                : "bg-red-100 text-red-600",
                            )}
                          >
                            {feedbacks[actualIndex] ? (
                              <Check className="h-5 w-5" />
                            ) : (
                              <X className="h-5 w-5" />
                            )}
                          </motion.div>
                          {feedback === "wrong-correct-answers" &&
                            feedbacks[actualIndex] === false && (
                              <div className="text-sm text-red-600 font-medium">
                                Answer: {q.answer}
                              </div>
                            )}
                        </>
                      )}
                    </div>
                  </div>
                </motion.div>
              );
            })}
          </div>

          {/* Single Check Answers Button */}
          {showResults ? (
            <ActivityResults
              score={score}
              total={gameQuestions.length}
              onRestart={handleResetWithShuffle}
            />
          ) : (
            <div className="relative flex justify-end">
              <Button
                disabled={!allQuestionsAnswered || allAnswered}
                onClick={handleCheckAllAnswers}
                variant="brand-lemon"
                size="lg"
              >
                {allAnswered ? "Answers Checked" : "Check Answers"}
              </Button>
            </div>
          )}
        </div>

        <ActivityResultsAlertDialog
          score={score}
          total={gameQuestions.length}
          open={allAnswered && !showResults}
          onOpenChange={(open) => {
            if (!open) {
              setShowResults(true);
            }
          }}
        />
      </div>
    </GameModeWrapper>
  );
};

export default ShortAnswerQuestions;

// app/components/primary-sources/activities/game-activities/short-answer-questions.vue
<script setup lang="ts">
import { computed, ref, watch } from "vue";
import { Icon } from "@iconify/vue";
import { useDebounceFn } from "@vueuse/core";
import { cn, getImageUrl, shuffle } from "@/lib/utils";
import { Button } from "@/components/ui/button";
import Input from "@/components/ui/inputs/input";
import ActivityTitle from "@/components/templates/activity-title";
import ActivityResults, {
  ActivityResultsAlertDialog,
} from "@/components/templates/results";
import GameModeWrapper from "@/components/ui/game-mode/game-mode-wrapper";
import type { GameStats } from "@/components/ui/game-mode";
import type { FeedbackType } from "@/lib/types/activity-types";
import { useObjects, type GameObject } from "~/composables/useObjects";
import { useSoundEffects } from "~/composables/use-sound-effects";

type Question = {
  id: number;
  question: string;
  answer: string;
  image?: string | null;
};

type Props = {
  questions: {
    title: string;
    type?: string;
    fontSize?: number;
    isGameMode?: boolean;
    gameTimeLimit?: number;
  };
  feedback?: FeedbackType;
};

const props = defineProps<Props>();

const { objects, loading, error, refetch } = useObjects({
  type: props.questions.type || null,
  limit: 10,
  autoFetch: true,
});

const gameQuestions = ref<Question[]>([]);
const score = ref(0);
const allAnswered = ref(false);
const checkedItems = ref<number[]>([]);
const answers = ref<Record<number, string>>({});
const feedbacks = ref<Record<number, boolean>>({});
const showResults = ref(false);
const gameComplete = ref(false);
const completedQuestions = ref(new Set<number>());
const incorrectQuestions = ref(new Set<number>());
const completedObjectIds = ref<number[]>([]);

const { playSound } = useSoundEffects();

const buildQuestions = (sourceObjects: GameObject[]) => {
  const nextQuestions = sourceObjects
    .filter((item) => item.name?.trim())
    .map((item) => ({
      id: item.id,
      question: item.syllables?.trim() || item.name,
      answer: item.name,
      image: getImageUrl(item.imagePath, true),
    }));

  gameQuestions.value = shuffle(nextQuestions);
};

watch(
  objects,
  (value) => {
    if (value.length) {
      buildQuestions(value);
    }
  },
  { immediate: true },
);

const allQuestionsAnswered = computed(() =>
  gameQuestions.value.every((_, index) => (answers.value[index] || "").trim() !== ""),
);

const handleTimeUp = () => {
  if (!gameComplete.value) {
    handleCheckAllAnswers();
  }
};

const handleGameComplete = (_stats: GameStats) => {
  gameComplete.value = true;
};

const handleResetWithShuffle = async () => {
  score.value = 0;
  allAnswered.value = false;
  checkedItems.value = [];
  answers.value = {};
  feedbacks.value = {};
  showResults.value = false;
  gameComplete.value = false;
  completedQuestions.value = new Set();
  incorrectQuestions.value = new Set();

  if (props.questions.isGameMode) {
    const currentObjectIds = objects.value.map((item) => item.id);
    const nextExcludedIds = [...completedObjectIds.value, ...currentObjectIds];
    completedObjectIds.value = nextExcludedIds;
    await refetch(nextExcludedIds);
    return;
  }

  buildQuestions(objects.value);
};

const checkAnswer = (userAnswer: string, correctAnswer: string) =>
  userAnswer.toLowerCase().trim() === correctAnswer.toLowerCase().trim();

const handleCheckAllAnswers = () => {
  let nextScore = 0;
  const nextFeedbacks: Record<number, boolean> = {};
  const nextCheckedItems: number[] = [];
  const nextCompletedQuestions = new Set<number>();
  const nextIncorrectQuestions = new Set<number>();

  gameQuestions.value.forEach((question, index) => {
    const userAnswer = answers.value[index] || "";
    const isCorrect = checkAnswer(userAnswer, question.answer);

    nextFeedbacks[index] = isCorrect;
    nextCheckedItems.push(index);
    nextCompletedQuestions.add(index);

    if (!isCorrect) {
      nextIncorrectQuestions.add(index);
    } else {
      nextScore += 1;
    }
  });

  score.value = nextScore;
  feedbacks.value = nextFeedbacks;
  checkedItems.value = nextCheckedItems;
  completedQuestions.value = nextCompletedQuestions;
  incorrectQuestions.value = nextIncorrectQuestions;
  allAnswered.value = true;
  gameComplete.value = true;

  playSound(nextScore === gameQuestions.value.length ? "success" : "failure");
};

const debouncedCheckAndSave = useDebounceFn(() => {}, 1000);

const handleInputChange = (index: number, value: string) => {
  answers.value = {
    ...answers.value,
    [index]: value,
  };

  debouncedCheckAndSave();
};

const handleResultsDialogChange = (open: boolean) => {
  if (!open) {
    showResults.value = true;
  }
};
</script>

<template>
  <div
    v-if="loading"
    class="flex min-h-[400px] items-center justify-center"
  >
    <div class="text-lg">Loading questions...</div>
  </div>

  <div
    v-else-if="error"
    class="flex min-h-[400px] items-center justify-center"
  >
    <div class="text-lg text-red-500">Error loading questions: {{ error }}</div>
  </div>

  <div
    v-else-if="gameQuestions.length === 0"
    class="flex min-h-[400px] items-center justify-center"
  >
    <div class="text-lg">No questions available</div>
  </div>

  <GameModeWrapper
    v-else
    :is-game-mode="props.questions.isGameMode || false"
    :total-questions="gameQuestions.length"
    :completed-questions="completedQuestions"
    :incorrect-questions="incorrectQuestions"
    :total-time-limit="props.questions.gameTimeLimit || 300"
    :on-time-up="handleTimeUp"
    :on-game-complete="handleGameComplete"
    :show-timer="props.questions.isGameMode || false"
    :show-progress="props.questions.isGameMode || false"
  >
    <div class="flex h-full flex-col">
      <ActivityTitle :title="props.questions.title" />

      <div class="flex h-full flex-col gap-2 bg-picton-blue-100">
        <div
          class="flex-1 space-y-4 overflow-y-auto py-4"
          :style="{ fontSize: props.questions.fontSize ? `${props.questions.fontSize}px` : '20px' }"
        >
          <div
            v-for="(question, index) in gameQuestions"
            :key="question.id"
            :class="
              cn('flex min-h-[80px] items-center rounded-lg', {
                'bg-picton-blue-50': !checkedItems.includes(index),
                'bg-green-100 text-green-700': feedbacks[index] === true,
                'bg-red-100 text-red-700': feedbacks[index] === false,
                'bg-lemon-50 text-lemon-700':
                  checkedItems.includes(index) && feedbacks[index] === undefined,
              })
            "
          >
            <div class="flex w-full items-center justify-between px-4 py-2">
              <div>
                <span class="mr-2 font-medium text-gray-600 md:mr-4">{{ index + 1 }}.</span>

                <div v-if="question.image" class="mr-4 h-28">
                  <img
                    :src="question.image"
                    :alt="question.question"
                    class="h-full w-full rounded-lg object-cover"
                  />
                </div>

                <div class="inline-flex flex-1 items-center gap-4">
                  <span class="font-medium">{{ question.question }}</span>

                  <span class="mx-1 inline-flex w-[150px] flex-col">
                    <Input
                      :model-value="answers[index] || ''"
                      type="text"
                      :disabled="checkedItems.includes(index)"
                      class="min-w-0 border-none bg-transparent px-2 text-center focus:outline-none"
                      :style="{ maxWidth: '320px' }"
                      @update:model-value="(value) => handleInputChange(index, String(value))"
                    />
                    <div
                      :class="
                        cn('border-b border-dashed border-picton-blue-700', {
                          'border-lemon-700': checkedItems.includes(index),
                        })
                      "
                    />
                  </span>
                </div>
              </div>

              <div class="flex items-center gap-2">
                <template v-if="checkedItems.includes(index)">
                  <div
                    :class="
                      cn(
                        'flex items-center justify-center rounded-full p-1',
                        feedbacks[index]
                          ? 'bg-green-100 text-green-600'
                          : 'bg-red-100 text-red-600',
                      )
                    "
                  >
                    <Icon
                      :icon="feedbacks[index] ? 'mdi:check' : 'mdi:close'"
                      width="20"
                      height="20"
                    />
                  </div>

                  <div
                    v-if="props.feedback === 'wrong-correct-answers' && feedbacks[index] === false"
                    class="text-sm font-medium text-red-600"
                  >
                    Answer: {{ question.answer }}
                  </div>
                </template>
              </div>
            </div>
          </div>
        </div>

        <ActivityResults
          v-if="showResults"
          :score="score"
          :total="gameQuestions.length"
          :on-restart="handleResetWithShuffle"
        />

        <div v-else class="relative flex justify-end">
          <Button
            variant="brand-lemon"
            size="lg"
            :disabled="!allQuestionsAnswered || allAnswered"
            @click="handleCheckAllAnswers"
          >
            {{ allAnswered ? "Answers Checked" : "Check Answers" }}
          </Button>
        </div>
      </div>

      <ActivityResultsAlertDialog
        :score="score"
        :total="gameQuestions.length"
        :open="allAnswered && !showResults"
        :on-open-change="handleResultsDialogChange"
      />
    </div>
  </GameModeWrapper>
</template>
