// nextjs-migration-package/components/interactive/InteractiveVideo.tsx
'use client'

import { useRef, useState, useEffect, useCallback, useImperativeHandle, forwardRef } from 'react'
import { useInteractiveVideo } from '@/lib/hooks/useInteractiveVideo'
import VideoTimeline from './VideoTimeline'
import QuizModal from './QuizModal'
import SelectionModal from './SelectionModal'
import type { Interaction, QuizInteraction, SelectionInteraction } from '@/types/interactive-video.interface'

interface Props {
  videoSrc: string
  interactions: Interaction[]
  onQuizSubmit?: (interaction: QuizInteraction, answer: string) => void
  onSelectionSubmit?: (interaction: SelectionInteraction, answers: Record<string, string>) => void
}

export interface InteractiveVideoRef {
  triggerQuiz: (quizId?: string) => void
  getDuration: () => number
  getCurrentTime: () => number
  videoRef: React.RefObject<HTMLVideoElement> | null
}

const InteractiveVideo = forwardRef<InteractiveVideoRef, Props>(
  ({ videoSrc, interactions, onQuizSubmit, onSelectionSubmit }, ref) => {
    const videoRef = useRef<HTMLVideoElement>(null)
    const containerRef = useRef<HTMLDivElement>(null)
    const videoState = useInteractiveVideo(interactions)
    const [activeQuiz, setActiveQuiz] = useState<QuizInteraction | null>(null)
    const [isQuizModalOpen, setIsQuizModalOpen] = useState(false)
    const [activeSelection, setActiveSelection] = useState<SelectionInteraction | null>(null)
    const [isSelectionModalOpen, setIsSelectionModalOpen] = useState(false)
    const [isFullscreen, setIsFullscreen] = useState(false)
    const [showControls, setShowControls] = useState(true)
    const controlsTimerRef = useRef<ReturnType<typeof setTimeout> | null>(null)
    const answeredIdsRef = useRef<Set<string>>(new Set())
    const quizPauseTimeRef = useRef<number>(0)
    const selectionPauseTimeRef = useRef<number>(0)

    const formatTime = useCallback((seconds: number): string => {
      if (isNaN(seconds) || !isFinite(seconds)) return '0:00'
      const mins = Math.floor(seconds / 60)
      const secs = Math.floor(seconds % 60)
      return `${mins}:${secs.toString().padStart(2, '0')}`
    }, [])

    const startControlsTimer = useCallback(() => {
      if (controlsTimerRef.current) clearTimeout(controlsTimerRef.current)
      if (!isQuizModalOpen && !isSelectionModalOpen) {
        controlsTimerRef.current = setTimeout(() => {
          if (!videoRef.current?.paused) {
            setShowControls(false)
          }
        }, 3000)
      }
    }, [isQuizModalOpen, isSelectionModalOpen])

    const resetControlsTimer = useCallback(() => {
      setShowControls(true)
      startControlsTimer()
    }, [startControlsTimer])

    const handleTimeUpdate = useCallback(() => {
      if (!videoRef.current) return
      const currentTime = videoRef.current.currentTime
      videoState.updateTime(currentTime)

      const INTERACTION_THRESHOLD = 0.5

      // Check for quiz interactions
      const quizInteraction = interactions.find(
        (interaction) => 
          interaction.type === 'quiz' && 
          !answeredIdsRef.current.has(interaction.id) &&
          Math.abs(currentTime - interaction.startTime) <= INTERACTION_THRESHOLD
      ) as QuizInteraction | undefined

      if (quizInteraction && !isQuizModalOpen && activeQuiz?.id !== quizInteraction.id) {
        setActiveQuiz(quizInteraction)
        setIsQuizModalOpen(true)
        if (videoRef.current) {
          quizPauseTimeRef.current = videoRef.current.currentTime
          if (!videoRef.current.paused) {
            videoRef.current.pause()
          }
        }
      }

      if (activeQuiz && !quizInteraction) {
        const timeDiff = Math.abs(currentTime - activeQuiz.startTime)
        if (timeDiff > INTERACTION_THRESHOLD) {
          setIsQuizModalOpen(false)
          setActiveQuiz(null)
        }
      }

      // Check for selection interactions
      const selectionInteraction = interactions.find(
        (interaction) => 
          interaction.type === 'selection' && 
          !answeredIdsRef.current.has(interaction.id) &&
          Math.abs(currentTime - interaction.startTime) <= INTERACTION_THRESHOLD
      ) as SelectionInteraction | undefined

      if (selectionInteraction && !isSelectionModalOpen && activeSelection?.id !== selectionInteraction.id) {
        setActiveSelection(selectionInteraction)
        setIsSelectionModalOpen(true)
        if (videoRef.current) {
          selectionPauseTimeRef.current = videoRef.current.currentTime
          if (!videoRef.current.paused) {
            videoRef.current.pause()
          }
        }
      }

      if (activeSelection && !selectionInteraction) {
        const timeDiff = Math.abs(currentTime - activeSelection.startTime)
        if (timeDiff > INTERACTION_THRESHOLD) {
          setIsSelectionModalOpen(false)
          setActiveSelection(null)
        }
      }
    }, [interactions, isQuizModalOpen, activeQuiz, isSelectionModalOpen, activeSelection, videoState])

    const handleLoadedMetadata = useCallback(() => {
      if (!videoRef.current) return
      videoState.setDuration(videoRef.current.duration)
      
      const initialQuiz = videoState.activeInteractions.find(
        (interaction) => interaction.type === 'quiz' && interaction.startTime === 0
      ) as QuizInteraction | undefined
      
      if (initialQuiz && !isQuizModalOpen) {
        setActiveQuiz(initialQuiz)
        setIsQuizModalOpen(true)
        if (videoRef.current) {
          videoRef.current.pause()
        }
      }
    }, [videoState, isQuizModalOpen])

    const handleVideoClick = useCallback(() => {
      if (!videoRef.current) return
      videoState.togglePlay(videoRef.current)
    }, [videoState])

    const handlePlay = useCallback(() => {
      videoState.setIsPlaying(true)
    }, [videoState])

    const handlePause = useCallback(() => {
      videoState.setIsPlaying(false)
      if (videoRef.current) {
        setTimeout(() => handleTimeUpdate(), 0)
      }
    }, [videoState, handleTimeUpdate])

    const handleSeek = useCallback((time: number) => {
      if (!videoRef.current) return
      videoState.seekTo(time, videoRef.current)
      setTimeout(() => handleTimeUpdate(), 0)
    }, [videoState, handleTimeUpdate])

    const handleQuizSubmit = useCallback((answer: string, isCorrect: boolean) => {
      if (!activeQuiz) return
      onQuizSubmit?.(activeQuiz, answer)
    }, [activeQuiz, onQuizSubmit])

    const handleQuizContinue = useCallback((isCorrect: boolean) => {
      if (!videoRef.current || !activeQuiz) return
      
      answeredIdsRef.current.add(activeQuiz.id)
      setIsQuizModalOpen(false)
      const quizId = activeQuiz.id
      setActiveQuiz(null)
      
      if (isCorrect === true) {
        const resumeTime = quizPauseTimeRef.current > 0 ? quizPauseTimeRef.current : videoRef.current.currentTime
        const quizInteraction = interactions.find(i => i.id === quizId && i.type === 'quiz') as QuizInteraction | undefined
        const quizEndTime = quizInteraction?.endTime || resumeTime
        const skipTime = Math.max(resumeTime, quizEndTime + 0.5)
        videoRef.current.currentTime = skipTime
        videoRef.current.play().catch(e => {
          console.error('Failed to resume video:', e)
          setTimeout(() => {
            videoRef.current?.play().catch(err => console.error('Retry failed:', err))
          }, 200)
        })
      } else if (isCorrect === false) {
        const sortedInteractions = [...interactions].sort((a, b) => a.startTime - b.startTime)
        const currentInteraction = sortedInteractions.find(i => i.id === quizId)
        const currentIndex = currentInteraction ? sortedInteractions.indexOf(currentInteraction) : -1
        let previousInteraction = null
        if (currentIndex > 0) {
          previousInteraction = sortedInteractions[currentIndex - 1]
        }
        answeredIdsRef.current.delete(quizId)
        
        if (previousInteraction) {
          const jumpTime = previousInteraction.endTime + 1
          videoRef.current.currentTime = jumpTime
        } else {
          videoRef.current.currentTime = 0
        }
        
        videoRef.current.play().catch(e => {
          console.error('Failed to resume video:', e)
          setTimeout(() => {
            videoRef.current?.play().catch(err => console.error('Retry failed:', err))
          }, 200)
        })
      }
      
      quizPauseTimeRef.current = 0
    }, [activeQuiz, interactions])

    const handleQuizClose = useCallback(() => {
      setIsQuizModalOpen(false)
      setActiveQuiz(null)
      quizPauseTimeRef.current = 0
    }, [])

    const handleSelectionSubmit = useCallback((answers: Record<string, string>) => {
      if (!activeSelection) return
      onSelectionSubmit?.(activeSelection, answers)
    }, [activeSelection, onSelectionSubmit])

    const handleSelectionContinue = useCallback((isCorrect: boolean) => {
      if (!videoRef.current || !activeSelection) return
      
      answeredIdsRef.current.add(activeSelection.id)
      setIsSelectionModalOpen(false)
      const interactionId = activeSelection.id
      setActiveSelection(null)
      
      if (isCorrect === true) {
        const resumeTime = selectionPauseTimeRef.current > 0 ? selectionPauseTimeRef.current : videoRef.current.currentTime
        const interaction = interactions.find(i => i.id === interactionId && i.type === 'selection') as SelectionInteraction | undefined
        const endTime = interaction?.endTime || resumeTime
        const skipTime = Math.max(resumeTime, endTime + 0.5)
        videoRef.current.currentTime = skipTime
        videoRef.current.play().catch(e => {
          console.error('Failed to resume video:', e)
          setTimeout(() => {
            videoRef.current?.play().catch(err => console.error('Retry failed:', err))
          }, 200)
        })
      } else if (isCorrect === false) {
        const sortedInteractions = [...interactions].sort((a, b) => a.startTime - b.startTime)
        const currentInteraction = sortedInteractions.find(i => i.id === interactionId)
        const currentIndex = currentInteraction ? sortedInteractions.indexOf(currentInteraction) : -1
        let previousInteraction = null
        if (currentIndex > 0) {
          previousInteraction = sortedInteractions[currentIndex - 1]
        }
        answeredIdsRef.current.delete(interactionId)
        
        if (previousInteraction) {
          const jumpTime = previousInteraction.endTime + 1
          videoRef.current.currentTime = jumpTime
        } else {
          videoRef.current.currentTime = 0
        }
        
        videoRef.current.play().catch(e => {
          console.error('Failed to resume video:', e)
          setTimeout(() => {
            videoRef.current?.play().catch(err => console.error('Retry failed:', err))
          }, 200)
        })
      }
      
      selectionPauseTimeRef.current = 0
    }, [activeSelection, interactions])

    const handleSelectionClose = useCallback(() => {
      setIsSelectionModalOpen(false)
      setActiveSelection(null)
      selectionPauseTimeRef.current = 0
    }, [])

    const triggerQuiz = useCallback((quizId?: string) => {
      const quizToShow = quizId 
        ? interactions.find(i => i.id === quizId && i.type === 'quiz') as QuizInteraction | undefined
        : interactions.find(i => i.type === 'quiz') as QuizInteraction | undefined
      
      if (quizToShow) {
        setActiveQuiz(quizToShow)
        setIsQuizModalOpen(true)
        if (videoRef.current && !videoRef.current.paused) {
          videoRef.current.pause()
        }
      }
    }, [interactions])

    useImperativeHandle(ref, () => ({
      triggerQuiz,
      getDuration: () => videoState.duration,
      getCurrentTime: () => videoState.currentTime,
      videoRef
    }), [videoState.duration, videoState.currentTime, triggerQuiz])

    const toggleFullscreen = useCallback(async () => {
      if (!containerRef.current) return

      try {
        if (!document.fullscreenElement) {
          await containerRef.current.requestFullscreen()
        } else {
          await document.exitFullscreen()
        }
      } catch (error) {
        console.error('Error toggling fullscreen:', error)
      }
    }, [])

    useEffect(() => {
      const handleFullscreenChange = () => {
        setIsFullscreen(!!document.fullscreenElement)
      }

      document.addEventListener('fullscreenchange', handleFullscreenChange)
      setIsFullscreen(!!document.fullscreenElement)
      startControlsTimer()

      return () => {
        document.removeEventListener('fullscreenchange', handleFullscreenChange)
        if (controlsTimerRef.current) clearTimeout(controlsTimerRef.current)
      }
    }, [startControlsTimer])

    // Watch for video source changes
    useEffect(() => {
      if (videoRef.current && videoSrc) {
        videoRef.current.load()
      }
    }, [videoSrc])

    // Watch for interactions changes
    useEffect(() => {
      if (videoRef.current && videoRef.current.paused) {
        handleTimeUpdate()
      }
    }, [interactions, handleTimeUpdate])

    return (
      <div ref={containerRef} className="relative w-full aspect-video bg-black rounded-lg overflow-hidden">
        <video
          ref={videoRef}
          className="w-full h-full object-contain"
          preload="auto"
          aria-label="Interactive educational video with quizzes"
          aria-describedby="video-description"
          onTimeUpdate={handleTimeUpdate}
          onLoadedMetadata={handleLoadedMetadata}
          onClick={handleVideoClick}
          onPlay={handlePlay}
          onPause={handlePause}
          onMouseEnter={resetControlsTimer}
          onMouseMove={resetControlsTimer}
          onMouseLeave={startControlsTimer}
          onContextMenu={(e) => e.preventDefault()}
          crossOrigin="use-credentials"
        >
          <source src={videoSrc} type="video/mp4" />
          Your browser does not support the video tag.
        </video>
        <div id="video-description" className="sr-only">
          Interactive video player with embedded quizzes. Quizzes will appear at specific timestamps during playback.
        </div>

        {/* Play/Pause Button Overlay */}
        {!videoState.isPlaying && (
          <button
            className="absolute inset-0 flex items-center justify-center bg-black/40 hover:bg-black/50 transition-all duration-300 z-20 group"
            onClick={handleVideoClick}
            aria-label="Play video"
          >
            <div className="relative">
              <div className="absolute inset-0 bg-white/20 rounded-full animate-ping opacity-75" />
              <div className="relative w-20 h-20 bg-white/90 rounded-full flex items-center justify-center shadow-2xl transform group-hover:scale-110 transition-transform duration-300">
                <svg className="w-10 h-10 text-primary ml-1" fill="currentColor" viewBox="0 0 24 24">
                  <path d="M8 5v14l11-7z"/>
                </svg>
              </div>
            </div>
          </button>
        )}

        {/* Timeline Controls */}
        <div 
          className={`absolute bottom-0 left-0 right-0 bg-gradient-to-t from-black/90 via-black/70 to-transparent p-4 backdrop-blur-sm z-40 transition-opacity duration-300 ${
            showControls || isQuizModalOpen || isSelectionModalOpen ? 'opacity-100' : 'opacity-0'
          }`}
          role="toolbar"
          aria-label="Video player controls"
          onMouseEnter={resetControlsTimer}
          onMouseLeave={startControlsTimer}
        >
          <div className="flex items-center gap-3">
            {/* Play/Pause Button */}
            <button
              className="flex-shrink-0 p-2.5 text-white hover:bg-white/25 rounded-full focus:outline-none focus:ring-2 focus:ring-white/50 transition-all duration-200 backdrop-blur-sm bg-white/10"
              aria-label={videoState.isPlaying ? 'Pause video' : 'Play video'}
              aria-pressed={videoState.isPlaying}
              onClick={handleVideoClick}
            >
              {!videoState.isPlaying ? (
                <svg className="w-5 h-5" fill="currentColor" viewBox="0 0 24 24">
                  <path d="M8 5v14l11-7z"/>
                </svg>
              ) : (
                <svg className="w-5 h-5" fill="currentColor" viewBox="0 0 24 24">
                  <path d="M6 4h4v16H6V4zm8 0h4v16h-4V4z"/>
                </svg>
              )}
            </button>
            
            {/* Time Display */}
            <span className="text-white text-sm font-mono min-w-[45px]" aria-label="Current time">
              {formatTime(videoState.currentTime)}
            </span>
            
            {/* Progress Bar */}
            <div 
              className="flex-1 min-w-0" 
              role="progressbar" 
              aria-valuenow={videoState.currentTime} 
              aria-valuemin={0} 
              aria-valuemax={videoState.duration} 
              aria-label={`Video progress: ${Math.round((videoState.currentTime / videoState.duration) * 100)}%`}
            >
              <VideoTimeline
                currentTime={videoState.currentTime || 0}
                duration={videoState.duration || 0}
                markers={videoState.timelineMarkers || []}
                onSeek={handleSeek}
              />
            </div>
            
            <span className="text-white text-sm font-mono min-w-[45px] text-right" aria-label="Total duration">
              {formatTime(videoState.duration)}
            </span>
            
            {/* Fullscreen Button */}
            <button
              className="flex-shrink-0 p-2.5 text-white hover:bg-white/25 rounded-full focus:outline-none focus:ring-2 focus:ring-white/50 transition-all duration-200 backdrop-blur-sm bg-white/10"
              aria-label={isFullscreen ? 'Exit fullscreen mode' : 'Enter fullscreen mode'}
              aria-pressed={isFullscreen}
              onClick={toggleFullscreen}
            >
              {!isFullscreen ? (
                <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M4 8V4m0 0h4M4 4l5 5m11-1V4m0 0h-4m4 0l-5 5M4 16v4m0 0h4m-4 0l5-5m11 5l-5-5m5 5v-4m0 4h-4" />
                </svg>
              ) : (
                <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M9 9V4.5M9 9H4.5M9 9L3.75 3.75M9 15v4.5M9 15H4.5M9 15l-5.25 5.25M15 9h4.5M15 9V4.5M15 9l5.25-5.25M15 15h4.5M15 15v4.5m0-4.5l5.25 5.25" />
                </svg>
              )}
            </button>
          </div>
        </div>

        {/* Quiz Modal */}
        {activeQuiz && isQuizModalOpen && (
          <QuizModal
            quiz={activeQuiz}
            isOpen={isQuizModalOpen}
            isFullscreen={isFullscreen}
            onSubmit={handleQuizSubmit}
            onContinue={handleQuizContinue}
            onClose={handleQuizClose}
          />
        )}
        
        {/* Selection Modal */}
        {activeSelection && isSelectionModalOpen && (
          <SelectionModal
            interaction={activeSelection}
            isOpen={isSelectionModalOpen}
            isFullscreen={isFullscreen}
            onSubmit={handleSelectionSubmit}
            onContinue={handleSelectionContinue}
            onClose={handleSelectionClose}
          />
        )}
      </div>
    )
  }
)

InteractiveVideo.displayName = 'InteractiveVideo'

export default InteractiveVideo

// app/components/interactive/InteractiveVideo.vue
<template>
  <ClientOnly>
    <div ref="containerRef" class="relative w-full aspect-video bg-black rounded-lg overflow-hidden">
      <video
        ref="videoRef"
        class="w-full h-full object-contain"
        preload="auto"
        aria-label="Interactive educational video with quizzes"
        aria-describedby="video-description"
        @timeupdate="handleTimeUpdate"
        @loadedmetadata="handleLoadedMetadata"
        @click="handleVideoClick"
        @play="handlePlay"
        @pause="handlePause"
        @mouseenter="showControls = true"
        @mousemove="resetControlsTimer"
        @mouseleave="startControlsTimer"
        @error="handleVideoError"
        @loadstart="handleLoadStart"
        @contextmenu.prevent
        crossorigin="use-credentials"
      >
        <source :src="videoSrc" type="video/mp4" />
        Your browser does not support the video tag.
      </video>
      <div id="video-description" class="sr-only">
        Interactive video player with embedded quizzes. Quizzes will appear at specific timestamps during playback.
      </div>


      <!-- Enhanced Play/Pause Button Overlay -->
      <button
        v-if="!videoState.isPlaying.value"
        class="absolute inset-0 flex items-center justify-center bg-black/40 hover:bg-black/50 transition-all duration-300 z-20 group"
        @click="handleVideoClick"
        aria-label="Play video"
      >
        <div class="relative">
          <div class="absolute inset-0 bg-white/20 rounded-full animate-ping opacity-75"></div>
          <div class="relative w-20 h-20 bg-white/90 rounded-full flex items-center justify-center shadow-2xl transform group-hover:scale-110 transition-transform duration-300">
            <svg class="w-10 h-10 text-primary ml-1" fill="currentColor" viewBox="0 0 24 24">
              <path d="M8 5v14l11-7z"/>
            </svg>
          </div>
        </div>
      </button>

      <!-- Enhanced Timeline Controls -->
      <div 
        class="absolute bottom-0 left-0 right-0 bg-gradient-to-t from-black/90 via-black/70 to-transparent p-4 backdrop-blur-sm z-40 transition-opacity duration-300"
        :class="showControls || isQuizModalOpen ? 'opacity-100' : 'opacity-0'"
        role="toolbar"
        aria-label="Video player controls"
        @mouseenter="showControls = true"
        @mouseleave="startControlsTimer"
      >
        <div class="flex items-center gap-3">
          <!-- Play/Pause Button -->
          <button
            class="flex-shrink-0 p-2.5 text-white hover:bg-white/25 rounded-full focus:outline-none focus:ring-2 focus:ring-white/50 transition-all duration-200 backdrop-blur-sm bg-white/10"
            :aria-label="videoState.isPlaying.value ? 'Pause video' : 'Play video'"
            :aria-pressed="videoState.isPlaying.value"
            @click="handleVideoClick"
          >
            <svg
              v-if="!videoState.isPlaying.value"
              class="w-5 h-5"
              fill="currentColor"
              viewBox="0 0 24 24"
            >
              <path d="M8 5v14l11-7z"/>
            </svg>
            <svg
              v-else
              class="w-5 h-5"
              fill="currentColor"
              viewBox="0 0 24 24"
            >
              <path d="M6 4h4v16H6V4zm8 0h4v16h-4V4z"/>
            </svg>
          </button>
          
          <!-- Time Display -->
          <!-- <span class="text-white text-sm font-mono min-w-[45px]" aria-label="Current time">
            {{ formatTime(videoState.currentTime.value) }}
          </span> -->
          
          <!-- Progress Bar -->
          <div class="flex-1 min-w-0" role="progressbar" :aria-valuenow="videoState.currentTime.value" :aria-valuemin="0" :aria-valuemax="videoState.duration.value" :aria-label="`Video progress: ${Math.round((videoState.currentTime.value / videoState.duration.value) * 100)}%`">
            <VideoTimeline
              :current-time="videoState.currentTime.value || 0"
              :duration="videoState.duration.value || 0"
              :markers="[...(videoState.timelineMarkers.value || [])]"
              @seek="handleSeek"
            />
          </div>
          
          <!-- <span class="text-white text-sm font-mono min-w-[45px] text-right" aria-label="Total duration">
            {{ formatTime(videoState.duration.value) }}
          </span>
           -->
          <!-- Fullscreen Button -->
          <button
            class="flex-shrink-0 p-2.5 text-white hover:bg-white/25 rounded-full focus:outline-none focus:ring-2 focus:ring-white/50 transition-all duration-200 backdrop-blur-sm bg-white/10"
            :aria-label="isFullscreen ? 'Exit fullscreen mode' : 'Enter fullscreen mode'"
            :aria-pressed="isFullscreen"
            @click="toggleFullscreen"
          >
            <svg
              v-if="!isFullscreen"
              class="w-5 h-5"
              fill="none"
              stroke="currentColor"
              viewBox="0 0 24 24"
            >
              <path
                stroke-linecap="round"
                stroke-linejoin="round"
                stroke-width="2"
                d="M4 8V4m0 0h4M4 4l5 5m11-1V4m0 0h-4m4 0l-5 5M4 16v4m0 0h4m-4 0l5-5m11 5l-5-5m5 5v-4m0 4h-4"
              />
            </svg>
            <svg
              v-else
              class="w-5 h-5"
              fill="none"
              stroke="currentColor"
              viewBox="0 0 24 24"
            >
              <path
                stroke-linecap="round"
                stroke-linejoin="round"
                stroke-width="2"
                d="M9 9V4.5M9 9H4.5M9 9L3.75 3.75M9 15v4.5M9 15H4.5M9 15l-5.25 5.25M15 9h4.5M15 9V4.5M15 9l5.25-5.25M15 15h4.5M15 15v4.5m0-4.5l5.25 5.25"
              />
            </svg>
          </button>
        </div>
      </div>

      <!-- Quiz Modal - Positioned within video container -->
      <QuizModal
        v-if="activeQuiz && isQuizModalOpen"
        :quiz="activeQuiz"
        :is-open="isQuizModalOpen"
        :is-fullscreen="isFullscreen"
        @submit="handleQuizSubmit"
        @continue="handleQuizContinue"
        @close="handleQuizClose"
      />
      
      <!-- Selection Modal -->
      <SelectionModal
        v-if="activeSelection && isSelectionModalOpen"
        :interaction="activeSelection"
        :is-open="isSelectionModalOpen"
        :is-fullscreen="isFullscreen"
        @submit="handleSelectionSubmit"
        @continue="handleSelectionContinue"
        @close="handleSelectionClose"
      />
    </div>
  </ClientOnly>
</template>

<script setup lang="ts">
import { ref, computed, watch, onMounted, onUnmounted, nextTick } from 'vue'
import { useInteractiveVideo } from '~/composable/useInteractiveVideo'
import VideoTimeline from '~/components/interactive/VideoTimeline.vue'
import QuizModal from '~/components/interactive/QuizModal.vue'
import SelectionModal from '~/components/interactive/SelectionModal.vue'
import type { Interaction, QuizInteraction, SelectionInteraction } from '~/types/interactive-video.interface'

interface Props {
  videoSrc: string
  interactions: Interaction[]
}

const props = defineProps<Props>()

const emit = defineEmits<{
  quizSubmit: [interaction: QuizInteraction, answer: string]
  selectionSubmit: [interaction: SelectionInteraction, answers: Record<string, string>]
}>()

const videoRef = ref<HTMLVideoElement | null>(null)
const containerRef = ref<HTMLDivElement | null>(null)
const videoState = useInteractiveVideo(props.interactions)
const activeQuiz = ref<QuizInteraction | null>(null)
const isQuizModalOpen = ref(false)
const activeSelection = ref<SelectionInteraction | null>(null)
const isSelectionModalOpen = ref(false)
const isFullscreen = ref(false)
const showControls = ref(true)
let controlsTimer: ReturnType<typeof setTimeout> | null = null

const formatTime = (seconds: number): string => {
  if (isNaN(seconds) || !isFinite(seconds)) return '0:00'
  const mins = Math.floor(seconds / 60)
  const secs = Math.floor(seconds % 60)
  return `${mins}:${secs.toString().padStart(2, '0')}`
}

const resetControlsTimer = () => {
  showControls.value = true
  startControlsTimer()
}

const startControlsTimer = () => {
  if (controlsTimer) clearTimeout(controlsTimer)
  if (!isQuizModalOpen.value && !isSelectionModalOpen.value) {
    controlsTimer = setTimeout(() => {
      if (!videoRef.value?.paused) {
        showControls.value = false
      }
    }, 3000)
  }
}


const handleTimeUpdate = () => {
  if (!videoRef.value) return
  const currentTime = videoRef.value.currentTime
  videoState.updateTime(currentTime)

  // Threshold for detecting interactions (since startTime === endTime, we need a small window)
  const INTERACTION_THRESHOLD = 0.5 // seconds

  // Check for quiz interactions - find any quiz that should be active now
  // Since interactions appear when paused at a specific time, we check if we're at or near that time
  const quizInteraction = props.interactions.find(
    (interaction) => 
      interaction.type === 'quiz' && 
      !answeredQuizIds.value.has(interaction.id) && // Don't show already answered quizzes
      Math.abs(currentTime - interaction.startTime) <= INTERACTION_THRESHOLD // Within threshold of interaction time
  ) as QuizInteraction | undefined

  // Show quiz if we're at the interaction time and modal isn't already open
  if (quizInteraction && !isQuizModalOpen.value && activeQuiz.value?.id !== quizInteraction.id) {
    console.log('Quiz detected at time:', currentTime, 'Quiz:', quizInteraction)
    activeQuiz.value = quizInteraction
    isQuizModalOpen.value = true
    // Store the current time when quiz appears (before pausing)
    if (videoRef.value) {
      quizPauseTime.value = videoRef.value.currentTime
      console.log('Stored quiz pause time:', quizPauseTime.value)
      if (!videoRef.value.paused) {
        videoRef.value.pause()
      }
    }
  }
  
  // Hide quiz if we've moved away from the interaction time
  if (activeQuiz.value && !quizInteraction) {
    const timeDiff = Math.abs(currentTime - activeQuiz.value.startTime)
    if (timeDiff > INTERACTION_THRESHOLD) {
      console.log('Hiding quiz, moved away from interaction time')
      isQuizModalOpen.value = false
      activeQuiz.value = null
    }
  }

  // Check for selection interactions
  const selectionInteraction = props.interactions.find(
    (interaction) => 
      interaction.type === 'selection' && 
      !answeredQuizIds.value.has(interaction.id) && // Don't show already answered interactions
      Math.abs(currentTime - interaction.startTime) <= INTERACTION_THRESHOLD // Within threshold of interaction time
  ) as SelectionInteraction | undefined

  // Show selection if we're at the interaction time and modal isn't already open
  if (selectionInteraction && !isSelectionModalOpen.value && activeSelection.value?.id !== selectionInteraction.id) {
    console.log('Selection detected at time:', currentTime, 'Interaction:', selectionInteraction)
    activeSelection.value = selectionInteraction
    isSelectionModalOpen.value = true
    // Store the current time when interaction appears (before pausing)
    if (videoRef.value) {
      selectionPauseTime.value = videoRef.value.currentTime
      console.log('Stored selection pause time:', selectionPauseTime.value)
      if (!videoRef.value.paused) {
        videoRef.value.pause()
      }
    }
  }
  
  // Hide selection if we've moved away from the interaction time
  if (activeSelection.value && !selectionInteraction) {
    const timeDiff = Math.abs(currentTime - activeSelection.value.startTime)
    if (timeDiff > INTERACTION_THRESHOLD) {
      console.log('Hiding selection, moved away from interaction time')
      isSelectionModalOpen.value = false
      activeSelection.value = null
    }
  }
}

const handleLoadedMetadata = () => {
  if (!videoRef.value) return
  videoState.setDuration(videoRef.value.duration)
  
  // Check if we should show a quiz at the start
  const initialQuiz = videoState.activeInteractions.value.find(
    (interaction) => interaction.type === 'quiz' && interaction.startTime === 0
  ) as QuizInteraction | undefined
  
  if (initialQuiz && !isQuizModalOpen.value) {
    activeQuiz.value = initialQuiz
    isQuizModalOpen.value = true
    if (videoRef.value) {
      videoRef.value.pause()
    }
  }
}

const handleVideoClick = () => {
  if (!videoRef.value) return
  videoState.togglePlay(videoRef.value)
}

const handlePlay = () => {
  if (videoState && videoState.setIsPlaying) {
    videoState.setIsPlaying(true)
  }
}

const handlePause = () => {
  if (videoState && videoState.setIsPlaying) {
    videoState.setIsPlaying(false)
  }
  // When video is paused, check if we're at an interaction time
  if (videoRef.value) {
    // Use nextTick to ensure currentTime is updated
    nextTick(() => {
      handleTimeUpdate()
    })
  }
}

const handleLoadStart = () => {
  console.log('Video load started. Source:', props.videoSrc)
}

const handleVideoError = (event: Event) => {
  const video = event.target as HTMLVideoElement
  const error = video.error
  console.error('Video error:', {
    code: error?.code,
    message: error?.message,
    source: props.videoSrc,
    networkState: video.networkState,
    readyState: video.readyState
  })
  
  if (error) {
    let errorMessage = 'Failed to load video'
    switch (error.code) {
      case 1: // MEDIA_ERR_ABORTED
        errorMessage = 'Video loading was aborted'
        break
      case 2: // MEDIA_ERR_NETWORK
        errorMessage = 'Network error while loading video. Check authentication and network connection.'
        break
      case 3: // MEDIA_ERR_DECODE
        errorMessage = 'Error decoding video'
        break
      case 4: // MEDIA_ERR_SRC_NOT_SUPPORTED
        errorMessage = 'Video format not supported'
        break
    }
    console.error('Video error details:', errorMessage)
  }
}

// Watch for video source changes and reload
watch(() => props.videoSrc, (newSrc, oldSrc) => {
  if (newSrc && newSrc !== oldSrc && videoRef.value) {
    console.log('Video source changed from', oldSrc, 'to', newSrc)
    videoRef.value.load() // Force reload
  }
}, { immediate: false })

// Watch for interactions changes and check if we should show any at current time
watch(() => props.interactions, (newInteractions) => {
  console.log('Interactions updated:', newInteractions.length)
  // If video is paused, check if we're at an interaction time
  if (videoRef.value && videoRef.value.paused) {
    handleTimeUpdate()
  }
}, { deep: true })

const handleSeek = (time: number) => {
  if (!videoRef.value) return
  videoState.seekTo(time, videoRef.value)
  // After seeking, check if we're at an interaction time
  nextTick(() => {
    handleTimeUpdate()
  })
}


const quizAnswerCorrect = ref<boolean | null>(null)
const quizPauseTime = ref<number>(0)
const answeredQuizIds = ref<Set<string>>(new Set())

const handleQuizSubmit = (answer: string, isCorrect: boolean) => {
  if (!activeQuiz.value) return
  
  // Store if answer was correct
  quizAnswerCorrect.value = isCorrect
  
  emit('quizSubmit', activeQuiz.value, answer)
}

const handleQuizContinue = (isCorrect: boolean) => {
  console.log('handleQuizContinue called with isCorrect:', isCorrect, 'quizPauseTime:', quizPauseTime.value)
  
  if (!videoRef.value || !activeQuiz.value) {
    console.error('Video ref or active quiz is null in handleQuizContinue')
    return
  }
  
  // Mark this quiz as answered so it won't show again
  answeredQuizIds.value.add(activeQuiz.value.id)
  console.log('Marked quiz as answered:', activeQuiz.value.id)
  
  // Close the quiz modal first
  isQuizModalOpen.value = false
  const quizId = activeQuiz.value.id
  activeQuiz.value = null
  
  // Handle video playback based on answer correctness when user clicks Continue
  if (isCorrect === true) {
    // Correct answer: resume from where it was paused, but skip past the quiz time range
    console.log('Resuming video from:', quizPauseTime.value)
    const resumeTime = quizPauseTime.value > 0 ? quizPauseTime.value : videoRef.value.currentTime
    
    // Find the quiz interaction to get its end time
    const quizInteraction = props.interactions.find(i => i.id === quizId && i.type === 'quiz') as QuizInteraction | undefined
    const quizEndTime = quizInteraction?.endTime || resumeTime
    
    // Skip to just after the quiz time range to prevent it from showing again
    const skipTime = Math.max(resumeTime, quizEndTime + 0.5)
    videoRef.value.currentTime = skipTime
    console.log('Skipping to time:', skipTime, 'to avoid quiz time range')
    
    videoRef.value.play().catch(e => {
      console.error('Failed to resume video:', e)
      // Try again after a short delay
      setTimeout(() => {
        videoRef.value?.play().catch(err => console.error('Retry failed:', err))
      }, 200)
    })
  } else if (isCorrect === false) {
    // Incorrect answer: go back to just after the previous interaction's end time + 1 second
    console.log('Incorrect answer - finding previous interaction')
    
    // Sort all interactions by startTime to find the previous one
    const sortedInteractions = [...props.interactions].sort((a, b) => a.startTime - b.startTime)
    
    // Find the current quiz interaction
    const currentInteraction = sortedInteractions.find(i => i.id === quizId)
    const currentIndex = currentInteraction ? sortedInteractions.indexOf(currentInteraction) : -1
    
    // Find the previous interaction (before the current one)
    let previousInteraction = null
    if (currentIndex > 0) {
      previousInteraction = sortedInteractions[currentIndex - 1]
    }
    
    // Remove the quiz from answered list so it can show again
    answeredQuizIds.value.delete(quizId)
    
    if (previousInteraction) {
      // Jump to previous interaction's end time + 1 second
      const jumpTime = previousInteraction.endTime + 1
      console.log('Jumping to previous interaction end time + 1s:', jumpTime, 'Previous interaction:', previousInteraction.id)
      videoRef.value.currentTime = jumpTime
    } else {
      // If no previous interaction, restart from beginning
      console.log('No previous interaction found - restarting from beginning')
      videoRef.value.currentTime = 0
    }
    
    videoRef.value.play().catch(e => {
      console.error('Failed to resume video:', e)
      // Try again after a short delay
      setTimeout(() => {
        videoRef.value?.play().catch(err => console.error('Retry failed:', err))
      }, 200)
    })
  }
  
  // Reset quiz answer state
  quizAnswerCorrect.value = null
  quizPauseTime.value = 0
}

const handleQuizClose = () => {
  isQuizModalOpen.value = false
  activeQuiz.value = null
  
  // Reset quiz answer state
  quizAnswerCorrect.value = null
  quizPauseTime.value = 0
}

const selectionPauseTime = ref<number>(0)

const handleSelectionSubmit = (answers: Record<string, string>) => {
  if (!activeSelection.value) return
  console.log('Selection submitted with answers:', answers)
  emit('selectionSubmit', activeSelection.value, answers)
}

const handleSelectionContinue = (isCorrect: boolean) => {
  console.log('handleSelectionContinue called with isCorrect:', isCorrect, 'pauseTime:', selectionPauseTime.value)
  
  if (!videoRef.value || !activeSelection.value) {
    console.error('Video ref or active selection is null')
    return
  }
  
  // Mark this interaction as answered so it won't show again
  answeredQuizIds.value.add(activeSelection.value.id)
  console.log('Marked selection as answered:', activeSelection.value.id)
  
  // Close the modal first
  isSelectionModalOpen.value = false
  const interactionId = activeSelection.value.id
  activeSelection.value = null
  
  // Handle video playback based on answer correctness
  if (isCorrect === true) {
    // Correct answer: resume from where it was paused, but skip past the interaction time range
    console.log('Resuming video from:', selectionPauseTime.value)
    const resumeTime = selectionPauseTime.value > 0 ? selectionPauseTime.value : videoRef.value.currentTime
    
    // Find the interaction to get its end time
    const interaction = props.interactions.find(i => i.id === interactionId && i.type === 'selection') as SelectionInteraction | undefined
    const endTime = interaction?.endTime || resumeTime
    
    // Skip to just after the interaction time range
    const skipTime = Math.max(resumeTime, endTime + 0.5)
    videoRef.value.currentTime = skipTime
    console.log('Skipping to time:', skipTime)
    
    videoRef.value.play().catch(e => {
      console.error('Failed to resume video:', e)
      setTimeout(() => {
        videoRef.value?.play().catch(err => console.error('Retry failed:', err))
      }, 200)
    })
  } else if (isCorrect === false) {
    // Incorrect answer: go back to just after the previous interaction's end time + 1 second
    console.log('Incorrect answer - finding previous interaction')
    
    // Sort all interactions by startTime to find the previous one
    const sortedInteractions = [...props.interactions].sort((a, b) => a.startTime - b.startTime)
    
    // Find the current selection interaction
    const currentInteraction = sortedInteractions.find(i => i.id === interactionId)
    const currentIndex = currentInteraction ? sortedInteractions.indexOf(currentInteraction) : -1
    
    // Find the previous interaction (before the current one)
    let previousInteraction = null
    if (currentIndex > 0) {
      previousInteraction = sortedInteractions[currentIndex - 1]
    }
    
    // Remove the interaction from answered list so it can show again
    answeredQuizIds.value.delete(interactionId)
    
    if (previousInteraction) {
      // Jump to previous interaction's end time + 1 second
      const jumpTime = previousInteraction.endTime + 1
      console.log('Jumping to previous interaction end time + 1s:', jumpTime, 'Previous interaction:', previousInteraction.id)
      videoRef.value.currentTime = jumpTime
    } else {
      // If no previous interaction, restart from beginning
      console.log('No previous interaction found - restarting from beginning')
      videoRef.value.currentTime = 0
    }
    
    videoRef.value.play().catch(e => {
      console.error('Failed to resume video:', e)
      setTimeout(() => {
        videoRef.value?.play().catch(err => console.error('Retry failed:', err))
      }, 200)
    })
  }
  
  selectionPauseTime.value = 0
}

const handleSelectionClose = () => {
  isSelectionModalOpen.value = false
  activeSelection.value = null
  selectionPauseTime.value = 0
}

// Expose method to manually trigger quiz (for testing)
const triggerQuiz = (quizId?: string) => {
  console.log('triggerQuiz called with quizId:', quizId)
  console.log('Available interactions:', props.interactions)
  const quizToShow = quizId 
    ? props.interactions.find(i => i.id === quizId && i.type === 'quiz') as QuizInteraction | undefined
    : props.interactions.find(i => i.type === 'quiz') as QuizInteraction | undefined
  
  if (quizToShow) {
    console.log('Manually triggering quiz:', quizToShow)
    activeQuiz.value = quizToShow
    isQuizModalOpen.value = true
    console.log('Quiz state - activeQuiz:', activeQuiz.value, 'isOpen:', isQuizModalOpen.value)
    if (videoRef.value && !videoRef.value.paused) {
      videoRef.value.pause()
    }
  } else {
    console.warn('No quiz found to trigger. Available interactions:', props.interactions)
  }
}

// Expose methods and properties for parent component
defineExpose({
  triggerQuiz,
  videoRef,
  getDuration: () => videoState.duration.value,
  getCurrentTime: () => videoState.currentTime.value,
  videoState
})

const toggleFullscreen = async () => {
  if (!containerRef.value) return

  try {
    if (!document.fullscreenElement) {
      await containerRef.value.requestFullscreen()
    } else {
      await document.exitFullscreen()
    }
  } catch (error) {
    console.error('Error toggling fullscreen:', error)
  }
}

const handleFullscreenChange = () => {
  isFullscreen.value = !!document.fullscreenElement
}

onMounted(() => {
  document.addEventListener('fullscreenchange', handleFullscreenChange)
  isFullscreen.value = !!document.fullscreenElement
  startControlsTimer()
})

onUnmounted(() => {
  document.removeEventListener('fullscreenchange', handleFullscreenChange)
  if (controlsTimer) clearTimeout(controlsTimer)
})
</script>
