// app/components/primary-sources/activities/comprehension-junior.vue
<script setup lang="ts">
import { computed, ref, watch } from "vue";
import { Button } from "@/components/ui/button";
import { cn, shuffle } from "@/lib/utils";
import Input from "@/components/ui/inputs/input.vue";
import ActivityTitle from "@/components/templates/activity-title";
import type { FeedbackType } from "@/lib/types/activity-types";
import { AnswerChecker } from "@/lib/utils/answer-checker";
import LeftNotesWithImages from "@/components/templates/left-notes-with-images";
import { useSoundEffects } from "~/composables/use-sound-effects";
import { Icon } from "@iconify/vue";
import ActivityResults, {
  ActivityResultsAlertDialog,
} from "@/components/templates/results";

type ComprehensionQuestion = {
  question: string;
  image?: string;
  answers: string[];
  acceptedAnswers?: string[];
  options: {
    id: string;
    text: string;
  }[];
};

type Props = {
  questions: {
    notes: string;
    title: string;
    image?: string;
    optionsTitle?: string;
    useAI?: boolean;
    algorithm: "Comprehension junior one" | "Comprehension junior two";
    questions: ComprehensionQuestion[];
  };
  feedback?: FeedbackType;
};

const props = withDefaults(defineProps<Props>(), {
  feedback: "wrong-correct",
});

const ui = useActivityUiText();
const answerChecker = new AnswerChecker();
const { playSound } = useSoundEffects();

const score = ref(0);
const allAnswered = ref(false);
const showResults = ref(false);
const activeQuestion = ref(0);
const shuffledIndexes = ref<number[]>([]);
const currentAnswers = ref<string[]>([]);
const attemptedQuestions = ref<Record<number, string[]>>({});
const correctAnswers = ref<Record<number, boolean>>({});
const isCheckingAnswers = ref(false);
const allUserAnswers = ref<Record<number, string[]>>({});

const shouldUseBatchAI = computed(
  () =>
    props.questions.algorithm === "Comprehension junior one" &&
    !!props.questions.useAI,
);
const currentQuestion = computed(
  () =>
    props.questions.questions[shuffledIndexes.value[activeQuestion.value] ?? 0],
);

const ensureAttemptedAnswerSlots = (questionIndex: number) => {
  const originalIndex = shuffledIndexes.value[questionIndex] ?? 0;
  const answerCount =
    props.questions.questions[originalIndex]?.answers.length || 1;
  return (
    attemptedQuestions.value[questionIndex] ||
    Array.from({ length: answerCount }, () => "")
  );
};

const ensureUserAnswerSlots = (questionIndex: number) => {
  const originalIndex = shuffledIndexes.value[questionIndex] ?? 0;
  const answerCount =
    props.questions.questions[originalIndex]?.answers.length || 1;
  return (
    allUserAnswers.value[questionIndex] ||
    Array.from({ length: answerCount }, () => "")
  );
};

const initializeActivity = () => {
  const indexes = shuffle(
    Array.from(
      { length: props.questions.questions.length },
      (_, index) => index,
    ),
  );
  shuffledIndexes.value = indexes;
  activeQuestion.value = 0;
  attemptedQuestions.value = {};
  correctAnswers.value = {};
  allUserAnswers.value = {};
  score.value = 0;
  allAnswered.value = false;
  showResults.value = false;
  currentAnswers.value = indexes.length
    ? Array.from(
        { length: props.questions.questions[indexes[0]]?.answers.length || 1 },
        () => "",
      )
    : [];
};

watch(() => props.questions, initializeActivity, {
  deep: true,
  immediate: true,
});

const setAnswer = (answerIndex: number, value: string | number) => {
  const nextAnswers = [...currentAnswers.value];
  nextAnswers[answerIndex] = String(value ?? "");
  currentAnswers.value = nextAnswers;
};

const isQuestionCorrect = async (
  questionIndex: number,
  userAnswers: string[],
) => {
  const originalIndex = shuffledIndexes.value[questionIndex];
  const question = props.questions.questions[originalIndex as number];

  if (!question) return false;

  if (shouldUseBatchAI.value) {
    try {
      const submissions = userAnswers.map((answer, answerIndex) => ({
        questionId: `${originalIndex}-${answerIndex}`,
        answer: answer.trim(),
      }));

      const aiQuestions = userAnswers.map((_, answerIndex) => ({
        id: `${originalIndex}-${answerIndex}`,
        question: question.question,
        acceptedAnswers: question.answers[answerIndex]
          ? [question.answers[answerIndex]]
          : [],
        strictMode: false,
        maxMarks: 1,
        questionType: "reasoning" as const,
        context: {
          notes: props.questions.notes,
          title: props.questions.title,
          questionText: question.question,
          image: question.image || props.questions.image,
        },
        evaluationCriteria:
          "Evaluate based on comprehension of the provided text/context and semantic similarity to the accepted answer.",
      }));

      const results = await answerChecker.checkAnswersWithAI(
        submissions,
        aiQuestions,
      );
      return results.every((result) => result.result.isCorrect);
    } catch {
      return userAnswers.every((answer) =>
        answerChecker.checkAnswer(answer, {
          acceptedAnswers: question.answers,
        }).isCorrect,
      );
    }
  }

  if (props.questions.algorithm === "Comprehension junior one") {
    return userAnswers.every(
      (answer) =>
        answerChecker.checkAnswer(answer, {
          acceptedAnswers: question.answers,
        }).isCorrect,
    );
  }

  return userAnswers.every(
    (answer, index) =>
      answer.trim().toLowerCase() ===
      (question.answers[index] || "").trim().toLowerCase(),
  );
};

const loadQuestionAnswers = (questionIndex: number) => {
  currentAnswers.value = shouldUseBatchAI.value
    ? [...ensureUserAnswerSlots(questionIndex)]
    : [...ensureAttemptedAnswerSlots(questionIndex)];
};

const advanceToNextQuestion = () => {
  if (activeQuestion.value >= shuffledIndexes.value.length - 1) {
    return false;
  }

  const nextQuestionIndex = activeQuestion.value + 1;
  activeQuestion.value = nextQuestionIndex;
  loadQuestionAnswers(nextQuestionIndex);
  return true;
};

const handleAnswerSubmission = async (
  questionIndex: number,
  userAnswers: string[],
) => {
  isCheckingAnswers.value = true;
  const isCorrect = await isQuestionCorrect(questionIndex, userAnswers);
  isCheckingAnswers.value = false;

  attemptedQuestions.value = {
    ...attemptedQuestions.value,
    [questionIndex]: userAnswers,
  };

  correctAnswers.value = {
    ...correctAnswers.value,
    [questionIndex]: isCorrect,
  };

  playSound(isCorrect ? "correct" : "failure");
  return isCorrect;
};

const handleNextQuestion = () => {
  const savedAnswers = [...currentAnswers.value];

  allUserAnswers.value = {
    ...allUserAnswers.value,
    [activeQuestion.value]: savedAnswers,
  };

  advanceToNextQuestion();
};

const handleCheckAnswers = async () => {
  isCheckingAnswers.value = true;

  if (shouldUseBatchAI.value) {
    const nextAllUserAnswers = {
      ...allUserAnswers.value,
      [activeQuestion.value]: [...currentAnswers.value],
    };
    allUserAnswers.value = nextAllUserAnswers;

    try {
      const submissions: { questionId: string; answer: string }[] = [];
      const aiQuestions: {
        id: string;
        question: string;
        acceptedAnswers: string[];
        strictMode: boolean;
        maxMarks: number;
        questionType: "reasoning";
        context: Record<string, unknown>;
        evaluationCriteria: string;
      }[] = [];

      shuffledIndexes.value.forEach((originalIndex, questionIndex) => {
        const question = props.questions.questions[originalIndex];
        const userAnswers = nextAllUserAnswers[questionIndex] || [];

        userAnswers.forEach((answer, answerIndex) => {
          const questionId = `${originalIndex}-${answerIndex}`;
          submissions.push({
            questionId,
            answer: answer.trim(),
          });

          aiQuestions.push({
            id: questionId,
            question: question.question,
            acceptedAnswers: question.answers,
            strictMode: false,
            maxMarks: 1,
            questionType: "reasoning",
            context: {
              notes: props.questions.notes,
              title: props.questions.title,
              questionText: question.question,
            },
            evaluationCriteria:
              "Evaluate based on comprehension of the provided text/context and semantic similarity to the accepted answer.",
          });
        });
      });

      const results = await answerChecker.checkAnswersWithAI(
        submissions,
        aiQuestions,
      );

      const nextCorrectAnswers: Record<number, boolean> = {};
      const nextAttemptedQuestions: Record<number, string[]> = {};

      shuffledIndexes.value.forEach((originalIndex, questionIndex) => {
        const userAnswers = nextAllUserAnswers[questionIndex] || [];
        nextAttemptedQuestions[questionIndex] = userAnswers;

        const questionResults = results.filter((result) =>
          result.questionId.startsWith(`${originalIndex}-`),
        );
        const isCorrect = questionResults.every(
          (result) => result.result.isCorrect,
        );

        nextCorrectAnswers[questionIndex] = isCorrect;
        playSound(isCorrect ? "correct" : "failure");
      });

      attemptedQuestions.value = nextAttemptedQuestions;
      correctAnswers.value = nextCorrectAnswers;
      score.value = Object.values(nextCorrectAnswers).filter(Boolean).length;
      allAnswered.value = true;
    } catch {
      const nextCorrectAnswers: Record<number, boolean> = {};

      for (let index = 0; index < shuffledIndexes.value.length; index += 1) {
        const answersForQuestion = nextAllUserAnswers[index] || [];
        nextCorrectAnswers[index] = await isQuestionCorrect(
          index,
          answersForQuestion,
        );
      }

      attemptedQuestions.value = nextAllUserAnswers;
      correctAnswers.value = nextCorrectAnswers;
      score.value = Object.values(nextCorrectAnswers).filter(Boolean).length;
      allAnswered.value = true;
    } finally {
      isCheckingAnswers.value = false;
    }

    return;
  }

  const savedAnswers = [...currentAnswers.value];
  const isCorrect = await handleAnswerSubmission(activeQuestion.value, savedAnswers);
  score.value = Object.values({
    ...correctAnswers.value,
    [activeQuestion.value]: isCorrect,
  }).filter(Boolean).length;

  if (activeQuestion.value < shuffledIndexes.value.length - 1) {
    advanceToNextQuestion();
    isCheckingAnswers.value = false;
    return;
  }

  allAnswered.value = true;
  isCheckingAnswers.value = false;
};

const resetActivity = () => {
  initializeActivity();
};

const questionParts = (questionText: string) => questionText.split("___");
const questionIsAnswered = (index: number) => {
  const answers = shouldUseBatchAI.value
    ? allUserAnswers.value[index] || []
    : attemptedQuestions.value[index] || [];

  return answers.length > 0 && answers.every((answer) => answer.trim() !== "");
};
const isQuestionCorrectState = (index: number) => correctAnswers.value[index] ?? false;
const displayAnswer = (index: number, answerIndex: number) =>
  attemptedQuestions.value[index]?.[answerIndex] ||
  allUserAnswers.value[index]?.[answerIndex] ||
  "_____";
const closeResultsDialog = (open: boolean) => {
  if (open) {
    return;
  }

  allAnswered.value = false;

  if (props.feedback === "none") {
    resetActivity();
    return;
  }

  showResults.value = true;
};
</script>

<template>
  <div class="flex h-full flex-col">
    <ActivityTitle :title="props.questions.title" />

    <div
      v-if="showResults"
      class="flex flex-1 flex-col gap-4 overflow-auto pb-4"
    >
      <div class="space-y-3">
        <div
          v-for="(originalIndex, visibleIndex) in shuffledIndexes"
          :key="`${visibleIndex}-${originalIndex}`"
          :class="
            cn(
              'rounded-xl border p-4',
              correctAnswers[visibleIndex]
                ? 'border-green-300 bg-green-50'
                : 'border-red-300 bg-red-50',
            )
          "
        >
          <div class="flex items-start gap-3">
            <div
              :class="
                cn(
                  'mt-1 flex h-8 w-8 items-center justify-center rounded-full',
                  isQuestionCorrectState(visibleIndex)
                    ? 'bg-green-100 text-green-700'
                    : 'bg-red-100 text-red-700',
                )
              "
            >
              <Icon
                :icon="
                  isQuestionCorrectState(visibleIndex)
                    ? 'heroicons:check-20-solid'
                    : 'heroicons:x-mark-20-solid'
                "
                width="18"
                height="18"
              />
            </div>

            <div class="flex-1 space-y-2 text-base leading-loose text-neutral-800">
              <template
                v-if="
                  props.questions.questions[originalIndex]?.question.includes(
                    '___',
                  )
                "
              >
                <template
                  v-for="(part, partIndex) in questionParts(
                    props.questions.questions[originalIndex]?.question || '',
                  )"
                  :key="`${visibleIndex}-${partIndex}`"
                >
                  <span>{{ partIndex === 0 ? `${visibleIndex + 1}. ${part}` : part }}</span>
                  <span
                    v-if="
                      partIndex <
                      questionParts(
                        props.questions.questions[originalIndex]?.question || '',
                      ).length - 1
                    "
                    class="mx-1 px-1"
                  >
                    <template v-if="props.feedback === 'wrong-correct-answers'">
                      <span
                        v-if="attemptedQuestions[visibleIndex]?.[partIndex]"
                        :class="
                          answerChecker.checkAnswer(
                            attemptedQuestions[visibleIndex][partIndex],
                            {
                              acceptedAnswers: props.questions.questions[
                                originalIndex
                              ]?.answers || [],
                            },
                          ).isCorrect
                            ? 'rounded bg-green-200 px-1 font-medium text-green-800'
                            : 'mr-1 rounded bg-red-200 px-1 font-medium text-red-800 line-through'
                        "
                      >
                        {{ attemptedQuestions[visibleIndex][partIndex] }}
                      </span>
                      <span
                        v-if="
                          !attemptedQuestions[visibleIndex]?.[partIndex] ||
                          !answerChecker.checkAnswer(
                            attemptedQuestions[visibleIndex][partIndex],
                            {
                              acceptedAnswers: props.questions.questions[
                                originalIndex
                              ]?.answers || [],
                            },
                          ).isCorrect
                        "
                        class="rounded bg-green-200 px-1 font-medium text-green-800"
                      >
                        {{
                          props.questions.questions[originalIndex]?.answers[
                            partIndex
                          ] || "_____"
                        }}
                      </span>
                    </template>
                    <template v-else>
                      <span
                        :class="
                          isQuestionCorrectState(visibleIndex)
                            ? 'rounded bg-green-200 px-1 font-medium text-green-800'
                            : 'rounded bg-red-200 px-1 font-medium text-red-800'
                        "
                      >
                        {{ displayAnswer(visibleIndex, partIndex) }}
                      </span>
                    </template>
                  </span>
                </template>
              </template>

              <template v-else>
                <p>
                  {{ `${visibleIndex + 1}. ${props.questions.questions[originalIndex]?.question}` }}
                </p>
                <div class="mt-1 pl-6">
                  <template v-if="props.feedback === 'wrong-correct-answers'">
                    <span
                      v-if="attemptedQuestions[visibleIndex]?.[0]"
                      :class="
                        answerChecker.checkAnswer(attemptedQuestions[visibleIndex][0], {
                          acceptedAnswers:
                            props.questions.questions[originalIndex]?.answers || [],
                        }).isCorrect
                          ? 'rounded bg-green-200 px-1 font-medium text-green-800'
                          : 'mr-1 rounded bg-red-200 px-1 font-medium text-red-800 line-through'
                      "
                    >
                      {{ attemptedQuestions[visibleIndex][0] }}
                    </span>
                    <span
                      v-if="
                        !attemptedQuestions[visibleIndex]?.[0] ||
                        !answerChecker.checkAnswer(attemptedQuestions[visibleIndex][0], {
                          acceptedAnswers:
                            props.questions.questions[originalIndex]?.answers || [],
                        }).isCorrect
                      "
                      class="rounded bg-green-200 px-1 font-medium text-green-800"
                    >
                      {{ props.questions.questions[originalIndex]?.answers[0] || "_____" }}
                    </span>
                  </template>
                  <template v-else>
                    <span
                      :class="
                        isQuestionCorrectState(visibleIndex)
                          ? 'rounded bg-green-200 px-1 font-medium text-green-800'
                          : 'rounded bg-red-200 px-1 font-medium text-red-800'
                      "
                    >
                      {{ displayAnswer(visibleIndex, 0) }}
                    </span>
                  </template>
                </div>
              </template>
            </div>
          </div>
        </div>
      </div>

      <ActivityResults
        :score="score"
        :total="props.questions.questions.length"
        :on-restart="resetActivity"
      />
    </div>

    <div
      v-else
      class="flex flex-1 flex-col gap-4"
    >
      <div
        class="grid flex-1 gap-4 md:grid-cols-[minmax(0,1fr)_minmax(0,1.4fr)]"
      >
        <LeftNotesWithImages
          :notes="`${props.questions.notes}`"
          :image="props.questions.image"
        />

        <div
          class="flex flex-col gap-4 rounded-2xl bg-white p-4 shadow-sm md:p-6"
        >
          <div
            v-if="currentQuestion"
            class="flex flex-1 flex-col gap-4"
          >
            <div class="overflow-auto">
              <div class="text-lg leading-loose text-neutral-700">
                <template v-if="currentQuestion.question.includes('___')">
                  <template
                    v-for="(part, partIndex) in questionParts(
                      currentQuestion.question,
                    )"
                    :key="`${activeQuestion}-${partIndex}`"
                  >
                    <span>
                      {{
                        partIndex === 0
                          ? `${activeQuestion + 1}. ${part}`
                          : part
                      }}
                    </span>
                    <span
                      v-if="
                        partIndex <
                        questionParts(currentQuestion.question).length - 1
                      "
                      class="mx-2 inline-flex w-32 align-middle"
                    >
                      <Input
                        :model-value="currentAnswers[partIndex] || ''"
                        class="rounded-none border-none bg-transparent px-0 text-center text-lg text-picton-blue-700 shadow-none"
                        @update:model-value="
                          (value) => setAnswer(partIndex, value)
                        "
                      />
                      <span
                        class="mt-9 block w-full border-b border-dashed border-picton-blue-700"
                      />
                    </span>
                  </template>
                </template>

                <template v-else>
                  <p>
                    {{
                      `${activeQuestion + 1}. ${currentQuestion.question}`
                    }}
                  </p>
                  <div class="mt-3">
                    <Input
                      :model-value="currentAnswers[0] || ''"
                      class="rounded-none border-none bg-transparent px-0 text-center text-lg text-picton-blue-700 shadow-none"
                      @update:model-value="(value) => setAnswer(0, value)"
                    />
                    <div
                      class="border-b border-dashed border-picton-blue-700"
                    />
                  </div>
                </template>
              </div>
            </div>

            <div
              v-if="currentQuestion.image"
              class="overflow-hidden rounded-2xl bg-picton-blue-50 p-4"
            >
              <img
                :src="currentQuestion.image"
                alt="Comprehension question"
                class="mx-auto max-h-72 w-full object-contain"
              />
            </div>
          </div>
        </div>
      </div>

      <div
        class="flex flex-col-reverse gap-4 md:flex-row md:items-center md:justify-between"
      >
        <div class="flex flex-wrap justify-center gap-3">
          <div
            v-for="(_, index) in shuffledIndexes"
            :key="index"
            :class="
              cn(
                'flex h-10 w-10 items-center justify-center rounded-lg text-sm font-semibold',
                questionIsAnswered(index)
                  ? 'bg-lemon-200 text-lemon-800'
                  : 'bg-picton-blue-200 text-picton-blue-800',
                index === activeQuestion && !questionIsAnswered(index)
                  ? 'ring-2 ring-picton-blue-500'
                  : '',
              )
            "
          >
            <template v-if="questionIsAnswered(index) && (!shouldUseBatchAI || allAnswered)">
              <Icon
                v-if="isQuestionCorrectState(index)"
                icon="heroicons:check-20-solid"
                width="20"
                height="20"
                class="text-green-600"
              />
              <Icon
                v-else
                icon="heroicons:x-mark-20-solid"
                width="20"
                height="20"
                class="text-red-600"
              />
            </template>
          </div>
        </div>

        <Button
          :disabled="
            currentAnswers.some((answer) => !answer?.trim()) ||
            isCheckingAnswers
          "
          class="group gap-2"
          @click="
            shouldUseBatchAI && activeQuestion < shuffledIndexes.length - 1
              ? handleNextQuestion()
              : handleCheckAnswers()
          "
        >
          <Icon
            icon="heroicons:sparkles"
            width="18"
            height="18"
            class="text-lemon-700 transition-transform duration-200 group-hover:scale-110"
          />
          {{
            isCheckingAnswers
              ? shouldUseBatchAI
                ? 'Checking All Answers...'
                : ui.checking
              : shouldUseBatchAI
                ? activeQuestion < shuffledIndexes.length - 1
                  ? ui.nextQuestion
                  : 'Check All Answers'
                : ui.checkAnswer
          }}
        </Button>
      </div>
    </div>

    <ActivityResultsAlertDialog
      :score="score"
      :total="props.questions.questions.length"
      :open="allAnswered"
      :on-open-change="closeResultsDialog"
    />
  </div>
</template>

// app/components/primary-sources/activities/comprehension-junior.tsx
"use client";

import { Check, X } from "lucide-react";
import React, { useCallback, useEffect, useState, useMemo } from "react";
import { motion, AnimatePresence } from "motion/react";

// Local imports
import { Button } from "@/components/ui/button";
import { cn, shuffle } from "@/lib/utils";
import { Input } from "@/components/ui/inputs/input";
import ActivityTitle from "@/components/templates/activity-title";
import { FeedbackType } from "@/lib/types/activity-types";
import { AnswerChecker } from "@/lib/utils/answer-checker";
import LeftNotesWithImages from "@/components/templates/left-notes-with-images";
import { useSoundEffects } from "@/shared/hooks/use-sound-effects";
import ActivityResults, {
  ActivityResultsAlertDialog,
} from "@/components/templates/results";

type TComprehensionJuniorQuestion = {
  notes: string;
  title: string;
  image?: string;
  optionsTitle?: string;
  useAI?: boolean;
  algorithm: "Comprehension junior one" | "Comprehension junior two";
  questions: {
    question: string;
    image?: string;
    answers: string[];
    options: {
      id: string;
      text: string;
    }[];
  }[];
};

const questionVariants = {
  enter: {
    x: 50,
    opacity: 0,
  },
  center: {
    x: 0,
    opacity: 1,
  },
  exit: {
    x: -50,
    opacity: 0,
  },
};

const answerChecker = new AnswerChecker();

const ComprehensionJunior = ({
  feedback,
  questions,
}: {
  feedback?: FeedbackType;
  questions: TComprehensionJuniorQuestion;
}) => {
  const [score, setScore] = useState(0);
  const [allAnswered, setAllAnswered] = useState(false);
  const [activeQuestion, setActiveQuestion] = useState(0);
  const [shuffledIndexes, setShuffledIndexes] = useState<number[]>([]);
  const [theTypedAnswers, setTheTypedAnswers] = useState<string[]>([]);
  const [attemptedQuestions, setAttemptedQuestions] = useState<
    Record<number, string[]>
  >({});
  const [showResults, setShowResults] = useState(false);
  const [correctAnswers, setCorrectAnswers] = useState<Record<number, boolean>>(
    {},
  );
  const [isCheckingAnswers, setIsCheckingAnswers] = useState(false);
  const [allUserAnswers, setAllUserAnswers] = useState<
    Record<number, string[]>
  >({}); // Store all answers for batch checking

  const { playSound } = useSoundEffects();

  // Determine if we should use batch AI checking
  const shouldUseBatchAI =
    questions.algorithm === "Comprehension junior one" && questions.useAI;

  const getCurrentQuestion = useCallback(() => {
    if (shuffledIndexes.length === 0) return questions.questions[0];
    return questions.questions[shuffledIndexes[activeQuestion]];
  }, [shuffledIndexes, activeQuestion, questions.questions]);

  useEffect(() => {
    shuffleQuestions();
  }, []);

  useEffect(() => {
    if (shuffledIndexes.length > 0) {
      const currentQuestion = getCurrentQuestion();
      setTheTypedAnswers(Array(currentQuestion.answers.length).fill(""));
    }
  }, [shuffledIndexes, activeQuestion, getCurrentQuestion]);

  const shuffleQuestions = () => {
    const indexes = Array.from(
      { length: questions.questions.length },
      (_, i) => i,
    );
    const shuffled = shuffle([...indexes]);
    setShuffledIndexes(shuffled);
    setActiveQuestion(0);

    setAttemptedQuestions(Object.fromEntries(shuffled.map((_, i) => [i, []])));
    setCorrectAnswers({});

    if (shuffled.length > 0) {
      const firstQuestion = questions.questions[shuffled[0]];
      setTheTypedAnswers(Array(firstQuestion.answers.length).fill(""));
    }
  };

  const checkAnswer = useCallback(
    async (questionIndex: number, answers: string[]) => {
      if (shuffledIndexes.length === 0) return false;

      const originalIndex = shuffledIndexes[questionIndex];

      if (
        questions.algorithm === "Comprehension junior one" &&
        questions.useAI
      ) {
        // Use AI checking for comprehension junior one when useAI is true
        try {
          setIsCheckingAnswers(true);

          const submissions = answers.map((answer, answerIndex) => ({
            questionId: `${originalIndex}-${answerIndex}`,
            answer: answer.trim(),
          }));

          const aiQuestions = answers.map((_, answerIndex) => ({
            id: `${originalIndex}-${answerIndex}`,
            question: questions.questions[originalIndex].question,
            context: {
              notes: questions.notes,
              title: questions.title,
              questionText: questions.questions[originalIndex].question,
              image:
                questions.questions[originalIndex].image || questions.image,
            },
            acceptedAnswers: [
              questions.questions[originalIndex].answers[answerIndex],
            ],
            strictMode: false,
            maxMarks: 1,
            questionType: "reasoning" as const,
            evaluationCriteria:
              "Evaluate based on comprehension of the provided text/context and semantic similarity to the accepted answer.",
          }));

          const results = await answerChecker.checkAnswersWithAI(
            submissions,
            aiQuestions,
          );

          // Check if all answers are correct
          return results.every((result) => result.result.isCorrect);
        } catch (error) {
          console.error(
            "AI checking failed, falling back to traditional method:",
            error,
          );
          // Fallback to traditional checking
          return answers.every((ans) => {
            const theResults = answerChecker.checkAnswer(ans, {
              acceptedAnswers: questions.questions[originalIndex].answers,
            });
            return theResults.isCorrect;
          });
        } finally {
          setIsCheckingAnswers(false);
        }
      } else if (questions.algorithm === "Comprehension junior one") {
        return answers.every((ans) => {
          const theResults = answerChecker.checkAnswer(ans, {
            acceptedAnswers: questions.questions[originalIndex].answers,
          });
          return theResults.isCorrect;
        });
      } else {
        return answers.every(
          (ans, i) =>
            ans.trim().toLowerCase() ===
            questions.questions[originalIndex].answers[i].trim().toLowerCase(),
        );
      }
    },
    [shuffledIndexes, questions],
  );

  // console.log(console.log(allUserAnswers[5]));

  // New function to check all answers at once using AI
  const checkAllAnswersWithAI = useCallback(async () => {
    if (shuffledIndexes.length === 0) return;

    try {
      setIsCheckingAnswers(true);

      // Prepare all submissions for AI checking
      const allSubmissions: { questionId: string; answer: string }[] = [];
      const allAIQuestions: any[] = [];

      shuffledIndexes.forEach((originalIndex, questionIndex) => {
        const userAnswers = allUserAnswers[questionIndex] || [];
        userAnswers.forEach((answer, answerIndex) => {
          const submissionId = `${originalIndex}-${answerIndex}`;
          allSubmissions.push({
            questionId: submissionId,
            answer: answer.trim(),
          });

          allAIQuestions.push({
            id: submissionId,
            question: questions.questions[originalIndex].question,
            context: {
              notes: questions.notes,
              title: questions.title,
              questionText: questions.questions[originalIndex].question,
            },
            acceptedAnswers: questions.questions[originalIndex].answers,
            strictMode: false,
            maxMarks: 1,
            questionType: "reasoning" as const,
            evaluationCriteria:
              "Evaluate based on comprehension of the provided text/context and semantic similarity to the accepted answer.",
          });
        });
      });

      const results = await answerChecker.checkAnswersWithAI(
        allSubmissions,
        allAIQuestions,
      );

      // Process results and update state
      const newCorrectAnswers: Record<number, boolean> = {};
      const newAttemptedQuestions: Record<number, string[]> = {};

      shuffledIndexes.forEach((originalIndex, questionIndex) => {
        const userAnswers = allUserAnswers[questionIndex] || [];
        newAttemptedQuestions[questionIndex] = userAnswers;

        // Check if all answers for this question are correct
        const questionResults = results.filter((result) =>
          result.questionId.startsWith(`${originalIndex}-`),
        );

        const allCorrect = questionResults.every(
          (result) => result.result.isCorrect,
        );
        newCorrectAnswers[questionIndex] = allCorrect;

        // Play sound for each question
        playSound(allCorrect ? "correct" : "failure");
      });

      setCorrectAnswers(newCorrectAnswers);
      setAttemptedQuestions(newAttemptedQuestions);

      // Calculate final score
      const finalScore =
        Object.values(newCorrectAnswers).filter(Boolean).length;
      setScore(finalScore);
      setAllAnswered(true);
    } catch (error) {
      console.error("AI batch checking failed:", error);
      // Fallback to individual checking
      for (let i = 0; i < shuffledIndexes.length; i++) {
        const userAnswers = allUserAnswers[i] || [];
        const isCorrect = await checkAnswer(i, userAnswers);

        setCorrectAnswers((prev) => ({ ...prev, [i]: isCorrect }));
        setAttemptedQuestions((prev) => ({ ...prev, [i]: userAnswers }));
      }

      const finalScore = Object.values(correctAnswers).filter(Boolean).length;
      setScore(finalScore);
      setAllAnswered(true);
    } finally {
      setIsCheckingAnswers(false);
    }
  }, [shuffledIndexes, allUserAnswers, questions, answerChecker]);

  const isAnswerCorrect = useCallback(
    (questionIndex: number) => {
      return correctAnswers[questionIndex] ?? false;
    },
    [correctAnswers],
  );

  // Update the allQuestionsAnswered logic for batch AI mode
  const allQuestionsAnswered = useMemo(() => {
    if (shuffledIndexes.length === 0) {
      return false;
    }

    if (shouldUseBatchAI) {
      // For batch AI, check if all questions have been answered (stored in allUserAnswers)
      return (
        Object.keys(allUserAnswers).length === shuffledIndexes.length &&
        Object.values(allUserAnswers).every((answers) =>
          answers.every((answer) => answer.trim() !== ""),
        )
      );
    } else {
      // Original logic for non-AI mode
      return (
        Object.keys(attemptedQuestions).length === shuffledIndexes.length &&
        Object.values(attemptedQuestions).every((answer) => answer.length > 0)
      );
    }
  }, [
    attemptedQuestions,
    allUserAnswers,
    shuffledIndexes.length,
    shouldUseBatchAI,
  ]);

  useEffect(() => {
    if (allQuestionsAnswered && !shouldUseBatchAI) {
      const newScore = Object.keys(correctAnswers).reduce(
        (acc, index) => (correctAnswers[Number(index)] ? acc + 1 : acc),
        0,
      );
      setScore(newScore);
      setAllAnswered(true);
    }
  }, [allQuestionsAnswered, correctAnswers, shouldUseBatchAI]);

  const handleAnswerSubmission = async (
    questionIndex: number,
    answer: string[],
  ) => {
    const isCorrect = await checkAnswer(questionIndex, answer);

    setAttemptedQuestions((prev) => ({
      ...prev,
      [questionIndex]: answer,
    }));

    setCorrectAnswers((prev) => ({
      ...prev,
      [questionIndex]: isCorrect,
    }));

    // Play appropriate sound based on answer correctness
    playSound(isCorrect ? "correct" : "failure");

    if (questionIndex < shuffledIndexes.length - 1) {
      setActiveQuestion(questionIndex + 1);
    }
  };

  // Handle next question for batch AI mode
  const handleNextQuestion = () => {
    // Store current answers
    setAllUserAnswers((prev) => ({
      ...prev,
      [activeQuestion]: [...theTypedAnswers],
    }));

    if (activeQuestion < shuffledIndexes.length - 1) {
      setActiveQuestion(activeQuestion + 1);
      const nextQuestion =
        questions.questions[shuffledIndexes[activeQuestion + 1]];
      setTheTypedAnswers(Array(nextQuestion.answers.length).fill(""));
    }
  };

  // console.log(attemptedQuestions);

  const handleCheckAnswer = async () => {
    if (shouldUseBatchAI) {
      // Store the last question's answers
      setAllUserAnswers((prev) => ({
        ...prev,
        [activeQuestion]: [...theTypedAnswers],
      }));
      // Check all answers at once
      await checkAllAnswersWithAI();
    } else {
      // Original behavior for non-AI mode
      await handleAnswerSubmission(activeQuestion, theTypedAnswers);

      if (activeQuestion < shuffledIndexes.length - 1) {
        const nextQuestion =
          questions.questions[shuffledIndexes[activeQuestion + 1]];
        setTheTypedAnswers(Array(nextQuestion.answers.length).fill(""));
      }
    }
  };

  const resetActivity = () => {
    setScore(0);
    setAllAnswered(false);
    setShowResults(false);
    setAllUserAnswers({});
    shuffleQuestions();
  };

  const ResultsSummary = () => {
    return (
      <div className="w-full space-y-3">
        {shuffledIndexes.map((originalIndex, idx) => {
          const question = questions.questions[originalIndex];
          const userAnswers = attemptedQuestions[idx] || [];
          const isCorrect = isAnswerCorrect(idx);

          const renderQuestionWithAnswers = () => {
            if (question.question.includes("___")) {
              const parts = question.question.split("___");

              return (
                <div className="text-base leading-loose">
                  {parts.map((part, i) => (
                    <React.Fragment key={i}>
                      <span>{i === 0 ? `${idx + 1}. ${part}` : part}</span>

                      {i < parts.length - 1 && (
                        <span className="mx-1 px-1">
                          {feedback === "wrong-correct-answers" ? (
                            <>
                              {userAnswers[i] && (
                                <span
                                  className={
                                    userAnswers[i]?.trim().toLowerCase() ===
                                    question.answers[i]?.trim().toLowerCase()
                                      ? "bg-green-200 text-green-800 px-1 rounded font-medium"
                                      : "bg-red-200 text-red-800 px-1 line-through rounded font-medium mr-1"
                                  }
                                >
                                  {userAnswers[i]}
                                </span>
                              )}
                              {(!userAnswers[i] ||
                                userAnswers[i]?.trim().toLowerCase() !==
                                  question.answers[i]
                                    ?.trim()
                                    .toLowerCase()) && (
                                <span className="bg-green-200 text-green-800 px-1 rounded font-medium">
                                  {question.answers[i]}
                                </span>
                              )}
                            </>
                          ) : (
                            <span
                              className={
                                isCorrect
                                  ? "bg-green-200 text-green-800 px-1 rounded font-medium"
                                  : "bg-red-200 text-red-800 px-1 rounded font-medium"
                              }
                            >
                              {userAnswers[i] || allUserAnswers[idx] || "_____"}
                            </span>
                          )}
                        </span>
                      )}
                    </React.Fragment>
                  ))}
                </div>
              );
            } else {
              return (
                <div className="text-base">
                  <p>{`${idx + 1}. ${question.question}`}</p>
                  {feedback === "wrong-correct-answers" ? (
                    <div className="mt-1 pl-6">
                      {userAnswers[0] && (
                        <span
                          className={
                            answerChecker.checkAnswer(userAnswers[0], {
                              acceptedAnswers: question.answers,
                            }).isCorrect
                              ? "bg-green-200 text-green-800 px-1 rounded font-medium"
                              : "bg-red-200 text-red-800 px-1 line-through rounded font-medium mr-1"
                          }
                        >
                          {userAnswers[0]}
                        </span>
                      )}
                      {(!userAnswers[0] ||
                        !answerChecker.checkAnswer(userAnswers[0], {
                          acceptedAnswers: question.answers,
                        }).isCorrect) && (
                        <span className="bg-green-200 text-green-800 px-1 rounded font-medium">
                          {question.answers[0]}
                        </span>
                      )}
                    </div>
                  ) : (
                    <div className="mt-1 pl-6">
                      <span
                        className={
                          isCorrect
                            ? "bg-green-200 text-green-800 px-1 rounded font-medium"
                            : "bg-red-200 text-red-800 px-1 rounded font-medium"
                        }
                      >
                        {userAnswers[0] || allUserAnswers[idx] || "_____"}
                      </span>
                    </div>
                  )}
                </div>
              );
            }
          };

          return (
            <div
              key={idx}
              className={cn(
                "p-3 rounded-md border",
                isCorrect
                  ? "border-green-300 bg-green-50"
                  : "border-red-300 bg-red-50",
              )}
            >
              <div className="flex items-start gap-3">
                <div
                  className={cn(
                    "w-8 h-8 rounded-full flex items-center justify-center mt-1",
                    isCorrect
                      ? "bg-green-100 text-green-700"
                      : "bg-red-100 text-red-700",
                  )}
                >
                  {isCorrect ? <Check size={18} /> : <X size={18} />}
                </div>

                <div className="flex-1">{renderQuestionWithAnswers()}</div>
              </div>
            </div>
          );
        })}
      </div>
    );
  };

  return (
    <div className="h-full flex flex-col">
      <ActivityTitle title={questions.title} />

      {showResults ? (
        <div className="flex-1 flex flex-col items-center justify-between p-4 overflow-auto">
          <ResultsSummary />
          <div className="w-full mt-4">
            <ActivityResults
              score={score}
              total={questions.questions.length}
              onRestart={resetActivity}
            />
          </div>
        </div>
      ) : (
        <div className="flex flex-col gap-4 h-full">
          <div className="flex flex-col md:flex-row justify-between gap-4 md:max-h-[calc(100dvh-150px)]">
            <LeftNotesWithImages
              notes={`${questions.notes}`}
              image={questions.image}
            />
            <div className="bg-white flex flex-col gap-4 justify-between w-full rounded-xl p-4 md:p-6">
              <AnimatePresence mode="wait">
                <motion.div
                  key={activeQuestion}
                  variants={questionVariants}
                  initial="enter"
                  animate="center"
                  exit="exit"
                  transition={{
                    duration: 0.3,
                    type: "spring",
                    stiffness: 300,
                    damping: 30,
                  }}
                  className="flex flex-col gap-4 justify-between h-full"
                >
                  {shuffledIndexes.length > 0 && (
                    <>
                      <div className="md:max-h-[250px] overflow-auto">
                        <div className="text-lg leading-loose">
                          {getCurrentQuestion().question.includes("___") ? (
                            getCurrentQuestion()
                              .question.split("___")
                              .map((part, i) => (
                                <React.Fragment key={i}>
                                  <span>
                                    {i === 0 &&
                                      questions.algorithm ===
                                        "Comprehension junior one" &&
                                      `${activeQuestion + 1}. `}
                                    {part}
                                  </span>

                                  {i !==
                                    getCurrentQuestion().question.split("___")
                                      .length -
                                      1 && (
                                    <div className="inline-block mx-2 align-middle">
                                      <Input
                                        type="text"
                                        className="max-w-40 rounded-none border-none bg-transparent text-picton-blue-700 text-center text-lg"
                                        value={theTypedAnswers[i] || ""}
                                        onChange={(e) =>
                                          setTheTypedAnswers((prev) => {
                                            const newAnswers = [...prev];
                                            newAnswers[i] = e.target.value;
                                            return newAnswers;
                                          })
                                        }
                                      />
                                      <div className="border-b border-dashed border-picton-blue-700" />
                                    </div>
                                  )}
                                </React.Fragment>
                              ))
                          ) : (
                            <>
                              <span>{`${activeQuestion + 1}. ${
                                getCurrentQuestion().question
                              }`}</span>
                              <div className="mt-2">
                                <Input
                                  type="text"
                                  className="rounded-none border-none bg-transparent text-picton-blue-700 text-center text-lg"
                                  value={theTypedAnswers[0] || ""}
                                  onChange={(e) =>
                                    setTheTypedAnswers([e.target.value])
                                  }
                                />
                                <div className="border-b border-dashed border-picton-blue-700" />
                              </div>
                            </>
                          )}
                        </div>
                      </div>
                      <div
                        className={cn(
                          "flex flex-col md:flex-row w-full gap-4 justify-between",
                          {
                            "md:h-[300px]": getCurrentQuestion().image,
                          },
                        )}
                      >
                        {getCurrentQuestion().image && (
                          <div className="w-full overflow-hidden">
                            <img
                              src={getCurrentQuestion().image}
                              alt="Comprehension junior Image"
                              className="object-contain w-full h-full rounded"
                            />
                          </div>
                        )}
                        {/*{((getCurrentQuestion().options.length > 0 &&
                          questions.algorithm === "Comprehension junior two") ||
                          (questions.optionsTitle &&
                            questions.optionsTitle?.length > 0)) && (
                          <div className="space-y-4 md:w-1/4">
                            <p className="font-bold">
                              {questions.algorithm ===
                              "Comprehension junior two"
                                ? "Options"
                                : questions.optionsTitle}
                            </p>
                            <div className="grid grid-cols-2 md:space-y-4 sm:grid-cols-4 md:grid-cols-4 md:block gap-2">
                              {getCurrentQuestion().options.map(
                                (option, optionIndex) => (
                                  <div
                                    key={optionIndex}
                                    className="text-picton-blue-700 md:min-w-20 text-lg leading-4"
                                  >
                                    {option.text}
                                  </div>
                                ),
                              )}
                            </div>
                          </div>
                        )}*/}
                      </div>
                    </>
                  )}
                </motion.div>
              </AnimatePresence>
            </div>
          </div>
          <div className="flex flex-col-reverse md:flex-row gap-4 md:items-center justify-between">
            <div className="flex justify-center gap-4 flex-wrap">
              {shuffledIndexes.map((_, index) => {
                // For batch AI mode, check if question has been answered in allUserAnswers
                const isAnswered = shouldUseBatchAI
                  ? allUserAnswers[index]?.length > 0 &&
                    allUserAnswers[index].every((ans) => ans.trim() !== "")
                  : attemptedQuestions[index]?.length > 0;

                return (
                  <div
                    key={index}
                    className={cn(
                      "w-10 h-10 rounded-lg flex items-center justify-center bg-picton-blue-200",
                      {
                        "bg-lemon-200": isAnswered,
                        "border-2 border-picton-blue-500":
                          index === activeQuestion && !isAnswered,
                      },
                    )}
                  >
                    {isAnswered &&
                      !shouldUseBatchAI &&
                      (isAnswerCorrect(index) ? (
                        <Check className="text-green-500" size={24} />
                      ) : (
                        <X className="text-red-500" size={24} />
                      ))}
                    {isAnswered &&
                      shouldUseBatchAI &&
                      allAnswered &&
                      (isAnswerCorrect(index) ? (
                        <Check className="text-green-500" size={24} />
                      ) : (
                        <X className="text-red-500" size={24} />
                      ))}
                  </div>
                );
              })}
            </div>

            {shouldUseBatchAI ? (
              // Show Next Question or Check All Answers button for batch AI mode
              activeQuestion === shuffledIndexes.length - 1 ? (
                <Button
                  disabled={
                    !theTypedAnswers.length ||
                    theTypedAnswers.some((answer) => !answer.trim()) ||
                    isCheckingAnswers
                  }
                  onClick={handleCheckAnswer}
                >
                  {isCheckingAnswers
                    ? "Checking All Answers..."
                    : "Check All Answers"}
                </Button>
              ) : (
                <Button
                  disabled={
                    !theTypedAnswers.length ||
                    theTypedAnswers.some((answer) => !answer.trim())
                  }
                  onClick={handleNextQuestion}
                >
                  Next Question
                </Button>
              )
            ) : (
              // Original Check Answer button for non-AI mode
              <Button
                disabled={
                  !theTypedAnswers.length ||
                  theTypedAnswers.some((answer) => !answer) ||
                  isCheckingAnswers
                }
                onClick={handleCheckAnswer}
              >
                {isCheckingAnswers ? "Checking..." : "Check Answer"}
              </Button>
            )}
          </div>
        </div>
      )}

      <ActivityResultsAlertDialog
        score={score}
        total={questions.questions.length}
        open={allAnswered}
        onOpenChange={(open) => {
          if (!open) {
            if (feedback === "none") {
              resetActivity();
            } else {
              setShowResults(true);
            }
            setAllAnswered(false);
          }
        }}
      />
    </div>
  );
};

export default ComprehensionJunior;
