// app/components/primary-sources/activities/complete-paragraph-without-clues.vue
<script setup lang="ts">
import { Fragment, computed, ref, watch } from "vue";
import { cn } from "@/lib/utils";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import ActivityTitle from "@/components/templates/activity-title";
import ActivityResults, {
  ActivityResultsAlertDialog,
} from "@/components/templates/results";
import type { FeedbackType } from "@/lib/types/activity-types";
import { AnswerChecker } from "@/lib/utils/answer-checker";
import { useSoundEffects } from "~/composables/use-sound-effects";

type Props = {
  feedback?: FeedbackType;
  questions: {
    title: string;
    fontSize?: string;
    paragraph: string;
    image?: string;
    answers: string[];
    options?: string[];
    withClues: boolean;
  };
};

const props = defineProps<Props>();
const answerChecker = new AnswerChecker();
const { playSound } = useSoundEffects();

const score = ref(0);
const allAnswered = ref(false);
const showResults = ref(false);
const userAnswers = ref<string[]>([]);
const isCorrectAnswers = ref<boolean[]>([]);

const initialize = () => {
  score.value = 0;
  allAnswered.value = false;
  showResults.value = false;
  userAnswers.value = Array.from({ length: props.questions.answers.length }, () => "");
  isCorrectAnswers.value = Array.from({ length: props.questions.answers.length }, () => false);
};

watch(() => props.questions, initialize, { deep: true, immediate: true });

const allAnswersFilled = computed(() => userAnswers.value.every((answer) => answer.trim() !== ""));
const paragraphParts = computed(() => props.questions.paragraph.split("___"));

const checkAnswers = () => {
  const correctness = userAnswers.value.map((answer, index) =>
    answerChecker.checkAnswer(answer.trim().toLowerCase(), {
      acceptedAnswers: [props.questions.answers[index].trim().toLowerCase()],
    }).isCorrect,
  );

  score.value = correctness.reduce((total, value) => total + (value ? 1 : 0), 0);
  isCorrectAnswers.value = correctness;
  allAnswered.value = true;
  playSound(score.value === props.questions.answers.length ? "success" : "failure");
};

const resetActivity = () => {
  initialize();
};
</script>

<template>
  <div class="flex h-full flex-col">
    <ActivityTitle :title="props.questions.title" />

    <template v-if="showResults">
      <div
        class="flex h-full w-full flex-col justify-between overflow-auto rounded-xl bg-picton-blue-50 p-4"
        :style="{ fontSize: props.questions.fontSize ? `${props.questions.fontSize}px` : '18px' }"
      >
        <div class="p-4 leading-loose">
          <template v-for="(part, index) in paragraphParts" :key="index">
            <span>{{ part }}</span>
            <span v-if="index < paragraphParts.length - 1" class="mx-1">
              <template v-if="props.feedback === 'wrong-correct-answers'">
                <span
                  v-if="userAnswers[index]"
                  :class="
                    cn(
                      'rounded px-2 py-1 font-medium',
                      isCorrectAnswers[index]
                        ? 'bg-green-200 text-green-800'
                        : 'mr-1 bg-red-200 text-red-800 line-through',
                    )
                  "
                >
                  {{ userAnswers[index] }}
                </span>
                <span
                  v-if="!userAnswers[index] || !isCorrectAnswers[index]"
                  class="rounded bg-green-200 px-2 py-1 font-medium text-green-800"
                >
                  {{ props.questions.answers[index] }}
                </span>
              </template>
              <span
                v-else
                :class="
                  cn(
                    'rounded px-2 py-1 font-medium',
                    isCorrectAnswers[index]
                      ? 'bg-green-200 text-green-800'
                      : 'bg-red-200 text-red-800',
                  )
                "
              >
                {{ userAnswers[index] || "_____" }}
              </span>
            </span>
          </template>
        </div>
      </div>

      <div class="mt-4 w-full">
        <ActivityResults
          :score="score"
          :total="props.questions.answers.length"
          :onRestart="resetActivity"
        />
      </div>
    </template>

    <div
      v-else
      class="flex h-full flex-col gap-4"
      :style="{ fontSize: props.questions.fontSize ? `${props.questions.fontSize}px` : '18px' }"
    >
      <div class="flex h-full flex-col gap-4 md:flex-row">
        <div class="flex h-full w-full flex-col gap-4 overflow-auto rounded-xl bg-picton-blue-50 p-6">
          <div
            v-if="props.questions.withClues"
            class="flex w-fit flex-wrap gap-4 rounded border-2 border-picton-blue-300 bg-picton-blue-100 py-4"
          >
            <p
              v-for="(answer, index) in props.questions.options || []"
              :key="index"
              class="px-3 text-lg leading-4 text-picton-blue-700"
            >
              {{ answer }}
            </p>
          </div>

          <div class="leading-loose">
            <template v-for="(part, index) in paragraphParts" :key="index">
              <span>
                <template v-for="(word, wordIndex) in part.split(' ')" :key="wordIndex">
                  <template v-if="wordIndex > 0"> </template>
                  <span
                    :class="word.startsWith('_') ? 'rounded bg-yellow-100 p-1 text-lemon-700' : ''"
                  >
                    {{ word.startsWith("_") ? word.slice(1) : word }}
                  </span>
                </template>
              </span>
              <span v-if="index < paragraphParts.length - 1" class="mx-2 inline-block align-middle">
                <Input
                  :model-value="userAnswers[index]"
                  type="text"
                  class="max-w-40 rounded-none border-none bg-transparent text-center !text-lg text-picton-blue-700"
                  :disabled="showResults"
                  @update:model-value="
                    (value) => {
                      const nextAnswers = [...userAnswers];
                      nextAnswers[index] = String(value ?? '');
                      userAnswers = nextAnswers;
                    }
                  "
                />
                <div class="border-b border-dashed border-picton-blue-700" />
              </span>
            </template>
          </div>
        </div>

        <div
          v-if="props.questions.image"
          class="flex items-center justify-center rounded-xl bg-white p-4 md:w-1/2"
        >
          <img
            :src="props.questions.image"
            alt="complete paragraph with clues"
            class="max-h-[600px] w-full object-contain"
          >
        </div>
      </div>

      <div class="flex justify-end">
        <Button :disabled="!allAnswersFilled" @click="checkAnswers">Check Answers</Button>
      </div>
    </div>

    <ActivityResultsAlertDialog
      :score="score"
      :total="props.questions.answers.length"
      :open="allAnswered"
      :onOpenChange="
        (open: boolean) => {
          if (!open) {
            if (props.feedback === 'none') {
              resetActivity();
            } else {
              showResults = true;
            }
            allAnswered = false;
          }
        }
      "
    />
  </div>
</template>

// app/components/primary-sources/activities/complete-paragraph-without-clues.tsx
"use client";

import { Fragment, useState, useCallback } from "react";
import { motion, AnimatePresence } from "framer-motion";

// local imports
import { cn } from "@/lib/utils";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import ActivityTitle from "@/components/templates/activity-title";
import { FeedbackType } from "@/lib/types/activity-types";
import { AnswerChecker } from "@/lib/utils/answer-checker";
import { useSoundEffects } from "@/shared/hooks/use-sound-effects";
import ActivityResults, {
  ActivityResultsAlertDialog,
} from "@/components/templates/results";

type TCompleteParagraphWithoutCluesProps = {
  feedback?: FeedbackType;
  questions: {
    title: string;
    fontSize?: string;
    paragraph: string;
    image?: string;
    answers: string[];
    options?: string[];
    withClues: boolean;
  };
};

const questionVariants = {
  enter: {
    x: 50,
    opacity: 0,
  },
  center: {
    x: 0,
    opacity: 1,
  },
  exit: {
    x: -50,
    opacity: 0,
  },
};

const answerChecker = new AnswerChecker();

const CompleteParagraphWithoutClues = ({
  feedback,
  questions,
}: TCompleteParagraphWithoutCluesProps) => {
  const [score, setScore] = useState(0);
  const [allAnswered, setAllAnswered] = useState(false);
  const [showResults, setShowResults] = useState(false);
  const [userAnswers, setUserAnswers] = useState<string[]>(
    Array.from({ length: questions.answers.length }, () => ""),
  );
  const [isCorrectAnswers, setIsCorrectAnswers] = useState<boolean[]>(
    Array.from({ length: questions.answers.length }, () => false),
  );

  const { playSound } = useSoundEffects();

  // Check if all answers are filled
  const allAnswersFilled = useCallback(() => {
    return userAnswers.every((answer) => answer.trim() !== "");
  }, [userAnswers]);

  // Check answers and calculate score
  const checkAnswers = useCallback(() => {
    const correctnessArray = userAnswers.map(
      (answer, index) =>
        answerChecker.checkAnswer(answer.trim().toLowerCase(), {
          acceptedAnswers: [questions.answers[index].trim().toLowerCase()],
        }).isCorrect,
    );

    const newScore = correctnessArray.reduce(
      (acc, isCorrect) => (isCorrect ? acc + 1 : acc),
      0,
    );

    setIsCorrectAnswers(correctnessArray);
    setScore(newScore);
    setAllAnswered(true);

    // Play success sound if all correct, otherwise play failure sound
    playSound(newScore === questions.answers.length ? "success" : "failure");
  }, [userAnswers, questions.answers, playSound]);

  const handleInputChange = (index: number, value: string) => {
    const newAnswers = [...userAnswers];
    newAnswers[index] = value;
    setUserAnswers(newAnswers);
  };

  const resetActivity = () => {
    setScore(0);
    setAllAnswered(false);
    setShowResults(false);
    setUserAnswers(Array.from({ length: questions.answers.length }, () => ""));
    setIsCorrectAnswers(
      Array.from({ length: questions.answers.length }, () => false),
    );
  };

  const ResultsSummary = () => {
    const paragraphParts = questions.paragraph.split("___");

    return (
      <div
        className="bg-picton-blue-50 flex flex-col overflow-auto h-full justify-between w-full rounded-xl p-4"
        style={{
          fontSize: questions.fontSize ? `${questions.fontSize}px` : "18px",
        }}
      >
        <div className="p-4 leading-loose">
          {paragraphParts.map((part, i) => (
            <Fragment key={i}>
              <span>{part}</span>
              {i < paragraphParts.length - 1 && (
                <span className="mx-1">
                  {feedback === "wrong-correct-answers" ? (
                    <>
                      {userAnswers[i] && (
                        <span
                          className={cn(
                            "px-2 py-1 rounded font-medium",
                            isCorrectAnswers[i]
                              ? "bg-green-200 text-green-800"
                              : "bg-red-200 text-red-800 line-through mr-1",
                          )}
                        >
                          {userAnswers[i]}
                        </span>
                      )}
                      {(!userAnswers[i] || !isCorrectAnswers[i]) && (
                        <span className="bg-green-200 text-green-800 px-2 py-1 rounded font-medium">
                          {questions.answers[i]}
                        </span>
                      )}
                    </>
                  ) : (
                    <span
                      className={cn(
                        "px-2 py-1 rounded font-medium",
                        isCorrectAnswers[i]
                          ? "bg-green-200 text-green-800"
                          : "bg-red-200 text-red-800",
                      )}
                    >
                      {userAnswers[i] || "_____"}
                    </span>
                  )}
                </span>
              )}
            </Fragment>
          ))}
        </div>
      </div>
    );
  };

  const renderParagraphWithInputs = () => {
    const paragraphParts = questions.paragraph.split("___");

    return (
      <div className="text-lg leading-loose">
        {paragraphParts.map((part, i) => {
          // Split the part by spaces to handle individual words
          const words = part.split(" ");

          return (
            <Fragment key={i}>
              <span>
                {words.map((word, wordIndex) => (
                  <Fragment key={wordIndex}>
                    {wordIndex > 0 && " "}
                    <span
                      className={
                        word.startsWith("_")
                          ? "bg-yellow-100 text-lemon-700 p-1 rounded"
                          : ""
                      }
                    >
                      {word.startsWith("_") ? word?.slice(1) : word}
                    </span>
                  </Fragment>
                ))}
              </span>
              {i < paragraphParts.length - 1 && (
                <span className="inline-block mx-2 align-middle">
                  <Input
                    type="text"
                    value={userAnswers[i]}
                    onChange={(e) => handleInputChange(i, e.target.value)}
                    className="max-w-40 rounded-none border-none bg-transparent text-picton-blue-700 text-center !text-lg"
                    disabled={showResults}
                  />
                  <div className="border-b border-dashed border-picton-blue-700" />
                </span>
              )}
            </Fragment>
          );
        })}
      </div>
    );
  };

  return (
    <div className="h-full flex flex-col">
      <ActivityTitle title={questions.title} />

      {showResults ? (
        <>
          <ResultsSummary />
          <div className="w-full mt-4">
            <ActivityResults
              score={score}
              total={questions.answers.length}
              onRestart={resetActivity}
            />
          </div>
        </>
      ) : (
        <div
          className="flex flex-col gap-4 h-full"
          style={{
            fontSize: questions.fontSize ? `${questions.fontSize}px` : "18px",
          }}
        >
          <div className="flex flex-col md:flex-row gap-4 h-full">
            <AnimatePresence mode="wait">
              <motion.div
                variants={questionVariants}
                initial="enter"
                animate="center"
                exit="exit"
                transition={{
                  duration: 0.3,
                  type: "spring",
                  stiffness: 300,
                  damping: 30,
                }}
                className="bg-picton-blue-50 flex flex-col overflow-auto h-full w-full rounded-xl p-6 gap-4"
              >
                {questions.withClues && (
                  <div className="flex flex-wrap gap-4 bg-picton-blue-100 border-2 border-picton-blue-300 w-fit py-4 rounded">
                    {questions.options?.map((answer, i) => (
                      <p
                        key={i}
                        className="text-picton-blue-700 text-lg leading-4 px-3"
                      >
                        <span>{answer}</span>
                      </p>
                    ))}
                  </div>
                )}

                <div className="leading-loose">
                  {renderParagraphWithInputs()}
                </div>
              </motion.div>
            </AnimatePresence>
            {questions.image && (
              <div className="bg-white md:w-1/2 flex items-center justify-center rounded-xl p-4">
                <img
                  src={questions.image}
                  alt="complete paragraph with clues"
                  className="object-contain w-full max-h-[600px]"
                />
              </div>
            )}
          </div>
          <div className="flex justify-end">
            <Button disabled={!allAnswersFilled()} onClick={checkAnswers}>
              Check Answers
            </Button>
          </div>
        </div>
      )}

      <ActivityResultsAlertDialog
        score={score}
        total={questions.answers.length}
        open={allAnswered}
        onOpenChange={(open) => {
          if (!open) {
            if (feedback === "none") {
              resetActivity();
            } else {
              setShowResults(true);
            }
            setAllAnswered(false);
          }
        }}
      />
    </div>
  );
};

export default CompleteParagraphWithoutClues;
