// app/components/primary-sources/activities/counting-mixed-objects.vue
<script setup lang="ts">
import { ref, watch } from "vue";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { cn, shuffle } from "@/lib/utils";
import ActivityTitle from "@/components/templates/activity-title";
import ActivityResults, {
  ActivityResultsAlertDialog,
} from "@/components/templates/results";
import { useSoundEffects } from "~/composables/use-sound-effects";

type Props = {
  questions: {
    title: string;
    questions: { type: string; src: string; count: string }[];
  };
};

const props = defineProps<Props>();
const { playSound } = useSoundEffects();

const generateItems = () => {
  const items: { id: string; type: string; src: string }[] = [];

  props.questions.questions.forEach((question) => {
    const count = Number.parseInt(question.count, 10);
    for (let index = 0; index < count; index += 1) {
      items.push({
        id: `${question.type}-${index}`,
        type: question.type,
        src: question.src,
      });
    }
  });

  return shuffle(items);
};

const items = ref(generateItems());
const questionsState = ref(props.questions.questions);
const userCounts = ref<Record<string, string>>({});
const isCompleted = ref(false);
const isResultsDialogOpen = ref(false);
const score = ref(0);

const initializeCounts = () => {
  userCounts.value = props.questions.questions.reduce((acc, question) => {
    acc[question.type] = "";
    return acc;
  }, {} as Record<string, string>);
};

watch(
  () => props.questions,
  () => {
    items.value = generateItems();
    questionsState.value = props.questions.questions;
    initializeCounts();
    isCompleted.value = false;
    isResultsDialogOpen.value = false;
    score.value = 0;
  },
  { deep: true, immediate: true },
);

const checkAnswers = () =>
  props.questions.questions.reduce(
    (total, question) => total + (userCounts.value[question.type] === question.count ? 1 : 0),
    0,
  );

const handleComplete = () => {
  score.value = checkAnswers();
  isCompleted.value = true;
  isResultsDialogOpen.value = true;
  playSound("success");
};

const handleRestart = () => {
  isCompleted.value = false;
  initializeCounts();
  items.value = generateItems();
  questionsState.value = shuffle([...props.questions.questions]);
};

const handleCountChange = (type: string, value: string) => {
  if (value === "" || /^\d+$/.test(value)) {
    userCounts.value = {
      ...userCounts.value,
      [type]: value,
    };
  }
};
</script>

<template>
  <div class="flex h-full flex-col">
    <ActivityTitle :title="props.questions.title" />

    <div class="flex h-full flex-col gap-4">
      <div class="flex h-full flex-col gap-4 md:flex-row">
        <div class="relative flex h-full w-full flex-wrap items-center justify-center gap-2 rounded bg-picton-blue-50 p-4">
          <div
            v-for="(item, index) in items"
            :key="index"
            class="flex h-16 w-16 cursor-move items-center justify-center rounded border border-picton-blue-300 bg-picton-blue-100 transition-transform duration-300 hover:scale-125 md:h-24 md:w-24"
          >
            <img :src="item.src" :alt="item.type" class="max-h-full max-w-full">
          </div>
        </div>

        <div
          :class="
            cn('space-y-4 rounded bg-picton-blue-50 p-1 md:p-4', {
              'md:w-1/2': !isCompleted,
              'md:w-3/4': isCompleted,
            })
          "
        >
          <div class="flex flex-row gap-4 md:flex-col md:gap-4">
            <div
              v-for="(question, index) in questionsState"
              :key="index"
              :class="
                isCompleted
                  ? userCounts[question.type] === question.count
                    ? 'flex flex-col items-center rounded border border-green-200 bg-green-50 md:flex-row md:space-x-3 md:p-2'
                    : 'flex flex-col items-center rounded border border-red-200 bg-red-50 md:flex-row md:space-x-3 md:p-2'
                  : 'flex flex-col items-center md:flex-row md:space-x-3 md:p-2'
              "
            >
              <div class="flex h-10 items-center justify-center md:h-14">
                <img :src="question.src" :alt="question.type" class="h-full w-full object-contain">
              </div>

              <div class="inline-block align-middle">
                <Input
                  :model-value="userCounts[question.type]"
                  type="text"
                  maxlength="2"
                  :disabled="isCompleted"
                  :class="
                    isCompleted
                      ? userCounts[question.type] === question.count
                        ? 'max-w-24 rounded-none border-none bg-transparent px-0 text-center text-xl text-green-700 md:!text-4xl'
                        : 'max-w-24 rounded-none border-none bg-transparent px-0 text-center text-xl text-red-700 md:!text-4xl'
                      : 'max-w-24 rounded-none border-none bg-transparent px-0 text-center text-xl text-picton-blue-700 md:!text-4xl'
                  "
                  @update:model-value="
                    (value) => handleCountChange(question.type, String(value ?? ''))
                  "
                />
                <div
                  :class="
                    isCompleted
                      ? userCounts[question.type] === question.count
                        ? 'border-b border-dashed border-green-700'
                        : 'border-b border-dashed border-red-700'
                      : 'border-b border-dashed border-picton-blue-700'
                  "
                />
              </div>

              <div class="flex-1">
                <div v-if="isCompleted" class="mt-1 text-sm">
                  <span
                    :class="
                      userCounts[question.type] === question.count
                        ? 'font-semibold text-green-700'
                        : 'font-semibold text-red-700'
                    "
                  >
                    {{
                      userCounts[question.type] === question.count
                        ? "Correct!"
                        : `Incorrect. Answer: ${question.count}`
                    }}
                  </span>

                  <div class="mt-1 flex flex-wrap">
                    <div
                      v-for="visualIndex in Number.parseInt(question.count, 10)"
                      :key="visualIndex"
                      class="m-1 flex h-8 w-8 items-center justify-center"
                    >
                      <img :src="question.src" :alt="question.type" class="max-h-full max-w-full">
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <div v-if="!isCompleted" class="mx-auto w-fit md:mx-0 md:ml-auto">
            <Button
              variant="brand-lemon"
              :disabled="Object.values(userCounts).some((value) => value === '')"
              @click="handleComplete"
            >
              Check Answers
            </Button>
          </div>
        </div>
      </div>

      <ActivityResults
        v-if="isCompleted"
        :score="score"
        :total="props.questions.questions.length"
        :onRestart="handleRestart"
      />
    </div>

    <ActivityResultsAlertDialog
      :score="score"
      :total="props.questions.questions.length"
      :open="isResultsDialogOpen"
      :onOpenChange="(open: boolean) => { isResultsDialogOpen = open; }"
    />
  </div>
</template>

// app/components/primary-sources/activities/counting-mixed-objects.tsx
// App.tsx
import { CheckIcon } from "lucide-react";
import { useState, useRef, useEffect } from "react";

// Local imports
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { cn, shuffle } from "@/lib/utils";
import ActivityTitle from "@/components/templates/activity-title";
import { useSoundEffects } from "@/shared/hooks/use-sound-effects";
import ActivityResults, {
  ActivityResultsAlertDialog,
} from "@/components/templates/results";

type CountingMixedObjectsProps = {
  questions: {
    title: string;
    questions: { type: string; src: string; count: string }[];
  };
};

type Position = {
  x: number;
  y: number;
};

const CountingMixedObjectsActivity = ({
  questions,
}: CountingMixedObjectsProps) => {
  // Generate flattened array of all items based on their counts
  const generateItems = () => {
    const allItems: { id: string; type: string; src: string }[] = [];

    questions.questions.forEach((question) => {
      const count = parseInt(question.count);
      for (let i = 0; i < count; i++) {
        allItems.push({
          id: `${question.type}-${i}`,
          type: question.type,
          src: question.src,
        });
      }
    });

    return shuffle(allItems);
  };

  const [items, setItems] = useState(generateItems);
  const [questionsState, setQuestionsState] = useState(questions.questions);
  const [positions, setPositions] = useState<Record<string, Position>>({});
  const [userCounts, setUserCounts] = useState<Record<string, string>>(() => {
    const initialCounts: Record<string, string> = {} as Record<string, string>;
    questionsState.forEach((q) => {
      initialCounts[q.type] = "";
    });
    return initialCounts;
  });
  // Add state for activity completion and results
  const [isCompleted, setIsCompleted] = useState(false);
  const [isResultsDialogOpen, setIsResultsDialogOpen] = useState(false);
  const [score, setScore] = useState(0);

  const containerRef = useRef<HTMLDivElement | null>(null);
  const [containerBounds, setContainerBounds] = useState({
    width: 0,
    height: 0,
    left: 0,
    top: 0,
  });

  const { playSound } = useSoundEffects();

  // Get container dimensions on mount and resize
  useEffect(() => {
    const updateContainerBounds = () => {
      if (containerRef.current) {
        const { width, height, left, top } =
          containerRef.current.getBoundingClientRect();
        setContainerBounds({ width, height, left, top });
      }
    };

    updateContainerBounds();
    window.addEventListener("resize", updateContainerBounds);

    return () => {
      window.removeEventListener("resize", updateContainerBounds);
    };
  }, [isCompleted]);

  // Check answers and calculate score
  const checkAnswers = () => {
    let correctCount = 0;

    questions.questions.forEach((question) => {
      if (userCounts[question.type] === question.count) {
        correctCount++;
      }
    });

    return correctCount;
  };

  // Handle activity completion
  const handleComplete = () => {
    const calculatedScore = checkAnswers();
    setScore(calculatedScore);
    setIsCompleted(true);
    setIsResultsDialogOpen(true);
    playSound("success");
  };

  // Handle activity restart
  const handleRestart = () => {
    setIsCompleted(false);
    setUserCounts(() => {
      const initialCounts: Record<string, string> = {} as Record<
        string,
        string
      >;
      questions.questions.forEach((q) => {
        initialCounts[q.type] = "";
      });
      return initialCounts;
    });
    // Regenerate and reshuffle items
    setItems(generateItems());
    setQuestionsState(shuffle(questions.questions));
    // Reset positions (they'll be recalculated on next render)
    setPositions({});
  };

  const handleCountChange = (type: string, value: string) => {
    // Only allow numeric input
    if (value === "" || /^\d+$/.test(value)) {
      setUserCounts((prev) => ({
        ...prev,
        [type]: value,
      }));
    }
  };

  return (
    <div className="flex flex-col h-full">
      <ActivityTitle title={questions.title} />

      <div className="flex flex-col gap-4 h-full">
        <div className="flex flex-col md:flex-row gap-4 h-full">
          <div className="w-full h-full p-4 bg-picton-blue-50 rounded relative flex flex-wrap items-center justify-center gap-2">
            {items.map((item, i) => (
              <div
                key={i}
                className="w-16 md:w-24 h-16 md:h-24 flex items-center justify-center bg-picton-blue-100 hover:scale-125 transition-transform duration-300 border border-picton-blue-300 rounded cursor-move"
              >
                <img
                  src={item.src}
                  alt={item.type}
                  className="max-w-full max-h-full"
                />
              </div>
            ))}
          </div>
          <div
            className={cn(
              "p-1 md:p-4 bg-picton-blue-50 rounded space-y-4 md:space-y-0",
              {
                "md:w-1/2": !isCompleted,
                "md:w-3/4": isCompleted,
              },
            )}
          >
            <div className="md:space-y-4 flex flex-row md:flex-col md:gap-4">
              {questionsState.map((question, i) => (
                <div
                  key={i}
                  className={`flex flex-col md:flex-row items-center md:space-x-3 md:p-2 rounded ${
                    isCompleted
                      ? userCounts[question.type] === question.count
                        ? "bg-green-50 border border-green-200"
                        : "bg-red-50 border border-red-200"
                      : ""
                  }`}
                >
                  <div className="h-10 md:h-14 flex items-center justify-center">
                    <img
                      src={question.src}
                      alt={question.type}
                      className="w-full h-full object-contain"
                    />
                  </div>
                  <div>
                    <div className="inline-block mx-2 align-middle">
                      <Input
                        type="text"
                        value={userCounts[question.type]}
                        onChange={(e) =>
                          handleCountChange(question.type, e.target.value)
                        }
                        className={`max-w-24 rounded-none border-none bg-transparent text-center text-xl px-0 md:!text-4xl ${
                          isCompleted
                            ? userCounts[question.type] === question.count
                              ? "text-green-700"
                              : "text-red-700"
                            : "text-picton-blue-700"
                        }`}
                        maxLength={2}
                        disabled={isCompleted}
                      />
                      <div
                        className={`border-b border-dashed ${
                          isCompleted
                            ? userCounts[question.type] === question.count
                              ? "border-green-700"
                              : "border-red-700"
                            : "border-picton-blue-700"
                        }`}
                      />
                    </div>
                  </div>
                  <div className="flex-1">
                    <div className="flex flex-wrap gap-1">
                      {/* Show feedback when completed or when user has entered a value */}
                      {isCompleted && (
                        <div className="text-sm mt-1">
                          <span
                            className={`font-semibold ${
                              isCompleted &&
                              userCounts[question.type] !== question.count
                                ? "text-red-700"
                                : userCounts[question.type] === question.count
                                  ? "text-green-700"
                                  : ""
                            }`}
                          >
                            {userCounts[question.type] === question.count ? (
                              <span>
                                Correct!{" "}
                                <CheckIcon className="inline" size={16} />
                              </span>
                            ) : isCompleted ? (
                              `Incorrect. Answer: ${question.count}`
                            ) : (
                              `Answer: ${question.count}`
                            )}
                          </span>
                          <div className="flex flex-wrap mt-1">
                            {[...Array(parseInt(question.count))].map(
                              (_, i) => (
                                <div
                                  key={i}
                                  className="w-8 h-8 m-1 flex items-center justify-center"
                                >
                                  <img
                                    src={question.src}
                                    alt={question.type}
                                    className="max-w-full max-h-full"
                                  />
                                </div>
                              ),
                            )}
                          </div>
                        </div>
                      )}
                    </div>
                  </div>
                </div>
              ))}
            </div>
            {!isCompleted && (
              <div className="w-fit mx-auto md:mx-0 md:ml-auto">
                <Button
                  onClick={handleComplete}
                  variant="brand-lemon"
                  disabled={Object.values(userCounts).some(
                    (value) => value === "",
                  )}
                >
                  Check Answers
                </Button>
              </div>
            )}
          </div>
        </div>

        {isCompleted && (
          <ActivityResults
            score={score}
            total={questions.questions.length}
            onRestart={handleRestart}
          />
        )}
      </div>

      {/* Results Dialog */}
      <ActivityResultsAlertDialog
        score={score}
        total={questions.questions.length}
        open={isResultsDialogOpen}
        onOpenChange={(open) => {
          setIsResultsDialogOpen(open);
        }}
      />
    </div>
  );
};

export default CountingMixedObjectsActivity;
