// app/components/primary-sources/activities/fraction-operation-activity.tsx
import React, { useEffect, useState } from "react";
import { Check, X } from "lucide-react";
import { cn } from "@/lib/utils";
import { Button } from "@/components/ui/button";

interface FractionQuestion {
  id: number;
  question: string; // e.g. (3/10) + (5/10) =
  answers: string[]; // e.g. ["(8/10)", "(4/5)"]
}

interface FractionOperationActivityProps {
  questions: FractionQuestion[];
  feedback?: "wrong-correct" | "wrong-correct-answers" | "none";
  isExamMode?: boolean;
  onActivityComplete?: (
    score: number,
    totalQuestions: number,
    userAnswers: any[],
  ) => void;
}

const parseFraction = (str: string) => {
  // Remove brackets and split numerator/denominator
  const match = str.match(/\(([^/]+)\/(.+)\)/);
  if (match) {
    return { numerator: match[1], denominator: match[2] };
  }
  // If not a fraction, treat as whole number
  return { numerator: str.replace(/[()]/g, ""), denominator: undefined };
};

// Component to render fractions in questions
const FractionDisplay: React.FC<{ numerator: string; denominator: string }> = ({
  numerator,
  denominator,
}) => {
  return (
    <span className="inline-flex flex-col items-center mx-1 text-3xl">
      <span className="leading-none">{numerator}</span>
      <span className="border-t border-picton-blue-700 w-full"></span>
      <span className="leading-none">{denominator}</span>
    </span>
  );
};

// Component to render the question with proper fraction formatting
const QuestionDisplay: React.FC<{ question: string }> = ({ question }) => {
  const renderQuestion = () => {
    // Split the question by spaces and process each part
    const parts = question.split(/(\s+)/);

    return parts.map((part, index) => {
      // Check if this part is a fraction in parentheses
      const fractionMatch = part.match(/\((\d+)\/(\d+)\)/);
      if (fractionMatch) {
        const [, numerator, denominator] = fractionMatch;
        return (
          <FractionDisplay
            key={index}
            numerator={numerator}
            denominator={denominator}
          />
        );
      }
      // Return the part as-is (spaces, operators, etc.)
      return <span key={index}>{part}</span>;
    });
  };

  return <div className="flex items-center">{renderQuestion()}</div>;
};

const FractionInput: React.FC<{
  value: string;
  onChange: (val: string) => void;
  disabled?: boolean;
}> = ({ value, onChange, disabled }) => {
  // For fraction input, split by '/'
  const [num, setNum] = useState("");
  const [den, setDen] = useState("");

  useEffect(() => {
    if (value.includes("/")) {
      const [n, d] = value.split("/");
      setNum(n);
      setDen(d);
    } else {
      setNum(value);
      setDen("");
    }
  }, [value]);

  return (
    <div className="flex flex-col items-center justify-center bg-white border-gray-400 rounded-lg w-16">
      <input
        className="text-center text-2xl font-medium border-none outline-none w-full h-10"
        value={num}
        onChange={(e) => {
          setNum(e.target.value);
          onChange(den ? `${e.target.value}/${den}` : e.target.value);
        }}
        disabled={disabled}
        inputMode="numeric"
        placeholder=""
      />
      <div className="border-t border-gray-400 w-full" />
      <input
        className="text-center text-2xl font-medium border-none outline-none w-full h-10"
        value={den}
        onChange={(e) => {
          setDen(e.target.value);
          onChange(num ? `${num}/${e.target.value}` : e.target.value);
        }}
        disabled={disabled}
        inputMode="numeric"
        placeholder=""
      />
    </div>
  );
};

const FractionOperationActivity: React.FC<FractionOperationActivityProps> = ({
  questions,
  feedback = "wrong-correct",
  isExamMode,
  onActivityComplete,
}) => {
  const [userAnswers, setUserAnswers] = useState<string[]>(
    Array(questions.length).fill(""),
  );
  const [submitted, setSubmitted] = useState(false);

  const checkAnswer = (user: string, correct: string[]) => {
    // Accept if user answer matches any correct answer (ignoring spaces and brackets)
    const normalize = (s: string) => s.replace(/[()\s]/g, "");
    const normalizedUser = normalize(user);

    // Handle special case where user enters whole number but answer expects fraction format
    const checkVariations = (userAnswer: string, correctAnswers: string[]) => {
      return correctAnswers.some((ans) => {
        const normalizedAns = normalize(ans);
        // Direct match
        if (normalizedAns === normalizedUser) return true;

        // Check if user entered a fraction that equals a whole number
        if (userAnswer.includes("/")) {
          const [num, den] = userAnswer.split("/");
          if (num && den && parseInt(num) === parseInt(den)) {
            return normalizedAns === "1";
          }
        }

        // Check if user entered whole number but answer is fraction
        if (!userAnswer.includes("/") && ans.includes("/")) {
          const match = ans.match(/\((\d+)\/(\d+)\)/);
          if (match) {
            const [, num, den] = match;
            if (parseInt(num) === parseInt(den) && userAnswer === "1") {
              return true;
            }
          }
        }

        return false;
      });
    };

    return checkVariations(user, correct);
  };

  const handleSubmit = () => {
    setSubmitted(true);
    if (onActivityComplete) {
      const score = questions.reduce(
        (acc, q, i) => acc + (checkAnswer(userAnswers[i], q.answers) ? 1 : 0),
        0,
      );
      onActivityComplete(score, questions.length, userAnswers);
    }
  };

  return (
    <div className="h-full flex flex-col">
      <div className="flex-1 flex gap-4">
        <div className="flex flex-col w-full gap-4 h-full">
          <div className="bg-picton-blue-50 p-4 h-full">
            <div className="grid grid-cols-3 gap-6 h-full">
              {questions.map((q, idx) => {
                const isCorrect =
                  submitted && checkAnswer(userAnswers[idx], q.answers);
                const hasResult = submitted;

                return (
                  <div
                    key={q.id}
                    className={cn(
                      "flex gap-4 items-center justify-center rounded-lg p-6 relative",
                      hasResult &&
                        isCorrect &&
                        "bg-green-50 border-2 border-green-200",
                      hasResult &&
                        !isCorrect &&
                        "bg-red-50 border-2 border-red-200",
                      !hasResult && "bg-picton-blue-100",
                    )}
                  >
                    {/* Question Display */}
                    <div className="text-2xl font-medium text-center">
                      <QuestionDisplay question={q.question} />
                    </div>

                    {/* Fraction Input */}
                    <FractionInput
                      value={userAnswers[idx]}
                      onChange={(val) => {
                        const arr = [...userAnswers];
                        arr[idx] = val;
                        setUserAnswers(arr);
                      }}
                      disabled={submitted}
                    />

                    {/* Feedback Icon */}
                    {hasResult && (
                      <div
                        className={cn(
                          "flex items-center justify-center rounded-full p-1 absolute top-2 right-2",
                          isCorrect
                            ? "bg-green-100 text-green-600"
                            : "bg-red-100 text-red-600",
                        )}
                      >
                        {isCorrect ? (
                          <Check className="h-5 w-5" />
                        ) : (
                          <X className="h-5 w-5" />
                        )}
                      </div>
                    )}

                    {/* Show correct answer if wrong and feedback allows it */}
                    {hasResult &&
                      !isCorrect &&
                      feedback === "wrong-correct-answers" && (
                        <div className="mt-2 text-center">
                          <p className="text-sm text-gray-500">
                            Correct answer:
                          </p>
                          <p className="text-green-600 font-medium">
                            {q.answers[0]} {/* Show first correct answer */}
                          </p>
                        </div>
                      )}
                  </div>
                );
              })}
            </div>
          </div>

          {/* Submit Button */}
          {!submitted && (
            <div className="flex justify-end p-4">
              <Button
                // className="bg-picton-blue-500 hover:bg-picton-blue-600 text-white px-8 py-3 rounded-lg text-lg font-medium shadow-md transition-colors"
                onClick={handleSubmit}
              >
                Check Answers
              </Button>
            </div>
          )}

          {/* Score Display */}
          {submitted && feedback !== "none" && (
            <div className="bg-picton-blue-50 p-4 text-center">
              <div className="text-xl font-bold text-gray-700">
                Score:{" "}
                {questions.reduce(
                  (acc, q, i) =>
                    acc + (checkAnswer(userAnswers[i], q.answers) ? 1 : 0),
                  0,
                )}
                /{questions.length}
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

export default FractionOperationActivity;

// app/components/primary-sources/activities/fraction-operation-activity.vue
<script setup lang="ts">
import { computed, ref } from "vue";
import { cn } from "@/lib/utils";
import { Button } from "@/components/ui/button";

type FractionQuestion = {
  id: number;
  question: string;
  answers: string[];
};

type Props = {
  questions: FractionQuestion[];
  feedback?: "wrong-correct" | "wrong-correct-answers" | "none";
  isExamMode?: boolean;
  onActivityComplete?: (
    score: number,
    totalQuestions: number,
    userAnswers: string[],
  ) => void;
};

const props = withDefaults(defineProps<Props>(), {
  feedback: "wrong-correct",
});

const userAnswers = ref<string[]>(Array.from({ length: props.questions.length }, () => ""));
const submitted = ref(false);

const parseQuestionParts = (question: string) =>
  question.split(/(\s+)/).map((part, index) => {
    const match = part.match(/\((\d+)\/(\d+)\)/);
    if (!match) {
      return { key: `${index}-${part}`, type: "text" as const, text: part };
    }

    return {
      key: `${index}-${part}`,
      type: "fraction" as const,
      numerator: match[1],
      denominator: match[2],
    };
  });

const normalize = (value: string) => value.replace(/[()\s]/g, "");

const checkAnswer = (userAnswer: string, correctAnswers: string[]) =>
  correctAnswers.some((answer) => {
    const normalizedAnswer = normalize(answer);
    const normalizedUser = normalize(userAnswer);

    if (normalizedAnswer === normalizedUser) {
      return true;
    }

    if (userAnswer.includes("/")) {
      const [num, den] = userAnswer.split("/");
      if (num && den && Number.parseInt(num, 10) === Number.parseInt(den, 10)) {
        return normalizedAnswer === "1";
      }
    }

    if (!userAnswer.includes("/") && answer.includes("/")) {
      const match = answer.match(/\((\d+)\/(\d+)\)/);
      if (match && Number.parseInt(match[1], 10) === Number.parseInt(match[2], 10)) {
        return userAnswer.trim() === "1";
      }
    }

    return false;
  });

const score = computed(() =>
  props.questions.reduce(
    (total, question, index) =>
      total + (checkAnswer(userAnswers.value[index], question.answers) ? 1 : 0),
    0,
  ),
);

const parseInputValue = (value: string) => {
  if (value.includes("/")) {
    const [numerator = "", denominator = ""] = value.split("/");
    return { numerator, denominator };
  }

  return { numerator: value, denominator: "" };
};

const updateAnswerPart = (
  index: number,
  part: "numerator" | "denominator",
  value: string,
) => {
  const current = parseInputValue(userAnswers.value[index]);
  const next = { ...current, [part]: value };

  userAnswers.value[index] =
    next.denominator || part === "denominator"
      ? `${next.numerator}/${next.denominator}`
      : next.numerator;
};

const handleSubmit = () => {
  submitted.value = true;
  props.onActivityComplete?.(score.value, props.questions.length, userAnswers.value);
};
</script>

<template>
  <div class="flex h-full flex-col">
    <div class="flex flex-1 gap-4">
      <div class="flex h-full w-full flex-col gap-4">
        <div class="h-full bg-picton-blue-50 p-4">
          <div class="grid h-full grid-cols-1 gap-6 xl:grid-cols-3">
            <div
              v-for="(question, index) in props.questions"
              :key="question.id"
              :class="
                cn(
                  'relative flex items-center justify-center gap-4 rounded-lg p-6',
                  !submitted && 'bg-picton-blue-100',
                  submitted && checkAnswer(userAnswers[index], question.answers) && 'border-2 border-green-200 bg-green-50',
                  submitted && !checkAnswer(userAnswers[index], question.answers) && 'border-2 border-red-200 bg-red-50',
                )
              "
            >
              <div class="text-center text-2xl font-medium">
                <div class="flex items-center">
                  <template v-for="part in parseQuestionParts(question.question)" :key="part.key">
                    <span v-if="part.type === 'text'">{{ part.text }}</span>
                    <span v-else class="mx-1 inline-flex flex-col items-center text-3xl">
                      <span class="leading-none">{{ part.numerator }}</span>
                      <span class="w-full border-t border-picton-blue-700" />
                      <span class="leading-none">{{ part.denominator }}</span>
                    </span>
                  </template>
                </div>
              </div>

              <div class="flex w-16 flex-col items-center justify-center rounded-lg border border-gray-400 bg-white">
                <input
                  :value="parseInputValue(userAnswers[index]).numerator"
                  :disabled="submitted"
                  inputmode="numeric"
                  class="h-10 w-full border-none text-center text-2xl font-medium outline-none"
                  @input="updateAnswerPart(index, 'numerator', ($event.target as HTMLInputElement).value)"
                >
                <div class="w-full border-t border-gray-400" />
                <input
                  :value="parseInputValue(userAnswers[index]).denominator"
                  :disabled="submitted"
                  inputmode="numeric"
                  class="h-10 w-full border-none text-center text-2xl font-medium outline-none"
                  @input="updateAnswerPart(index, 'denominator', ($event.target as HTMLInputElement).value)"
                >
              </div>

              <div
                v-if="submitted"
                :class="
                  cn(
                    'absolute right-2 top-2 flex items-center justify-center rounded-full p-1',
                    checkAnswer(userAnswers[index], question.answers)
                      ? 'bg-green-100 text-green-600'
                      : 'bg-red-100 text-red-600',
                  )
                "
              >
                {{ checkAnswer(userAnswers[index], question.answers) ? "✓" : "✕" }}
              </div>

              <div
                v-if="
                  submitted &&
                  !checkAnswer(userAnswers[index], question.answers) &&
                  props.feedback === 'wrong-correct-answers'
                "
                class="mt-2 text-center"
              >
                <p class="text-sm text-gray-500">Correct answer:</p>
                <p class="font-medium text-green-600">{{ question.answers[0] }}</p>
              </div>
            </div>
          </div>
        </div>

        <div v-if="!submitted" class="flex justify-end p-4">
          <Button @click="handleSubmit">Check Answers</Button>
        </div>

        <div v-else-if="props.feedback !== 'none'" class="bg-picton-blue-50 p-4 text-center">
          <div class="text-xl font-bold text-gray-700">Score: {{ score }}/{{ props.questions.length }}</div>
        </div>
      </div>
    </div>
  </div>
</template>
