// app/components/primary-sources/activities/matching-items-picture-text.tsx
"use client";

import { DragEndEvent, DragMoveEvent, DragStartEvent } from "@dnd-kit/core";
import { useState, Fragment, useCallback, memo, useEffect } from "react";

// Local imports
import { cn, getImageUrl, shuffle } from "@/lib/utils";
import DNDContext from "@/components/layout/dnd-context";
import Droppable from "@/components/ui/dnd/droppable";
import Draggable from "@/components/ui/dnd/draggable";
import ActivityTitle from "@/components/templates/activity-title";
import ActivityResults, {
  ActivityResultsAlertDialog,
} from "@/components/templates/results";
import { useSoundEffects } from "@/shared/hooks/use-sound-effects";
import { useObjects } from "@/hooks/useObjects";
import { GameModeWrapper, GameStats } from "@/components/ui/game-mode";
import { useWindowSize } from "@/shared/hooks/use-window-size";

type TMatchingItemsPictureTextActivityProps = {
  questions: {
    title: string;
    fontSize?: string;
    category: "text-to-text" | "image-to-text" | "image-to-image";
    leftItems: MatchingItem[];
    rightItems: MatchingItem[];
    isGameMode?: boolean;
    type?: string;
    gameTimeLimit?: number;
    useStrict?: boolean;
  };
};

interface MatchingItem {
  id: string;
  content: string | { color: string } | { imageSrc: string };
}

const MatchingItemsPictureTextActivity = ({
  questions: currentQuestion,
}: TMatchingItemsPictureTextActivityProps) => {
  // State to track completed objects for replay functionality
  const [completedObjectIds, setCompletedObjectIds] = useState<number[]>([]);

  // Fetch objects for game mode
  const { objects, loading, error, refetch } = useObjects({
    type: currentQuestion.isGameMode ? currentQuestion.type || null : null,
    limit: 6, // 6 pairs of items
    // useStrict: currentQuestion.useStrict,
  });

  // Convert objects to MatchingItem format for game mode
  const getGameItems = () => {
    if (!currentQuestion.isGameMode) {
      return {
        leftItems: currentQuestion.leftItems,
        rightItems: currentQuestion.rightItems,
      };
    }

    if (currentQuestion.category === "image-to-text") {
      // Matching items pictures game - image to syllables
      const leftItems = objects.map((obj) => ({
        id: String(obj.id),
        content: { imageSrc: getImageUrl(obj.imagePath, true) },
      }));
      const rightItems = objects.map((obj) => ({
        id: String(obj.id),
        content: obj.syllables || obj.name, // Use syllables or fallback to name
      }));
      return { leftItems, rightItems };
    } else {
      // Matching items game - object name to syllables
      const leftItems = objects.map((obj) => ({
        id: String(obj.id),
        content: obj.name,
      }));
      const rightItems = objects.map((obj) => ({
        id: String(obj.id),
        content: obj.syllables || obj.name, // Use syllables or fallback to name
      }));
      return { leftItems, rightItems };
    }
  };

  const { leftItems: gameLeftItems, rightItems: gameRightItems } =
    getGameItems();
  const [connections, setConnections] = useState<
    {
      "start-key": string;
      "start-position": { x: number; y: number };
      "end-key": string;
      "end-position": { x: number; y: number };
      isCorrect?: boolean;
    }[]
  >([]);
  const [dragStart, setDragStart] = useState<{ x: number; y: number } | null>(
    null,
  );
  const [score, setScore] = useState(0);
  const [allAnswered, setAllAnswered] = useState(false);
  const [showResults, setShowResults] = useState(false);
  const [dragEnd, setDragEnd] = useState<{ x: number; y: number } | null>(null);
  const [shuffledRightItems, setShuffledRightItems] = useState<MatchingItem[]>(
    [],
  );
  const [timeUp, setTimeUp] = useState(false);
  const [isResetting, setIsResetting] = useState(false);
  const [completedPairs, setCompletedPairs] = useState<Set<number>>(new Set());
  const [incorrectAttempts, setIncorrectAttempts] = useState<Set<number>>(
    new Set(),
  );

  const { width } = useWindowSize();
  const { playSound } = useSoundEffects();

  // Initial shuffling of right items
  useEffect(() => {
    if (currentQuestion.isGameMode && !loading && gameRightItems.length > 0) {
      // Reset game state when new objects are loaded
      setConnections([]);
      setScore(0);
      setAllAnswered(false);
      setShowResults(false);
      setTimeUp(false);
      setIsResetting(false);
      setCompletedPairs(new Set());
      setIncorrectAttempts(new Set());
      setShuffledRightItems(shuffle([...gameRightItems]));
    } else if (!currentQuestion.isGameMode) {
      setShuffledRightItems(shuffle([...currentQuestion.rightItems]));
    }
  }, [currentQuestion.isGameMode, loading, objects, gameRightItems.length]);

  useEffect(() => {
    // If all the connections are made, show the score
    const totalItems = currentQuestion.isGameMode
      ? gameLeftItems.length
      : currentQuestion.leftItems.length;
    if (connections.length === totalItems) {
      // Calculate the score
      const correctConnections = connections.filter(
        (connection) => connection.isCorrect,
      );

      setScore(correctConnections.length);

      setAllAnswered(true);

      // Update completed pairs for game mode
      if (currentQuestion.isGameMode) {
        const completedSet = new Set<number>();
        connections.forEach((_, index) => completedSet.add(index));
        setCompletedPairs(completedSet);
      }
    }
  }, [
    connections,
    currentQuestion.isGameMode,
    gameLeftItems.length,
    currentQuestion.leftItems.length,
  ]);

  const handleDragStart = useCallback((event: DragStartEvent) => {
    const { active } = event;

    // Get the id of the active draggable, get the element and get the position
    const el = document.getElementById(String(active.id));
    if (!el) return;

    const { x, y } = {
      x: el.offsetLeft + el.offsetWidth,
      y: el.offsetTop + el.offsetHeight / 2,
    };

    setDragStart({ x, y });
  }, []);

  const handleDragEnd = useCallback(
    (event: DragEndEvent) => {
      const { over, active } = event;

      if (over && String(over.id).startsWith("right-")) {
        const fromItem = String(active.id).split("-")[1];
        const toItem = String(over.id).split("-")[1];

        // Get the id of the active draggable, get the element and get the position
        const activeEl = document.getElementById(String(active.id));
        const overEl = document.getElementById(String(over.id));

        setDragStart(null);
        setDragEnd(null);

        playSound("click");

        if (activeEl && overEl) {
          setConnections((prevConnections) => {
            // Remove any existing connection to the same end-key or start-key
            const filteredConnections = prevConnections.filter(
              (connection) =>
                connection["start-key"] !== String(active.id) &&
                connection["end-key"] !== String(over.id),
            );

            // Check if the match is correct
            const leftItems = currentQuestion.isGameMode
              ? gameLeftItems
              : currentQuestion.leftItems;
            const rightItems = currentQuestion.isGameMode
              ? gameRightItems
              : currentQuestion.rightItems;

            const leftItem = leftItems.find(
              (item) => String(item.id) === fromItem,
            );
            const rightItem = rightItems.find(
              (item) => String(item.id) === toItem,
            );
            const isCorrect = leftItem?.id === rightItem?.id;

            // Track incorrect attempt for game mode
            if (!isCorrect && currentQuestion.isGameMode) {
              setIncorrectAttempts((prev) => new Set([...prev, Date.now()]));
            }

            return [
              ...filteredConnections,
              {
                "start-key": String(active.id),
                "start-position": {
                  x: activeEl.offsetLeft + activeEl.offsetWidth,
                  y: activeEl.offsetTop + activeEl.offsetHeight / 2,
                },
                "end-key": String(over.id),
                "end-position": {
                  x: overEl.offsetLeft,
                  y: overEl.offsetTop + overEl.offsetHeight / 2,
                },
                isCorrect,
              },
            ];
          });
        }
      } else {
        setDragStart(null);
        setDragEnd(null);
      }
    },
    [
      currentQuestion.leftItems,
      currentQuestion.rightItems,
      currentQuestion.isGameMode,
      gameLeftItems,
      gameRightItems,
    ],
  );

  const handleDragMove = useCallback((event: DragMoveEvent) => {
    const { active } = event;

    const el = document.getElementById(String(active.id));
    if (!el) return;

    const { x, y } = {
      x: event.delta.x + el.offsetWidth + el.offsetLeft,
      y: event.delta.y + el.offsetTop + el.offsetHeight / 2,
    };

    setDragEnd({ x, y });
  }, []);

  const endKeyHasConnection = (id: string) => {
    return connections.some((connection) => connection["end-key"] === id);
  };

  // Handle game time up
  const handleGameTimeUp = () => {
    if (!allAnswered && !timeUp) {
      setTimeUp(true);
      setAllAnswered(true);
      playSound("failure");
    }
  };

  // Handle game completion from timer
  const handleGameComplete = (stats: GameStats) => {
    if (!allAnswered && !timeUp) {
      setAllAnswered(true);
    }
  };

  // Handle reset after completion dialog
  const handleReset = () => {
    setIsResetting(true);
    setAllAnswered(false);
    setShowResults(true);

    setTimeout(() => {
      setIsResetting(false);
    }, 50);
  };

  // Handle play again
  const resetActivity = () => {
    setIsResetting(true);
    setConnections([]);
    setScore(0);
    setAllAnswered(false);
    setShowResults(false);
    setTimeUp(false);
    setCompletedPairs(new Set());
    setIncorrectAttempts(new Set());

    if (currentQuestion.isGameMode) {
      // Track completed objects before fetching new ones
      const newCompletedIds = objects.map((obj) => obj.id);
      const updatedCompletedIds = [
        ...new Set([...completedObjectIds, ...newCompletedIds]),
      ];
      setCompletedObjectIds(updatedCompletedIds);

      // For game mode, fetch new objects excluding completed ones
      refetch(updatedCompletedIds);
    } else {
      // For regular mode, reinitialize with existing items
      setShuffledRightItems(shuffle([...currentQuestion.rightItems]));
    }

    setTimeout(() => {
      setIsResetting(false);
    }, 100);
  };

  const renderItemContent = (item: MatchingItem) => {
    let content;
    if (typeof item.content === "string") {
      content = item.content;
    } else if ("imageSrc" in item.content) {
      content = (
        <div className="w-20 md:w-36 max-h-[400px]">
          <img
            src={item.content.imageSrc}
            alt={item.id}
            className="object-contain w-full h-full"
          />
        </div>
      );
    }

    return content;
  };

  // Show loading state for game mode
  if (currentQuestion.isGameMode && loading) {
    return (
      <div className="flex items-center justify-center h-full">
        <h1 className="text-2xl font-bold mb-4">Loading objects...</h1>
      </div>
    );
  }

  // Show error state for game mode
  if (currentQuestion.isGameMode && error) {
    return (
      <div className="flex items-center justify-center h-full">
        <h1 className="text-2xl font-bold mb-4 text-red-700">
          Error loading objects: {error}
        </h1>
      </div>
    );
  }

  // Show message if no objects found in game mode
  if (currentQuestion.isGameMode && !loading && gameLeftItems.length === 0) {
    return (
      <div className="flex items-center justify-center h-full">
        <h1 className="text-2xl font-bold mb-4">
          No objects found for the specified criteria
        </h1>
      </div>
    );
  }

  const leftItemsToRender = currentQuestion.isGameMode
    ? gameLeftItems
    : currentQuestion.leftItems;
  const totalPairs = leftItemsToRender.length;

  return (
    <GameModeWrapper
      isGameMode={currentQuestion.isGameMode || false}
      totalQuestions={totalPairs}
      completedQuestions={completedPairs}
      incorrectQuestions={incorrectAttempts}
      totalTimeLimit={currentQuestion.gameTimeLimit}
      onTimeUp={handleGameTimeUp}
      onGameComplete={handleGameComplete}
      showTimer={currentQuestion.isGameMode || false}
      showProgress={currentQuestion.isGameMode || false}
      className="h-full"
    >
      <div className="flex flex-col h-full text-lg">
        <ActivityTitle title={currentQuestion.title} />

        <DNDContext
          onDragStart={handleDragStart}
          onDragEnd={handleDragEnd}
          onDragMove={handleDragMove}
        >
          <div
            className="flex justify-between h-full md:p-4 relative overflow-hidden"
            style={{
              fontSize:
                width <= 640
                  ? "14px"
                  : `${currentQuestion.fontSize}px` || "20px",
            }}
          >
            <div
              className={cn("space-y-4 flex flex-col justify-evenly", {
                "md:w-[15%]":
                  currentQuestion.category === "image-to-image" ||
                  currentQuestion.category === "image-to-text",
                "w-[30%]": currentQuestion.category === "text-to-text",
              })}
            >
              {leftItemsToRender.map((item, i) => {
                // Optimize className logic to avoid complex conditions during drag
                let itemClassName =
                  "w-full bg-picton-blue-200 rounded-lg flex items-center justify-center p-1 md:p-4 relative";

                if (currentQuestion.category === "text-to-text") {
                  itemClassName += " min-h-20";
                }

                if (showResults) {
                  itemClassName += " cursor-default";
                  const connection = connections.find(
                    (conn) => conn["start-key"] === `left-${item.id}`,
                  );
                  if (connection?.isCorrect) {
                    itemClassName = itemClassName.replace(
                      "bg-picton-blue-200",
                      "bg-green-100 border-2 border-green-300",
                    );
                  } else if (connection && !connection.isCorrect) {
                    itemClassName = itemClassName.replace(
                      "bg-picton-blue-200",
                      "bg-red-100 border-2 border-red-300",
                    );
                  }
                }

                return (
                  <Draggable
                    key={i}
                    id={`left-${item.id}`}
                    resize={false}
                    disabled={showResults}
                    className={itemClassName}
                  >
                    <span className="pointer-events-none">
                      {renderItemContent(item)}
                    </span>
                  </Draggable>
                );
              })}
            </div>
            <div
              className={cn("space-y-4 flex flex-col justify-evenly", {
                "md:w-[15%]": currentQuestion.category === "image-to-image",
                "w-[30%] md:w-auto md:max-w-xl":
                  currentQuestion.category === "text-to-text" ||
                  currentQuestion.category === "image-to-text",
              })}
            >
              {shuffledRightItems.map((item, i) => {
                // Optimize className logic to avoid complex conditions during drag
                let itemClassName =
                  "w-full rounded-lg flex items-center justify-start relative p-1 md:p-4";

                if (
                  currentQuestion.category === "text-to-text" ||
                  currentQuestion.category === "image-to-text"
                ) {
                  itemClassName += " p-2 md:p-4 leading-5";
                }

                if (currentQuestion.category === "image-to-image") {
                  itemClassName += " !justify-center";
                }

                if (
                  currentQuestion.category === "text-to-text" ||
                  currentQuestion.category === "image-to-text"
                ) {
                  itemClassName += " min-h-20";
                }

                if (showResults) {
                  itemClassName += " cursor-default";
                  const connection = connections.find(
                    (conn) => conn["end-key"] === `right-${item.id}`,
                  );
                  if (connection?.isCorrect) {
                    itemClassName += " bg-green-100 border-2 border-green-300";
                  } else if (connection && !connection.isCorrect) {
                    itemClassName += " bg-red-100 border-2 border-red-300";
                  } else {
                    itemClassName += " bg-picton-blue-50";
                  }
                } else {
                  const hasConnection = endKeyHasConnection(`right-${item.id}`);
                  if (hasConnection) {
                    itemClassName += " bg-lemon-100 text-lemon-700";
                  } else {
                    itemClassName += " bg-picton-blue-50";
                  }
                }

                return (
                  <Droppable
                    key={i}
                    id={`right-${item.id}`}
                    disabled={showResults}
                    isOverClassName="bg-lemon-50"
                    className={itemClassName}
                  >
                    {renderItemContent(item)}
                  </Droppable>
                );
              })}
            </div>

            {/* Connection lines */}
            <DrawLines
              connections={connections}
              dragStart={showResults ? null : dragStart}
              dragEnd={showResults ? null : dragEnd}
              showCorrectness={showResults}
            />

            {/* Results overlay with animated feedback */}
            {showResults && (
              <div className="absolute inset-0 pointer-events-none">
                {/* Correctness indicators for left items */}
                <div
                  className={cn(
                    "absolute space-y-4 flex flex-col justify-evenly",
                    {
                      "w-[15%]":
                        currentQuestion.category === "image-to-image" ||
                        currentQuestion.category === "image-to-text",
                      "w-[30%]": currentQuestion.category === "text-to-text",
                    },
                  )}
                  style={{
                    top: "1rem",
                    left: "1rem",
                    height: "calc(100% - 2rem)",
                  }}
                >
                  {leftItemsToRender.map((item, i) => {
                    const connection = connections.find(
                      (conn) => conn["start-key"] === `left-${item.id}`,
                    );
                    return (
                      <div
                        key={i}
                        className="relative w-full h-full flex items-center justify-center"
                      >
                        {connection && (
                          <div
                            className={cn(
                              "absolute -top-2 -right-2 w-6 h-6 rounded-full flex items-center justify-center text-white text-sm font-bold z-10 shadow-lg",
                              {
                                "bg-green-500": connection.isCorrect,
                                "bg-red-500": !connection.isCorrect,
                              },
                            )}
                          >
                            {connection.isCorrect ? "✓" : "✗"}
                          </div>
                        )}
                      </div>
                    );
                  })}
                </div>

                {/* Correctness indicators for right items */}
                <div
                  className={cn(
                    "absolute space-y-4 flex flex-col justify-evenly",
                    {
                      "w-[15%]": currentQuestion.category === "image-to-image",
                      "w-[30%]": currentQuestion.category === "text-to-text",
                      "max-w-xl": currentQuestion.category === "image-to-text",
                    },
                  )}
                  style={{
                    top: "1rem",
                    right: "1rem",
                    height: "calc(100% - 2rem)",
                    left: "auto",
                    // currentQuestion.category === "image-to-text"
                    //   ? "auto"
                    //   : currentQuestion.category === "image-to-image"
                    //     ? "70%"
                    //     : "70%",
                  }}
                >
                  {shuffledRightItems.map((item, i) => {
                    const connection = connections.find(
                      (conn) => conn["end-key"] === `right-${item.id}`,
                    );
                    return (
                      <div
                        key={i}
                        className="relative w-full h-full flex items-center justify-start"
                      >
                        {connection && (
                          <div
                            className={cn(
                              "absolute -top-2 -left-2 w-6 h-6 rounded-full flex items-center justify-center text-white text-sm font-bold z-10 shadow-lg",
                              {
                                "bg-green-500": connection.isCorrect,
                                "bg-red-500": !connection.isCorrect,
                              },
                            )}
                          >
                            {connection.isCorrect ? "✓" : "✗"}
                          </div>
                        )}
                      </div>
                    );
                  })}
                </div>
              </div>
            )}
          </div>
        </DNDContext>
        {showResults && (
          <ActivityResults
            score={timeUp ? 0 : score}
            total={totalPairs}
            onRestart={resetActivity}
          />
        )}

        <ActivityResultsAlertDialog
          score={timeUp ? 0 : score}
          total={totalPairs}
          open={allAnswered && !isResetting && !showResults}
          onOpenChange={(open) => {
            if (!open) {
              handleReset();
            }
          }}
          completionMessage={
            timeUp
              ? "⏰ Time's up! Don't worry, you can try again with new items. Keep practicing to improve your syllable matching skills!"
              : `Fantastic work! You successfully matched all ${totalPairs} pairs! Your syllable recognition skills are excellent!`
          }
        />
      </div>
    </GameModeWrapper>
  );
};

// Updated line drawing component with correctness indicators
const DrawLines = memo(
  ({
    connections,
    dragStart,
    dragEnd,
    showCorrectness = false,
  }: {
    connections: {
      "start-key": string;
      "start-position": { x: number; y: number };
      "end-key": string;
      "end-position": { x: number; y: number };
      isCorrect?: boolean;
    }[];
    dragStart: { x: number; y: number } | null;
    dragEnd: { x: number; y: number } | null;
    showCorrectness?: boolean;
  }) => {
    // Only recalculate positions once when showing results, not during drag
    const [recalculatedConnections, setRecalculatedConnections] = useState<
      typeof connections
    >([]);

    useEffect(() => {
      if (showCorrectness && connections.length > 0) {
        // Only recalculate once when results are first shown
        const updated = connections.map((connection) => {
          const startEl = document.getElementById(connection["start-key"]);
          const endEl = document.getElementById(connection["end-key"]);

          if (startEl && endEl) {
            return {
              ...connection,
              "start-position": {
                x: startEl.offsetLeft + startEl.offsetWidth,
                y: startEl.offsetTop + startEl.offsetHeight / 2,
              },
              "end-position": {
                x: endEl.offsetLeft,
                y: endEl.offsetTop + endEl.offsetHeight / 2,
              },
            };
          }

          return connection;
        });
        setRecalculatedConnections(updated);
      }
    }, [showCorrectness]);
    // Draw a line between two points using a div
    const renderLine = (
      start: { x: number; y: number },
      end: { x: number; y: number },
      key: string,
      isCorrect?: boolean,
    ) => {
      // Calculate distance between points
      const dx = end.x - start.x;
      const dy = end.y - start.y;
      const distance = Math.sqrt(dx * dx + dy * dy);

      // Calculate angle
      const angle = (Math.atan2(dy, dx) * 180) / Math.PI;

      const lineBackground = showCorrectness
        ? isCorrect
          ? "linear-gradient(to right, #22c55e 8px, transparent 8px)"
          : "linear-gradient(to right, #ef4444 8px, transparent 8px)"
        : "linear-gradient(to right, #a17507 5px, transparent 5px)";

      const lineWidth = showCorrectness ? (isCorrect ? "4px" : "3px") : "2px";

      return (
        <Fragment key={key}>
          {/* Start circle */}
          <div
            className={
              showCorrectness
                ? isCorrect
                  ? "bg-green-500"
                  : "bg-red-500"
                : "bg-lemon-700"
            }
            style={{
              position: "absolute",
              left: start.x - (showCorrectness ? 6 : 5),
              top: start.y - (showCorrectness ? 6 : 5),
              width: showCorrectness ? "12px" : "10px",
              height: showCorrectness ? "12px" : "10px",
              borderRadius: "50%",
              zIndex: 1,
              boxShadow: showCorrectness ? "0 2px 4px rgba(0,0,0,0.2)" : "none",
            }}
          />

          {/* Line */}
          <div
            style={{
              position: "absolute",
              left: start.x,
              top: start.y,
              width: `${distance}px`,
              height: lineWidth,
              backgroundImage: lineBackground,
              backgroundSize: showCorrectness
                ? "16px " + lineWidth
                : "10px " + lineWidth,
              backgroundRepeat: "repeat-x",
              transformOrigin: "0 0",
              transform: `rotate(${angle}deg)`,
              zIndex: 0,
              boxShadow: showCorrectness ? "0 2px 4px rgba(0,0,0,0.1)" : "none",
            }}
          />

          {/* End Circle */}
          <div
            className={
              showCorrectness
                ? isCorrect
                  ? "bg-green-500"
                  : "bg-red-500"
                : "bg-lemon-700"
            }
            style={{
              position: "absolute",
              left: end.x - (showCorrectness ? 6 : 5),
              top: end.y - (showCorrectness ? 6 : 5),
              width: showCorrectness ? "12px" : "10px",
              height: showCorrectness ? "12px" : "10px",
              borderRadius: "50%",
              zIndex: 1,
              boxShadow: showCorrectness ? "0 2px 4px rgba(0,0,0,0.2)" : "none",
            }}
          />
        </Fragment>
      );
    };

    const connectionsToRender =
      showCorrectness && recalculatedConnections.length > 0
        ? recalculatedConnections
        : connections;

    return (
      <div className="absolute top-0 left-0 w-full h-full pointer-events-none overflow-visible">
        {connectionsToRender.map((connection) =>
          renderLine(
            connection["start-position"],
            connection["end-position"],
            `${connection["start-key"]}-${connection["end-key"]}`,
            connection.isCorrect,
          ),
        )}

        {dragStart && dragEnd && renderLine(dragStart, dragEnd, "drag-line")}
      </div>
    );
  },
);

DrawLines.displayName = "DrawLines";

export default MatchingItemsPictureTextActivity;

// app/components/primary-sources/activities/matching-items-picture-text.vue
<script setup lang="ts">
// @ts-nocheck
import { computed, nextTick, ref, watch } from "vue";
import { useWindowSize } from "@vueuse/core";
import { cn, getImageUrl, shuffle } from "@/lib/utils";
import DNDContext from "@/components/layout/dnd-context";
import Droppable from "@/components/ui/dnd/droppable";
import Draggable from "@/components/ui/dnd/draggable";
import ActivityTitle from "@/components/templates/activity-title";
import ActivityResults, {
  ActivityResultsAlertDialog,
} from "@/components/templates/results";
import { useObjects } from "@/hooks/useObjects";
import GameModeWrapper from "@/components/ui/game-mode/game-mode-wrapper.vue";
import type { GameStats } from "@/components/ui/game-mode/types";
import { useSoundEffects } from "~/composables/use-sound-effects";

interface MatchingItem {
  id: string;
  content: string | { color: string } | { imageSrc: string };
}

interface Point {
  x: number;
  y: number;
}

interface Connection {
  "start-key": string;
  "start-position": Point;
  "end-key": string;
  "end-position": Point;
  isCorrect?: boolean;
}

type Props = {
  questions: {
    title: string;
    fontSize?: string;
    category: "text-to-text" | "image-to-text" | "image-to-image";
    leftItems: MatchingItem[];
    rightItems: MatchingItem[];
    isGameMode?: boolean;
    type?: string;
    gameTimeLimit?: number;
    useStrict?: boolean;
  };
};

type DragEndEvent = {
  active: { id: string };
  over?: { id: string };
};

const props = defineProps<Props>();
const { playSound } = useSoundEffects();
const { width } = useWindowSize();

const boardRef = ref<HTMLElement | null>(null);
const completedObjectIds = ref<number[]>([]);
const connections = ref<Connection[]>([]);
const recalculatedConnections = ref<Connection[]>([]);
const dragStart = ref<Point | null>(null);
const dragEnd = ref<Point | null>(null);
const score = ref(0);
const allAnswered = ref(false);
const showResults = ref(false);
const timeUp = ref(false);
const isResetting = ref(false);
const completedPairs = ref(new Set<number>());
const incorrectAttempts = ref(new Set<number>());
const shuffledRightItems = ref<MatchingItem[]>([]);

const { objects, loading, error, refetch } = useObjects({
  type: props.questions.isGameMode ? props.questions.type || null : null,
  limit: 6,
  autoFetch: !!props.questions.isGameMode,
});

const getGameItems = () => {
  if (!props.questions.isGameMode) {
    return {
      leftItems: props.questions.leftItems,
      rightItems: props.questions.rightItems,
    };
  }

  if (props.questions.category === "image-to-text") {
    return {
      leftItems: objects.value.map((obj) => ({
        id: String(obj.id),
        content: { imageSrc: getImageUrl(obj.imagePath, true) },
      })),
      rightItems: objects.value.map((obj) => ({
        id: String(obj.id),
        content: obj.syllables || obj.name,
      })),
    };
  }

  return {
    leftItems: objects.value.map((obj) => ({
      id: String(obj.id),
      content: obj.name,
    })),
    rightItems: objects.value.map((obj) => ({
      id: String(obj.id),
      content: obj.syllables || obj.name,
    })),
  };
};

const leftItems = computed(() => getGameItems().leftItems);
const rightItems = computed(() => getGameItems().rightItems);
const totalPairs = computed(() => leftItems.value.length);

const resetRoundState = () => {
  connections.value = [];
  recalculatedConnections.value = [];
  dragStart.value = null;
  dragEnd.value = null;
  score.value = 0;
  allAnswered.value = false;
  showResults.value = false;
  timeUp.value = false;
  completedPairs.value = new Set();
  incorrectAttempts.value = new Set();
};

watch(
  [() => leftItems.value, () => rightItems.value, loading],
  ([left, right, isLoading]) => {
    if (isLoading || !left.length || !right.length) return;

    resetRoundState();
    shuffledRightItems.value = shuffle([...right]);
  },
  { immediate: true },
);

watch(
  connections,
  (value) => {
    if (value.length !== leftItems.value.length || !leftItems.value.length) return;

    const correctConnections = value.filter((connection) => connection.isCorrect);
    score.value = correctConnections.length;
    allAnswered.value = true;

    if (props.questions.isGameMode) {
      const completedSet = new Set<number>();
      value.forEach((_, index) => completedSet.add(index));
      completedPairs.value = completedSet;
    }
  },
  { deep: true },
);

watch(
  [showResults, width],
  async ([resultsVisible]) => {
    if (!resultsVisible || !connections.value.length) return;

    await nextTick();
    refreshConnectionPositions();
  },
  { flush: "post" },
);

const boardFontSize = computed(() => {
  if (width.value <= 640) return "14px";
  return props.questions.fontSize ? `${props.questions.fontSize}px` : "20px";
});

const isImageItem = (item?: MatchingItem | null) =>
  !!item && typeof item.content !== "string" && "imageSrc" in item.content;

const getItemValue = (item?: MatchingItem | null) => {
  if (!item) return "";
  if (typeof item.content === "string") return item.content;
  if ("imageSrc" in item.content) return item.content.imageSrc;
  return "";
};

const getRelativePoint = (clientX: number, clientY: number): Point | null => {
  if (!boardRef.value) return null;

  const boardRect = boardRef.value.getBoundingClientRect();
  return {
    x: clientX - boardRect.left,
    y: clientY - boardRect.top,
  };
};

const getElementPoint = (element: HTMLElement, side: "start" | "end"): Point | null => {
  if (!boardRef.value) return null;

  const boardRect = boardRef.value.getBoundingClientRect();
  const rect = element.getBoundingClientRect();

  return {
    x: side === "start" ? rect.right - boardRect.left : rect.left - boardRect.left,
    y: rect.top + rect.height / 2 - boardRect.top,
  };
};

const refreshConnectionPositions = () => {
  recalculatedConnections.value = connections.value.map((connection) => {
    const startEl = document.getElementById(connection["start-key"]);
    const endEl = document.getElementById(connection["end-key"]);

    if (!(startEl instanceof HTMLElement) || !(endEl instanceof HTMLElement)) {
      return connection;
    }

    const startPosition = getElementPoint(startEl, "start");
    const endPosition = getElementPoint(endEl, "end");

    if (!startPosition || !endPosition) {
      return connection;
    }

    return {
      ...connection,
      "start-position": startPosition,
      "end-position": endPosition,
    };
  });
};

const handleDragStartCapture = (event: DragEvent) => {
  if (showResults.value || timeUp.value) return;

  const target = event.target instanceof HTMLElement
    ? event.target.closest('[id^="left-"]')
    : null;

  if (!(target instanceof HTMLElement)) return;

  const startPoint = getElementPoint(target, "start");
  if (!startPoint) return;

  dragStart.value = startPoint;
  dragEnd.value = startPoint;
};

const handleDragOverBoard = (event: DragEvent) => {
  if (!dragStart.value) return;

  event.preventDefault();

  const nextPoint = getRelativePoint(event.clientX, event.clientY);
  if (!nextPoint) return;

  dragEnd.value = nextPoint;
};

const clearDragPreview = () => {
  dragStart.value = null;
  dragEnd.value = null;
};

const handleDragEnd = (event: DragEndEvent) => {
  const activeId = String(event.active?.id || "");
  const overId = String(event.over?.id || "");

  if (!activeId || !overId.startsWith("right-")) {
    clearDragPreview();
    return;
  }

  const fromItem = activeId.split("-")[1];
  const toItem = overId.split("-")[1];
  const activeEl = document.getElementById(activeId);
  const overEl = document.getElementById(overId);

  clearDragPreview();
  playSound("click");

  if (!(activeEl instanceof HTMLElement) || !(overEl instanceof HTMLElement)) {
    return;
  }

  const startPosition = getElementPoint(activeEl, "start");
  const endPosition = getElementPoint(overEl, "end");

  if (!startPosition || !endPosition) return;

  const leftItem = leftItems.value.find((item) => String(item.id) === fromItem);
  const rightItem = rightItems.value.find((item) => String(item.id) === toItem);
  const isCorrect = leftItem?.id === rightItem?.id;

  connections.value = [
    ...connections.value.filter(
      (connection) =>
        connection["start-key"] !== activeId &&
        connection["end-key"] !== overId,
    ),
    {
      "start-key": activeId,
      "start-position": startPosition,
      "end-key": overId,
      "end-position": endPosition,
      isCorrect,
    },
  ];

  if (!isCorrect && props.questions.isGameMode) {
    incorrectAttempts.value = new Set([
      ...incorrectAttempts.value,
      Date.now() + Math.random(),
    ]);
  }
};

const endKeyHasConnection = (id: string) =>
  connections.value.some((connection) => connection["end-key"] === id);

const connectionByStartKey = (id: string) =>
  connections.value.find((connection) => connection["start-key"] === id);

const connectionByEndKey = (id: string) =>
  connections.value.find((connection) => connection["end-key"] === id);

const handleGameTimeUp = () => {
  if (!allAnswered.value && !timeUp.value) {
    timeUp.value = true;
    allAnswered.value = true;
    playSound("failure");
  }
};

const handleGameComplete = (_stats: GameStats) => {
  if (!allAnswered.value && !timeUp.value) {
    allAnswered.value = true;
  }
};

const handleShowResults = async () => {
  isResetting.value = true;
  allAnswered.value = false;
  showResults.value = true;

  await nextTick();
  refreshConnectionPositions();

  window.setTimeout(() => {
    isResetting.value = false;
  }, 50);
};

const handleRestart = async () => {
  isResetting.value = true;
  resetRoundState();

  if (props.questions.isGameMode) {
    const updatedIds = [
      ...new Set([...completedObjectIds.value, ...objects.value.map((item) => item.id)]),
    ];
    completedObjectIds.value = updatedIds;
    await refetch(updatedIds);
  } else {
    shuffledRightItems.value = shuffle([...props.questions.rightItems]);
  }

  window.setTimeout(() => {
    isResetting.value = false;
  }, 100);
};

const connectionsToRender = computed(() =>
  showResults.value && recalculatedConnections.value.length
    ? recalculatedConnections.value
    : connections.value,
);

const buildLinePresentation = (
  start: Point,
  end: Point,
  key: string,
  isCorrect?: boolean,
) => {
  const dx = end.x - start.x;
  const dy = end.y - start.y;
  const distance = Math.sqrt(dx * dx + dy * dy);
  const angle = (Math.atan2(dy, dx) * 180) / Math.PI;

  const lineBackground = showResults.value
    ? isCorrect
      ? "linear-gradient(to right, #22c55e 8px, transparent 8px)"
      : "linear-gradient(to right, #ef4444 8px, transparent 8px)"
    : "linear-gradient(to right, #a17507 5px, transparent 5px)";

  const lineWidth = showResults.value ? (isCorrect ? "4px" : "3px") : "2px";
  const dotClass = showResults.value
    ? isCorrect
      ? "bg-green-500"
      : "bg-red-500"
    : "bg-lemon-700";

  return {
    key,
    startCircleClass: dotClass,
    endCircleClass: dotClass,
    startCircleStyle: {
      left: `${start.x - (showResults.value ? 6 : 5)}px`,
      top: `${start.y - (showResults.value ? 6 : 5)}px`,
      width: showResults.value ? "12px" : "10px",
      height: showResults.value ? "12px" : "10px",
      boxShadow: showResults.value ? "0 2px 4px rgba(0,0,0,0.2)" : "none",
    },
    lineStyle: {
      left: `${start.x}px`,
      top: `${start.y}px`,
      width: `${distance}px`,
      height: lineWidth,
      backgroundImage: lineBackground,
      backgroundSize: showResults.value ? `16px ${lineWidth}` : `10px ${lineWidth}`,
      transform: `rotate(${angle}deg)`,
      boxShadow: showResults.value ? "0 2px 4px rgba(0,0,0,0.1)" : "none",
    },
    endCircleStyle: {
      left: `${end.x - (showResults.value ? 6 : 5)}px`,
      top: `${end.y - (showResults.value ? 6 : 5)}px`,
      width: showResults.value ? "12px" : "10px",
      height: showResults.value ? "12px" : "10px",
      boxShadow: showResults.value ? "0 2px 4px rgba(0,0,0,0.2)" : "none",
    },
  };
};

const renderedConnections = computed(() =>
  connectionsToRender.value.map((connection) =>
    buildLinePresentation(
      connection["start-position"],
      connection["end-position"],
      `${connection["start-key"]}-${connection["end-key"]}`,
      connection.isCorrect,
    ),
  ),
);

const liveDragLine = computed(() => {
  if (!dragStart.value || !dragEnd.value || showResults.value) return null;
  return buildLinePresentation(dragStart.value, dragEnd.value, "drag-line");
});
</script>

<template>
  <div v-if="props.questions.isGameMode && loading" class="flex h-full items-center justify-center">
    <h1 class="text-2xl font-bold">Loading objects...</h1>
  </div>

  <div v-else-if="props.questions.isGameMode && error" class="flex h-full items-center justify-center">
    <h1 class="text-2xl font-bold text-red-700">Error loading objects: {{ error }}</h1>
  </div>

  <div v-else-if="props.questions.isGameMode && !leftItems.length" class="flex h-full items-center justify-center">
    <h1 class="text-2xl font-bold">No objects found for the specified criteria</h1>
  </div>

  <GameModeWrapper
    v-else
    class="h-full"
    :is-game-mode="!!props.questions.isGameMode"
    :total-questions="totalPairs"
    :completed-questions="completedPairs"
    :incorrect-questions="incorrectAttempts"
    :total-time-limit="props.questions.gameTimeLimit || 300"
    :on-time-up="handleGameTimeUp"
    :on-game-complete="handleGameComplete"
  >
    <div class="flex h-full flex-col text-lg">
      <ActivityTitle :title="props.questions.title" />

      <DNDContext :onDragEnd="handleDragEnd">
        <div
          ref="boardRef"
          class="relative flex h-full justify-between overflow-hidden md:p-4"
          :style="{ fontSize: boardFontSize }"
          @dragstart.capture="handleDragStartCapture"
          @dragover="handleDragOverBoard"
          @dragend.capture="clearDragPreview"
        >
          <div
            :class="
              cn('flex flex-col justify-evenly space-y-4', {
                'w-[30%]': props.questions.category === 'text-to-text',
                'md:w-[15%]':
                  props.questions.category === 'image-to-image'
                  || props.questions.category === 'image-to-text',
              })
            "
          >
            <Draggable
              v-for="item in leftItems"
              :id="`left-${item.id}`"
              :key="item.id"
              :resize="false"
              :disabled="showResults"
              :class="
                cn(
                  'relative flex w-full items-center justify-center rounded-lg bg-picton-blue-200 p-1 md:p-4',
                  props.questions.category === 'text-to-text' && 'min-h-20',
                  showResults && 'cursor-default',
                  showResults && connectionByStartKey(`left-${item.id}`)?.isCorrect && 'border-2 border-green-300 bg-green-100',
                  showResults && connectionByStartKey(`left-${item.id}`) && !connectionByStartKey(`left-${item.id}`)?.isCorrect && 'border-2 border-red-300 bg-red-100',
                )
              "
            >
              <span class="pointer-events-none">
                <div v-if="isImageItem(item)" class="max-h-[400px] w-20 md:w-36">
                  <img
                    :src="getItemValue(item)"
                    :alt="item.id"
                    class="pointer-events-none h-full w-full select-none object-contain"
                    draggable="false"
                  >
                </div>
                <span v-else>{{ getItemValue(item) }}</span>
              </span>
            </Draggable>
          </div>

          <div
            :class="
              cn('flex flex-col justify-evenly space-y-4', {
                'md:w-[15%]': props.questions.category === 'image-to-image',
                'w-[30%] md:w-auto md:max-w-xl':
                  props.questions.category === 'text-to-text'
                  || props.questions.category === 'image-to-text',
              })
            "
          >
            <Droppable
              v-for="item in shuffledRightItems"
              :id="`right-${item.id}`"
              :key="item.id"
              :disabled="showResults"
              isOverClassName="bg-lemon-50"
              :class="
                cn(
                  'relative flex w-full items-center justify-start rounded-lg p-1 md:p-4',
                  (props.questions.category === 'text-to-text'
                    || props.questions.category === 'image-to-text') && 'min-h-20 p-2 leading-5 md:p-4',
                  props.questions.category === 'image-to-image' && '!justify-center',
                  showResults && 'cursor-default',
                  showResults && connectionByEndKey(`right-${item.id}`)?.isCorrect && 'border-2 border-green-300 bg-green-100',
                  showResults && connectionByEndKey(`right-${item.id}`) && !connectionByEndKey(`right-${item.id}`)?.isCorrect && 'border-2 border-red-300 bg-red-100',
                  showResults && !connectionByEndKey(`right-${item.id}`) && 'bg-picton-blue-50',
                  !showResults && endKeyHasConnection(`right-${item.id}`) && 'bg-lemon-100 text-lemon-700',
                  !showResults && !endKeyHasConnection(`right-${item.id}`) && 'bg-picton-blue-50',
                )
              "
            >
              <div v-if="isImageItem(item)" class="max-h-[400px] w-20 md:w-36">
                <img
                  :src="getItemValue(item)"
                  :alt="item.id"
                  class="pointer-events-none h-full w-full select-none object-contain"
                  draggable="false"
                >
              </div>
              <span v-else>{{ getItemValue(item) }}</span>
            </Droppable>
          </div>

          <div class="pointer-events-none absolute inset-0 overflow-visible">
            <template v-for="line in renderedConnections" :key="line.key">
              <div
                :class="line.startCircleClass"
                class="absolute z-[1] rounded-full"
                :style="line.startCircleStyle"
              />
              <div
                class="absolute z-0 origin-top-left bg-repeat-x"
                :style="line.lineStyle"
              />
              <div
                :class="line.endCircleClass"
                class="absolute z-[1] rounded-full"
                :style="line.endCircleStyle"
              />
            </template>

            <template v-if="liveDragLine">
              <div
                :class="liveDragLine.startCircleClass"
                class="absolute z-[1] rounded-full"
                :style="liveDragLine.startCircleStyle"
              />
              <div
                class="absolute z-0 origin-top-left bg-repeat-x"
                :style="liveDragLine.lineStyle"
              />
              <div
                :class="liveDragLine.endCircleClass"
                class="absolute z-[1] rounded-full"
                :style="liveDragLine.endCircleStyle"
              />
            </template>
          </div>

          <div v-if="showResults" class="pointer-events-none absolute inset-0">
            <div
              :class="
                cn('absolute flex flex-col justify-evenly space-y-4', {
                  'w-[30%]': props.questions.category === 'text-to-text',
                  'w-[15%]':
                    props.questions.category === 'image-to-image'
                    || props.questions.category === 'image-to-text',
                })
              "
              style="top: 1rem; left: 1rem; height: calc(100% - 2rem);"
            >
              <div
                v-for="item in leftItems"
                :key="`${item.id}-indicator`"
                class="relative flex h-full w-full items-center justify-center"
              >
                <div
                  v-if="connectionByStartKey(`left-${item.id}`)"
                  :class="
                    cn(
                      'absolute -right-2 -top-2 z-10 flex h-6 w-6 items-center justify-center rounded-full text-sm font-bold text-white shadow-lg',
                      connectionByStartKey(`left-${item.id}`)?.isCorrect ? 'bg-green-500' : 'bg-red-500',
                    )
                  "
                >
                  {{ connectionByStartKey(`left-${item.id}`)?.isCorrect ? "✓" : "✗" }}
                </div>
              </div>
            </div>

            <div
              :class="
                cn('absolute flex flex-col justify-evenly space-y-4', {
                  'w-[15%]': props.questions.category === 'image-to-image',
                  'w-[30%]': props.questions.category === 'text-to-text',
                  'max-w-xl': props.questions.category === 'image-to-text',
                })
              "
              style="top: 1rem; right: 1rem; left: auto; height: calc(100% - 2rem);"
            >
              <div
                v-for="item in shuffledRightItems"
                :key="`${item.id}-indicator`"
                class="relative flex h-full w-full items-center justify-start"
              >
                <div
                  v-if="connectionByEndKey(`right-${item.id}`)"
                  :class="
                    cn(
                      'absolute -left-2 -top-2 z-10 flex h-6 w-6 items-center justify-center rounded-full text-sm font-bold text-white shadow-lg',
                      connectionByEndKey(`right-${item.id}`)?.isCorrect ? 'bg-green-500' : 'bg-red-500',
                    )
                  "
                >
                  {{ connectionByEndKey(`right-${item.id}`)?.isCorrect ? "✓" : "✗" }}
                </div>
              </div>
            </div>
          </div>
        </div>
      </DNDContext>

      <ActivityResults
        v-if="showResults"
        :score="timeUp ? 0 : score"
        :total="totalPairs"
        :on-restart="handleRestart"
      />

      <ActivityResultsAlertDialog
        :score="timeUp ? 0 : score"
        :total="totalPairs"
        :open="allAnswered && !isResetting && !showResults"
        :on-open-change="
          (open) => {
            if (open) {
              return;
            }
            handleShowResults();
          }
        "
      />
    </div>
  </GameModeWrapper>
</template>
