// app/components/primary-sources/activities/matching-with-letters.vue
<script setup lang="ts">
import { computed, ref, watch } from "vue";
import DNDContext from "@/components/layout/dnd-context";
import Droppable from "@/components/ui/dnd/droppable";
import Draggable from "@/components/ui/dnd/draggable";
import ActivityTitle from "@/components/templates/activity-title";
import ActivityResults, {
  ActivityResultsAlertDialog,
} from "@/components/templates/results";
import { shuffle } from "@/lib/utils";
import { useSoundEffects } from "~/composables/use-sound-effects";

type Props = {
  questions: {
    title: string;
    questions: {
      id: string;
      text: string;
      image?: string;
      correctAnswer: string;
    }[];
    answers: string[];
  };
};

type DragEndEvent = {
  active: { id: string };
  over?: { id: string };
};

const props = defineProps<Props>();
const { playSound } = useSoundEffects();

const createShuffledAnswers = (
  answers: string[],
  questions: Props["questions"]["questions"],
) => {
  const parts = answers.map((answer) => {
    const [prefix, ...rest] = answer.split("|");
    return {
      prefix,
      content: rest.join(".").trim(),
    };
  });

  const shuffledContents = shuffle(parts.map((part) => part.content));
  const contentToLetterMap = new Map<string, string>();

  parts.forEach((part) => {
    const newIndex = shuffledContents.findIndex((content) => content === part.content);
    if (newIndex !== -1) {
      contentToLetterMap.set(part.content, parts[newIndex].prefix);
    }
  });

  const correctAnswerMapping = new Map<string, string>();
  questions.forEach((question) => {
    const originalContent = parts.find((part) => part.prefix === question.correctAnswer)?.content;
    if (!originalContent) return;

    const newLetter = contentToLetterMap.get(originalContent);
    if (newLetter) {
      correctAnswerMapping.set(question.id, newLetter);
    }
  });

  return {
    shuffledAnswers: parts.map((part, index) => ({
      display: `${part.prefix}. ${shuffledContents[index]}`,
      letter: part.prefix,
      content: shuffledContents[index],
    })),
    correctAnswerMapping,
  };
};

const answers = ref<(string | undefined)[]>([]);
const score = ref(0);
const allAnswered = ref(false);
const showResults = ref(false);
const shuffledState = ref(createShuffledAnswers([...props.questions.answers], props.questions.questions));

watch(
  () => props.questions,
  () => {
    answers.value = [];
    score.value = 0;
    allAnswered.value = false;
    showResults.value = false;
    shuffledState.value = createShuffledAnswers(
      [...props.questions.answers],
      props.questions.questions,
    );
  },
  { deep: true, immediate: true },
);

watch(
  answers,
  (value) => {
    if (value.length === props.questions.questions.length && !value.includes(undefined)) {
      score.value = value.reduce((total, answer, index) => {
        const question = props.questions.questions[index];
        return total + (answer === shuffledState.value.correctAnswerMapping.get(question.id) ? 1 : 0);
      }, 0);
      allAnswered.value = true;
      playSound("success");
    }
  },
  { deep: true },
);

const availableAnswers = computed(() =>
  shuffledState.value.shuffledAnswers.filter((answer) => !answers.value.includes(answer.letter)),
);

const isAnswerCorrect = (questionIndex: number) => {
  const question = props.questions.questions[questionIndex];
  return answers.value[questionIndex] === shuffledState.value.correctAnswerMapping.get(question.id);
};

const handleDragEnd = (event: DragEndEvent) => {
  if (showResults.value) return;

  const draggedId = String(event.active?.id || "");
  if (!draggedId) return;

  if (!event.over) {
    answers.value = answers.value.map((answer) => (answer === draggedId ? undefined : answer));
    playSound("click");
    return;
  }

  const dropQuestion = props.questions.questions.find(
    (question) => question.id === String(event.over?.id),
  );

  if (!dropQuestion) return;

  const nextAnswers = [...answers.value];
  const existingIndex = nextAnswers.findIndex((answer) => answer === draggedId);
  if (existingIndex !== -1) {
    nextAnswers[existingIndex] = undefined;
  }

  nextAnswers[Number.parseInt(dropQuestion.id, 10) - 1] = draggedId;
  answers.value = nextAnswers;
  playSound("click");
};

const resetActivity = () => {
  answers.value = [];
  score.value = 0;
  allAnswered.value = false;
  showResults.value = false;
  shuffledState.value = createShuffledAnswers(
    [...props.questions.answers],
    props.questions.questions,
  );
};
</script>

<template>
  <div class="flex h-full flex-col">
    <ActivityTitle :title="props.questions.title" />

    <DNDContext :onDragEnd="handleDragEnd">
      <div class="flex h-full flex-col justify-between gap-4 overflow-auto md:flex-row">
        <div class="flex w-full flex-col justify-between rounded-xl bg-picton-blue-50 p-4 md:max-h-[calc(100dvh-100px)] md:overflow-y-auto">
          <div class="flex flex-col gap-y-4">
            <div
              v-for="(question, index) in props.questions.questions"
              :key="question.id"
              class="flex items-center gap-4 text-lg text-picton-blue-700"
            >
              <p>{{ index + 1 }}.</p>
              <div class="flex w-full items-center justify-between gap-4">
                <div class="flex flex-col items-center gap-2 sm:flex-row">
                  <img
                    v-if="question.image"
                    :src="question.image"
                    :alt="question.text"
                    class="h-16 sm:h-24"
                  >
                  <span>{{ question.text }}</span>
                </div>

                <div class="flex items-center gap-2">
                  <template v-if="answers[index]">
                    <div
                      v-if="showResults"
                      :class="
                        isAnswerCorrect(index)
                          ? 'flex h-10 w-14 items-center justify-center rounded bg-green-100 text-green-700'
                          : 'flex h-10 w-14 items-center justify-center rounded bg-red-100 text-red-700'
                      "
                    >
                      {{ answers[index] }}
                    </div>
                    <Draggable
                      v-else
                      :id="answers[index]!"
                      class="flex h-10 w-14 items-center justify-center rounded bg-lemon-200 text-xl font-semibold text-lemon-700"
                    >
                      {{ answers[index] }}
                    </Draggable>

                    <div v-if="showResults" :class="isAnswerCorrect(index) ? 'text-green-500' : 'text-red-500'">
                      {{ isAnswerCorrect(index) ? "✓" : "✕" }}
                    </div>
                  </template>

                  <Droppable
                    v-else
                    :id="question.id"
                    class="h-10 w-14 rounded bg-picton-blue-200"
                    isOverClassName="bg-lemon-200"
                  />
                </div>
              </div>
            </div>
          </div>

          <div class="flex w-full flex-col gap-y-4 rounded-xl">
            <ActivityResults
              v-if="showResults"
              :score="score"
              :total="props.questions.questions.length"
              :onRestart="resetActivity"
            />
            <template v-else>
              <h3 class="mb-2 font-semibold">Options</h3>
              <div class="flex flex-wrap gap-4 text-lg">
                <Draggable
                  v-for="(answer, index) in availableAnswers"
                  :key="index"
                  :id="answer.letter"
                  class="flex h-10 w-14 items-center justify-center rounded bg-lemon-200 text-xl font-semibold text-lemon-700"
                >
                  <span>{{ answer.letter }}</span>
                </Draggable>
              </div>
            </template>
          </div>
        </div>

        <div class="flex w-full flex-col gap-4 rounded-xl bg-picton-blue-50 p-4 text-lg md:max-h-[calc(100dvh-100px)] md:overflow-auto">
          <div
            v-for="(answer, index) in shuffledState.shuffledAnswers"
            :key="index"
            class="flex items-center gap-4"
          >
            <p>
              <span class="text-xl font-semibold">{{ answer.display.slice(0, 1) }})</span>
              <span>{{ answer.display.slice(2) }}</span>
            </p>
            <div class="h-10" />
          </div>
        </div>
      </div>
    </DNDContext>

    <ActivityResultsAlertDialog
      :score="score"
      :total="props.questions.questions.length"
      :open="allAnswered && !showResults"
      :onOpenChange="
        (open: boolean) => {
          allAnswered = false;
          if (!open) {
            showResults = true;
          }
        }
      "
    />
  </div>
</template>

// app/components/primary-sources/activities/matching-with-letters.tsx
"use client";

import { motion } from "motion/react";
import { Check, X } from "lucide-react";
import { DragEndEvent } from "@dnd-kit/core";
import React, { useEffect, useState } from "react";

// Local imports
import { shuffle } from "@/lib/utils";
import Droppable from "@/components/ui/dnd/droppable";
import Draggable from "@/components/ui/dnd/draggable";
import DNDContext from "@/components/layout/dnd-context";
import ActivityTitle from "@/components/templates/activity-title";
import { useSoundEffects } from "@/shared/hooks/use-sound-effects";
import ActivityResults, {
  ActivityResultsAlertDialog,
} from "@/components/templates/results";

type TMatchingWithLettersActivityProps = {
  questions: {
    title: string;
    questions: {
      id: string;
      text: string;
      image?: string;
      correctAnswer: string;
    }[];
    answers: string[];
  };
};

// Helper function to create properly shuffled answers and return correct mapping
const createShuffledAnswers = (answers: string[], questions: any[]) => {
  // Extract letter prefixes and content separately
  const parts = answers.map((answer) => {
    const parts = answer.split("|");
    const prefix = parts[0]; // Just the letter (e.g., "A") without the period
    const content = parts.slice(1).join(".").trim(); // The rest is content
    return { prefix, content };
  });

  // Keep prefixes in order, shuffle only the content
  const shuffledContents = shuffle([...parts.map((p) => p.content)]);

  // Create a mapping to track which letter corresponds to which content after shuffling
  const contentToLetterMap = new Map();

  // For each original content, find which letter it will be associated with after shuffling
  parts.forEach((part) => {
    const originalContent = part.content;
    const newIndex = shuffledContents.findIndex(
      (content) => content === originalContent,
    );
    if (newIndex !== -1) {
      // Map original content to the letter that will display it after shuffling
      contentToLetterMap.set(originalContent, parts[newIndex].prefix);
    }
  });

  // Create mapping for correct answers (question ID to correct letter after shuffling)
  const correctAnswerMapping = new Map();
  questions.forEach((q) => {
    const originalLetter = q.correctAnswer;
    // Find the original content for this letter
    const originalContent = parts.find(
      (p) => p.prefix === originalLetter,
    )?.content;
    if (originalContent) {
      // Get the new letter for this content after shuffling
      const newLetter = contentToLetterMap.get(originalContent);
      correctAnswerMapping.set(q.id, newLetter);
    }
  });

  // Recombine in original letter order but with shuffled content
  const theParts = parts.map((part, index) => {
    const newAnswer = `${part.prefix}. ${shuffledContents[index]}`;
    return {
      display: newAnswer,
      letter: part.prefix, // Just "A", "B", etc.
      originalIndex: index,
      content: shuffledContents[index],
    };
  });

  return { shuffledAnswers: theParts, correctAnswerMapping };
};

const MatchingWithLettersActivity = ({
  questions,
}: TMatchingWithLettersActivityProps) => {
  const [score, setScore] = useState(0);
  const [allAnswered, setAllAnswered] = useState(false);
  const [answers, setAnswers] = useState<(string | undefined)[]>([]);
  const [showResults, setShowResults] = useState(false);

  const { playSound } = useSoundEffects();

  // Track both shuffled answers and correct answer mapping
  const [shuffledState, setShuffledState] = useState(() => {
    return createShuffledAnswers([...questions.answers], questions.questions);
  });

  const shuffledAnswers = shuffledState.shuffledAnswers;
  const correctAnswerMapping = shuffledState.correctAnswerMapping;

  useEffect(() => {
    if (
      answers.length === questions.questions.length &&
      !answers.includes(undefined)
    ) {
      const score = answers.reduce((acc, answer, index) => {
        const question = questions.questions[index];
        // Use the correct answer mapping to check if the answer is correct
        const correctLetterForQuestion = correctAnswerMapping.get(question.id);
        return acc + (answer === correctLetterForQuestion ? 1 : 0);
      }, 0);
      setScore(score);
      setAllAnswered(true);
      playSound("success");
    }
  }, [answers, questions.questions, correctAnswerMapping]);

  const handleDragEnd = (event: DragEndEvent) => {
    const { active, over } = event;
    if (!active) return;

    // Don't allow changes when showing results
    if (showResults) return;

    // If there's no drop target (dragged outside droppable zones), remove the answer
    if (!over) {
      setAnswers((prevAnswers) => {
        const newAnswers = [...prevAnswers];
        const index = newAnswers.findIndex(
          (answer) => answer === String(active.id),
        );
        if (index !== -1) {
          newAnswers[index] = undefined;
        }
        return newAnswers;
      });
      playSound("click");
      return;
    }

    const question = questions.questions.find(
      (question) => question.id === String(over.id),
    );
    if (!question) return;

    // set the answer into the answers array on the same index as the question index.
    // If the answer is already their but the user wants to change it, then replace the answer.
    setAnswers((prevAnswers) => {
      const newAnswers = [...prevAnswers];
      const index = newAnswers.findIndex(
        (answer) => answer === String(active.id),
      );
      if (index !== -1) {
        newAnswers[index] = undefined;
      }
      newAnswers[parseInt(question.id) - 1] = String(active.id);
      return newAnswers;
    });

    playSound("click");
  };

  const resetActivity = () => {
    setShowResults(false);
    setAllAnswered(false);
    setScore(0);
    setAnswers([]);
    // Update both the shuffled answers and the correct answer mapping
    const newShuffledState = createShuffledAnswers(
      [...questions.answers],
      questions.questions,
    );
    setShuffledState(newShuffledState);
  };

  const isAnswerCorrect = (questionIndex: number) => {
    const question = questions.questions[questionIndex];
    const answer = answers[questionIndex];
    const correctLetter = correctAnswerMapping.get(question.id);
    return answer === correctLetter;
  };

  return (
    <div className="flex flex-col h-full">
      <ActivityTitle title={questions.title} />

      <DNDContext onDragEnd={handleDragEnd}>
        <div className="flex flex-col md:flex-row justify-between h-full overflow-auto gap-4">
          <div className="bg-picton-blue-50 flex flex-col justify-between w-full rounded-xl md:max-h-[calc(100dvh-100px)] md:overflow-y-auto p-4">
            <div className="flex flex-col gap-y-4">
              {questions.questions.map((question, index) => (
                <div
                  key={question.id}
                  className="flex gap-4 items-center text-picton-blue-700 text-lg"
                >
                  <p>{index + 1}.</p>
                  <div className="flex gap-4 items-center justify-between w-full">
                    <div className="flex flex-col sm:flex-row items-center gap-2">
                      {question.image && (
                        <img
                          src={question?.image}
                          alt={question.text}
                          className="h-16 sm:h-24"
                        />
                      )}
                      <span>{question.text}</span>
                    </div>
                    <div className="flex items-center gap-2">
                      {answers[index] ? (
                        <>
                          {showResults ? (
                            <div
                              className={`${
                                isAnswerCorrect(index)
                                  ? "bg-green-100 text-green-700"
                                  : "bg-red-100 text-red-700"
                              } rounded w-14 h-10 flex items-center justify-center`}
                            >
                              {answers[index]}
                            </div>
                          ) : (
                            <Draggable
                              id={answers[index]}
                              className="bg-lemon-200 text-lemon-700 rounded w-14 h-10 text-xl font-semibold flex items-center justify-center"
                            >
                              {answers[index]}
                            </Draggable>
                          )}
                          {showResults && (
                            <motion.div
                              initial={{ scale: 0 }}
                              animate={{ scale: 1 }}
                              transition={{
                                type: "spring",
                                stiffness: 260,
                                damping: 20,
                              }}
                            >
                              {isAnswerCorrect(index) ? (
                                <Check className="text-green-500" />
                              ) : (
                                <X className="text-red-500" />
                              )}
                            </motion.div>
                          )}
                        </>
                      ) : (
                        <Droppable
                          id={question.id}
                          isOverClassName="bg-lemon-200"
                          className="bg-picton-blue-200 rounded w-14 h-10"
                        ></Droppable>
                      )}
                    </div>
                  </div>
                </div>
              ))}
            </div>
            <div className="flex flex-col w-full rounded-xl gap-y-4">
              {showResults ? (
                <ActivityResults
                  score={score}
                  total={questions.questions.length}
                  onRestart={resetActivity}
                />
              ) : (
                <>
                  <h3 className="font-semibold mb-2">Options</h3>
                  <div className="flex flex-wrap gap-4 text-lg">
                    {!showResults &&
                      shuffledAnswers
                        .filter((answer) => !answers.includes(answer.letter))
                        .map((answer, i) => (
                          <Draggable
                            key={i}
                            id={answer.letter}
                            className="flex justify-center gap-4 rounded text-xl font-semibold w-14 h-10 items-center text-lemon-700 bg-lemon-200"
                          >
                            <span>{answer.letter}</span>
                          </Draggable>
                        ))}
                  </div>
                </>
              )}
            </div>
          </div>

          <div className="bg-picton-blue-50 w-full rounded-xl text-lg flex flex-col gap-4 p-4 md:max-h-[calc(100dvh-100px)] md:overflow-auto">
            {shuffledAnswers.map((answer, i) => (
              <div className="flex gap-4 items-center" key={i}>
                <p>
                  <span className="font-semibold text-xl">
                    {answer.display.slice(0, 1)})
                  </span>
                  <span>{answer.display.slice(2)}</span>
                </p>
                <div className="h-10" />
              </div>
            ))}
          </div>
        </div>
      </DNDContext>

      <ActivityResultsAlertDialog
        score={score}
        total={questions.questions.length}
        open={allAnswered && !showResults}
        onOpenChange={(open) => {
          setAllAnswered(false);
          if (!open) {
            setShowResults(true);
          }
        }}
      />
    </div>
  );
};

export default MatchingWithLettersActivity;
