// app/components/primary-sources/activities/missing-values.tsx
import { useState } from "react";
import * as motion from "motion/react-client";

// Local imports
import { shuffle } from "@/lib/utils";
import { Button } from "@/components/ui/button";
import CustomInput from "@/components/ui/inputs/custom-input";
import ActivityTitle from "@/components/templates/activity-title";
import { FeedbackType } from "@/lib/types/activity-types";
import ActivityResults, {
  ActivityResultsAlertDialog,
} from "@/components/templates/results";
import { Input } from "@/components/ui/input";

interface SequenceQuestion {
  title: string;
  questions: {
    id: string;
    sequence: (string | null)[];
    blankIndices: number[];
    correctAnswers: string[];
  }[];
}

interface MissingValuesActivityProps {
  feedback?: FeedbackType;
  questions: SequenceQuestion;
}

const MissingValuesActivity = ({
  feedback,
  questions: { title, questions: questionsProp },
}: MissingValuesActivityProps) => {
  const [questions, setQuestions] =
    useState<SequenceQuestion["questions"]>(questionsProp);
  const [answers, setAnswers] = useState<Record<string, string>>({});
  const [validations, setValidations] = useState<Record<string, boolean>>({});
  const [showFeedback, setShowFeedback] = useState<boolean>(false);

  // states for activity results
  const [isCompleted, setIsCompleted] = useState<boolean>(false);
  const [score, setScore] = useState<number>(0);
  const [showResultsDialog, setShowResultsDialog] = useState<boolean>(false);

  // Handle input changes
  const handleInputChange = (
    questionId: string,
    blankIndex: number,
    value: string
  ) => {
    const answerKey = `${questionId}-${blankIndex}`;
    // Allow any input - letters, numbers, symbols
    setAnswers({
      ...answers,
      [answerKey]: value,
    });
  };

  // Check answers
  const checkAnswers = () => {
    const newValidations: Record<string, boolean> = {};
    let correctCount = 0;

    questions.forEach((question) => {
      question.blankIndices.forEach((blankIndex, index) => {
        const answerKey = `${question.id}-${blankIndex}`;
        const userAnswer = answers[answerKey] || "";
        const expectedAnswer = question.correctAnswers[index];
        // Compare strings directly, case-sensitive
        const isCorrect = userAnswer.trim() === expectedAnswer;

        newValidations[answerKey] = isCorrect;
        if (isCorrect) {
          correctCount++;
        }
      });
    });

    if (feedback !== "none") {
      setShowFeedback(true);
    }

    setValidations(newValidations);
    setScore(correctCount);

    // Show results dialog
    setShowResultsDialog(true);
  };

  // Reset the activity
  const resetActivity = () => {
    setQuestions(shuffle(questionsProp));
    setAnswers({});
    setValidations({});
    setIsCompleted(false);
    setShowFeedback(false);
    setScore(0);
  };

  // Handle closing the results dialog
  const handleResultsDialogClose = (open: boolean) => {
    setShowResultsDialog(open);
    if (!open) {
      if (feedback === "none") {
        // If feedback is "none", reset the activity immediately
        resetActivity();
      } else {
        // Otherwise, mark as completed to show the feedback
        setIsCompleted(true);
      }
    }
  };

  // Get the input class based on feedback type and validation state
  const getInputClass = (answerKey: string) => {
    if (!showFeedback || feedback === "none") {
      return "border-gray-300 focus:border-blue-500 focus:outline-none";
    }

    return validations[answerKey]
      ? "text-green-600 border-green-500 bg-green-50"
      : "text-red-600 border-red-500 bg-red-50";
  };

  // Count total number of blank fields for scoring
  const getTotalBlanks = () => {
    return questions.reduce(
      (total, question) => total + question.blankIndices.length,
      0
    );
  };

  return (
    <div className="flex flex-col h-full">
      <ActivityTitle title={title} />

      <>
        <div className="space-y-4">
          {questions.map((question, i) => (
            <div
              key={question.id}
              className="flex items-center bg-picton-blue-50 px-2 py-4 md:p-4 rounded-lg"
            >
              <div className="font-bold text-lg mr-1">{i + 1}.</div>
              <div className="flex flex-wrap gap-2 flex-1">
                {question.sequence.map((number, index) => {
                  const isBlank = question.blankIndices.includes(index);
                  if (isBlank) {
                    const blankIndexPosition =
                      question.blankIndices.indexOf(index);
                    const correctAnswer =
                      question.correctAnswers[blankIndexPosition];
                    const answerKey = `${question.id}-${index}`;

                    return (
                      <motion.div
                        key={`q${question.id}-blank-${index}`}
                        initial={{ scale: 1 }}
                        animate={{
                          scale:
                            showFeedback && feedback !== "none"
                              ? validations[answerKey]
                                ? [1, 1.1, 1]
                                : [1, 0.9, 1]
                              : 1,
                          x:
                            showFeedback &&
                            !validations[answerKey] &&
                            feedback !== "none"
                              ? [0, -5, 5, -5, 5, 0]
                              : 0,
                        }}
                        transition={{ duration: 0.5 }}
                        className="relative"
                      >
                        <Input
                          value={answers[answerKey] || ""}
                          onChange={(e) =>
                            handleInputChange(
                              question.id,
                              index,
                              e.target.value
                            )
                          }
                          className={`w-[90px] h-12 border-2 text-center bg-transparent !text-2xl font-semibold rounded ${getInputClass(
                            answerKey
                          )}`}
                          disabled={showFeedback}
                        />
                      </motion.div>
                    );
                  }
                  return (
                    <div
                      key={`q${question.id}-${index}`}
                      className="bg-picton-blue-100 w-20 h-12 flex items-center justify-center text-lg font-semibold rounded"
                    >
                      {number !== null ? number : "_"}
                    </div>
                  );
                })}
              </div>
            </div>
          ))}
        </div>

        {!showFeedback ? (
          <Button
            variant="brand-lemon"
            onClick={checkAnswers}
            className="w-fit mx-auto mt-4"
          >
            Check Answers
          </Button>
        ) : (
          isCompleted && (
            <ActivityResults
              score={score}
              total={getTotalBlanks()}
              onRestart={resetActivity}
            />
          )
        )}
      </>

      <ActivityResultsAlertDialog
        score={score}
        total={getTotalBlanks()}
        open={showResultsDialog}
        onOpenChange={handleResultsDialogClose}
      />
    </div>
  );
};

export default MissingValuesActivity;

// app/components/primary-sources/activities/missing-values.vue
<script setup lang="ts">
import { computed, ref, watch } from "vue";
import ActivityTitle from "@/components/templates/activity-title";
import ActivityResults, {
  ActivityResultsAlertDialog,
} from "@/components/templates/results";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { shuffle } from "@/lib/utils";
import type { FeedbackType } from "@/lib/types/activity-types";

type SequenceQuestion = {
  title: string;
  questions: {
    id: string;
    sequence: (string | null)[];
    blankIndices: number[];
    correctAnswers: string[];
  }[];
};

type Props = {
  feedback?: FeedbackType;
  questions: SequenceQuestion;
};

const props = defineProps<Props>();

const questions = ref<SequenceQuestion["questions"]>([...props.questions.questions]);
const answers = ref<Record<string, string>>({});
const validations = ref<Record<string, boolean>>({});
const showFeedback = ref(false);
const isCompleted = ref(false);
const score = ref(0);
const showResultsDialog = ref(false);

watch(
  () => props.questions.questions,
  (value) => {
    questions.value = [...value];
    answers.value = {};
    validations.value = {};
    showFeedback.value = false;
    isCompleted.value = false;
    score.value = 0;
    showResultsDialog.value = false;
  },
  { deep: true },
);

const totalBlanks = computed(() =>
  questions.value.reduce((total, question) => total + question.blankIndices.length, 0),
);

const answerKey = (questionId: string, blankIndex: number) => `${questionId}-${blankIndex}`;

const handleInputChange = (questionId: string, blankIndex: number, value: string) => {
  answers.value = {
    ...answers.value,
    [answerKey(questionId, blankIndex)]: value,
  };
};

const checkAnswers = () => {
  const nextValidations: Record<string, boolean> = {};
  let correctCount = 0;

  questions.value.forEach((question) => {
    question.blankIndices.forEach((blankIndex, index) => {
      const key = answerKey(question.id, blankIndex);
      const userAnswer = answers.value[key] || "";
      const expectedAnswer = question.correctAnswers[index];
      const isCorrect = userAnswer.trim() === expectedAnswer;

      nextValidations[key] = isCorrect;
      if (isCorrect) {
        correctCount += 1;
      }
    });
  });

  if (props.feedback !== "none") {
    showFeedback.value = true;
  }

  validations.value = nextValidations;
  score.value = correctCount;
  showResultsDialog.value = true;
};

const resetActivity = () => {
  questions.value = shuffle([...props.questions.questions]);
  answers.value = {};
  validations.value = {};
  isCompleted.value = false;
  showFeedback.value = false;
  score.value = 0;
  showResultsDialog.value = false;
};

const handleResultsDialogClose = (open: boolean) => {
  showResultsDialog.value = open;
  if (!open) {
    if (props.feedback === "none") {
      resetActivity();
    } else {
      isCompleted.value = true;
    }
  }
};

const getInputClass = (key: string) => {
  if (!showFeedback.value || props.feedback === "none") {
    return "border-gray-300 focus:border-blue-500 focus:outline-none";
  }

  return validations.value[key]
    ? "border-green-500 bg-green-50 text-green-600"
    : "border-red-500 bg-red-50 text-red-600";
};
</script>

<template>
  <div class="flex h-full flex-col">
    <ActivityTitle :title="props.questions.title" />

    <div class="space-y-4">
      <div
        v-for="(question, questionIndex) in questions"
        :key="question.id"
        class="flex items-center rounded-lg bg-picton-blue-50 px-2 py-4 md:p-4"
      >
        <div class="mr-1 text-lg font-bold">{{ questionIndex + 1 }}.</div>
        <div class="flex flex-1 flex-wrap gap-2">
          <template v-for="(item, index) in question.sequence" :key="`q${question.id}-${index}`">
            <div
              v-if="!question.blankIndices.includes(index)"
              class="flex h-12 w-20 items-center justify-center rounded bg-picton-blue-100 text-lg font-semibold"
            >
              {{ item !== null ? item : "_" }}
            </div>

            <div v-else class="relative">
              <Input
                :model-value="answers[answerKey(question.id, index)] || ''"
                @update:model-value="
                  (value) => handleInputChange(question.id, index, String(value ?? ''))
                "
                :disabled="showFeedback"
                :class="[
                  'h-12 w-[90px] rounded border-2 bg-transparent text-center !text-2xl font-semibold',
                  getInputClass(answerKey(question.id, index)),
                ]"
              />
            </div>
          </template>
        </div>
      </div>
    </div>

    <Button
      v-if="!showFeedback"
      variant="brand-lemon"
      class="mx-auto mt-4 w-fit"
      @click="checkAnswers"
    >
      Check Answers
    </Button>

    <ActivityResults
      v-else-if="isCompleted"
      :score="score"
      :total="totalBlanks"
      :onRestart="resetActivity"
    />

    <ActivityResultsAlertDialog
      :score="score"
      :total="totalBlanks"
      :open="showResultsDialog"
      :onOpenChange="handleResultsDialogClose"
    />
  </div>
</template>
