// app/components/primary-sources/activities/number-matrix.tsx
import { useState } from "react";
import * as motion from "motion/react-client";

// Local imports
import { cn } from "@/lib/utils";
import { Button } from "@/components/ui/button";
import CustomInput from "@/components/ui/inputs/custom-input";
import ActivityTitle from "@/components/templates/activity-title";
import { FeedbackType } from "@/lib/types/activity-types";
import { useSoundEffects } from "@/shared/hooks/use-sound-effects";
import ActivityResults, {
  ActivityResultsAlertDialog,
} from "@/components/templates/results";

interface NumberMatrixQuestion {
  title: string;
  questions: {
    id: number;
    sequence: (number | string)[]; // Can be numbers or patterns like "1/1"
    patternIndices: number[]; // Indices where patterns occur
    correctAnswers: number[]; // Correct answers for the patterns
  }[];
}

interface NumberMatrixActivityProps {
  feedback?: FeedbackType;
  questions: NumberMatrixQuestion;
}

const NumberMatrixActivity = ({
  feedback,
  questions: { title, questions: questionsProp },
}: NumberMatrixActivityProps) => {
  const [questions, setQuestions] =
    useState<NumberMatrixQuestion["questions"]>(questionsProp);
  const [answers, setAnswers] = useState<Record<string, string>>({});
  const [validations, setValidations] = useState<Record<string, boolean>>({});
  const [showFeedback, setShowFeedback] = useState<boolean>(false);

  // states for activity results
  const [isCompleted, setIsCompleted] = useState<boolean>(false);
  const [score, setScore] = useState<number>(0);
  const [showResultsDialog, setShowResultsDialog] = useState<boolean>(false);

  const { playSound } = useSoundEffects();

  // Handle input changes
  const handleInputChange = (
    questionId: number,
    patternIndex: number,
    value: string,
  ) => {
    const answerKey = `${questionId}-${patternIndex}`;
    // Only allow numbers and empty strings
    if (value === "" || /^\d+$/.test(value)) {
      setAnswers({
        ...answers,
        [answerKey]: value,
      });
    }
  };

  // Check answers
  const checkAnswers = () => {
    const newValidations: Record<string, boolean> = {};
    let correctCount = 0;

    questions.forEach((question) => {
      question.patternIndices.forEach((patternIndex, index) => {
        const answerKey = `${question.id}-${patternIndex}`;
        const userAnswer = parseInt(answers[answerKey] || "", 10);
        const expectedAnswer = question.correctAnswers[index];
        const isCorrect = !isNaN(userAnswer) && userAnswer === expectedAnswer;

        newValidations[answerKey] = isCorrect;
        if (isCorrect) {
          correctCount++;
        }
      });
    });

    if (feedback !== "none") {
      setShowFeedback(true);
    }

    setValidations(newValidations);
    setScore(correctCount);

    // Show results dialog
    setShowResultsDialog(true);
    playSound("success");
  };

  // Reset the activity
  const resetActivity = () => {
    setQuestions(questionsProp);
    setAnswers({});
    setValidations({});
    setIsCompleted(false);
    setShowFeedback(false);
    setScore(0);
  };

  // Handle closing the results dialog
  const handleResultsDialogClose = (open: boolean) => {
    setShowResultsDialog(open);
    if (!open) {
      if (feedback === "none") {
        // If feedback is "none", reset the activity immediately
        resetActivity();
      } else {
        // Otherwise, mark as completed to show the feedback
        setIsCompleted(true);
      }
    }
  };

  // Count total number of pattern fields for scoring
  const getTotalPatterns = () => {
    return questions.reduce(
      (total, question) => total + question.patternIndices.length,
      0,
    );
  };

  return (
    <div className="flex flex-col h-full">
      <ActivityTitle title={title} />

      <>
        <div className="rounded-lg overflow-x-auto md:overflow-auto bg-picton-blue-50">
          {questions.map((question) => (
            <div key={question.id} className={` p-1`}>
              <div className="flex items-center gap-2">
                {question.sequence.map((item, index) => {
                  const isPattern = question.patternIndices.includes(index);
                  if (isPattern) {
                    const patternIndexPosition =
                      question.patternIndices.indexOf(index);
                    const correctAnswer =
                      question.correctAnswers[patternIndexPosition];
                    const answerKey = `${question.id}-${index}`;

                    return (
                      <motion.div
                        key={`q${question.id}-pattern-${index}`}
                        initial={{ scale: 1 }}
                        animate={{
                          scale:
                            showFeedback && feedback !== "none"
                              ? validations[answerKey]
                                ? [1, 1.1, 1]
                                : [1, 0.9, 1]
                              : 1,
                          x:
                            showFeedback &&
                            !validations[answerKey] &&
                            feedback !== "none"
                              ? [0, -5, 5, -5, 5, 0]
                              : 0,
                        }}
                        transition={{ duration: 0.5 }}
                        className="relative w-full flex flex-col items-center justify-center"
                      >
                        {/* <div className="text-center mb-1">{item}</div> */}
                        <CustomInput
                          value={answers[answerKey] || ""}
                          onChange={(e) =>
                            handleInputChange(question.id, index, e)
                          }
                          noBorder
                          className={cn(
                            "min-w-12 md:min-w-20 md:min-h-14 flex items-center justify-center border-2 text-center text-lg font-semibold rounded",
                            {
                              "bg-lemon-200 border-none text-lemon-700":
                                answers[answerKey],
                              "border-picton-blue-300":
                                !showFeedback || feedback === "none",
                              "border-green-500 bg-green-50 text-green-700":
                                validations[answerKey],
                              "border-red-500 bg-red-50 text-red-700":
                                !validations[answerKey] && showFeedback,
                            },
                          )}
                          inputClassName="w-full h-full text-lg border-none !text-xl"
                          isCorrect={
                            showFeedback ? validations[answerKey] : undefined
                          }
                          disabled={showFeedback}
                          correctAnswer={
                            feedback === "wrong-correct-answers"
                              ? correctAnswer
                              : undefined
                          }
                        />
                      </motion.div>
                    );
                  }
                  return (
                    <div
                      key={`q${question.id}-${index}`}
                      className="bg-picton-blue-100 w-full min-w-12 md:min-w-20 min-h-14 flex items-center justify-center text-xl font-semibold rounded"
                    >
                      {item}
                    </div>
                  );
                })}
              </div>
            </div>
          ))}
        </div>

        {!showFeedback ? (
          <Button
            variant="brand-lemon"
            onClick={checkAnswers}
            className="w-fit ml-auto mt-4"
          >
            Check Answers
          </Button>
        ) : (
          isCompleted && (
            <ActivityResults
              score={score}
              total={getTotalPatterns()}
              onRestart={resetActivity}
            />
          )
        )}
      </>

      <ActivityResultsAlertDialog
        score={score}
        total={getTotalPatterns()}
        open={showResultsDialog}
        onOpenChange={handleResultsDialogClose}
      />
    </div>
  );
};

export default NumberMatrixActivity;

// app/components/primary-sources/activities/number-matrix.vue
<script setup lang="ts">
import { computed, ref, watch } from "vue";
import { Button } from "@/components/ui/button";
import CustomInput from "@/components/ui/inputs/custom-input";
import ActivityTitle from "@/components/templates/activity-title";
import ActivityResults, {
  ActivityResultsAlertDialog,
} from "@/components/templates/results";
import { cn } from "@/lib/utils";
import type { FeedbackType } from "@/lib/types/activity-types";
import { useSoundEffects } from "~/composables/use-sound-effects";

type NumberMatrixQuestion = {
  title: string;
  questions: {
    id: number;
    sequence: (number | string)[];
    patternIndices: number[];
    correctAnswers: number[];
  }[];
};

type Props = {
  feedback?: FeedbackType;
  questions: NumberMatrixQuestion;
};

const props = defineProps<Props>();

const questions = ref<NumberMatrixQuestion["questions"]>([...props.questions.questions]);
const answers = ref<Record<string, string>>({});
const validations = ref<Record<string, boolean>>({});
const showFeedback = ref(false);
const isCompleted = ref(false);
const score = ref(0);
const showResultsDialog = ref(false);

const { playSound } = useSoundEffects();

watch(
  () => props.questions.questions,
  (value) => {
    questions.value = [...value];
    answers.value = {};
    validations.value = {};
    showFeedback.value = false;
    isCompleted.value = false;
    score.value = 0;
    showResultsDialog.value = false;
  },
  { deep: true },
);

const totalPatterns = computed(() =>
  questions.value.reduce((total, question) => total + question.patternIndices.length, 0),
);

const getAnswerKey = (questionId: number, patternIndex: number) => `${questionId}-${patternIndex}`;

const handleInputChange = (questionId: number, patternIndex: number, value: string) => {
  if (value !== "" && !/^\d+$/.test(value)) {
    return;
  }

  answers.value = {
    ...answers.value,
    [getAnswerKey(questionId, patternIndex)]: value,
  };
};

const checkAnswers = () => {
  const nextValidations: Record<string, boolean> = {};
  let correctCount = 0;

  questions.value.forEach((question) => {
    question.patternIndices.forEach((patternIndex, index) => {
      const key = getAnswerKey(question.id, patternIndex);
      const userAnswer = Number.parseInt(answers.value[key] || "", 10);
      const expectedAnswer = question.correctAnswers[index];
      const isCorrect = !Number.isNaN(userAnswer) && userAnswer === expectedAnswer;

      nextValidations[key] = isCorrect;
      if (isCorrect) {
        correctCount += 1;
      }
    });
  });

  if (props.feedback !== "none") {
    showFeedback.value = true;
  }

  validations.value = nextValidations;
  score.value = correctCount;
  showResultsDialog.value = true;
  playSound("success");
};

const resetActivity = () => {
  questions.value = [...props.questions.questions];
  answers.value = {};
  validations.value = {};
  isCompleted.value = false;
  showFeedback.value = false;
  score.value = 0;
  showResultsDialog.value = false;
};

const handleResultsDialogClose = (open: boolean) => {
  showResultsDialog.value = open;
  if (!open) {
    if (props.feedback === "none") {
      resetActivity();
    } else {
      isCompleted.value = true;
    }
  }
};
</script>

<template>
  <div class="flex h-full flex-col">
    <ActivityTitle :title="props.questions.title" />

    <div class="overflow-x-auto rounded-lg bg-picton-blue-50 md:overflow-auto">
      <div v-for="question in questions" :key="question.id" class="p-1">
        <div class="flex items-center gap-2">
          <template v-for="(item, index) in question.sequence" :key="`q${question.id}-${index}`">
            <div
              v-if="!question.patternIndices.includes(index)"
              class="flex min-h-14 w-full min-w-12 items-center justify-center rounded bg-picton-blue-100 text-xl font-semibold md:min-w-20"
            >
              {{ item }}
            </div>

            <div
              v-else
              class="relative flex w-full flex-col items-center justify-center"
            >
              <CustomInput
                :value="answers[getAnswerKey(question.id, index)] || ''"
                :onChange="(value) => handleInputChange(question.id, index, value)"
                noBorder
                :disabled="showFeedback"
                :isCorrect="showFeedback ? validations[getAnswerKey(question.id, index)] : undefined"
                :correctAnswer="
                  props.feedback === 'wrong-correct-answers'
                    ? question.correctAnswers[question.patternIndices.indexOf(index)]
                    : undefined
                "
                :className="
                  cn(
                    'min-h-14 min-w-12 items-center justify-center rounded border-2 text-center text-lg font-semibold md:min-w-20',
                    {
                      'border-none bg-lemon-200 text-lemon-700':
                        answers[getAnswerKey(question.id, index)],
                      'border-picton-blue-300': !showFeedback || props.feedback === 'none',
                      'border-green-500 bg-green-50 text-green-700':
                        validations[getAnswerKey(question.id, index)],
                      'border-red-500 bg-red-50 text-red-700':
                        !validations[getAnswerKey(question.id, index)] && showFeedback,
                    },
                  )
                "
                inputClassName="h-full w-full border-none !text-xl text-lg"
              />
            </div>
          </template>
        </div>
      </div>
    </div>

    <Button
      v-if="!showFeedback"
      variant="brand-lemon"
      class="ml-auto mt-4 w-fit"
      @click="checkAnswers"
    >
      Check Answers
    </Button>

    <ActivityResults
      v-else-if="isCompleted"
      :score="score"
      :total="totalPatterns"
      :onRestart="resetActivity"
    />

    <ActivityResultsAlertDialog
      :score="score"
      :total="totalPatterns"
      :open="showResultsDialog"
      :onOpenChange="handleResultsDialogClose"
    />
  </div>
</template>
