// app/components/primary-sources/activities/single-check-table.tsx
import { motion } from "motion/react";
import { CheckIcon, X } from "lucide-react";
import { useState, useEffect } from "react";

// Local imports
import { cn, shuffle } from "@/lib/utils";
import ActivityTitle from "@/components/templates/activity-title";
import { FeedbackType } from "@/lib/types/activity-types";
import { useSoundEffects } from "@/shared/hooks/use-sound-effects";
import ActivityResults, {
  ActivityResultsAlertDialog,
} from "@/components/templates/results";

type MediaContent = {
  type: "image" | "video";
  url: string;
  alt: string;
};

type TableQuestion = {
  id: number;
  question: string;
  options: {
    text: string;
    isCorrect: boolean;
  }[];
  media?: MediaContent;
  description?: string;
};

type GridAnswer = {
  questionId: number;
  columnIndex: number;
  isChecked: boolean;
  isCorrect?: boolean;
};

type TSingleCheckTableProps = {
  questions: {
    title: string;
    fontSize?: string;
    questionHeader?: string;
    columnHeaders?: string[];
    questions: TableQuestion[];
  };
  feedback?: FeedbackType;
};

const SingleCheckTable = ({
  questions: {
    title,
    fontSize,
    questionHeader,
    columnHeaders,
    questions: originalQuestions,
  },
  feedback,
}: TSingleCheckTableProps) => {
  const [answers, setAnswers] = useState<GridAnswer[]>([]);
  const [showResults, setShowResults] = useState(false);
  const [score, setScore] = useState({ correct: 0, total: 0 });
  const [_, setIsComplete] = useState(false);
  const [allAnswered, setAllAnswered] = useState(false);
  const [showCorrectAnswers, setShowCorrectAnswers] = useState(false);
  const [questions, setQuestions] = useState<TableQuestion[]>([]);

  const { playSound } = useSoundEffects();

  // Function to shuffle questions
  const shuffleQuestions = () => {
    setQuestions(shuffle([...originalQuestions]));
  };

  // Initialize answers
  useEffect(() => {
    const initialAnswers: GridAnswer[] = [];
    originalQuestions.forEach((question) => {
      question.options.forEach((_, index) => {
        initialAnswers.push({
          questionId: question.id,
          columnIndex: index,
          isChecked: false,
        });
      });
    });
    setAnswers(initialAnswers);
    setQuestions(shuffle([...originalQuestions]));
  }, [originalQuestions]);

  const toggleAnswer = (questionId: number, columnIndex: number) => {
    setAnswers((prev) =>
      prev.map((answer) => {
        if (answer.questionId === questionId) {
          // If this is the column being clicked
          if (answer.columnIndex === columnIndex) {
            return { ...answer, isChecked: !answer.isChecked };
          }
          // Uncheck other columns for the same question
          return { ...answer, isChecked: false };
        }
        return answer;
      }),
    );
    playSound("click");
  };

  // Handle keyboard navigation for accessibility
  const handleKeyDown = (
    e: React.KeyboardEvent,
    questionId: number,
    columnIndex: number,
  ) => {
    if (e.key === "Enter" || e.key === " ") {
      e.preventDefault();
      toggleAnswer(questionId, columnIndex);
    }
  };

  // Check if all questions have at least one answer
  useEffect(() => {
    const questionAnswered = new Set();
    answers.forEach((answer) => {
      if (answer.isChecked) {
        questionAnswered.add(answer.questionId);
      }
    });
    setIsComplete(questionAnswered.size === questions.length);

    // Automatically check answers when all questions are answered
    if (
      questionAnswered.size === questions.length &&
      questions.length > 0 &&
      !showResults &&
      !allAnswered
    ) {
      checkAnswers();
    }
  }, [answers, questions]);

  const checkAnswers = () => {
    let correctCount = 0;
    const newAnswers = answers.map((answer) => {
      const question = originalQuestions.find(
        (q) => q.id === answer.questionId,
      );
      if (!question) return answer;

      const option = question.options[answer.columnIndex];
      const isCorrect = answer.isChecked && option.isCorrect;

      if (isCorrect) correctCount++;

      return { ...answer, isCorrect };
    });

    setAnswers(newAnswers);
    setScore({ correct: correctCount, total: originalQuestions.length });
    setAllAnswered(true);
    playSound("success");
  };

  const resetActivity = () => {
    setAnswers((prev) =>
      prev.map((answer) => ({
        ...answer,
        isChecked: false,
        isCorrect: undefined,
      })),
    );
    setShowResults(false);
    setShowCorrectAnswers(false);
    setIsComplete(false);
    shuffleQuestions();
  };

  return (
    <div className="flex flex-col h-full">
      <ActivityTitle title={title} />
      <div className="flex-1 bg-picton-blue-100 p-4 rounded-lg">
        <table
          className="w-full border-collapse"
          style={{
            fontSize: fontSize ? `${fontSize}px` : "20px",
          }}
        >
          <thead>
            <tr className="text-lg">
              <th className="w-1/3 text-start pl-4 py-6 bg-picton-blue-500 text-white rounded-tl-lg border-b border-picton-blue-300">
                {questionHeader || "Question"}
              </th>
              {questions.length > 0 &&
                questions[0].options.map((_, index) => {
                  // Use column headers if available, otherwise use option text
                  const headerText =
                    columnHeaders?.[index] ||
                    (questions[0].options.length > index
                      ? questions[0].options[index].text
                      : `Column ${index + 1}`);

                  return (
                    <th
                      key={index}
                      className={cn(
                        "p-2 bg-picton-blue-500 text-white text-center w-1/6",
                        {
                          "rounded-tr-lg":
                            index === questions[0].options.length - 1,
                        },
                      )}
                    >
                      {headerText}
                    </th>
                  );
                })}
            </tr>
          </thead>
          <tbody>
            {questions.map((question, rowIndex) => (
              <tr key={question.id}>
                <td
                  className={cn("p-4 bg-picton-blue-200 text-picton-blue-700", {
                    "rounded-bl-lg": rowIndex === questions.length - 1,
                    "border-b border-picton-blue-300":
                      rowIndex < questions.length - 1,
                  })}
                >
                  <div className="flex flex-col gap-2">
                    {question.media && question.media.type === "image" && (
                      <div className="flex max-w-[210px] max-h-[210px]">
                        <img
                          src={question.media.url}
                          alt={question.media.alt}
                          className="w-full h-full max-w-[210px] max-h-[210px] object-contain"
                        />
                      </div>
                    )}
                    <div
                      className="font-medium whitespace-pre-line"
                      dangerouslySetInnerHTML={{ __html: question.question }}
                    />
                  </div>
                </td>
                {question.options.map((option, colIndex) => {
                  const answer = answers.find(
                    (a) =>
                      a.questionId === question.id &&
                      a.columnIndex === colIndex,
                  );

                  return (
                    <td
                      key={colIndex}
                      className={cn("border p-0 cursor-pointer bg-white", {
                        "bg-green-100": showResults && answer?.isCorrect,
                        "bg-red-100":
                          showResults &&
                          answer?.isChecked &&
                          !answer?.isCorrect,
                      })}
                      onClick={() =>
                        !showResults && toggleAnswer(question.id, colIndex)
                      }
                    >
                      <div className="flex items-center justify-center h-12">
                        <div
                          className={cn(
                            "w-8 h-8 rounded border-2 flex items-center justify-center transition-all",
                            answer?.isChecked && !showResults
                              ? "bg-picton-blue-500 border-picton-blue-500"
                              : "bg-white border-gray-300 hover:border-picton-blue-300",
                          )}
                        >
                          {answer?.isChecked && (
                            <motion.div
                              initial={{ scale: 0 }}
                              animate={{ scale: 1 }}
                              className={cn("mx-auto w-fit text-white", {
                                "text-green-600":
                                  showResults && answer.isCorrect,
                                "text-red-600":
                                  showResults && !answer.isCorrect,
                              })}
                            >
                              {showResults && !answer.isCorrect ? (
                                <X className="w-6 h-6" />
                              ) : (
                                <CheckIcon className="w-6 h-6" />
                              )}
                            </motion.div>
                          )}
                          {showCorrectAnswers &&
                            !answer?.isChecked &&
                            option.isCorrect && (
                              <motion.div
                                initial={{ opacity: 0 }}
                                animate={{ opacity: 1 }}
                                className="text-green-600"
                              >
                                <CheckIcon className="w-6 h-6" />
                              </motion.div>
                            )}
                        </div>
                      </div>
                    </td>
                  );
                })}
              </tr>
            ))}
          </tbody>
        </table>

        {showResults && (
          <div className="mt-4">
            <ActivityResults
              score={score.correct}
              total={score.total}
              onRestart={resetActivity}
            />
          </div>
        )}
      </div>{" "}
      <ActivityResultsAlertDialog
        score={score.correct}
        total={score.total}
        open={allAnswered}
        onOpenChange={(open) => {
          if (!open) {
            if (feedback === "none") {
              resetActivity();
            } else if (feedback === "wrong-correct") {
              setShowResults(true);
              setAllAnswered(false);
            } else if (feedback === "wrong-correct-answers") {
              setShowResults(true);
              //   setShowCorrectAnswers(true);
              setAllAnswered(false);
            }
          }
        }}
      />
    </div>
  );
};

export default SingleCheckTable;

// app/components/primary-sources/activities/single-check-table.vue
<script setup lang="ts">
import { computed, ref, watch } from "vue";
import { cn, shuffle } from "@/lib/utils";
import ActivityTitle from "@/components/templates/activity-title";
import ActivityResults, {
  ActivityResultsAlertDialog,
} from "@/components/templates/results";
import type { FeedbackType } from "@/lib/types/activity-types";
import { useSoundEffects } from "~/composables/use-sound-effects";

type MediaContent = {
  type: "image" | "video";
  url: string;
  alt: string;
};

type TableQuestion = {
  id: number;
  question: string;
  options: {
    text: string;
    isCorrect: boolean;
  }[];
  media?: MediaContent;
  description?: string;
};

type GridAnswer = {
  questionId: number;
  columnIndex: number;
  isChecked: boolean;
  isCorrect?: boolean;
};

type Props = {
  questions: {
    title: string;
    fontSize?: string;
    questionHeader?: string;
    columnHeaders?: string[];
    questions: TableQuestion[];
  };
  feedback?: FeedbackType;
};

const props = defineProps<Props>();
const { playSound } = useSoundEffects();

const answers = ref<GridAnswer[]>([]);
const showResults = ref(false);
const score = ref({ correct: 0, total: 0 });
const allAnswered = ref(false);
const showCorrectAnswers = ref(false);
const shuffledQuestions = ref<TableQuestion[]>([]);

const initializeAnswers = () => {
  answers.value = props.questions.questions.flatMap((question) =>
    question.options.map((_, index) => ({
      questionId: question.id,
      columnIndex: index,
      isChecked: false,
    })),
  );
  shuffledQuestions.value = shuffle([...props.questions.questions]);
  showResults.value = false;
  showCorrectAnswers.value = false;
  allAnswered.value = false;
};

watch(() => props.questions.questions, initializeAnswers, { deep: true, immediate: true });

const toggleAnswer = (questionId: number, columnIndex: number) => {
  answers.value = answers.value.map((answer) => {
    if (answer.questionId !== questionId) return answer;
    if (answer.columnIndex === columnIndex) {
      return { ...answer, isChecked: !answer.isChecked };
    }
    return { ...answer, isChecked: false };
  });
  playSound("click");
};

const answerFor = (questionId: number, columnIndex: number) =>
  answers.value.find(
    (answer) => answer.questionId === questionId && answer.columnIndex === columnIndex,
  );

const checkAnswers = () => {
  let correctCount = 0;

  answers.value = answers.value.map((answer) => {
    const question = props.questions.questions.find((item) => item.id === answer.questionId);
    if (!question) return answer;

    const option = question.options[answer.columnIndex];
    const correct = answer.isChecked && option.isCorrect;
    if (correct) correctCount += 1;

    return { ...answer, isCorrect: correct };
  });

  score.value = { correct: correctCount, total: props.questions.questions.length };
  allAnswered.value = true;
  playSound("success");
};

watch(
  answers,
  (value) => {
    const answeredQuestions = new Set(
      value.filter((answer) => answer.isChecked).map((answer) => answer.questionId),
    );

    if (
      answeredQuestions.size === shuffledQuestions.value.length &&
      shuffledQuestions.value.length > 0 &&
      !showResults.value &&
      !allAnswered.value
    ) {
      checkAnswers();
    }
  },
  { deep: true },
);

const resetActivity = () => {
  initializeAnswers();
};
</script>

<template>
  <div class="flex h-full flex-col">
    <ActivityTitle :title="props.questions.title" />

    <div class="flex-1 rounded-lg bg-picton-blue-100 p-4">
      <table
        class="w-full border-collapse"
        :style="{ fontSize: props.questions.fontSize ? `${props.questions.fontSize}px` : '20px' }"
      >
        <thead>
          <tr class="text-lg">
            <th class="w-1/3 rounded-tl-lg border-b border-picton-blue-300 bg-picton-blue-500 py-6 pl-4 text-start text-white">
              {{ props.questions.questionHeader || "Question" }}
            </th>
            <th
              v-for="(_, index) in shuffledQuestions[0]?.options || []"
              :key="index"
              :class="
                cn('w-1/6 bg-picton-blue-500 p-2 text-center text-white', {
                  'rounded-tr-lg': index === (shuffledQuestions[0]?.options.length || 1) - 1,
                })
              "
            >
              {{
                props.questions.columnHeaders?.[index] ||
                shuffledQuestions[0]?.options[index]?.text ||
                `Column ${index + 1}`
              }}
            </th>
          </tr>
        </thead>
        <tbody>
          <tr v-for="(question, rowIndex) in shuffledQuestions" :key="question.id">
            <td
              :class="
                cn('bg-picton-blue-200 p-4 text-picton-blue-700', {
                  'rounded-bl-lg': rowIndex === shuffledQuestions.length - 1,
                  'border-b border-picton-blue-300': rowIndex < shuffledQuestions.length - 1,
                })
              "
            >
              <div class="flex flex-col gap-2">
                <div v-if="question.media?.type === 'image'" class="flex max-h-[210px] max-w-[210px]">
                  <img
                    :src="question.media.url"
                    :alt="question.media.alt"
                    class="h-full max-h-[210px] w-full max-w-[210px] object-contain"
                  >
                </div>
                <div class="whitespace-pre-line font-medium" v-html="question.question" />
              </div>
            </td>

            <td
              v-for="(option, colIndex) in question.options"
              :key="colIndex"
              :class="
                cn('cursor-pointer border bg-white p-0', {
                  'bg-green-100': showResults && answerFor(question.id, colIndex)?.isCorrect,
                  'bg-red-100':
                    showResults &&
                    answerFor(question.id, colIndex)?.isChecked &&
                    !answerFor(question.id, colIndex)?.isCorrect,
                })
              "
              @click="!showResults && toggleAnswer(question.id, colIndex)"
            >
              <div class="flex h-12 items-center justify-center">
                <div
                  :class="
                    cn(
                      'flex h-8 w-8 items-center justify-center rounded border-2 transition-all',
                      answerFor(question.id, colIndex)?.isChecked && !showResults
                        ? 'border-picton-blue-500 bg-picton-blue-500 text-white'
                        : 'border-gray-300 bg-white hover:border-picton-blue-300',
                    )
                  "
                >
                  <span
                    v-if="answerFor(question.id, colIndex)?.isChecked"
                    :class="[
                      'mx-auto w-fit',
                      showResults && answerFor(question.id, colIndex)?.isCorrect && 'text-green-600',
                      showResults && answerFor(question.id, colIndex)?.isCorrect === false && 'text-red-600',
                    ]"
                  >
                    {{
                      showResults && answerFor(question.id, colIndex)?.isCorrect === false
                        ? "✕"
                        : "✓"
                    }}
                  </span>

                  <span
                    v-if="showCorrectAnswers && !answerFor(question.id, colIndex)?.isChecked && option.isCorrect"
                    class="text-green-600"
                  >
                    ✓
                  </span>
                </div>
              </div>
            </td>
          </tr>
        </tbody>
      </table>

      <div v-if="showResults" class="mt-4">
        <ActivityResults :score="score.correct" :total="score.total" :onRestart="resetActivity" />
      </div>
    </div>

    <ActivityResultsAlertDialog
      :score="score.correct"
      :total="score.total"
      :open="allAnswered"
      :onOpenChange="
        (open: boolean) => {
          if (!open) {
            if (props.feedback === 'none') {
              resetActivity();
            } else if (props.feedback === 'wrong-correct') {
              showResults = true;
              allAnswered = false;
            } else if (props.feedback === 'wrong-correct-answers') {
              showResults = true;
              allAnswered = false;
            }
          }
        }
      "
    />
  </div>
</template>
