// app/components/primary-sources/activities/numbers-activities/shared/answer-drop-zone.tsx
"use client";

import { ReactNode } from "react";
import Droppable from "@/components/ui/dnd/droppable";
import Draggable from "@/components/ui/dnd/draggable";
import { Check } from "lucide-react";
import { Input } from "@/components/ui/input";
import { cn } from "@/lib/utils";

export type AnswerType = "drag-drop" | "input" | "click";

type AnswerDropZoneProps = {
  id: string;
  answerType: AnswerType;
  currentAnswer?: string;
  correctAnswer?: string;
  showResults?: boolean;
  placeholder?: string;
  onInputChange?: (value: string) => void;
  onClickChange?: (value: string) => void;
  className?: string;
  children?: ReactNode;
  isDraggable?: boolean;
  dragId?: string;
  isSelected?: boolean;
};

const AnswerDropZone = ({
  id,
  answerType,
  currentAnswer = "",
  correctAnswer,
  showResults = false,
  placeholder = "Drop answer here",
  onInputChange,
  onClickChange,
  className = "",
  children,
  isDraggable = false,
  dragId,
  isSelected = false,
}: AnswerDropZoneProps) => {
  const isCorrect = showResults && currentAnswer === correctAnswer;
  const isIncorrect =
    showResults && currentAnswer !== correctAnswer && currentAnswer !== "";

  const getResultStyles = () => {
    if (!showResults) return "";
    if (isCorrect) return "!bg-green-200 !text-green-700 !border-green-300";
    if (isIncorrect) return "bg-red-200 text-red-700 border-red-300";
    return "";
  };

  const baseStyles = `
    min-h-[60px] flex items-center justify-center bg-picton-blue-100 rounded-lg transition-colors duration-200
    ${className} ${getResultStyles()}
  `;

  const renderContent = () => {
    if (children) return children;
    if (currentAnswer) return currentAnswer;
    return placeholder;
  };

  switch (answerType) {
    case "drag-drop":
      if (currentAnswer && isDraggable && dragId) {
        return (
          <Draggable
            id={dragId}
            className={`${baseStyles} bg-lemon-200 text-lemon-700 cursor-move`}
          >
            {renderContent()}
          </Draggable>
        );
      }
      return (
        <Droppable
          id={id}
          className={baseStyles}
          isOverClassName="bg-lemon-100 border-lemon-400"
        >
          {renderContent()}
        </Droppable>
      );

    case "input":
      return (
        // <input
        //   type="text"
        //   value={currentAnswer}
        //   onChange={(e) => onInputChange?.(e.target.value)}
        //   placeholder={placeholder}
        //   className={`${baseStyles} p-2 border-solid text-center text-lg font-medium`}
        //   disabled={showResults}
        // />
        <div className={className}>
          <Input
            type="text"
            value={currentAnswer}
            onChange={(e) => onInputChange?.(e.target.value)}
            className={cn(
              "text-center border-none font-medium !text-3xl bg-transparent focus-visible:ring-offset-0",
              showResults && {
                "bg-green-200 text-green-600": isCorrect,
                "bg-red-100 text-red-600": isIncorrect,
              }
            )}
            disabled={showResults}
          />
          <div
            className={cn(
              "border-b border-dashed mt-1",
              showResults
                ? {
                    "border-green-600": isCorrect,
                    "border-red-600": isIncorrect,
                  }
                : "border-picton-blue-700"
            )}
          />
        </div>
      );

    case "click":
      return (
        <div
          onClick={() => !showResults && onClickChange?.(id)}
          className={`transition-colors
            ${isSelected ? "bg-picton-blue-200 border-picton-blue-400" : ""}
            ${
              showResults
                ? "cursor-default"
                : "cursor-pointer hover:bg-picton-blue-100"
            } ${baseStyles}`}
        >
          <div className="flex items-center justify-center gap-2">
            {isSelected && <Check size={32} />}
          </div>
        </div>
      );

    default:
      return <div className={baseStyles}>{renderContent()}</div>;
  }
};

export default AnswerDropZone;

// app/components/primary-sources/activities/numbers-activities/shared/answer-drop-zone.vue
<script setup lang="ts">
import { computed, useSlots } from "vue";
import Droppable from "~/components/ui/dnd/droppable";
import Draggable from "~/components/ui/dnd/draggable";
import Input from "~/components/ui/inputs/input";
import { cn } from "~/utilities/utils";

export type AnswerType = "drag-drop" | "input" | "click";

type AnswerDropZoneProps = {
  id: string;
  answerType: AnswerType;
  currentAnswer?: string;
  correctAnswer?: string;
  showResults?: boolean;
  placeholder?: string;
  onInputChange?: (value: string) => void;
  onClickChange?: (value: string) => void;
  className?: string;
  isDraggable?: boolean;
  dragId?: string;
  isSelected?: boolean;
};

const props = withDefaults(defineProps<AnswerDropZoneProps>(), {
  currentAnswer: "",
  showResults: false,
  placeholder: "Drop answer here",
  className: "",
  isDraggable: false,
  isSelected: false,
});

const slots = useSlots();

const isCorrect = computed(
  () => props.showResults && props.currentAnswer === props.correctAnswer,
);
const isIncorrect = computed(
  () =>
    props.showResults &&
    props.currentAnswer !== props.correctAnswer &&
    props.currentAnswer !== "",
);

const resultStyles = computed(() => {
  if (!props.showResults) return "";
  if (isCorrect.value) return "!bg-green-200 !text-green-700 !border-green-300";
  if (isIncorrect.value) return "bg-red-200 text-red-700 border-red-300";
  return "";
});

const baseStyles = computed(
  () => `
    min-h-[60px] flex items-center justify-center bg-picton-blue-100 rounded-lg transition-colors duration-200
    ${props.className} ${resultStyles.value}
  `,
);

const renderTextContent = computed(() => {
  if (props.currentAnswer) return props.currentAnswer;
  return props.placeholder;
});
</script>

<template>
  <!-- drag-drop -->
  <template v-if="props.answerType === 'drag-drop'">
    <Draggable
      v-if="props.currentAnswer && props.isDraggable && props.dragId"
      :id="props.dragId"
      :class="`${baseStyles} bg-lemon-200 text-lemon-700 cursor-move`"
    >
      <slot v-if="slots.default" />
      <template v-else>{{ renderTextContent }}</template>
    </Draggable>

    <Droppable
      v-else
      :id="props.id"
      :class="baseStyles"
      isOverClassName="bg-lemon-100 border-lemon-400"
    >
      <slot v-if="slots.default" />
      <template v-else>{{ renderTextContent }}</template>
    </Droppable>
  </template>

  <!-- input -->
  <template v-else-if="props.answerType === 'input'">
    <div :class="props.className">
      <Input
        type="text"
        :model-value="props.currentAnswer"
        :disabled="props.showResults"
        :placeholder="props.placeholder"
        :class="
          cn(
            'text-center border-none font-medium !text-3xl bg-transparent focus-visible:ring-offset-0',
            props.showResults && {
              'bg-green-200 text-green-600': isCorrect,
              'bg-red-100 text-red-600': isIncorrect,
            },
          )
        "
        @update:modelValue="(v: string) => props.onInputChange?.(v)"
      />
      <div
        :class="
          cn(
            'border-b border-dashed mt-1',
            props.showResults
              ? {
                  'border-green-600': isCorrect,
                  'border-red-600': isIncorrect,
                }
              : 'border-picton-blue-700',
          )
        "
      />
    </div>
  </template>

  <!-- click -->
  <template v-else-if="props.answerType === 'click'">
    <div
      :class="`transition-colors
        ${props.isSelected ? 'bg-picton-blue-200 border-picton-blue-400' : ''}
        ${props.showResults ? 'cursor-default' : 'cursor-pointer hover:bg-picton-blue-100'}
        ${baseStyles}`"
      @click="() => !props.showResults && props.onClickChange?.(props.id)"
    >
      <div class="flex items-center justify-center gap-2">
        <span v-if="props.isSelected" class="text-2xl leading-none">✓</span>
      </div>
    </div>
  </template>

  <!-- fallback -->
  <template v-else>
    <div :class="baseStyles">
      <slot v-if="slots.default" />
      <template v-else>{{ renderTextContent }}</template>
    </div>
  </template>
</template>
