// app/components/ui/inputs/input.vue
<script setup lang="ts">
import { computed } from "vue";
import { cva, type VariantProps } from "class-variance-authority";
import { cn } from "~/utilities/utils";

const inputVariants = cva(
  "flex h-10 w-full rounded-md border px-3 py-2 file:border-0 file:bg-transparent file:text-sm file:font-medium focus-visible:outline-none disabled:cursor-not-allowed disabled:opacity-50 dark:border-gray-800 dark:bg-gray-950 dark:ring-offset-gray-950 dark:file:text-gray-50 dark:placeholder:text-gray-400 dark:focus-visible:ring-gray-300",
  {
    variants: {
      variant: {
        default:
          "border-gray-200 bg-white file:text-gray-950 placeholder:text-gray-500",
        brand:
          "text-lemon-600 border-lemon-300 bg-lemon-50 file:text-lemon-800 placeholder:text-lemon-600 focus-visible:ring-lemon-600",
        picton:
          "text-picton-blue-500 border-picton-blue-300 bg-picton-blue-50 file:text-picton-blue-600 placeholder:text-picton-blue-500 focus-visible:ring-picton-blue-800 focus-visible:ring-0",
      },
    },
    defaultVariants: {
      variant: "default",
    },
  },
);

type InputVariants = VariantProps<typeof inputVariants>;

const props = withDefaults(
  defineProps<{
    modelValue?: string;
    variant?: InputVariants["variant"];
    type?: string;
    removeArrows?: boolean;
    placeholder?: string;
    disabled?: boolean;
    class?: string;
  }>(),
  {
    variant: "default",
    type: "text",
    removeArrows: false,
    placeholder: "",
    disabled: false,
    class: "",
  },
);

const emit = defineEmits<{
  "update:modelValue": [value: string];
}>();

const inputClassName = computed(() =>
  cn(
    inputVariants({ variant: props.variant }),
    props.class,
    props.removeArrows &&
      "[appearance:textfield] [&::-webkit-outer-spin-button]:appearance-none [&::-webkit-inner-spin-button]:appearance-none",
  ),
);

const handleInput = (event: Event) => {
  const target = event.target as HTMLInputElement;
  emit("update:modelValue", target.value);
};
</script>

<template>
  <input
    :type="props.type"
    :value="props.modelValue"
    :placeholder="props.placeholder"
    :disabled="props.disabled"
    :class="inputClassName"
    autocomplete="off"
    autocapitalize="off"
    autocorrect="off"
    :spellcheck="false"
    @input="handleInput"
  >
</template>

// app/components/UI/input.tsx
import * as React from "react";

import { cn } from "@/lib/utils";

const Input = React.forwardRef<HTMLInputElement, React.ComponentProps<"input">>(
  ({ className, type, ...props }, ref) => {
    return (
      <input
        type={type}
        className={cn(
          "flex h-10 w-full rounded-md border px-3 py-2 text-base ring-offset-picton-blue-50 file:border-0 file:bg-transparent file:text-sm file:font-medium focus-visible:outline-none focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50 md:text-sm dark:border-gray-800 dark:bg-picton-blue-950 dark:ring-offset-gray-950 dark:file:text-gray-50 dark:placeholder:text-gray-400 dark:focus-visible:ring-gray-300 text-picton-blue-500 border-picton-blue-300 bg-picton-blue-50 file:text-picton-blue-600 placeholder:text-picton-blue-400 focus-visible:ring-picton-blue-800 focus-visible:ring-0",
          className
        )}
        ref={ref}
        {...props}
        spellCheck="false"
        // Grammarly disable spell checking
        data-gramm="false"
        data-gramm_editor="false"
        data-enable-grammarly="false"
      />
    );
  }
);
Input.displayName = "Input";

export { Input };
